#!/usr/tce/bin/python

'''
quick script to test that sample lists generated by build_trainer_lists.py
contain unique indices.

usage: sanity.py id_mapping_fn bar_fn t0_fn [t1_fn, ...]
'''


import sys

if len(sys.argv) == 1 :
  print '''
    usage: sanity.py id_mapping_fn sample_list_dir sample_list_base_name num_sample_lists
    where: bar_fn, t0_fn, etc, are outputs from build_trainer_lists.py
    function: test that the intersection of the sample IDs in the
              sample lists are empty, and that every sample_ID
              is in either one sample list or in the exclusion (bar) file\n
    example usage: 
      python sanity.py \\
        /p/lustre2/brainusr/datasets/10MJAG/1M_A/id_mapping.txt \\
        /p/lustre2/brainusr/datasets/10MJAG/1M_A/select_samples_test/another_dir \\
        my_samples.txt \\
        10 
        
    CAUTION: this script is fragile: it may break if/when model_zoo/jag_utils/select_samples.cpp is modified
        '''


  exit(9)

#======================================================================
def buildInc(mp, fn) :
  r = set()
  print 'buildInc; opening:', fn
  a = open(fn)
  a.readline()
  a.readline()
  a.readline()
  for line in a :
    t = line.split()
    for j in t[3:] :
      r.add(j)
  return r

#======================================================================
def buildExc(mp, fn) :
  s = set()
  print 'buildExc; opening:', fn
  a = open(fn)
  a.readline()
  a.readline()
  a.readline()
  for line in a :
    t = line.split()
    for j in t[3:] :
      s.add(j)
  r = set()
  for sample_id in mp :
    if sample_id not in s :
      r.add(sample_id)
  return r

#======================================================================
#build set that contains all sample names
mp = set()
a = open(sys.argv[1])
for line in a :
  t = line.split()
  for j in t[1:] :
    mp.add(j)
print '\nlen(map):', len(mp)

sample_list_dir = sys.argv[2]
sample_list_base_name = sys.argv[3]

#build exclusion set; this set contains all valid (successful) sample IDs
s2 = buildExc(mp, sample_list_dir + '/t__' + sample_list_base_name + '_bar')

data = []
data.append(s2)

for j in range(int(sys.argv[4])) :
  s2 = buildInc(mp, sample_list_dir + '/t' + str(j) + '_' + sample_list_base_name)
  data.append(s2)
  print len(s2)
print
print '===================================================================='
print 'running intersection test ...'
success = True
for j in range(0, len(data)-1) :
  for k in range(1, len(data)) :
    if j != k :
      a = data[j]
      b = data[k]
      #print 'testing', j, 'against', k
      r = len(a.intersection(b))
      if r != 0 :
        print 'FAILED: ', j, 'intersection with',k, '=' , r
        success = False
if success :
  print '  SUCCESS!'

print
print 'testing that all samples appear in one sample list, or the bar file'

s2 = set()
for j in range(0, len(data)) :
  for sample_id in data[j] :
    assert(sample_id in mp)
    mp.remove(sample_id)
if len(mp) == 0 :
  print '  SUCCESS!'
else :
  print '  FAILED; len(mp)= ', len(mp), 'should be zero'
