"""LBANN Python interface."""

# Check for Python 3
import sys
if sys.version_info[0] != 3:
    raise ImportError('Python 3 is required')

# Import lbann_pb2 module generated by protobuf
# Note: This should be built automatically during the LBANN build
# process. If it's not in the default Python search path, try to find
# it with some heuristics.
try:
    import lbann_pb2
except ImportError:
    import os.path
    import lbann.contrib.lc.paths
    sys.path.append(os.path.join(lbann.contrib.lc.paths.install_dir(),
                                 'share', 'python'))
    import lbann_pb2

# Import core functionality into lbann namespace
from lbann.util import lbann_dir
from lbann.callback import *
from lbann.layer import *
from lbann.metric import *
from lbann.trainer import *
from lbann.model import *
from lbann.objective_function import *
from lbann.optimizer import *
from lbann.weights import *
from lbann.launcher import run
