base.hpp
LBANN_ERROR
DISPLAY_MATRIX
log_msg
log_simple_msg
LBANN_MAKE_STR
_LBANN_MAKE_STR
matrix_format
data_layout
execution_mode
pool_mode
using EGrid = El::Grid
using Grid = El::Grid
using Mat = El::Matrix<lbann::DataType>
using AbsDistMat = El::AbstractDistMatrix<lbann::DataType>
using ElMat = El::ElementalMatrix<lbann::DataType>
using BlockMat = El::BlockMatrix<lbann::DataType>
using MCMRMat = El::DistMatrix<lbann::DataType, El::MC , El::MR >
using CircMat = El::DistMatrix<lbann::DataType, El::CIRC, El::CIRC>
using StarMat = El::DistMatrix<lbann::DataType, El::STAR, El::STAR>
using StarVCMat = El::DistMatrix<lbann::DataType, El::STAR, El::VC >
using VCStarMat = El::DistMatrix<lbann::DataType, El::VC , El::STAR>
using MCStarMat = El::DistMatrix<lbann::DataType, El::MC , El::STAR>
using MRStarMat = El::DistMatrix<lbann::DataType, El::MR , El::STAR>
using StarMRMat = El::DistMatrix<lbann::DataType, El::STAR, El::MR >
using DistMat = MCMRMat
using RowSumMat = MCStarMat
using ColSumStarVCMat = VCStarMat
using ColSumMat = MRStarMat
using EvalType = double
static matrix_format data_layout_to_matrix_format(data_layout layout)
References MODEL_PARALLEL, MC_MR, DATA_PARALLEL, STAR_STAR.
static const char* _to_string(execution_mode m)
References training, validation, testing, prediction, invalid.
Referenced by lbann::lbann_callback_debug::on_batch_begin, lbann::lbann_callback_debug::on_forward_prop_begin, lbann::lbann_callback_debug::on_forward_prop_end, lbann::lbann_callback_debug::on_backward_prop_begin, lbann::lbann_callback_debug::on_backward_prop_end, lbann::lbann_callback_debug::on_batch_evaluate_begin, lbann::lbann_callback_debug::on_batch_evaluate_end, lbann::lbann_callback_debug::on_evaluate_forward_prop_begin, lbann::lbann_callback_debug::on_evaluate_forward_prop_end, lbann::lbann_callback_debug_io::print_fp_start, lbann::lbann_callback_debug_io::print_phase_start, lbann::lbann_callback_dump_minibatch_sample_indices::dump_to_file.
std::string get_pool_mode_name(pool_mode m)
returns a string representation of the pool_mode
References pool_mode_names.
Referenced by lbann::pooling_layer< T_layout >::get_description.
static void _display_matrix(ElMat *m, const char *name)
Print the dimensions and name of a Elemental matrix.