lbann::offline_patches_npz
using lbann::offline_patches_npz::label_t = uint8_t
using lbann::offline_patches_npz::sample_t = std::pair<std::vector<std::string>, label_t>
bool lbann::offline_patches_npz::m_checked_ok
Whether loaded data have passed the format check.
Referenced by load, get_sample, get_label.
size_t lbann::offline_patches_npz::m_num_patches
The number of image patches per sample (i.e. the num of patch files to read)
Referenced by get_num_patches, check_data, get_description, get_sample.
cnpy::NpyArray lbann::offline_patches_npz::m_item_root_list
List of index sequences to the dictionary of common file path substrings (m_file_root_list) per patch file (dimension: num_samples * num_patches)
Referenced by load, check_data, get_description, get_sample.
cnpy::NpyArray lbann::offline_patches_npz::m_item_variant_list
List of index sequences to the dictionary of common file path substrings (m_file_variant_list) per patch file (dimension: num_samples * num_patches)
Referenced by load, check_data, get_description, get_sample.
std::vector<label_t> lbann::offline_patches_npz::m_item_class_list
list of labels (dimension: num_samples)
Referenced by get_num_samples, load, check_data, get_description, get_sample, get_label.
std::vector<std::string> lbann::offline_patches_npz::m_file_root_list
The list of common substrings that a file path starts with (dimension is, for example 1000 in case of imagenet data)
Referenced by load, check_data, get_description, get_sample.
std::vector<std::string> lbann::offline_patches_npz::m_file_variant_list
Referenced by load, check_data, get_description, get_sample.
std::string lbann::offline_patches_npz::m_file_root_list_name
The text file name of file_root_list.
std::string lbann::offline_patches_npz::m_file_variant_list_name
The text file name of file_variant_list.
std::string lbann::offline_patches_npz::m_variant_divider
A substring after which the file name of variants begins to differ (e.g., ".JPEG.")
Referenced by get_description, get_sample.
bool lbann::offline_patches_npz::m_fetch_text_dict_at_once
control how the text dictionary files are loaded: whether to load all at once and parse or to stream in
lbann::offline_patches_npz::offline_patches_npz()
bool lbann::offline_patches_npz::load(const std::string filename, size_t first_n=0u)
Load the data in the compressed numpy format file. Use only first_n available samples if specified.
References m_item_class_list, m_file_root_list, m_file_variant_list, lbann::check_if_file_exists, lbann::cnpy_utils::shrink_to_fit, m_item_root_list, m_item_variant_list, m_checked_ok, check_data.
Referenced by lbann::data_reader_triplet::load.
std::string lbann::offline_patches_npz::get_description() const
Show the description.
References lbann::cnpy_utils::show_shape, m_item_root_list, m_item_variant_list, m_item_class_list, m_file_root_list, m_file_variant_list, m_variant_divider, get_num_samples, m_num_patches.
size_t lbann::offline_patches_npz::get_num_samples() const
Return the number of samples.
References m_item_class_list.
Referenced by lbann::data_reader_triplet::get_image_list, lbann::data_reader_triplet::load, get_description, get_sample, get_label.
size_t lbann::offline_patches_npz::get_num_patches() const
Return the number of patches per sample (the number of image data sources)
References m_num_patches, get_sample, get_label, check_data.
offline_patches_npz::sample_t lbann::offline_patches_npz::get_sample(const size_t idx) const
Reconsturct and return the meta-data (patch file names and the label) of idx-th sample.
References m_checked_ok, get_num_samples, m_num_patches, m_item_root_list, m_file_root_list, m_item_variant_list, m_file_variant_list, m_variant_divider, m_item_class_list.
Referenced by lbann::data_reader_triplet::get_sample, get_num_patches, lbann::data_reader_triplet::fetch_datum, lbann::data_reader_triplet::get_image_list_of_current_mb, lbann::data_reader_triplet::get_image_list.
offline_patches_npz::label_t lbann::offline_patches_npz::get_label(const size_t idx) const
Return the label of idx-th sample.
References m_checked_ok, get_num_samples, m_item_class_list.
Referenced by get_num_patches, lbann::data_reader_triplet::fetch_label.
bool lbann::offline_patches_npz::check_data() const
Check the dimensions of loaded data.
References m_item_root_list, m_item_variant_list, m_file_root_list, m_file_variant_list, m_item_class_list, m_num_patches.
Referenced by get_num_patches, load.