lbann::data_store_pilot2_molecular
friend lbann::data_store_pilot2_molecular::data_store_merge_samples
pilot2_molecular_reader* lbann::data_store_pilot2_molecular::m_pilot2_reader
Referenced by setup, construct_data_store, fill_in_data, build_nabor_map, get_data_buf, exchange_data.
std::unordered_map<int, std::vector<double> > lbann::data_store_pilot2_molecular::m_data
the data store. Note that this will break if word size = 4; only meaningful on the owning processor
Referenced by fill_in_data, exchange_data.
std::unordered_map<int, std::vector<int> > lbann::data_store_pilot2_molecular::m_neighbors
maps: a shuffled index to the corresponding molecule's neighbors' indices
Referenced by build_nabor_map, get_data_buf, get_required_molecules.
std::unordered_map<int, std::vector<double> > lbann::data_store_pilot2_molecular::m_my_molecules
contains the data of all molecules required by this processor to execute one epoch. Maps: molecule data_id to set of neighbors (including self: data_id); this is the set of molecules required in one call to fetch_datum by the data reader
Referenced by get_data_buf, exchange_data.
std::vector<std::vector<double> > lbann::data_store_pilot2_molecular::m_data_buffer
the buffers that will be passed to data_readers::fetch_datum
Referenced by setup, get_data_buf.
int lbann::data_store_pilot2_molecular::m_owner_rank
the process that "owns" the data, i.e, this is the only process whose m_reader will load data from disk
Referenced by setup, build_nabor_map, exchange_data.
bool lbann::data_store_pilot2_molecular::m_owner
true if this processor "owns" the data
Referenced by setup, build_nabor_map, exchange_data.
bool lbann::data_store_pilot2_molecular::m_shuffle
support for data_store_merge_samples
Referenced by set_no_shuffle.
lbann::data_store_pilot2_molecular::data_store_pilot2_molecular(generic_data_reader *reader, model *m)
ctor
References lbann::generic_data_store::set_name.
Referenced by copy.
lbann::data_store_pilot2_molecular::data_store_pilot2_molecular(const data_store_pilot2_molecular &)=default
copy ctor
data_store_pilot2_molecular& lbann::data_store_pilot2_molecular::operator=(const data_store_pilot2_molecular &)=default
operator=
data_store_pilot2_molecular* lbann::data_store_pilot2_molecular::copy() const override
References data_store_pilot2_molecular, ~data_store_pilot2_molecular, get_data_buf, setup.
lbann::data_store_pilot2_molecular::~data_store_pilot2_molecular() override
dtor
Referenced by copy.
void lbann::data_store_pilot2_molecular::get_data_buf(int data_id, int tid, std::vector< double > *&buf) override
References m_data_buffer, m_neighbors, m_my_molecules, m_pilot2_reader, lbann::pilot2_molecular_reader::get_num_features.
Referenced by copy.
void lbann::data_store_pilot2_molecular::setup() override
called by generic_data_reader::setup_data_store
References lbann::get_time, m_owner, lbann::generic_data_store::m_reader, lbann::generic_data_reader::get_compound_rank, lbann::generic_data_store::m_rank, m_owner_rank, lbann::generic_data_reader::get_role, lbann::generic_data_store::setup, lbann::generic_data_store::m_in_memory, m_pilot2_reader, lbann::generic_data_store::get_minibatch_index_vector, lbann::generic_data_store::m_master, lbann::generic_data_store::exchange_mb_indices, m_data_buffer, construct_data_store, build_nabor_map, exchange_data.
Referenced by copy.
void lbann::data_store_pilot2_molecular::clear_minibatch_indices()
needed to support data_reader_merge_samples (compound reader)
References lbann::generic_data_store::m_my_minibatch_indices_v.
Referenced by lbann::data_store_merge_features::~data_store_merge_features, lbann::data_store_merge_samples::setup.
void lbann::data_store_pilot2_molecular::add_minibatch_index(int idx)
needed to support data_reader_merge_samples (compound reader)
References lbann::generic_data_store::m_my_minibatch_indices_v.
void lbann::data_store_pilot2_molecular::set_no_shuffle()
needed to support data_reader_merge_samples (compound reader)
References m_shuffle.
void lbann::data_store_pilot2_molecular::construct_data_store()
fills in m_data
References m_pilot2_reader, lbann::pilot2_molecular_reader::get_word_size, lbann::pilot2_molecular_reader::get_features_8, lbann::pilot2_molecular_reader::get_num_samples_per_frame, lbann::generic_data_store::m_num_global_indices, lbann::pilot2_molecular_reader::get_num_features, fill_in_data.
Referenced by setup.
void lbann::data_store_pilot2_molecular::fill_in_data(const int data_id, const int num_samples_per_frame, const int num_features, double *features)
called by construct_data_store()
References m_pilot2_reader, lbann::pilot2_molecular_reader::get_frame, lbann::cnpy_utils::data, m_data, lbann::pilot2_molecular_reader::scale_data.
Referenced by construct_data_store.
void lbann::data_store_pilot2_molecular::build_nabor_map()
fills in m_neighbors
References m_owner, m_pilot2_reader, lbann::pilot2_molecular_reader::get_neighbors_data_size, m_owner_rank, lbann::generic_data_store::m_mpi_comm, lbann::pilot2_molecular_reader::get_neighbors_8, lbann::generic_data_store::m_shuffled_indices, lbann::pilot2_molecular_reader::get_frame, lbann::pilot2_molecular_reader::get_max_neighborhood, lbann::pilot2_molecular_reader::get_num_samples_per_frame, lbann::pilot2_molecular_reader::get_num_neighbors, m_neighbors.
Referenced by setup.
void lbann::data_store_pilot2_molecular::exchange_data() override
fills in m_my_molecules using non-blocking MPI send/recv
References lbann::get_time, get_required_molecules, lbann::generic_data_store::m_rank, m_my_molecules, m_pilot2_reader, lbann::pilot2_molecular_reader::get_num_features, lbann::cnpy_utils::data, m_owner_rank, lbann::generic_data_store::m_mpi_comm, m_owner, lbann::generic_data_store::m_np, m_data, lbann::generic_data_store::m_reader, lbann::generic_data_reader::get_role.
Referenced by setup.
void lbann::data_store_pilot2_molecular::get_required_molecules(std::unordered_set< int > &s, int p)
returns, in 's,' the set of molecules required for processor 'p' for the next epoch
References lbann::generic_data_store::m_all_minibatch_indices, m_neighbors.
Referenced by exchange_data.