lbann::lbann_callback_debug
execution_mode lbann::lbann_callback_debug::m_debug_phase
The phase to debug.
Referenced by on_batch_begin, on_forward_prop_begin, on_forward_prop_end, on_backward_prop_begin, on_backward_prop_end, on_batch_evaluate_begin, on_batch_evaluate_end, on_evaluate_forward_prop_begin, on_evaluate_forward_prop_end.
lbann::lbann_callback_debug::lbann_callback_debug(execution_mode phase=execution_mode::invalid, lbann_summary *summarizer=nullptr)
Debug a particular phase; use invalid to debug every phase.
References operator=.
Referenced by copy.
lbann::lbann_callback_debug::lbann_callback_debug(const lbann_callback_debug &)=default
lbann_callback_debug& lbann::lbann_callback_debug::operator=(const lbann_callback_debug &)=default
Referenced by lbann_callback_debug.
lbann_callback_debug* lbann::lbann_callback_debug::copy() const override
References lbann_callback_debug, on_batch_begin, on_forward_prop_begin, on_forward_prop_end, on_backward_prop_begin, on_backward_prop_end, on_batch_evaluate_begin, on_batch_evaluate_end, on_evaluate_forward_prop_begin, on_evaluate_forward_prop_end.
void lbann::lbann_callback_debug::on_batch_begin(model *m) override
Print that a batch is being started.
References m_debug_phase, invalid, lbann::model::get_execution_mode, _to_string.
Referenced by copy.
void lbann::lbann_callback_debug::on_forward_prop_begin(model *m, Layer *l) override
Print that forward prop for a layer is beginning.
References m_debug_phase, invalid, lbann::model::get_execution_mode, lbann::model::get_comm, lbann::lbann_comm::get_model_rank, lbann::lbann_comm::get_rank_in_model, lbann::model::get_cur_epoch, lbann::model::get_cur_step, _to_string, lbann::Layer::get_name, lbann::Layer::get_type.
Referenced by copy.
void lbann::lbann_callback_debug::on_forward_prop_end(model *m, Layer *l) override
Print that forward prop for a layer has completed.
References m_debug_phase, invalid, lbann::model::get_execution_mode, lbann::model::get_comm, lbann::lbann_comm::get_model_rank, lbann::lbann_comm::get_rank_in_model, lbann::model::get_cur_epoch, lbann::model::get_cur_step, _to_string, lbann::Layer::get_name, lbann::Layer::get_type.
Referenced by copy.
void lbann::lbann_callback_debug::on_backward_prop_begin(model *m, Layer *l) override
Print that backward prop for a layer is beginning.
References m_debug_phase, invalid, lbann::model::get_execution_mode, lbann::model::get_comm, lbann::lbann_comm::get_model_rank, lbann::lbann_comm::get_rank_in_model, lbann::model::get_cur_epoch, lbann::model::get_cur_step, _to_string, lbann::Layer::get_name, lbann::Layer::get_type.
Referenced by copy.
void lbann::lbann_callback_debug::on_backward_prop_end(model *m, Layer *l) override
Print that backward prop for a layer has completed.
References m_debug_phase, invalid, lbann::model::get_execution_mode, lbann::model::get_comm, lbann::lbann_comm::get_model_rank, lbann::lbann_comm::get_rank_in_model, lbann::model::get_cur_epoch, lbann::model::get_cur_step, _to_string, lbann::Layer::get_name, lbann::Layer::get_type.
Referenced by copy.
void lbann::lbann_callback_debug::on_batch_evaluate_begin(model *m) override
Print that an evaluation batch is being started.
References m_debug_phase, invalid, lbann::model::get_execution_mode, validation, lbann::model::get_cur_validation_step, testing, lbann::model::get_cur_testing_step, lbann::model::get_comm, lbann::lbann_comm::get_model_rank, lbann::lbann_comm::get_rank_in_model, _to_string.
Referenced by copy.
void lbann::lbann_callback_debug::on_batch_evaluate_end(model *m) override
Print that an evaluation batch has completed.
References m_debug_phase, invalid, lbann::model::get_execution_mode, validation, lbann::model::get_cur_validation_step, testing, lbann::model::get_cur_testing_step, lbann::model::get_comm, lbann::lbann_comm::get_model_rank, lbann::lbann_comm::get_rank_in_model, _to_string.
Referenced by copy.
void lbann::lbann_callback_debug::on_evaluate_forward_prop_begin(model *m, Layer *l) override
Print that an evaluation forward prop is beginning.
References m_debug_phase, invalid, lbann::model::get_execution_mode, validation, lbann::model::get_cur_validation_step, testing, lbann::model::get_cur_testing_step, lbann::model::get_comm, lbann::lbann_comm::get_model_rank, lbann::lbann_comm::get_rank_in_model, _to_string, lbann::Layer::get_name, lbann::Layer::get_type.
Referenced by copy.
void lbann::lbann_callback_debug::on_evaluate_forward_prop_end(model *m, Layer *l) override
Print that an evaluation forward prop has completed.
References m_debug_phase, invalid, lbann::model::get_execution_mode, validation, lbann::model::get_cur_validation_step, testing, lbann::model::get_cur_testing_step, lbann::model::get_comm, lbann::lbann_comm::get_model_rank, lbann::lbann_comm::get_rank_in_model, _to_string, lbann::Layer::get_name, lbann::Layer::get_type.
Referenced by copy.
std::string lbann::lbann_callback_debug::name() const override
Return this callback's name.