lbann::dropout
EvalType lbann::dropout< T_layout >::m_keep_prob
Probability of keeping each unit.
Referenced by lbann::dropout< T_layout >::operator=, lbann::dropout< T_layout >::get_description, lbann::dropout< T_layout >::fp_compute_cpu, lbann::dropout< T_layout >::bp_compute_cpu, lbann::dropout< T_layout >::fp_compute_gpu, lbann::dropout< T_layout >::bp_compute_gpu.
std::unique_ptr<AbsDistMat> lbann::dropout< T_layout >::m_mask
Current dropout mask (a scaled Bernoulli random matrix).
Referenced by lbann::dropout< T_layout >::operator=, lbann::dropout< T_layout >::setup_matrices, lbann::dropout< T_layout >::fp_compute_cpu, lbann::dropout< T_layout >::bp_compute_cpu.
lbann::dropout< T_layout >::dropout(lbann_comm *comm, EvalType keep_prob=EvalType(0.5), cudnn::cudnn_manager *cudnn=nullptr)
keep_prob dropout probability. Keep units with probabiliy keep_prob.
References DATA_PARALLEL, lbann::Layer::m_using_gpus, lbann::Layer::m_cudnn.
Referenced by lbann::dropout< T_layout >::copy.
lbann::dropout< T_layout >::dropout(const dropout &other)
dropout& lbann::dropout< T_layout >::operator=(const dropout &other)
References lbann::Layer::operator=, lbann::dropout< T_layout >::m_keep_prob, lbann::dropout< T_layout >::m_mask.
lbann::dropout< T_layout >::~dropout() override
dropout* lbann::dropout< T_layout >::copy() const override
Copy function. This function dynamically allocates memory for a layer instance and instantiates a copy. The caller is responsible for deallocating the instance.
References lbann::dropout< T_layout >::dropout.
std::string lbann::dropout< T_layout >::get_type() const override
Get the layer type's name. A layer type name should be brief, human-readable description of the layer's mathematical operation.
std::string lbann::dropout< T_layout >::get_description() const override
Get a human-readable description of the layer parameters.
References lbann::dropout< T_layout >::m_keep_prob, lbann::Layer::get_data_layout_string, lbann::dropout< T_layout >::get_data_layout.
void lbann::dropout< T_layout >::setup_matrices(const El::Grid &grid) override
Instantiate distributed matrices. If the layer has already been setup, this function should destroy all matrices and reinstantiate them. However, it is not guaranteed that derived classes will obey this behavior.
References lbann::Layer::setup_matrices, lbann::Layer::m_using_gpus, lbann::dropout< T_layout >::m_mask, lbann::Layer::get_activations.
data_layout lbann::dropout< T_layout >::get_data_layout() const override
Get data layout of the data tensors. We assume that the data layouts of the previous activations, activations, previous error signals, and error signals are the same. Each concrete layer that is templated on its data layout should override this function to return its template parameter.
Referenced by lbann::dropout< T_layout >::get_description.
void lbann::dropout< T_layout >::setup_gpu() override
Setup GPU objects. Called by the setup function if GPUs are enabled. The base method initializes GPU matrices for the previous activations, activations, previous error signals, and error signals. It also initializes cuDNN tensor descriptors.
References lbann::Layer::setup_gpu, LBANN_ERROR, lbann::Layer::m_cudnn.
void lbann::dropout< T_layout >::fp_compute() override
Perform the computation for the forward propagation step.
References lbann::Layer::m_using_gpus, lbann::dropout< T_layout >::fp_compute_gpu, lbann::dropout< T_layout >::fp_compute_cpu.
void lbann::dropout< T_layout >::bp_compute() override
Perform the computation for the backward propagation step.
References lbann::Layer::m_using_gpus, lbann::dropout< T_layout >::bp_compute_gpu, lbann::dropout< T_layout >::bp_compute_cpu.
void lbann::dropout< T_layout >::fp_setup_data(int mini_batch_size) override
Setup data for forward propagation. Base method gets previous activations from parent layers and resizes activations for the current mini-batch size.
References lbann::Layer::m_using_gpus, lbann::Layer::m_model, lbann::model::get_execution_mode, training, lbann::Layer::fp_setup_data.
void lbann::dropout< T_layout >::fp_compute_cpu()
References lbann::Layer::get_prev_activations, lbann::Layer::get_activations, lbann::Layer::m_model, lbann::model::get_execution_mode, training, lbann::dropout< T_layout >::m_keep_prob, lbann::dropout< T_layout >::m_mask, lbann::bernoulli_fill_procdet, lbann::get_fast_generator.
Referenced by lbann::dropout< T_layout >::fp_compute.
void lbann::dropout< T_layout >::bp_compute_cpu()
Adjust gradients for dropout in backprop.
References lbann::Layer::get_prev_error_signals, lbann::Layer::get_error_signals, lbann::Layer::m_model, lbann::model::get_execution_mode, training, lbann::dropout< T_layout >::m_keep_prob, lbann::dropout< T_layout >::m_mask.
Referenced by lbann::dropout< T_layout >::bp_compute.
void lbann::dropout< T_layout >::fp_compute_gpu()
References LBANN_ERROR, lbann::Layer::m_cudnn, lbann::Layer::m_model, lbann::model::get_execution_mode, training, lbann::dropout< T_layout >::m_keep_prob.
Referenced by lbann::dropout< T_layout >::fp_compute.
void lbann::dropout< T_layout >::bp_compute_gpu()
References LBANN_ERROR, lbann::Layer::m_cudnn, lbann::Layer::m_model, lbann::model::get_execution_mode, training, lbann::dropout< T_layout >::m_keep_prob, lbann::get_generator.
Referenced by lbann::dropout< T_layout >::bp_compute.