lbann::rmsprop
DataType lbann::rmsprop::m_decay_rate
Decay rate.
Referenced by unpack_scalars, operator=, get_description, step_compute.
DataType lbann::rmsprop::m_eps
Small factor to avoid division by zero.
Referenced by operator=, get_description, step_compute.
AbsDistMat* lbann::rmsprop::m_cache
RMSprop cache.
Referenced by rmsprop, operator=, ~rmsprop, setup, step_compute, save_to_checkpoint_shared, load_from_checkpoint_shared.
lbann::rmsprop::rmsprop(lbann_comm *comm, DataType learning_rate, DataType decay_rate, DataType eps=DataType(1e-8))
Constructor.
Referenced by copy.
lbann::rmsprop::rmsprop(const rmsprop &other)
Copy constructor.
References m_cache.
rmsprop & lbann::rmsprop::operator=(const rmsprop &other)
Copy assignment operator.
References lbann::optimizer::operator=, m_decay_rate, m_eps, m_cache.
lbann::rmsprop::~rmsprop() override
Destructor.
References m_cache.
rmsprop* lbann::rmsprop::copy() const override
Create a copy.
References rmsprop.
std::string lbann::rmsprop::get_type() const override
Get the optimizer name.
References get_description, setup, step_compute.
std::string lbann::rmsprop::get_description() const override
Get a human-readable description of the optimizer.
References lbann::optimizer::get_description, m_decay_rate, m_eps.
Referenced by get_type.
void lbann::rmsprop::setup(weights &w) override
Setup optimizer.
References lbann::optimizer::setup, m_cache, lbann::optimizer::m_gradient.
Referenced by get_type.
void lbann::rmsprop::step_compute(AbsDistMat &values, const AbsDistMat &gradient) override
Perform the computation in an optimization step.
References m_cache, m_decay_rate, lbann::optimizer::m_learning_rate, m_eps.
Referenced by get_type.
bool lbann::rmsprop::pack_scalars(persist &p)
References lbann::persist::write_datatype, lbann::train.
bool lbann::rmsprop::unpack_scalars(persist &p, struct packing_header *header)
References lbann::persist::read_datatype, lbann::train, lbann::rmsprop::packing_header::decay_rate, m_decay_rate.
void lbann::rmsprop::unpack_header(struct packing_header &header)
References lbann::rmsprop::packing_header::decay_rate, save_to_checkpoint_shared, load_from_checkpoint_shared.
bool lbann::rmsprop::save_to_checkpoint_shared(persist &p, std::string m_name) override
References lbann::optimizer::save_to_checkpoint_shared, m_cache, lbann::persist::write_distmat, lbann::train.
Referenced by unpack_header.
bool lbann::rmsprop::load_from_checkpoint_shared(persist &p, std::string m_name) override
References lbann::optimizer::load_from_checkpoint_shared, m_cache, lbann::persist::read_distmat, lbann::train.
Referenced by unpack_header.