lbann::lbann_callback_ltfb
lbann_comm* lbann::lbann_callback_ltfb::m_comm
LBANN communicator.
Referenced by operator=, setup, on_batch_begin.
int lbann::lbann_callback_ltfb::m_round_size
Number of minibatches in a round.
Referenced by operator=, on_batch_begin.
std::vector<weights*> lbann::lbann_callback_ltfb::m_local_weights
Weights from local model.
Referenced by lbann_callback_ltfb, operator=, ~lbann_callback_ltfb, setup, on_batch_begin.
lbann::lbann_callback_ltfb::lbann_callback_ltfb(int round_size, lbann_summary *summarizer=nullptr)
Constructor. round_size The number of minibatches in each round.
Referenced by copy.
lbann::lbann_callback_ltfb::lbann_callback_ltfb(const lbann_callback_ltfb &other)
References m_local_weights.
lbann_callback_ltfb & lbann::lbann_callback_ltfb::operator=(const lbann_callback_ltfb &other)
References m_comm, m_round_size, m_local_weights.
lbann::lbann_callback_ltfb::~lbann_callback_ltfb() override
References m_local_weights.
lbann_callback_ltfb* lbann::lbann_callback_ltfb::copy() const override
References lbann_callback_ltfb.
std::string lbann::lbann_callback_ltfb::name() const override
Return this callback's name.
References setup, on_batch_begin.
void lbann::lbann_callback_ltfb::setup(model *m) override
Set up LTFB.
References m_comm, lbann::model::get_comm, m_local_weights, lbann::model::get_weights, lbann::model::get_callbacks, LBANN_ERROR.
Referenced by name.
void lbann::lbann_callback_ltfb::on_batch_begin(model *m) override
Potentially run an LTFB round.
References lbann::model::get_execution_mode, lbann::model::get_cur_step, training, m_round_size, m_comm, lbann::lbann_comm::am_world_master, lbann::lbann_comm::get_model_rank, lbann::anonymous_namespace{callback_ltfb.cpp}::assign_partners, lbann::anonymous_namespace{callback_ltfb.cpp}::evaluate, lbann::model::get_weights, lbann::anonymous_namespace{callback_ltfb.cpp}::exchange_weights, m_local_weights, lbann::lbann_comm::am_model_master.
Referenced by name.