lbann::lbann_callback_gradient_check
DataType lbann::lbann_callback_gradient_check::m_step_size
Step size for numerical differentiation.
Referenced by on_test_begin.
bool lbann::lbann_callback_gradient_check::m_verbose
Whether to print results for each parameter.
Referenced by on_test_begin.
bool lbann::lbann_callback_gradient_check::m_fail_on_error
Whether to throw an exception for large gradient errors.
Referenced by on_test_begin.
lbann::lbann_callback_gradient_check::lbann_callback_gradient_check(DataType step_size=DataType(0), bool verbose=false, bool fail_on_error=false)
Constructor. step_size Step size for numerical differentiation. verbose Whether to print results for each parameter.
Referenced by copy.
lbann::lbann_callback_gradient_check::lbann_callback_gradient_check(const lbann_callback_gradient_check &)=default
lbann_callback_gradient_check& lbann::lbann_callback_gradient_check::operator=(const lbann_callback_gradient_check &)=default
lbann_callback_gradient_check* lbann::lbann_callback_gradient_check::copy() const override
References lbann_callback_gradient_check, on_test_begin.
void lbann::lbann_callback_gradient_check::on_test_begin(model *m) override
Called at the beginning of testing.
References comm, lbann::model::get_comm, lbann::model::get_layers, lbann::model::get_weights, compute_objective_function, m_step_size, lbann::model::get_current_mini_batch_size, lbann::model::get_objective_function, lbann::objective_function::differentiate, lbann::objective_function::compute_weight_regularization, lbann::lbann_comm::am_world_master, m_fail_on_error, m_verbose.
Referenced by copy.
std::string lbann::lbann_callback_gradient_check::name() const override
Return this callback's name.
References compute_objective_function.
DataType lbann::lbann_callback_gradient_check::compute_objective_function(model *m)
Compute objective function value. It is assumed that input data has already been loaded into the activations of the first layer.
References lbann::model::get_layers, lbann::model::get_objective_function, lbann::objective_function::start_evaluation, lbann::model::get_execution_mode, lbann::model::get_current_mini_batch_size, lbann::objective_function::finish_evaluation.
Referenced by name, on_test_begin.