lbann::greedy_layerwise_autoencoder
int lbann::greedy_layerwise_autoencoder::m_phase
Current training phase. If negative, the model is sequential.
Referenced by greedy_layerwise_autoencoder, operator=, set_phase, restore_sequential_model, forward_prop, backward_prop.
int lbann::greedy_layerwise_autoencoder::m_num_phases
Number of training phases.
Referenced by operator=, setup_layer_topology, train.
std::vector<int> lbann::greedy_layerwise_autoencoder::m_sections
Layer indices for the boundaries of model sections. The first half sections are considered as encoders and the second half as decoders. Each training phase consists of training an encoder and decoder while keeping the rest of the model frozen.
Referenced by operator=, setup_layer_topology, set_phase, restore_sequential_model, forward_prop, backward_prop.
Layer* lbann::greedy_layerwise_autoencoder::m_reconstruction
Reconstruction layer for training phases.
Referenced by ~greedy_layerwise_autoencoder, set_phase, restore_sequential_model, forward_prop, backward_prop.
lbann::greedy_layerwise_autoencoder::greedy_layerwise_autoencoder(lbann_comm *comm, int mini_batch_size, objective_function *obj_fn, optimizer *default_optimizer)
Constructor.
Referenced by copy.
lbann::greedy_layerwise_autoencoder::greedy_layerwise_autoencoder(const greedy_layerwise_autoencoder &)
Copy constructor.
References set_phase, m_phase.
greedy_layerwise_autoencoder & lbann::greedy_layerwise_autoencoder::operator=(const greedy_layerwise_autoencoder &)
Copy assignment operator.
References lbann::sequential_model::operator=, m_num_phases, m_sections, m_phase, set_phase.
lbann::greedy_layerwise_autoencoder::~greedy_layerwise_autoencoder() override
Destructor.
References m_reconstruction.
greedy_layerwise_autoencoder* lbann::greedy_layerwise_autoencoder::copy() const override
Create copy.
References greedy_layerwise_autoencoder.
std::string lbann::greedy_layerwise_autoencoder::name() const override
Get model name.
References train.
void lbann::greedy_layerwise_autoencoder::train(int num_epochs) override
Train greedy layerwise autoencoder.
References lbann::model::do_train_begin_cbs, m_num_phases, set_phase, lbann::model::get_terminate_training, lbann::model::reset_mode_and_model, training, lbann::model::do_epoch_begin_cbs, lbann::model::train_mini_batch, lbann::model::evaluate, validation, lbann::model::m_current_epoch, lbann::model::do_epoch_end_cbs, lbann::model::reset_epoch_statistics, restore_sequential_model, lbann::model::do_train_end_cbs.
Referenced by name.
void lbann::greedy_layerwise_autoencoder::setup_layer_topology() override
Set up topology of layer graph. Called in setup function. Determine model sections.
References lbann::sequential_model::setup_layer_topology, lbann::model::m_layers, m_sections, m_num_phases.
void lbann::greedy_layerwise_autoencoder::set_phase(int phase)
Set the greedy layerwise autoencoder to a training phase. During a phase, an encoder and decoder section of the model are trained while the rest of the model is frozen.
References restore_sequential_model, m_phase, m_sections, lbann::model::m_layers, m_reconstruction, MODEL_PARALLEL, lbann::model::m_comm, DATA_PARALLEL, lbann::Layer::set_name, lbann::Layer::add_parent_layer, lbann::model::m_objective_function, lbann::objective_function::get_terms, lbann::loss_function::set_target_layer.
Referenced by greedy_layerwise_autoencoder, operator=, train.
void lbann::greedy_layerwise_autoencoder::restore_sequential_model()
Set the greedy layerwise autoencover to a sequential model.
References m_phase, m_sections, lbann::model::m_layers, lbann::Layer::get_child_layers, lbann::Layer::get_parent_layers, m_reconstruction, lbann::model::m_objective_function, lbann::objective_function::get_terms, lbann::loss_function::set_target_layer.
Referenced by train, set_phase.
void lbann::greedy_layerwise_autoencoder::forward_prop(execution_mode mode) override
Forward prop step.
References m_phase, lbann::model::forward_prop, lbann::model::do_model_forward_prop_begin_cbs, m_sections, lbann::model::m_layers, lbann::model::do_layer_forward_prop_begin_cbs, lbann::Layer::forward_prop, lbann::model::do_layer_forward_prop_end_cbs, m_reconstruction, lbann::model::do_model_forward_prop_end_cbs.
void lbann::greedy_layerwise_autoencoder::backward_prop() override
Backward prop step.
References m_phase, lbann::model::backward_prop, lbann::model::do_model_backward_prop_begin_cbs, m_sections, lbann::model::do_layer_backward_prop_begin_cbs, m_reconstruction, lbann::Layer::back_prop, lbann::model::do_layer_backward_prop_end_cbs, lbann::model::m_layers, lbann::model::do_model_backward_prop_end_cbs.