lbann::loss_function
AbsDistMat* lbann::loss_function::m_gradient
Gradient matrix.
Referenced by lbann::cross_entropy_with_uncertainty::setup, loss_function, operator=, ~loss_function, setup, differentiate, save_to_checkpoint_shared, load_from_checkpoint_shared, lbann::polya_negloglike::setup.
lbann::loss_function::loss_function(EvalType scale_factor=EvalType(1))
Default constructor.
lbann::loss_function::loss_function(const loss_function &other)
Copy constructor.
References m_gradient.
loss_function & lbann::loss_function::operator=(const loss_function &other)
Copy assignment operator.
References lbann::objective_function_term::operator=, m_gradient.
Referenced by lbann::cross_entropy_with_uncertainty::operator=, lbann::polya_negloglike::operator=.
lbann::loss_function::~loss_function() override
Destructor.
References m_gradient.
void lbann::loss_function::set_target_layer(generic_target_layer *layer)
References lbann::objective_function_term::m_layers.
Referenced by lbann::greedy_layerwise_autoencoder::set_phase, lbann::greedy_layerwise_autoencoder::restore_sequential_model.
void lbann::loss_function::setup(model &m) override
Setup objective function term.
References lbann::objective_function_term::setup, lbann::objective_function_term::m_layers, lbann::model::get_layers, lbann::objective_function_term::m_weights, m_gradient.
Referenced by lbann::cross_entropy_with_uncertainty::setup, lbann::polya_negloglike::setup.
void lbann::loss_function::start_evaluation() override
Start evaluation of the objective function term.
References lbann::objective_function_term::m_layers, prediction, start_evaluate_compute.
EvalType lbann::loss_function::finish_evaluation() override
Finish evaluation of the objective function term.
References lbann::objective_function_term::m_scale_factor, lbann::objective_function_term::m_layers, prediction, finish_evaluate_compute.
void lbann::loss_function::differentiate() override
Compute the gradient of the objective function term. The gradient is computed w.r.t. the objective function term inputs.
References lbann::objective_function_term::m_scale_factor, lbann::objective_function_term::m_layers, prediction, m_gradient, differentiate_compute.
void lbann::loss_function::compute_weight_regularization() override
Loss functions do not directly contribute to the gradient update of the weight matrix, they are applied through backprop
References start_evaluate_compute, prediction, finish_evaluate_compute, differentiate_compute, save_to_checkpoint_shared, load_from_checkpoint_shared.
virtual void lbann::loss_function::start_evaluate_compute(const AbsDistMat &prediction, const AbsDistMat &ground_truth)=0
Start evaluation the loss function. This should not include the scale factor.
Referenced by compute_weight_regularization, start_evaluation.
virtual EvalType lbann::loss_function::finish_evaluate_compute(const AbsDistMat &prediction, const AbsDistMat &ground_truth)=0
Finish evaluation of the loss function. This should not include the scale factor.
Referenced by compute_weight_regularization, finish_evaluation.
virtual void lbann::loss_function::differentiate_compute(const AbsDistMat &prediction, const AbsDistMat &ground_truth, AbsDistMat &gradient)=0
Compute the loss function gradient. The gradient should be w.r.t. the prediction vector. This should not include the scale factor.
Referenced by compute_weight_regularization, differentiate.
bool lbann::loss_function::save_to_checkpoint_shared(lbann::persist &p) override
References lbann::persist::write_distmat, lbann::train, m_gradient.
Referenced by compute_weight_regularization.
bool lbann::loss_function::load_from_checkpoint_shared(lbann::persist &p) override
References lbann::persist::read_distmat, lbann::train, m_gradient.
Referenced by compute_weight_regularization.