lbann::adagrad
DataType lbann::adagrad::m_eps
Small factor to avoid division by zero.
Referenced by operator=, get_description, step_compute.
AbsDistMat* lbann::adagrad::m_cache
AdaGrad cache.
Referenced by adagrad, operator=, ~adagrad, setup, step_compute, save_to_checkpoint_shared, load_from_checkpoint_shared.
lbann::adagrad::adagrad(lbann_comm *comm, DataType learning_rate, DataType eps=DataType(1e-8))
Constructor.
Referenced by copy.
lbann::adagrad::adagrad(const adagrad &other)
Copy constructor.
References m_cache.
adagrad & lbann::adagrad::operator=(const adagrad &other)
Copy assignment operator.
References lbann::optimizer::operator=, m_eps, m_cache.
lbann::adagrad::~adagrad() override
Destructor.
References m_cache.
adagrad* lbann::adagrad::copy() const override
Create a copy.
References adagrad.
std::string lbann::adagrad::get_type() const override
Get the optimizer name.
References get_description, setup, step_compute, update.
std::string lbann::adagrad::get_description() const override
Get a human-readable description of the optimizer.
References lbann::optimizer::get_description, m_eps.
Referenced by get_type.
void lbann::adagrad::setup(weights &w) override
Setup optimizer.
References lbann::optimizer::setup, m_cache, lbann::optimizer::m_gradient.
Referenced by get_type.
void lbann::adagrad::step_compute(AbsDistMat &values, const AbsDistMat &gradient) override
Perform the computation in an optimization step.
References m_cache, lbann::optimizer::m_learning_rate, m_eps.
Referenced by get_type.
void lbann::adagrad::setup(AbsDistMat *parameters)
Set parameters to optimize and initialize optimizer.
void lbann::adagrad::update(const AbsDistMat *gradient)
Update parameters using objective function gradient.
Referenced by get_type.
std::string lbann::adagrad::name() const
References save_to_checkpoint_shared, load_from_checkpoint_shared.
bool lbann::adagrad::save_to_checkpoint_shared(persist &p, std::string m_name) override
References lbann::optimizer::save_to_checkpoint_shared, m_cache, lbann::persist::write_distmat, lbann::train.
Referenced by name.
bool lbann::adagrad::load_from_checkpoint_shared(persist &p, std::string m_name) override
References lbann::optimizer::load_from_checkpoint_shared, m_cache, lbann::persist::read_distmat, lbann::train.
Referenced by name.