lbann::batch_normalization
DataType lbann::batch_normalization< T_layout >::m_decay
Decay rate for the running statistics.
Referenced by lbann::batch_normalization< T_layout >::operator=, lbann::batch_normalization< T_layout >::fp_compute_cpu.
DataType lbann::batch_normalization< T_layout >::m_epsilon
Small number to avoid division by zero.
Referenced by lbann::batch_normalization< T_layout >::operator=.
bool lbann::batch_normalization< T_layout >::m_use_global_stats
Whether to use global statistics when training.
Referenced by lbann::batch_normalization< T_layout >::operator=.
AbsDistMat* lbann::batch_normalization< T_layout >::m_mean
Current minibatch means.
Referenced by lbann::batch_normalization< T_layout >::operator=, lbann::batch_normalization< T_layout >::deallocate_matrices.
AbsDistMat* lbann::batch_normalization< T_layout >::m_var
Current minibatch standard deviations.
Referenced by lbann::batch_normalization< T_layout >::operator=, lbann::batch_normalization< T_layout >::deallocate_matrices.
AbsDistMat* lbann::batch_normalization< T_layout >::m_mean_gradient
Gradient w.r.t. means.
Referenced by lbann::batch_normalization< T_layout >::operator=, lbann::batch_normalization< T_layout >::deallocate_matrices.
AbsDistMat* lbann::batch_normalization< T_layout >::m_var_gradient
Gradient w.r.t. standard deviations.
Referenced by lbann::batch_normalization< T_layout >::operator=, lbann::batch_normalization< T_layout >::deallocate_matrices.
AbsDistMat* lbann::batch_normalization< T_layout >::m_scale_gradient
Gradient w.r.t. scaling terms.
Referenced by lbann::batch_normalization< T_layout >::operator=, lbann::batch_normalization< T_layout >::deallocate_matrices.
AbsDistMat* lbann::batch_normalization< T_layout >::m_bias_gradient
Gradient w.r.t. bias terms.
Referenced by lbann::batch_normalization< T_layout >::operator=, lbann::batch_normalization< T_layout >::deallocate_matrices.
lbann::batch_normalization< T_layout >::batch_normalization(lbann_comm *comm, DataType decay=0.9, DataType epsilon=1e-5, bool use_global_stats=false, cudnn::cudnn_manager *cudnn=nullptr)
Set up batch normalization. decay Controls the momentum of the running mean/standard deviation averages. epsilon A small number to avoid division by zero. use_global_stats Whether to use global statistics when training.
References DATA_PARALLEL, lbann::Layer::m_using_gpus, lbann::Layer::m_cudnn.
Referenced by lbann::batch_normalization< T_layout >::copy.
lbann::batch_normalization< T_layout >::batch_normalization(const batch_normalization &other)
batch_normalization& lbann::batch_normalization< T_layout >::operator=(const batch_normalization &other)
References lbann::Layer::operator=, lbann::batch_normalization< T_layout >::m_decay, lbann::batch_normalization< T_layout >::m_epsilon, lbann::batch_normalization< T_layout >::m_use_global_stats, lbann::batch_normalization< T_layout >::deallocate_matrices, lbann::batch_normalization< T_layout >::m_mean, lbann::batch_normalization< T_layout >::m_var, lbann::batch_normalization< T_layout >::m_mean_gradient, lbann::batch_normalization< T_layout >::m_var_gradient, lbann::batch_normalization< T_layout >::m_scale_gradient, lbann::batch_normalization< T_layout >::m_bias_gradient.
std::string lbann::batch_normalization< T_layout >::get_description() const override
Returns description of ctor params
References lbann::Layer::get_data_layout_string, lbann::batch_normalization< T_layout >::get_data_layout.
virtual lbann::batch_normalization< T_layout >::~batch_normalization() override
References lbann::batch_normalization< T_layout >::deallocate_matrices.
batch_normalization* lbann::batch_normalization< T_layout >::copy() const override
Copy function. This function dynamically allocates memory for a layer instance and instantiates a copy. The caller is responsible for deallocating the instance.
References lbann::batch_normalization< T_layout >::batch_normalization.
std::string lbann::batch_normalization< T_layout >::get_type() const override
Get the layer type's name. A layer type name should be brief, human-readable description of the layer's mathematical operation.
void lbann::batch_normalization< T_layout >::setup_matrices(const El::Grid &grid) override
Instantiate distributed matrices. If the layer has already been setup, this function should destroy all matrices and reinstantiate them. However, it is not guaranteed that derived classes will obey this behavior.
References lbann::Layer::setup_matrices, lbann::batch_normalization< T_layout >::deallocate_matrices.
data_layout lbann::batch_normalization< T_layout >::get_data_layout() const override
Get data layout of the data tensors. We assume that the data layouts of the previous activations, activations, previous error signals, and error signals are the same. Each concrete layer that is templated on its data layout should override this function to return its template parameter.
Referenced by lbann::batch_normalization< T_layout >::get_description.
void lbann::batch_normalization< T_layout >::setup_data() override
Setup layer data. Called by the setup function. The base method sets the previous activation, activation, previous error signal, and error signal matrices to zero matrices with the proper dimensions. Matrix buffers are pinned if needed for GPU transfers.
References lbann::Layer::setup_data, lbann::Layer::m_weights, lbann::Layer::m_name, lbann::Layer::m_comm, lbann::Layer::m_cudnn, lbann::Layer::m_model, lbann::model::create_optimizer, lbann::model::add_weights, lbann::Layer::m_neuron_dims, lbann::Layer::m_frozen, lbann::Layer::is_frozen.
void lbann::batch_normalization< T_layout >::setup_gpu() override
Setup GPU objects. Called by the setup function if GPUs are enabled. The base method initializes GPU matrices for the previous activations, activations, previous error signals, and error signals. It also initializes cuDNN tensor descriptors.
References lbann::Layer::setup_gpu, lbann::Layer::m_cudnn.
void lbann::batch_normalization< T_layout >::fp_compute() override
Perform the computation for the forward propagation step.
References lbann::Layer::m_using_gpus, lbann::batch_normalization< T_layout >::fp_compute_gpu, lbann::batch_normalization< T_layout >::fp_compute_cpu.
void lbann::batch_normalization< T_layout >::bp_compute() override
Perform the computation for the backward propagation step.
References lbann::Layer::m_using_gpus, lbann::batch_normalization< T_layout >::bp_compute_gpu, lbann::batch_normalization< T_layout >::bp_compute_cpu.
void lbann::batch_normalization< T_layout >::fp_compute_gpu()
References lbann::Layer::m_model, lbann::model::get_execution_mode, training, lbann::Layer::get_prev_activations, lbann::Layer::m_cudnn, lbann::Layer::m_neuron_dims, lbann::Layer::m_num_neurons, lbann::Layer::m_weights.
Referenced by lbann::batch_normalization< T_layout >::fp_compute.
void lbann::batch_normalization< T_layout >::bp_compute_gpu()
References lbann::Layer::m_model, lbann::model::get_execution_mode, training, lbann::Layer::m_cudnn, lbann::Layer::m_weights, lbann::model::get_effective_mini_batch_size, lbann::Layer::get_prev_activations, lbann::Layer::m_neuron_dims, lbann::optimizer::add_to_gradient_staging.
Referenced by lbann::batch_normalization< T_layout >::bp_compute.
void lbann::batch_normalization< T_layout >::fp_compute_cpu()
References lbann::Layer::m_model, lbann::model::get_execution_mode, training, lbann::Layer::get_prev_activations, lbann::Layer::get_local_activations, lbann::Layer::m_neuron_dims, lbann::Layer::m_num_neurons, lbann::Layer::m_weights, lbann::Layer::m_comm, lbann::lbann_comm::allreduce, lbann::batch_normalization< T_layout >::m_decay.
Referenced by lbann::batch_normalization< T_layout >::fp_compute.
void lbann::batch_normalization< T_layout >::bp_compute_cpu()
References lbann::Layer::m_model, lbann::model::get_execution_mode, training, lbann::Layer::m_weights, lbann::Layer::get_prev_activations, lbann::Layer::get_local_prev_error_signals, lbann::Layer::get_local_error_signals, lbann::model::get_effective_mini_batch_size, lbann::Layer::m_neuron_dims, lbann::Layer::m_num_neurons, lbann::Layer::m_comm, lbann::lbann_comm::allreduce, lbann::optimizer::add_to_gradient_staging.
Referenced by lbann::batch_normalization< T_layout >::bp_compute.
void lbann::batch_normalization< T_layout >::deallocate_matrices()
References lbann::batch_normalization< T_layout >::m_mean, lbann::batch_normalization< T_layout >::m_var, lbann::batch_normalization< T_layout >::m_mean_gradient, lbann::batch_normalization< T_layout >::m_var_gradient, lbann::batch_normalization< T_layout >::m_scale_gradient, lbann::batch_normalization< T_layout >::m_bias_gradient.
Referenced by lbann::batch_normalization< T_layout >::operator=, lbann::batch_normalization< T_layout >::~batch_normalization, lbann::batch_normalization< T_layout >::setup_matrices.