lbann::target_layer
lbann::target_layer< T_io_buffer, T_layout >::target_layer(lbann_comm *comm, generic_input_layer *input_layer, int num_parallel_readers, std::map< execution_mode, generic_data_reader *> data_readers, bool shared_data_reader, bool for_regression=false)
References lbann::target_layer< T_io_buffer, T_layout >::validate_data_layout, lbann::target_layer< T_io_buffer, T_layout >::initialize_io_buffer, lbann::Layer::m_comm, lbann::generic_target_layer::io_buffer, lbann::generic_io_buffer::fetch_data_fn, lbann::io_layer::is_for_regression, lbann::generic_io_buffer::update_data_reader_fn, lbann::target_layer< T_io_buffer, T_layout >::operator=.
Referenced by lbann::target_layer< T_io_buffer, T_layout >::copy.
lbann::target_layer< T_io_buffer, T_layout >::target_layer(const target_layer &)=default
target_layer& lbann::target_layer< T_io_buffer, T_layout >::operator=(const target_layer &)=default
Referenced by lbann::target_layer< T_io_buffer, T_layout >::target_layer.
target_layer* lbann::target_layer< T_io_buffer, T_layout >::copy() const override
Copy function. This function dynamically allocates memory for a layer instance and instantiates a copy. The caller is responsible for deallocating the instance.
References lbann::target_layer< T_io_buffer, T_layout >::target_layer.
std::string lbann::target_layer< T_io_buffer, T_layout >::get_type() const override
Returns description of ctor params
References lbann::generic_target_layer::io_buffer, lbann::generic_io_buffer::get_type, lbann::target_layer< T_io_buffer, T_layout >::validate_data_layout.
void lbann::target_layer< T_io_buffer, T_layout >::validate_data_layout()
Referenced by lbann::target_layer< T_io_buffer, T_layout >::target_layer, lbann::target_layer< T_io_buffer, T_layout >::get_type.
void lbann::target_layer< T_io_buffer, T_layout >::initialize_io_buffer(lbann_comm *comm, int num_parallel_readers, std::map< execution_mode, generic_data_reader *> data_readers)
References comm.
Referenced by lbann::target_layer< T_io_buffer, T_layout >::target_layer.
data_layout lbann::target_layer< T_io_buffer, T_layout >::get_data_layout() const override
Get data layout of the data tensors. We assume that the data layouts of the previous activations, activations, previous error signals, and error signals are the same. Each concrete layer that is templated on its data layout should override this function to return its template parameter.
void lbann::target_layer< partitioned_io_buffer, data_layout::MODEL_PARALLEL >::validate_data_layout()
void lbann::target_layer< partitioned_io_buffer, data_layout::DATA_PARALLEL >::validate_data_layout()
void lbann::target_layer< distributed_io_buffer, data_layout::MODEL_PARALLEL >::validate_data_layout()
void lbann::target_layer< distributed_io_buffer, data_layout::DATA_PARALLEL >::validate_data_layout()