lbann::protobuf_utils
void lbann::protobuf_utils::load_prototext(const bool master, const int argc, char **argv, std::vector< lbann_data::LbannPB *> &models_out)
convience wrapper: calls parse_prototext_filenames_from_command_line(), then load_prototext(), then verify_prototext(). This is the only function that needs to be called from, e.g, model_zoo/lbann.cpp; the three called functions are made public for testing.
References parse_prototext_filenames_from_command_line, read_in_prototext_files, verify_prototext.
void lbann::protobuf_utils::parse_prototext_filenames_from_command_line(bool master, int argc, char **argv, std::vector< prototext_fn_triple > &names)
parses the command line for model=<string> reader=<string> optimizer=<string> and their multi counterparts: model={<string_1>,<string_2>,...} reader={<string_1>,<string_2>,...} optimizer={<string_1>,<string_2>,...} If the multi-model option is given, the reader and optimzier can either be single, or contain the same number of filenames as does the model={...} specification
References lbann::prototext_fn_triple::model, lbann::prototext_fn_triple::reader, lbann::prototext_fn_triple::optimizer.
Referenced by load_prototext.
void lbann::protobuf_utils::read_in_prototext_files(bool master, std::vector< prototext_fn_triple > &names, std::vector< lbann_data::LbannPB *> &models_out)
References read_prototext_file.
Referenced by load_prototext.
void lbann::protobuf_utils::verify_prototext(bool master, const std::vector< lbann_data::LbannPB *> &models)
attempts to verify the all models are valid, and contain an optimizer and reader
Referenced by load_prototext.