lbann::weights_initializer
lbann_comm* lbann::weights_initializer::m_comm
LBANN communicator.
Referenced by construct_matrix.
lbann::weights_initializer::weights_initializer(lbann_comm *comm)
Constructor.
References ~weights_initializer, copy, construct_matrix, initialize_entries.
virtual lbann::weights_initializer::~weights_initializer()=default
Destructor.
Referenced by weights_initializer.
virtual weights_initializer* lbann::weights_initializer::copy() const =0
Create a copy.
Referenced by weights_initializer, lbann::weights::weights, lbann::weights::operator=.
AbsDistMat * lbann::weights_initializer::construct_matrix(int height=0, int width=0, El::Distribution col_dist=El::STAR, El::Distribution row_dist=El::STAR) const
Construct a weights matrix with the initialization scheme. The caller is responsible for deallocating the matrix.
References m_comm, lbann::lbann_comm::get_model_grid, initialize_entries.
Referenced by weights_initializer, lbann::weights::setup.
virtual void lbann::weights_initializer::initialize_entries(AbsDistMat &weights_matrix) const =0
Initialize entries in a weights matrix.
Referenced by lbann::glorot_normal_initializer::copy, lbann::glorot_uniform_initializer::copy, lbann::he_normal_initializer::copy, lbann::he_uniform_initializer::copy, weights_initializer, lbann::constant_initializer::copy, lbann::uniform_initializer::copy, lbann::normal_initializer::copy, construct_matrix.