lbann::lbann_callback_check_init
lbann::lbann_callback_check_init::lbann_callback_check_init()
References operator=.
Referenced by copy.
lbann::lbann_callback_check_init::lbann_callback_check_init(const lbann_callback_check_init &)=default
lbann_callback_check_init& lbann::lbann_callback_check_init::operator=(const lbann_callback_check_init &)=default
Referenced by lbann_callback_check_init.
lbann_callback_check_init* lbann::lbann_callback_check_init::copy() const override
References lbann_callback_check_init, on_train_begin.
void lbann::lbann_callback_check_init::on_train_begin(model *m) override
Check initializations.
References lbann::model::get_cur_epoch, comm, lbann::model::get_comm, lbann::lbann_comm::am_world_master, lbann::lbann_comm::get_num_models, lbann::model::get_weights, lbann::model, lbann::lbann_comm::global_barrier, lbann::lbann_comm::get_model_rank, lbann::lbann_comm::recv, check_equal, lbann::lbann_comm::get_rank_in_model, lbann::lbann_comm::send.
Referenced by copy.
std::string lbann::lbann_callback_check_init::name() const override
Return this callback's name.
References check_equal.
bool lbann::lbann_callback_check_init::check_equal(const Mat &x, const Mat &y) const
Return true if x == y.
Referenced by name, on_train_begin.