lbann::weights
friend class optimizer
std::string lbann::weights::m_name
Weights name. See get_name function.
Referenced by set_name, get_name, weights, operator=, setup, save_to_checkpoint_shared, write_proto, load_from_checkpoint_shared.
lbann_comm* lbann::weights::m_comm
Reference to LBANN communicator.
Referenced by weights, operator=, write_proto.
cudnn::cudnn_manager* lbann::weights::m_cudnn
Reference to cuDNN manager.
Referenced by get_cudnn_manager, lbann::optimizer::setup, weights, operator=, setup, setup_gpu, get_values, set_values, set_value, get_values_view.
std::vector<int> lbann::weights::m_matrix_height_dims
Tensor dimensions corresponding to matrix height. See get_matrix_height_dims function.
Referenced by get_matrix_height_dims, operator=, setup.
std::vector<int> lbann::weights::m_matrix_width_dims
Tensor dimensions corresponding to matrix width. See get_matrix_width_dims function.
Referenced by get_matrix_width_dims, operator=, setup.
AbsDistMat* lbann::weights::m_values
Weights matrix.
Referenced by lbann::optimizer::step, weights, operator=, ~weights, setup, setup_gpu, get_values, set_values, set_value, get_values_view, save_to_checkpoint_shared, write_proto, load_from_checkpoint_shared.
weights_initializer* lbann::weights::m_initializer
Weights initializer. Default is zero initialization.
Referenced by get_initializer, weights, operator=, ~weights, setup, set_initializer.
optimizer* lbann::weights::m_optimizer
Weights optimizer. Default is nullptr, which corresponds to no optimizer.
Referenced by get_optimizer, weights, operator=, ~weights, setup, set_optimizer, save_to_checkpoint_shared, load_from_checkpoint_shared.
bool lbann::weights::m_frozen
Avoid weight update if frozen
Referenced by get_optimizer, freeze, unfreeze, is_frozen, operator=.
lbann::weights::weights(lbann_comm *comm, cudnn::cudnn_manager *cudnn=nullptr)
References m_name, m_initializer, m_comm.
Referenced by copy.
lbann::weights::weights(const weights &other)
References m_values, m_initializer, lbann::weights_initializer::copy, m_optimizer, lbann::optimizer::copy, lbann::optimizer::set_weights, m_cudnn, get_matrix_height, get_matrix_width.
weights & lbann::weights::operator=(const weights &other)
References m_name, m_comm, m_cudnn, m_matrix_height_dims, m_matrix_width_dims, m_values, m_initializer, m_optimizer, lbann::weights_initializer::copy, lbann::optimizer::copy, get_matrix_height, get_matrix_width, m_frozen.
lbann::weights::~weights()
References m_values, m_initializer, m_optimizer.
void lbann::weights::set_name(const std::string name)
Set weights name. Each set of weights in a model should have a unique, human-readable name.
References m_name.
Referenced by lbann::proto::construct_weights.
std::string lbann::weights::get_name() const
Get weights name.
References m_name.
Referenced by lbann::lbann_callback_imcomm::do_summary, lbann::lbann_callback_timeline::on_optimize_end, lbann::optimizer::get_description.
virtual weights* lbann::weights::copy() const
Create a copy of the weights. This function dynamically allocates memory for a weights instance and instantiates a copy. The caller is responsible for deallocating the instance.
References weights, setup, get_dims.
void lbann::weights::setup(int size)
Setup weights as a vector. The weight matrix is setup as a (size x 1) matrix in STAR,STAR format.
Referenced by copy, setup.
void lbann::weights::setup(std::vector< int > dims)
Setup weights as a tensor. The weight matrix is setup as a (prod(dims) x 1) matrix in STAR,STAR format.
References setup.
void lbann::weights::setup(int matrix_height, int matrix_width, El::Distribution col_dist, El::Distribution row_dist)
Setup weights as a matrix. The weight matrix is setup as a (matrix_height x matrix_width) matrix in col_dist,row_dist format.
References setup.
void lbann::weights::setup(std::vector< int > matrix_height_dims, std::vector< int > matrix_width_dims, El::Distribution col_dist, El::Distribution row_dist)
Setup weights as a matrix with tensor dimensions. The weight matrix is setup as a (prod(matrix_height_dims) x prod(matrix_width_dims)) matrix in col_dist,row_dist format.
References m_values, m_matrix_height_dims, m_matrix_width_dims, m_name, get_dims_string, m_initializer, lbann::weights_initializer::construct_matrix, get_matrix_height, get_matrix_width, m_cudnn, setup_gpu, m_optimizer, lbann::optimizer::setup.
std::vector< int > lbann::weights::get_dims() const
Get weight tensor dimensions. The dimensions are sorted in decreasing order of the data strides. This is a generalization of the "NCHW/NHWC" notation commonly used to describe image data.These dimensions are obtained by concatenating the matrix width dimensions with the matrix height dimensions (in that order). If the weight matrix is duplicated on all processes (i.e. in STAR,STAR layout) and the local matrices are fully-packed, the tensor data is fully-packed. If the matrix is STAR,STAR and the local matrices are not fully-packed, the tensor data is fully-packed w.r.t. the matrix height dimensions.
References get_matrix_width_dims, get_matrix_height_dims.
Referenced by copy, set_value, write_proto.
int lbann::weights::get_size() const
Get number of weights.
References get_matrix_height, get_matrix_width.
Referenced by lbann::optimizer::add_to_gradient, lbann::optimizer::add_to_gradient_staging, lbann::optimizer::step, set_value.
const std::vector<int>& lbann::weights::get_matrix_height_dims() const
Get tensor dimensions corresponding to weight matrix height. The dimensions are sorted in decreasing order of strides. Matrix rows are fully-packed w.r.t. the matrix height dimensions.
References m_matrix_height_dims.
Referenced by get_dims, get_matrix_height.
const std::vector<int>& lbann::weights::get_matrix_width_dims() const
Get tensor dimensions corresponding to weight matrix width. The dimensions are sorted in decreasing order of strides. Matrix columns are fully-packed w.r.t. the matrix width dimensions.
References m_matrix_width_dims, get_matrix_height, get_matrix_width.
Referenced by get_dims, get_matrix_width.
int lbann::weights::get_matrix_height() const
Get weight matrix height. If there are no matrix height dimensions, the height is one.
References get_matrix_height_dims.
Referenced by get_size, get_matrix_width_dims, lbann::adam::adam, lbann::adam::operator=, lbann::optimizer::setup, lbann::sgd::sgd, lbann::sgd::operator=, weights, operator=, setup, set_value, write_proto.
int lbann::weights::get_matrix_width() const
Get weight matrix width. If there are no matrix width dimensions, the width is one.
References get_matrix_width_dims.
Referenced by get_size, get_matrix_width_dims, lbann::adam::adam, lbann::adam::operator=, lbann::optimizer::setup, lbann::sgd::sgd, lbann::sgd::operator=, weights, operator=, setup, set_value, write_proto.
cudnn::cudnn_manager* lbann::weights::get_cudnn_manager()
Get reference to cuDNN manager.
References m_cudnn.
weights_initializer& lbann::weights::get_initializer()
Get weights initializer.
References m_initializer.
const weights_initializer& lbann::weights::get_initializer() const
Get weights initializer (const).
References m_initializer, set_initializer.
void lbann::weights::set_initializer(weights_initializer *initializer)
Set weights initializer. This takes ownership of the initializer and deallocates it during destruction.
References m_initializer.
Referenced by get_initializer, lbann::proto::construct_weights.
optimizer* lbann::weights::get_optimizer()
Get weights optimizer.
References m_frozen, m_optimizer.
Referenced by lbann::lbann_callback_imcomm::do_summary.
const optimizer* lbann::weights::get_optimizer() const
Get weights optimizer (const).
References m_frozen, m_optimizer, set_optimizer, get_values, set_values, set_value, get_values_view.
void lbann::weights::set_optimizer(optimizer *opt)
Set weights optimizer. This takes ownership of the optimizer and deallocates it during destruction.
References m_optimizer.
Referenced by get_optimizer, lbann::proto::construct_weights.
const AbsDistMat & lbann::weights::get_values()
Get the weight matrix.
References m_values, m_cudnn.
Referenced by get_optimizer, lbann::lbann_callback_optimizerwise_adaptive_learning_rate::optimizer_schedule, lbann::optimizer::setup, lbann::optimizer::step, get_values_view.
void lbann::weights::set_values(const AbsDistMat &values)
Set the weight matrix.
References m_values, m_cudnn.
Referenced by get_optimizer.
void lbann::weights::set_value(DataType value, int index)
Set a weight value.
References get_size, get_matrix_height.
Referenced by get_optimizer, set_value.
void lbann::weights::set_value(DataType value, std::vector< int > pos)
Set an entry in the weight tensor.
References get_dims, set_value.
void lbann::weights::set_value(DataType value, int row, int col)
Set an entry in the weight matrix.
References get_matrix_height, get_matrix_width, m_cudnn, m_values.
void lbann::weights::get_values_view(AbsDistMat &values_v)
Get a view into the weight matrix. If values_v has a different matrix distribution than the weight matrix, the matrix values are copied into values_v.
References get_values, m_cudnn, m_values.
Referenced by get_optimizer.
void lbann::weights::freeze()
References m_frozen.
void lbann::weights::unfreeze()
References m_frozen.
bool lbann::weights::is_frozen() const
References m_frozen, save_to_checkpoint_shared, load_from_checkpoint_shared, write_proto.
bool lbann::weights::save_to_checkpoint_shared(persist &p)
References m_name, m_values, lbann::persist::write_distmat, lbann::model, m_optimizer, lbann::optimizer::save_to_checkpoint_shared.
Referenced by is_frozen.
bool lbann::weights::load_from_checkpoint_shared(persist &p)
References m_name, m_values, lbann::persist::read_distmat, lbann::model, m_optimizer, lbann::optimizer::load_from_checkpoint_shared.
Referenced by is_frozen.
void lbann::weights::write_proto(lbann_data::WeightsData *proto) const
Write weights to proto file
References m_name, get_dims, get_matrix_height, get_matrix_width, m_values, m_comm, lbann::lbann_comm::am_world_master.
Referenced by is_frozen.
void lbann::weights::setup_gpu()
Setup GPU objects for weights.
References m_values, m_cudnn.
Referenced by setup.
std::string lbann::weights::get_dims_string(const std::vector< int > &height_dims, const std::vector< int > &width_dims)
Get string describing weight tensor dimensions. height_dims and width_dims are the dimensions of the weight matrix.
Referenced by setup.