lbann::csv_reader
char lbann::csv_reader::m_separator
String value that separates data.
Referenced by set_separator, operator=, load, fetch_line, fetch_line_label_response.
int lbann::csv_reader::m_skip_cols
Number of columns (from the left) to skip.
Referenced by set_skip_cols, get_linearized_data_size, operator=, load, fetch_line, fetch_line_label_response.
int lbann::csv_reader::m_skip_rows
Number of rows to skip.
Referenced by set_skip_rows, operator=, load.
bool lbann::csv_reader::m_has_header
Whether the CSV file has a header.
Referenced by set_has_header, operator=, load.
int lbann::csv_reader::m_label_col
Column containing labels. -1 is used for the last column. The label column ignores skipped columns, and can be among columns that are skipped.
Referenced by set_label_col, get_linearized_data_size, operator=, load, fetch_line_label_response.
int lbann::csv_reader::m_response_col
Column containing responses; functions the same as the label column.
Referenced by set_response_col, operator=, load, fetch_line_label_response.
bool lbann::csv_reader::m_disable_labels
Whether to fetch labels.
Referenced by disable_labels, operator=, load, fetch_line_label_response.
bool lbann::csv_reader::m_disable_responses
Whether to fetch responses.
Referenced by enable_responses, operator=, load, fetch_line_label_response.
int lbann::csv_reader::m_num_cols
Number of columns (including the label column and skipped columns).
Referenced by get_linearized_data_size, operator=, load, fetch_line, fetch_line_label_response.
int lbann::csv_reader::m_num_samples
Number of samples.
Referenced by operator=, load.
int lbann::csv_reader::m_num_labels
Number of label classes.
Referenced by get_num_labels, get_linearized_label_size, operator=, load.
std::vector<std::ifstream*> lbann::csv_reader::m_ifstreams
Input file streams (per-thread).
Referenced by csv_reader, operator=, ~csv_reader, load, fetch_raw_line, setup_ifstreams.
std::vector<std::streampos> lbann::csv_reader::m_index
Index mapping lines (samples) to their start offset within the file. This excludes the header, but includes a final entry indicating the length of the file.
Referenced by operator=, load, fetch_raw_line.
std::vector<int> lbann::csv_reader::m_labels
Store labels.
Referenced by operator=, load, fetch_label.
std::vector<DataType> lbann::csv_reader::m_responses
Store responses.
Referenced by operator=, load, fetch_response.
std::unordered_map<int, std::function<DataType(const std::string&)> > lbann::csv_reader::m_col_transforms
Per-column transformation functions.
Referenced by set_column_transform, operator=, fetch_line, fetch_line_label_response.
std::function<int(const std::string&)> lbann::csv_reader::m_label_transform
Label transform function that converts to an int.
Referenced by set_label_transform, operator=, load.
std::function<DataType(const std::string&)> lbann::csv_reader::m_response_transform
Response transform function that converts to a DataType.
Referenced by set_response_transform, operator=, load.
lbann::csv_reader::csv_reader(bool shuffle=true)
This defaults to using the last column for the label/response.
Referenced by copy.
lbann::csv_reader::csv_reader(const csv_reader &)
References m_ifstreams, setup_ifstreams.
csv_reader & lbann::csv_reader::operator=(const csv_reader &)
References lbann::generic_data_reader::operator=, m_separator, m_skip_cols, m_skip_rows, m_has_header, m_label_col, m_response_col, m_disable_labels, m_disable_responses, m_num_cols, m_num_samples, m_num_labels, m_index, m_labels, m_responses, m_col_transforms, m_label_transform, m_response_transform, m_ifstreams, setup_ifstreams.
lbann::csv_reader::~csv_reader() override
References m_ifstreams.
csv_reader* lbann::csv_reader::copy() const override
References csv_reader.
std::string lbann::csv_reader::get_type() const override
Return this data_reader's type
void lbann::csv_reader::set_label_col(int col)
Set the label column.
References m_label_col.
Referenced by lbann::data_reader_nci::data_reader_nci.
void lbann::csv_reader::set_response_col(int col)
Set the response column.
References m_response_col.
Referenced by lbann::data_reader_nci::data_reader_nci.
void lbann::csv_reader::disable_labels(bool b=true)
Disable fetching labels.
References m_disable_labels.
void lbann::csv_reader::enable_responses(bool b=false)
Enable fetching responses (disabled by default).
References m_disable_responses.
Referenced by lbann::data_reader_nci::data_reader_nci.
void lbann::csv_reader::set_separator(char sep)
Set the column separator (default is ',').
References m_separator.
Referenced by lbann::data_reader_nci::data_reader_nci.
void lbann::csv_reader::set_skip_cols(int cols)
Set the number of columns (from the left) to skip; default 0.
References m_skip_cols.
Referenced by lbann::data_reader_nci::data_reader_nci.
void lbann::csv_reader::set_skip_rows(int rows)
Set the number of rows (from the top) to skip; default 0.
References m_skip_rows.
Referenced by lbann::data_reader_nci::data_reader_nci.
void lbann::csv_reader::set_has_header(bool b)
Set whether the CSV file has a header; default true.
References m_has_header.
Referenced by lbann::data_reader_nci::data_reader_nci.
void lbann::csv_reader::set_column_transform(int col, std::function< DataType(const std::string &)> f)
Supply a custom transform to convert an input string to a numerical value. col The column to apply this transform to; do not account for skipped columns. f The transform to apply.
References m_col_transforms.
void lbann::csv_reader::set_label_transform(std::function< int(const std::string &)> f)
Supply a custom transform to convert the label column to an integer. Note that the label should be an integer starting from 0.
References m_label_transform.
Referenced by lbann::data_reader_nci::data_reader_nci.
void lbann::csv_reader::set_response_transform(std::function< DataType(const std::string &)> f)
Supply a custom transform to convert the response column to a DataType.
References m_response_transform, load.
void lbann::csv_reader::load() override
This parses the header of the CSV to determine column information.
References setup_ifstreams, m_ifstreams, skip_rows, m_skip_rows, m_num_cols, m_separator, m_skip_cols, m_disable_labels, m_label_col, m_disable_responses, m_response_col, lbann::generic_data_reader::get_data_filename, m_has_header, m_index, m_label_transform, m_labels, m_response_transform, m_responses, m_num_labels, m_num_samples, lbann::generic_data_reader::m_shuffled_indices, lbann::generic_data_reader::select_subset_of_data.
Referenced by set_response_transform.
int lbann::csv_reader::get_num_labels() const override
Return the number of labels (classes) in this dataset.
References m_num_labels.
int lbann::csv_reader::get_linearized_data_size() const override
Get the linearized size (i.e. number of elements) in a sample.
References m_label_col, m_skip_cols, m_num_cols.
Referenced by get_data_dims.
int lbann::csv_reader::get_linearized_label_size() const override
Get the linearized size (i.e. number of elements) in a label.
References m_num_labels.
const std::vector<int> lbann::csv_reader::get_data_dims() const override
Get the dimensions of the data.
References get_linearized_data_size, fetch_line_label_response, setup_data_store, fetch_datum, fetch_label, fetch_response, fetch_line, skip_rows, setup_ifstreams, fetch_raw_line.
std::vector< DataType > lbann::csv_reader::fetch_line_label_response(int data_id)
Return the parsed CSV line and store the label and response in the m_labels and m_responses vectors, respectively. The label and response are not present in the vector. (Made public to support data store functionality)
References fetch_raw_line, m_num_cols, m_separator, m_disable_labels, m_label_col, m_disable_responses, m_response_col, m_skip_cols, m_col_transforms.
Referenced by get_data_dims, fetch_datum, lbann::data_store_csv::setup, lbann::data_store_csv::get_data_buf_DataType, lbann::data_store_csv::populate_datastore.
void lbann::csv_reader::setup_data_store(model *m) override
sets up a data_store.
References lbann::generic_data_reader::m_data_store, lbann::generic_data_store::setup.
Referenced by get_data_dims.
bool lbann::csv_reader::fetch_datum(Mat &X, int data_id, int mb_idx, int tid) override
Fetch the data associated with data_id. Note this does not normalize the data.
References lbann::generic_data_reader::m_data_store, lbann::generic_data_store::get_data_buf_DataType, fetch_line_label_response.
Referenced by get_data_dims.
bool lbann::csv_reader::fetch_label(Mat &Y, int data_id, int mb_idx, int tid) override
Fetch the label associated with data_id.
References m_labels.
Referenced by get_data_dims.
bool lbann::csv_reader::fetch_response(Mat &Y, int data_id, int mb_idx, int tid) override
Fetch the response associated with data_id.
References m_responses.
Referenced by get_data_dims.
std::vector< DataType > lbann::csv_reader::fetch_line(int data_id)
Return the parsed CSV line. This does not extract the label/response.
References fetch_raw_line, m_num_cols, m_separator, m_skip_cols, m_col_transforms.
Referenced by get_data_dims.
void lbann::csv_reader::skip_rows(std::ifstream &s, int rows)
Skip rows in an ifstream.
Referenced by get_data_dims, load.
void lbann::csv_reader::setup_ifstreams()
Initialize the ifstreams vector.
References m_ifstreams, lbann::generic_data_reader::get_file_dir, lbann::generic_data_reader::get_data_filename.
Referenced by get_data_dims, csv_reader, operator=, load.
std::string lbann::csv_reader::fetch_raw_line(int data_id)
Return a raw line from the CSV file. (Made public to support data store functionality)
References m_ifstreams, m_index.
Referenced by get_data_dims, fetch_line, fetch_line_label_response.