lbann::boolean_false_positives_metric
lbann::boolean_false_positives_metric::boolean_false_positives_metric(lbann_comm *comm)
References operator=, ~boolean_false_positives_metric.
Referenced by copy.
lbann::boolean_false_positives_metric::boolean_false_positives_metric(const boolean_false_positives_metric &other)=default
boolean_false_positives_metric& lbann::boolean_false_positives_metric::operator=(const boolean_false_positives_metric &other)=default
Referenced by boolean_false_positives_metric.
virtual lbann::boolean_false_positives_metric::~boolean_false_positives_metric()=default
Referenced by boolean_false_positives_metric.
boolean_false_positives_metric* lbann::boolean_false_positives_metric::copy() const override
Copy function.
References boolean_false_positives_metric.
std::string lbann::boolean_false_positives_metric::name() const override
Return a string name for this metric.
std::string lbann::boolean_false_positives_metric::get_unit() const override
Return a display unit for this metric. Default is an empty string. This is overriden if the metric has units, e.g. "%" or "sec".
References evaluate_compute, prediction.
EvalType lbann::boolean_false_positives_metric::evaluate_compute(const AbsDistMat &prediction, const AbsDistMat &ground_truth) override
Computation to evaluate the metric function. This returns the sum of metric values across the mini-batch, not the mean value.
References lbann::metric::get_comm, lbann::lbann_comm::allreduce.
Referenced by get_unit.