lbann::persist
int lbann::persist::m_rank
uint64_t lbann::persist::m_bytes
int lbann::persist::m_model_fd
int lbann::persist::m_train_fd
int lbann::persist::m_validate_fd
char lbann::persist::m_model_filename[1024][1024]
char lbann::persist::m_train_filename[1024][1024]
char lbann::persist::m_validate_filename[1024][1024]
char lbann::persist::m_checkpoint_dir[1024][1024]
Referenced by lbann::save_rng_to_checkpoint_shared, lbann::load_rng_from_checkpoint_shared.
lbann::persist::persist()
lbann::persist::~persist()
int lbann::persist::get_rank() const
Referenced by lbann::generic_input_layer::save_to_checkpoint_shared, lbann::generic_input_layer::load_from_checkpoint_shared, lbann::io_layer::io_layer, lbann::generic_data_reader::save_to_checkpoint_shared, lbann::generic_data_reader::load_from_checkpoint_shared, lbann::metric::save_to_checkpoint_shared, lbann::metric::load_from_checkpoint_shared, lbann::model::save_to_checkpoint_shared, lbann::model::load_from_checkpoint_shared, lbann::sequential_model::save_to_checkpoint_shared, lbann::sequential_model::load_from_checkpoint_shared, lbann::adam::save_to_checkpoint_shared, lbann::adam::load_from_checkpoint_shared, lbann::sgd::save_to_checkpoint_shared, lbann::sgd::load_from_checkpoint_shared.
void lbann::persist::open_checkpoint(const char *dir, bool per_rank, bool val_end)
References lbann::makedir, lbann::openwrite.
Referenced by lbann::lbann_callback_checkpoint::checkpointShared.
void lbann::persist::close_checkpoint()
References lbann::closewrite.
Referenced by lbann::lbann_callback_checkpoint::checkpointShared.
void lbann::persist::open_restart(const char *dir, bool per_rank)
References lbann::openread.
Referenced by lbann::lbann_callback_checkpoint::restartShared.
void lbann::persist::close_restart()
References lbann::closeread.
Referenced by lbann::lbann_callback_checkpoint::restartShared.
uint64_t lbann::persist::get_bytes() const
References lbann::write_distmat, lbann::read_distmat, lbann::write_bytes, lbann::read_bytes, lbann::write_uint32, lbann::read_uint32, lbann::write_uint64, lbann::read_uint64, lbann::write_int32_contig, lbann::read_int32_contig, lbann::write_float, lbann::read_float, lbann::write_string, lbann::read_string, lbann::write_double, lbann::read_double, lbann::writeDist, lbann::readDist.
Referenced by lbann::lbann_callback_checkpoint::checkpointShared, lbann::lbann_callback_checkpoint::restartShared.
bool lbann::persist::write_distmat(persist_type type, const char *name, DistMat *M)
Referenced by lbann::loss_function::save_to_checkpoint_shared, lbann::adagrad::save_to_checkpoint_shared, lbann::adam::save_to_checkpoint_shared, lbann::rmsprop::save_to_checkpoint_shared, lbann::sgd::save_to_checkpoint_shared, lbann::weights::save_to_checkpoint_shared.
bool lbann::persist::read_distmat(persist_type type, const char *name, DistMat *M)
References lbann::exists.
Referenced by lbann::loss_function::load_from_checkpoint_shared, lbann::adagrad::load_from_checkpoint_shared, lbann::adam::load_from_checkpoint_shared, lbann::rmsprop::load_from_checkpoint_shared, lbann::sgd::load_from_checkpoint_shared, lbann::weights::load_from_checkpoint_shared.
bool lbann::persist::write_bytes(persist_type type, const char *name, const void *buf, size_t size)
bool lbann::persist::read_bytes(persist_type type, const char *name, void *buf, size_t size)
bool lbann::persist::write_uint32(persist_type type, const char *name, uint32_t val)
References lbann::write_bytes.
Referenced by lbann::model::save_to_checkpoint_shared, lbann::sequential_model::save_to_checkpoint_shared.
bool lbann::persist::read_uint32(persist_type type, const char *name, uint32_t *val)
References lbann::read_bytes.
Referenced by lbann::model::load_from_checkpoint_shared, lbann::sequential_model::load_from_checkpoint_shared.
bool lbann::persist::write_uint64(persist_type type, const char *name, uint64_t val)
References lbann::write_bytes.
Referenced by lbann::generic_data_reader::pack_scalars, lbann::generic_input_layer::save_to_checkpoint_shared, lbann::io_layer::io_layer, lbann::metric_statistics::pack_scalars, lbann::model::save_to_checkpoint_shared.
bool lbann::persist::read_uint64(persist_type type, const char *name, uint64_t *val)
References lbann::read_bytes.
Referenced by lbann::generic_data_reader::unpack_scalars, lbann::generic_input_layer::load_from_checkpoint_shared, lbann::io_layer::io_layer, lbann::metric_statistics::unpack_scalars, lbann::model::load_from_checkpoint_shared.
bool lbann::persist::write_int32_contig(persist_type type, const char *name, const int32_t *buf, uint64_t count)
References lbann::write_bytes.
Referenced by lbann::generic_data_reader::pack_scalars.
bool lbann::persist::read_int32_contig(persist_type type, const char *name, int32_t *buf, uint64_t count)
References lbann::read_bytes.
Referenced by lbann::generic_data_reader::unpack_scalars.
bool lbann::persist::write_float(persist_type type, const char *name, float val)
References lbann::write_bytes.
bool lbann::persist::read_float(persist_type type, const char *name, float *val)
References lbann::read_bytes.
bool lbann::persist::write_string(persist_type type, const char *name, const char *val, int str_length)
References lbann::write_bytes.
bool lbann::persist::read_string(persist_type type, const char *name, char *val, int str_length)
References lbann::read_bytes.
bool lbann::persist::write_double(persist_type type, const char *name, double val)
References lbann::write_bytes.
Referenced by lbann::metric_statistics::pack_scalars.
bool lbann::persist::read_double(persist_type type, const char *name, double *val)
References lbann::read_bytes.
Referenced by lbann::metric_statistics::unpack_scalars.
bool lbann::persist::write_datatype(persist_type type, const char *name, DataType val)
References lbann::write_bytes.
Referenced by lbann::adam::pack_scalars, lbann::rmsprop::pack_scalars, lbann::sgd::pack_scalars, lbann::optimizer::save_to_checkpoint_shared.
bool lbann::persist::read_datatype(persist_type type, const char *name, DataType *val)
References lbann::read_bytes.
Referenced by lbann::adam::unpack_scalars, lbann::rmsprop::unpack_scalars, lbann::sgd::unpack_scalars, lbann::optimizer::load_from_checkpoint_shared.
int lbann::persist::get_fd(persist_type type) const