lbann::data_store_merge_features
std::vector<int> lbann::data_store_merge_features::m_my_minibatch_indices
this contains a concatenation of the indices in m_minibatch_indices (see: generic_data_reader.hpp)
MPI_Win lbann::data_store_merge_features::m_win
allocate mem for m_data
when running in in-memory mode, this buffer will contain the concatenated datawill contain data to be passed to the data_reader maps indices wrt shuffled indices to indices in m_my_data
Referenced by ~data_store_merge_features.
lbann::data_store_merge_features::data_store_merge_features(generic_data_reader *reader, model *m)
ctor
References lbann::generic_data_store::set_name.
Referenced by copy.
lbann::data_store_merge_features::data_store_merge_features(const data_store_merge_features &)=default
copy ctor
data_store_merge_features& lbann::data_store_merge_features::operator=(const data_store_merge_features &)=default
operator=
data_store_merge_features* lbann::data_store_merge_features::copy() const override
References data_store_merge_features, ~data_store_merge_features.
lbann::data_store_merge_features::~data_store_merge_features() override
dtor
References m_win, setup, lbann::generic_data_store::m_rank, lbann::generic_data_store::setup, lbann::generic_data_store::m_reader, lbann::generic_data_reader::get_role, lbann::generic_data_store::m_in_memory, lbann::generic_data_store::get_minibatch_index_vector, lbann::generic_compound_data_reader::get_data_readers, lbann::generic_data_reader::get_data_store, lbann::data_store_pilot2_molecular::clear_minibatch_indices, lbann::generic_data_store::m_my_minibatch_indices_v, exchange_data.
Referenced by copy.
void lbann::data_store_merge_features::get_data_buf(int data_id, std::vector< unsigned char > *&buf, int multi_idx=0) override
called by various image data readers
void lbann::data_store_merge_features::setup() override
called by generic_data_reader::setup_data_store
Referenced by ~data_store_merge_features.
void lbann::data_store_merge_features::exchange_data() override
Referenced by ~data_store_merge_features.