lbann::lbann_callback_variable_minibatch
const int lbann::lbann_callback_variable_minibatch::m_starting_mbsize
Initial mini-batch size.
Referenced by on_train_begin.
int lbann::lbann_callback_variable_minibatch::m_current_mini_batch_size
The current mini-batch size for this epoch. This is kept separately from the model's get_current_mini_batch_size() method, as calling that in on_epoch_end returns the size of the last mini- batch, not the "base" mini-batch.
Referenced by on_epoch_end, lbann::lbann_callback_step_minibatch::schedule.
int lbann::lbann_callback_variable_minibatch::m_ramp_count
Current number of epochs left to ramp the learning rate.
Referenced by on_epoch_end.
float lbann::lbann_callback_variable_minibatch::m_lr_incr
Amount to increment the learning rate by when ramping.
Referenced by on_epoch_end.
lbann::lbann_callback_variable_minibatch::lbann_callback_variable_minibatch(int starting_mbsize)
lbann::lbann_callback_variable_minibatch::lbann_callback_variable_minibatch(const lbann_callback_variable_minibatch &)=default
lbann_callback_variable_minibatch& lbann::lbann_callback_variable_minibatch::operator=(const lbann_callback_variable_minibatch &)=default
Referenced by lbann::lbann_callback_minibatch_schedule::minibatch_step::minibatch_step.
void lbann::lbann_callback_variable_minibatch::on_train_begin(model *m) override
Set the initial mini-batch size.
References lbann::model::get_cur_epoch, lbann::model::get_layers, LBANN_ERROR, m_starting_mbsize, lbann::model::get_max_mini_batch_size, lbann::model::get_comm, lbann::lbann_comm::am_world_master, lbann::generic_input_layer::calculate_num_iterations_per_epoch_training_spans_models.
void lbann::lbann_callback_variable_minibatch::on_epoch_end(model *m) override
Potentially change the mini-batch size.
References lbann::model::get_layers, LBANN_ERROR, comm, lbann::model::get_comm, schedule, lbann::model::get_max_mini_batch_size, lbann::lbann_comm::am_model_master, lbann::lbann_comm::get_model_rank, lbann::generic_input_layer::calculate_num_iterations_per_epoch_training_spans_models, m_current_mini_batch_size, m_ramp_count, change_learning_rate, get_current_learning_rate, m_lr_incr, lbann::model::get_cur_epoch.
virtual bool lbann::lbann_callback_variable_minibatch::schedule(model *m, int &new_mbsize, float &new_lr, int &ramp_time)=0
Implemented by child classes to provide the mini-batch/learning schedule. This is called at the end of every training epoch. If it returns false, no changes are made from the currently established schedule. If this returns true, the mini-batch size will be changed accordingly. If the mini-batch size is larger than the model's maximum mini-batch size, a warning is printed and the maximum mini-batch size is used. If new_lr also non-zero, the learning rate will be changed to new_lr, with a linear ramp time. (If ramp_time is 0, it is changed immediately.) Note changing the learning rate while in a ramp may lead to unexpected behavior; also be aware of interactions with other learning rate schedules.
Referenced by lbann::lbann_callback_step_minibatch::name, lbann::lbann_callback_minibatch_schedule::name, on_epoch_end.
void lbann::lbann_callback_variable_minibatch::change_learning_rate(model *m, float new_lr) const
Change the learning rate of every layer in m to new_lr.
References lbann::model::get_weights, lbann::optimizer::set_learning_rate.
Referenced by on_epoch_end.
float lbann::lbann_callback_variable_minibatch::get_current_learning_rate(model *m) const
Get the current learning rate (assumes every layer has the same one).
References lbann::model::get_weights, lbann::optimizer::get_learning_rate.
Referenced by on_epoch_end, lbann::lbann_callback_step_minibatch::schedule.