lbann::lbann_callback_timeline
std::string lbann::lbann_callback_timeline::m_outdir
Directory to write output to.
Referenced by on_train_end.
EvalType lbann::lbann_callback_timeline::m_start_time
Time training started; all times are relative to this.
Referenced by get_rel_time, on_train_begin.
EvalType lbann::lbann_callback_timeline::m_fp_start_time
Time the current layer's forward pass started.
Referenced by on_forward_prop_begin, on_forward_prop_end.
EvalType lbann::lbann_callback_timeline::m_bp_start_time
Time the current layer's backward pass started.
Referenced by on_backward_prop_begin, on_backward_prop_end.
EvalType lbann::lbann_callback_timeline::m_opt_start_time
Time the current weights' optimization pass started.
Referenced by on_optimize_begin, on_optimize_end.
std::unordered_map<std::string, std::vector<std::pair<EvalType, EvalType> > > lbann::lbann_callback_timeline::m_fp_times
Store (relative) timing information.
Referenced by on_train_begin, on_train_end, on_forward_prop_end.
std::unordered_map<std::string, std::vector<std::pair<EvalType, EvalType> > > lbann::lbann_callback_timeline::m_bp_times
Referenced by on_train_begin, on_train_end, on_backward_prop_end.
std::unordered_map<std::string, std::vector<std::pair<EvalType, EvalType> > > lbann::lbann_callback_timeline::m_opt_times
Referenced by on_train_begin, on_train_end, on_optimize_end.
lbann::lbann_callback_timeline::lbann_callback_timeline(std::string outdir)
References operator=.
Referenced by copy.
lbann::lbann_callback_timeline::lbann_callback_timeline(const lbann_callback_timeline &)=default
lbann_callback_timeline& lbann::lbann_callback_timeline::operator=(const lbann_callback_timeline &)=default
Referenced by lbann_callback_timeline.
lbann_callback_timeline* lbann::lbann_callback_timeline::copy() const override
References lbann_callback_timeline.
std::string lbann::lbann_callback_timeline::name() const override
Return this callback's name.
References on_train_begin, on_train_end, lbann::lbann_callback::on_forward_prop_begin, lbann::lbann_callback::on_forward_prop_end, lbann::lbann_callback::on_backward_prop_begin, lbann::lbann_callback::on_backward_prop_end, lbann::lbann_callback::on_optimize_begin, lbann::lbann_callback::on_optimize_end, on_forward_prop_begin, on_forward_prop_end, on_backward_prop_begin, on_backward_prop_end, on_optimize_begin, on_optimize_end.
void lbann::lbann_callback_timeline::on_train_begin(model *m) override
Called at the beginning of training.
References lbann::model::get_layers, m_fp_times, m_bp_times, lbann::model::get_weights, m_opt_times, lbann::model::get_comm, lbann::lbann_comm::model_barrier, m_start_time, lbann::get_time.
Referenced by name.
void lbann::lbann_callback_timeline::on_train_end(model *m) override
Called at the end of training.
References m_outdir, lbann::model::get_comm, lbann::lbann_comm::get_model_rank, lbann::lbann_comm::get_rank_in_model, m_fp_times, m_bp_times, m_opt_times.
Referenced by name.
void lbann::lbann_callback_timeline::on_forward_prop_begin(model *m, Layer *l) override
Called when a layer begins forward propagation.
References m_fp_start_time, get_rel_time.
Referenced by name.
void lbann::lbann_callback_timeline::on_forward_prop_end(model *m, Layer *l) override
Called when a layer ends forward propagation.
References get_rel_time, m_fp_times, lbann::Layer::get_name, m_fp_start_time.
Referenced by name.
void lbann::lbann_callback_timeline::on_backward_prop_begin(model *m, Layer *l) override
Called when a layer begins backward propagation.
References m_bp_start_time, get_rel_time.
Referenced by name.
void lbann::lbann_callback_timeline::on_backward_prop_end(model *m, Layer *l) override
Called when a layer ends backward propagation.
References get_rel_time, m_bp_times, lbann::Layer::get_name, m_bp_start_time.
Referenced by name.
void lbann::lbann_callback_timeline::on_optimize_begin(model *m, weights *w) override
Called when weights begins optimization.
References m_opt_start_time, get_rel_time.
Referenced by name.
void lbann::lbann_callback_timeline::on_optimize_end(model *m, weights *w) override
Called when weights ends optimization.
References get_rel_time, m_opt_times, lbann::weights::get_name, m_opt_start_time.
Referenced by name.
EvalType lbann::lbann_callback_timeline::get_rel_time() const
Get time relative to the start time.
References lbann::get_time, m_start_time.
Referenced by on_forward_prop_begin, on_forward_prop_end, on_backward_prop_begin, on_backward_prop_end, on_optimize_begin, on_optimize_end.