lbann::binary_cross_entropy
lbann::binary_cross_entropy::binary_cross_entropy(EvalType scale_factor=EvalType(1))
Default constructor.
References operator=, ~binary_cross_entropy.
Referenced by copy.
lbann::binary_cross_entropy::binary_cross_entropy(const binary_cross_entropy &other)=default
Copy constructor.
binary_cross_entropy& lbann::binary_cross_entropy::operator=(const binary_cross_entropy &other)=default
Copy assignment operator.
Referenced by binary_cross_entropy.
lbann::binary_cross_entropy::~binary_cross_entropy() override=default
Destructor.
Referenced by binary_cross_entropy.
binary_cross_entropy* lbann::binary_cross_entropy::copy() const override
Copy function.
References binary_cross_entropy.
std::string lbann::binary_cross_entropy::name() const override
Get the name of the objective function term.
void lbann::binary_cross_entropy::start_evaluate_compute(const AbsDistMat &prediction, const AbsDistMat &ground_truth) override
Compute the binary cross entropy objective function. Given a prediction $\hat{y}$ and ground truth
References finish_evaluate_compute, prediction, differentiate_compute.
EvalType lbann::binary_cross_entropy::finish_evaluate_compute(const AbsDistMat &prediction, const AbsDistMat &ground_truth) override
Finish evaluation.
Referenced by start_evaluate_compute.
void lbann::binary_cross_entropy::differentiate_compute(const AbsDistMat &prediction, const AbsDistMat &ground_truth, AbsDistMat &gradient) override
Compute the gradient of the binary cross entropy objective function. Given a prediction $\hat{y}$ and ground truth $y$, the gradient of the binary cross entropy is \[ \nabla_{\hat{y}} CE(\hat{y}, y) = -y/\hat{y} + (1-y)/(1-\hat{y}) \]
Referenced by start_evaluate_compute.