lbann::adam
DataType lbann::adam::m_beta1
Update factor for first moment estimate.
Referenced by unpack_scalars, operator=, get_description, step_compute.
DataType lbann::adam::m_beta2
Update factor for second moment estimate.
Referenced by unpack_scalars, operator=, get_description, step_compute.
DataType lbann::adam::m_eps
Small factor to avoid division by zero.
Referenced by unpack_scalars, operator=, get_description, step_compute.
DataType lbann::adam::m_current_beta1
beta1 ^ iteration.
Referenced by unpack_scalars, operator=, step_compute.
DataType lbann::adam::m_current_beta2
beta2 ^ iteration.
Referenced by unpack_scalars, operator=, step_compute.
AbsDistMat* lbann::adam::m_moment1
First moment estimates.
Referenced by adam, operator=, ~adam, setup, step_compute, save_to_checkpoint_shared, load_from_checkpoint_shared.
AbsDistMat* lbann::adam::m_moment2
Second moment estimates.
Referenced by adam, operator=, ~adam, setup, step_compute, save_to_checkpoint_shared, load_from_checkpoint_shared.
lbann::adam::adam(lbann_comm *comm, DataType learning_rate, DataType beta1=DataType(0.9), DataType beta2=DataType(0.99), DataType eps=DataType(1e-8), cudnn::cudnn_manager *cudnn=nullptr)
Constructor.
Referenced by copy.
lbann::adam::adam(const adam &other)
Copy constructor.
References m_moment1, m_moment2, lbann::optimizer::m_cudnn, lbann::optimizer::m_weights, lbann::weights::get_matrix_height, lbann::weights::get_matrix_width.
adam & lbann::adam::operator=(const adam &other)
Copy assignment operator.
References lbann::optimizer::operator=, m_beta1, m_beta2, m_eps, m_current_beta1, m_current_beta2, m_moment1, m_moment2, lbann::optimizer::m_cudnn, lbann::optimizer::m_weights, lbann::weights::get_matrix_height, lbann::weights::get_matrix_width.
lbann::adam::~adam() override
Destructor.
References m_moment1, m_moment2, lbann::optimizer::m_cudnn.
adam* lbann::adam::copy() const override
Create a copy.
References adam.
std::string lbann::adam::get_type() const override
Returns the optimizer name.
References get_description, setup, step_compute.
std::string lbann::adam::get_description() const override
Get a human-readable description of the optimizer.
References lbann::optimizer::get_description, m_beta1, m_beta2, m_eps.
Referenced by get_type.
void lbann::adam::setup(weights &w) override
Setup optimizer.
References lbann::optimizer::setup, lbann::optimizer::m_gradient, m_moment1, m_moment2, lbann::optimizer::m_cudnn.
Referenced by get_type.
void lbann::adam::step_compute(AbsDistMat &values, const AbsDistMat &gradient) override
Perform the computation in an optimization step.
References m_current_beta1, m_beta1, m_current_beta2, m_beta2, lbann::optimizer::m_learning_rate, m_moment1, m_moment2, m_eps.
Referenced by get_type.
bool lbann::adam::pack_scalars(persist &p)
References lbann::persist::write_datatype, lbann::train.
Referenced by save_to_checkpoint_shared.
bool lbann::adam::unpack_scalars(persist &p, struct packing_header *header)
References lbann::persist::read_datatype, lbann::train, lbann::adam::packing_header::beta1, m_beta1, lbann::adam::packing_header::beta2, m_beta2, lbann::adam::packing_header::eps, m_eps, lbann::adam::packing_header::current_beta1, m_current_beta1, lbann::adam::packing_header::current_beta2, m_current_beta2.
Referenced by load_from_checkpoint_shared.
void lbann::adam::unpack_header(struct packing_header &header)
References lbann::adam::packing_header::beta1, lbann::adam::packing_header::beta2, lbann::adam::packing_header::eps, lbann::adam::packing_header::current_beta1, lbann::adam::packing_header::current_beta2, save_to_checkpoint_shared, load_from_checkpoint_shared.
Referenced by load_from_checkpoint_shared.
bool lbann::adam::save_to_checkpoint_shared(persist &p, std::string m_name) override
References lbann::optimizer::save_to_checkpoint_shared, lbann::persist::get_rank, pack_scalars, m_moment1, m_moment2, lbann::persist::write_distmat, lbann::train.
Referenced by unpack_header.
bool lbann::adam::load_from_checkpoint_shared(persist &p, std::string m_name) override
References lbann::optimizer::load_from_checkpoint_shared, lbann::persist::get_rank, unpack_scalars, unpack_header, m_moment1, m_moment2, lbann::persist::read_distmat, lbann::train.
Referenced by unpack_header.