lbann::lbann_callback_dump_minibatch_sample_indices
std::string lbann::lbann_callback_dump_minibatch_sample_indices::m_basename
Basename for writing files.
Referenced by dump_to_file.
lbann::lbann_callback_dump_minibatch_sample_indices::lbann_callback_dump_minibatch_sample_indices(std::string basename, int batch_interval=1)
basename The basename for writing files.
References operator=.
Referenced by copy.
lbann::lbann_callback_dump_minibatch_sample_indices::lbann_callback_dump_minibatch_sample_indices(const lbann_callback_dump_minibatch_sample_indices &)=default
lbann_callback_dump_minibatch_sample_indices& lbann::lbann_callback_dump_minibatch_sample_indices::operator=(const lbann_callback_dump_minibatch_sample_indices &)=default
Referenced by lbann_callback_dump_minibatch_sample_indices.
lbann_callback_dump_minibatch_sample_indices* lbann::lbann_callback_dump_minibatch_sample_indices::copy() const override
References lbann_callback_dump_minibatch_sample_indices, on_forward_prop_end, on_evaluate_forward_prop_end, dump_to_file.
void lbann::lbann_callback_dump_minibatch_sample_indices::on_forward_prop_end(model *m, Layer *l) override
Called when a layer ends forward propagation.
References dump_to_file, lbann::model::get_cur_step.
Referenced by copy.
void lbann::lbann_callback_dump_minibatch_sample_indices::on_evaluate_forward_prop_end(model *m, Layer *l) override
Called when a layer ends forward propagation for evaluation (validation / testing).
References lbann::model::get_execution_mode, validation, dump_to_file, lbann::model::get_cur_validation_step, testing, lbann::model::get_cur_testing_step.
Referenced by copy.
void lbann::lbann_callback_dump_minibatch_sample_indices::dump_to_file(model *m, Layer *l, int64_t step)
References lbann::Layer::get_sample_indices_per_mb, m_basename, _to_string, lbann::model::get_execution_mode, lbann::model::get_comm, lbann::lbann_comm::get_model_rank, lbann::lbann_comm::get_rank_in_model, lbann::model::get_cur_epoch, lbann::model::get_cur_step, lbann::Layer::get_name.
Referenced by copy, on_forward_prop_end, on_evaluate_forward_prop_end.
std::string lbann::lbann_callback_dump_minibatch_sample_indices::name() const override
Return this callback's name.