lbann::kl_divergence
std::string lbann::kl_divergence::m_z_mean_layer_name
input layer parameters to the KL-divergence function. z_mean is mean of Gaussian distribution in latent space z_log_sigma is (log) variance of distribution in latent space string and pointer variables are layer name and layer pointer respectively
Referenced by setup.
std::string lbann::kl_divergence::m_z_log_sigma_layer_name
Referenced by setup.
Layer* lbann::kl_divergence::m_z_mean_layer
Referenced by setup, finish_evaluation, differentiate.
Layer* lbann::kl_divergence::m_z_log_sigma_layer
Referenced by setup, finish_evaluation, differentiate.
lbann::kl_divergence::kl_divergence(std::string layer1, std::string layer2)
Default constructor.
Referenced by copy.
lbann::kl_divergence::kl_divergence(const kl_divergence &other)=default
Copy constructor.
kl_divergence& lbann::kl_divergence::operator=(const kl_divergence &other)=default
Copy assignment operator.
lbann::kl_divergence::~kl_divergence() override=default
Destructor.
kl_divergence* lbann::kl_divergence::copy() const override
Copy function.
References kl_divergence.
std::string lbann::kl_divergence::name() const override
Get the name of the objective function term.
References setup, start_evaluation, finish_evaluation, differentiate.
void lbann::kl_divergence::setup(model &m) override
Setup KL divergence regularization term.
References lbann::objective_function_term::setup, lbann::model::get_layers, m_z_mean_layer_name, m_z_mean_layer, m_z_log_sigma_layer_name, m_z_log_sigma_layer.
Referenced by name.
void lbann::kl_divergence::start_evaluation() override
Start evaluation of the objective function term. This should include the scaling factor. The result is not available until finish_evaluation has been called.
Referenced by name.
EvalType lbann::kl_divergence::finish_evaluation() override
Get the value of the KL divergence regularization term.
References lbann::objective_function_term::m_scale_factor, m_z_mean_layer, lbann::Layer::get_activations, m_z_log_sigma_layer, lbann::Layer::get_local_activations, lbann::objective_function_term::get_comm, lbann::lbann_comm::allreduce.
Referenced by name.
void lbann::kl_divergence::differentiate() override
Regularization terms are applied to the objective function. Add kl_loss to gradient/error signal.
References lbann::objective_function_term::m_scale_factor, m_z_mean_layer, lbann::Layer::get_activations, m_z_log_sigma_layer, lbann::Layer::get_child_layers, lbann::Layer::add_to_error_signal.
Referenced by name.
void lbann::kl_divergence::compute_weight_regularization() override
Compute the gradient of the weight regularization term. The gradient is computed w.r.t. the weights.