lbann::data_store_triplet
lbann::data_store_triplet::data_store_triplet(generic_data_reader *reader, model *m)
ctor
References lbann::generic_data_store::set_name, operator=.
Referenced by copy.
lbann::data_store_triplet::data_store_triplet(const data_store_triplet &)=default
copy ctor
data_store_triplet& lbann::data_store_triplet::operator=(const data_store_triplet &)=default
operator=
Referenced by data_store_triplet.
data_store_triplet* lbann::data_store_triplet::copy() const override
References data_store_triplet.
lbann::data_store_triplet::~data_store_triplet() override
dtor
References setup, get_sample.
void lbann::data_store_triplet::setup() override
called by generic_data_reader::setup_data_store
References lbann::get_time, lbann::generic_data_store::m_rank, lbann::generic_data_store::m_reader, lbann::generic_data_reader::get_role, lbann::generic_data_store::set_name, lbann::generic_data_store::m_in_memory, lbann::data_store_multi_images::setup.
Referenced by ~data_store_triplet.
std::vector< std::string > lbann::data_store_triplet::get_sample(size_t idx) const override
References lbann::generic_data_store::m_reader, lbann::data_reader_triplet::get_sample.
Referenced by ~data_store_triplet.