lbann::recurrent_model
int lbann::recurrent_model::m_unroll_depth
The number of times to unroll the recurrent network.
Referenced by recurrent_model, setup_layer_topology, setup_layers.
std::unordered_map<const Layer*, Layer*> lbann::recurrent_model::m_previous_step_layer
Map to corresponding layer in previous step. Layers in the first step map to null pointers. The input and target layers map to themselves.
Referenced by setup_layer_topology, setup_layers.
std::unordered_map<const Layer*, Layer*> lbann::recurrent_model::m_next_step_layer
Map to corresponding layer in next step. Layers in the last step map to null pointers. The input and target layers map to themselves.
Referenced by setup_layer_topology.
lbann::recurrent_model::recurrent_model(lbann_comm *comm, int mini_batch_size, objective_function *obj_fn, optimizer *default_optimizer, int unroll_depth)
Constructor.
References m_unroll_depth.
Referenced by copy.
lbann::recurrent_model::recurrent_model(const recurrent_model &other)=default
Copy constructor.
recurrent_model& lbann::recurrent_model::operator=(const recurrent_model &other)=default
Copy assignment operator.
lbann::recurrent_model::~recurrent_model() override=default
Destructor.
recurrent_model* lbann::recurrent_model::copy() const override
Create copy.
References recurrent_model.
std::string lbann::recurrent_model::name() const override
Get model name.
void lbann::recurrent_model::freeze_layers_under_frozen_surface() override
For general DAG models, users need to manually specify each layer to freeze in the model description prototext.
References setup_layer_topology, setup_layers.
void lbann::recurrent_model::setup_layer_topology() override
Set up topology of layer graph. Called in setup function. All layers in connected component of layer graph are added to the model and all parent/child relationships between layers are reciprocated.
References lbann::model::m_layers, m_previous_step_layer, m_next_step_layer, lbann::anonymous_namespace{recurrent.cpp}::unroll_input_layer, m_unroll_depth, lbann::anonymous_namespace{recurrent.cpp}::unroll_target_layer, lbann::anonymous_namespace{recurrent.cpp}::add_unrolled_layers, lbann::anonymous_namespace{recurrent.cpp}::add_placeholder_layers, lbann::anonymous_namespace{recurrent.cpp}::setup_unrolled_layer_pointers, lbann::model::setup_layer_topology.
Referenced by freeze_layers_under_frozen_surface.
void lbann::recurrent_model::setup_layers() override
Set up layers. Called in setup function.
References lbann::model::m_layers, m_unroll_depth, lbann::slice_layer< T_layout >::get_slice_points, m_previous_step_layer, lbann::model::m_comm, lbann::lbann_comm::am_world_master, lbann::model::print_layer_description.
Referenced by freeze_layers_under_frozen_surface.