lbann::r2_metric
lbann::r2_metric::r2_metric(lbann_comm *comm)
Constructor.
References operator=, ~r2_metric.
Referenced by copy.
lbann::r2_metric::r2_metric(const r2_metric &other)=default
Copy constructor.
r2_metric& lbann::r2_metric::operator=(const r2_metric &other)=default
Copy assignment operator.
Referenced by r2_metric.
virtual lbann::r2_metric::~r2_metric()=default
Destructor.
Referenced by r2_metric.
r2_metric* lbann::r2_metric::copy() const override
Copy function.
References r2_metric.
std::string lbann::r2_metric::name() const override
Return a string name for this metric.
References evaluate_compute, prediction.
EvalType lbann::r2_metric::evaluate_compute(const AbsDistMat &prediction, const AbsDistMat &ground_truth) override
Computation to evaluate the metric function. numerator = Sum(Square(ground_truth - prediction) denominator = Sum(Square(ground_truth - Mean(ground_truth))) return (1 - numerator/(denominator + epsilon))
References lbann::entrywise_mean_and_stdev.
Referenced by name.