lbann::sgd
DataType lbann::sgd::m_momentum
Momentum.
Referenced by unpack_scalars, operator=, get_description, step_compute.
bool lbann::sgd::m_nesterov
Nesterov acceleration.
Referenced by operator=, get_description, step_compute.
AbsDistMat* lbann::sgd::m_velocity
Velocity term for momentum SGD.
Referenced by sgd, operator=, ~sgd, setup, step_compute, save_to_checkpoint_shared, load_from_checkpoint_shared.
lbann::sgd::sgd(lbann_comm *comm, DataType learning_rate, DataType momentum=DataType(0), bool nesterov=false)
Constructor.
Referenced by copy.
lbann::sgd::sgd(const sgd &other)
Copy constructor.
References m_velocity, lbann::optimizer::m_cudnn, lbann::optimizer::m_weights, lbann::weights::get_matrix_height, lbann::weights::get_matrix_width.
sgd & lbann::sgd::operator=(const sgd &other)
Copy assignment operator.
References lbann::optimizer::operator=, m_momentum, m_nesterov, m_velocity, lbann::optimizer::m_cudnn, lbann::optimizer::m_weights, lbann::weights::get_matrix_height, lbann::weights::get_matrix_width.
lbann::sgd::~sgd() override
Destructor.
References m_velocity, lbann::optimizer::m_cudnn.
sgd* lbann::sgd::copy() const override
Create a copy.
References sgd.
std::string lbann::sgd::get_type() const override
Get the optimizer name.
References get_description, setup, step_compute.
std::string lbann::sgd::get_description() const override
Get a human-readable description of the optimizer.
References lbann::optimizer::get_description, m_momentum, m_nesterov.
Referenced by get_type.
void lbann::sgd::setup(weights &w) override
Setup optimizer.
References lbann::optimizer::setup, lbann::optimizer::m_gradient, m_velocity, lbann::optimizer::m_cudnn.
Referenced by get_type.
void lbann::sgd::step_compute(AbsDistMat &values, const AbsDistMat &gradient) override
Perform the computation in an optimization step.
References m_momentum, lbann::optimizer::m_learning_rate, m_velocity, m_nesterov.
Referenced by get_type.
bool lbann::sgd::pack_scalars(persist &p)
References lbann::persist::write_datatype, lbann::train.
Referenced by save_to_checkpoint_shared.
bool lbann::sgd::unpack_scalars(persist &p, struct packing_header *header)
References lbann::persist::read_datatype, lbann::train, lbann::sgd::packing_header::momentum, m_momentum.
Referenced by load_from_checkpoint_shared.
void lbann::sgd::unpack_header(struct packing_header &header)
References lbann::sgd::packing_header::momentum, save_to_checkpoint_shared, load_from_checkpoint_shared.
Referenced by load_from_checkpoint_shared.
bool lbann::sgd::save_to_checkpoint_shared(persist &p, std::string m_name) override
References lbann::optimizer::save_to_checkpoint_shared, lbann::persist::get_rank, pack_scalars, m_velocity, lbann::persist::write_distmat, lbann::train.
Referenced by unpack_header.
bool lbann::sgd::load_from_checkpoint_shared(persist &p, std::string m_name) override
References lbann::optimizer::load_from_checkpoint_shared, lbann::persist::get_rank, unpack_scalars, unpack_header, m_velocity, lbann::persist::read_distmat, lbann::train.
Referenced by unpack_header.