lbann::lbann_image_preprocessor
bool lbann::lbann_image_preprocessor::m_horizontal_flip
Whether to do horizontal flips.
Referenced by horizontal_flip, augment.
bool lbann::lbann_image_preprocessor::m_vertical_flip
Whether to do vertical flips.
Referenced by vertical_flip, augment.
float lbann::lbann_image_preprocessor::m_rotation_range
Range in degrees for rotations (0-180).
Referenced by rotation, augment.
float lbann::lbann_image_preprocessor::m_horizontal_shift
Range (fraction of total width) for horizontal shifts.
Referenced by horizontal_shift, augment.
float lbann::lbann_image_preprocessor::m_vertical_shift
Range (fraction of total height) for vertical shifts.
Referenced by vertical_shift, augment.
float lbann::lbann_image_preprocessor::m_shear_range
Shear angle (radians).
Referenced by shear_range, augment.
bool lbann::lbann_image_preprocessor::m_mean_subtraction
Whether to normalize to 0 mean.
Referenced by subtract_mean, normalize.
bool lbann::lbann_image_preprocessor::m_unit_variance
Whether to normalize to unit variance.
Referenced by unit_variance, normalize.
bool lbann::lbann_image_preprocessor::m_scale
Whether to scale to [0, 1].
Referenced by scale, normalize.
bool lbann::lbann_image_preprocessor::m_z_score
Whether to normalize via z-score.
Referenced by z_score, normalize.
float lbann::lbann_image_preprocessor::m_noise_factor
Referenced by add_noise, pixel_noise.
lbann::lbann_image_preprocessor::lbann_image_preprocessor()
lbann::lbann_image_preprocessor::lbann_image_preprocessor(const lbann_image_preprocessor &)=default
lbann_image_preprocessor& lbann::lbann_image_preprocessor::operator=(const lbann_image_preprocessor &)=default
virtual lbann::lbann_image_preprocessor::~lbann_image_preprocessor()
void lbann::lbann_image_preprocessor::horizontal_flip(bool b)
Whether to do random horizontal flips.
References m_horizontal_flip.
Referenced by disable_augmentation, init_generic_preprocessor.
void lbann::lbann_image_preprocessor::vertical_flip(bool b)
Whether to do random vertical flips.
References m_vertical_flip.
Referenced by disable_augmentation, init_generic_preprocessor.
void lbann::lbann_image_preprocessor::rotation(float range)
Do random rotations up to range degrees (0-180).
References m_rotation_range.
Referenced by disable_augmentation, init_generic_preprocessor.
void lbann::lbann_image_preprocessor::horizontal_shift(float range)
Do random horizontal shifts up to range (fraction of image width).
References m_horizontal_shift.
Referenced by disable_augmentation, init_generic_preprocessor.
void lbann::lbann_image_preprocessor::vertical_shift(float range)
Do random vertical shifts up to range (fraction of image height).
References m_vertical_shift.
Referenced by disable_augmentation, init_generic_preprocessor.
void lbann::lbann_image_preprocessor::shear_range(float range)
Do random shears up to range (radians).
References m_shear_range.
Referenced by disable_augmentation, init_generic_preprocessor.
void lbann::lbann_image_preprocessor::subtract_mean(bool b)
Whether to subtract the sample-wise mean.
References m_mean_subtraction.
Referenced by init_generic_preprocessor.
void lbann::lbann_image_preprocessor::unit_variance(bool b)
Whether to normalize to unit variance, sample-wise.
References m_unit_variance.
Referenced by normalize, init_generic_preprocessor.
void lbann::lbann_image_preprocessor::scale(bool b)
Whether to scale to [0, 1] (assumes max value is 255).
References m_scale.
Referenced by init_generic_preprocessor.
void lbann::lbann_image_preprocessor::z_score(bool b)
Whether to normalize by z-scores, sample-wise. This and mean subtraction/unit variance are mutually exclusive.
References m_z_score.
Referenced by normalize, init_generic_preprocessor.
void lbann::lbann_image_preprocessor::disable_augmentation()
Disable all data augmentation.
References horizontal_flip, vertical_flip, rotation, horizontal_shift, vertical_shift, shear_range.
Referenced by init_generic_preprocessor.
void lbann::lbann_image_preprocessor::add_noise(float noise_factor=0.0f)
Add noise to data (disable by default) noise_factor control the ammount of noise to be set to a value above zero but less than 1 (say 0.5)
References m_noise_factor, augment, normalize.
Referenced by init_generic_preprocessor.
void lbann::lbann_image_preprocessor::augment(Mat &pixels, unsigned imheight, unsigned imwidth, unsigned num_channels)
Preprocess pixels according to the currently-set augmentation transforms. pixels The pixels to process as a column vector (num x 1 mat). imheight Height of the image in pixels. imwidth Width of the image in pixels. num_channels The number of channels pixels has.
References m_horizontal_flip, m_vertical_flip, m_rotation_range, m_horizontal_shift, m_vertical_shift, m_shear_range, cv_pixels, lbann::get_generator, flip, anonymous_namespace{image_preprocessor.cpp}::pi, affine_trans, col_pixels.
Referenced by add_noise, lbann::cifar10_reader::fetch_datum, lbann::imagenet_reader_org::fetch_datum, lbann::mnist_reader::fetch_datum.
void lbann::lbann_image_preprocessor::normalize(Mat &pixels, unsigned num_channels)
Normalize poxels according to the currently-set transforms. pixels The pixels to process as a column vector. num_channels The number of channels pixels has.
References m_z_score, m_mean_subtraction, m_unit_variance, z_score, m_scale, unit_scale, mean_subtraction, unit_variance.
Referenced by add_noise, lbann::cifar10_reader::fetch_datum, lbann::imagenet_reader_org::fetch_datum, lbann::mnist_reader::fetch_datum.
virtual void lbann::lbann_image_preprocessor::save_image(Mat &pixels, const std::string filename, bool do_scale=true)
External interface to saving an image. Classes that want to support this should use it to interface with internal_save_image. pixels The image to save (as a column vector). filename The image filename (type inferred from extension). scale Whether pixels has been scaled (default true).
void lbann::lbann_image_preprocessor::mean_subtraction(Mat &pixels, unsigned num_channels)
References lbann::entrywise_mean_and_stdev.
Referenced by normalize.
void lbann::lbann_image_preprocessor::unit_variance(Mat &pixels, unsigned num_channels)
References lbann::entrywise_mean_and_stdev.
void lbann::lbann_image_preprocessor::unit_scale(Mat &pixels, unsigned num_channels)
Referenced by normalize.
void lbann::lbann_image_preprocessor::z_score(Mat &pixels, unsigned num_channels)
References lbann::entrywise_mean_and_stdev.
void lbann::lbann_image_preprocessor::pixel_noise(Mat &pixels)
References m_noise_factor.
Referenced by lbann::cifar10_reader::fetch_datum, lbann::imagenet_reader_org::fetch_datum, lbann::mnist_reader::fetch_datum.
cv::Mat lbann::lbann_image_preprocessor::cv_pixels(const Mat &pixels, unsigned imheight, unsigned imwidth, unsigned num_channels)
Convert a column vector of pixels to an OpenCV matrix.
Referenced by augment, internal_save_image.
void lbann::lbann_image_preprocessor::col_pixels(const cv::Mat &sqpixels, Mat &pixels, unsigned num_channels)
Undo cv_pixels.
Referenced by augment.
void lbann::lbann_image_preprocessor::flip(cv::Mat &sqpixels, int flip_flag)
Flip sqpixels. flip_flag OpenCV flip flag: 0=vertical, 1=horizontal, -1=both.
Referenced by augment.
void lbann::lbann_image_preprocessor::affine_trans(cv::Mat &sqpixels, const Mat &trans)
Apply the affine transformation in 3x3 matrix trans.
Referenced by augment.
void lbann::lbann_image_preprocessor::internal_save_image(Mat &pixels, const std::string filename, unsigned imheight, unsigned imwidth, unsigned num_channels, bool do_scale)
Save pixels to filename.
References cv_pixels.
Referenced by lbann::image_data_reader::save_image, lbann::data_reader_jag::save_image.