lbann::lbann_callback_debug_io
execution_mode lbann::lbann_callback_debug_io::m_debug_phase
The phase to debug.
Referenced by on_epoch_begin, on_forward_prop_begin, on_validation_begin, on_evaluate_forward_prop_begin, on_test_begin.
int lbann::lbann_callback_debug_io::m_debug_lvl
Referenced by on_forward_prop_begin, on_evaluate_forward_prop_begin.
lbann::lbann_callback_debug_io::lbann_callback_debug_io(execution_mode phase=execution_mode::invalid, int debug_lvl=0, lbann_summary *summarizer=nullptr)
Debug a particular phase; use invalid to debug every phase.
References operator=.
Referenced by copy.
lbann::lbann_callback_debug_io::lbann_callback_debug_io(const lbann_callback_debug_io &)=default
lbann_callback_debug_io& lbann::lbann_callback_debug_io::operator=(const lbann_callback_debug_io &)=default
Referenced by lbann_callback_debug_io.
lbann_callback_debug_io* lbann::lbann_callback_debug_io::copy() const override
References lbann_callback_debug_io, on_epoch_begin, on_forward_prop_begin, on_validation_begin, on_evaluate_forward_prop_begin, on_test_begin, print_fp_start, print_phase_start.
void lbann::lbann_callback_debug_io::on_epoch_begin(model *m) override
BVE FIXME.
Print that a training epoch is being started.TodoThe use of execution_mode invalid needs to be reconsidered
References m_debug_phase, invalid, training, print_phase_start.
Referenced by copy.
void lbann::lbann_callback_debug_io::on_forward_prop_begin(model *m, Layer *l) override
Print that forward prop for a layer is beginning.
References m_debug_lvl, lbann::model::get_comm, lbann::lbann_comm::get_rank_in_model, m_debug_phase, invalid, lbann::model::get_execution_mode, print_fp_start.
Referenced by copy.
void lbann::lbann_callback_debug_io::on_validation_begin(model *m) override
Print I/O details at the beginning of validation.
References m_debug_phase, invalid, validation, print_phase_start.
Referenced by copy.
void lbann::lbann_callback_debug_io::on_evaluate_forward_prop_begin(model *m, Layer *l) override
Print that an evaluation forward prop is beginning.
References m_debug_lvl, lbann::model::get_comm, lbann::lbann_comm::get_rank_in_model, m_debug_phase, invalid, lbann::model::get_execution_mode, print_fp_start.
Referenced by copy.
void lbann::lbann_callback_debug_io::on_test_begin(model *m) override
Print I/O details at the beginning of testing.
References m_debug_phase, invalid, testing, print_phase_start.
Referenced by copy.
void lbann::lbann_callback_debug_io::print_fp_start(model *m, generic_input_layer *input)
Common format for printing I/O stats at the start of a mini-batch
References lbann::model::get_execution_mode, training, lbann::model::get_cur_step, validation, lbann::model::get_cur_validation_step, testing, lbann::model::get_cur_testing_step, lbann::model::get_comm, lbann::lbann_comm::get_model_rank, lbann::lbann_comm::get_rank_in_model, lbann::model::get_cur_epoch, _to_string, lbann::Layer::get_name, lbann::generic_input_layer::get_type, lbann::generic_input_layer::get_data_reader, lbann::generic_data_reader::get_current_mini_batch_index, lbann::generic_input_layer::get_num_iterations_per_epoch, lbann::generic_data_reader::get_loaded_mini_batch_index, lbann::generic_input_layer::get_current_mini_batch_size, lbann::generic_input_layer::get_current_global_mini_batch_size, lbann::generic_data_reader::get_position, lbann::generic_data_reader::get_sample_stride.
Referenced by copy, on_forward_prop_begin, on_evaluate_forward_prop_begin.
void lbann::lbann_callback_debug_io::print_phase_start(model *m, execution_mode mode)
Common format for printing I/O stats at the start of a phase
References lbann::model::get_layers, training, lbann::model::get_cur_step, validation, lbann::model::get_cur_validation_step, testing, lbann::model::get_cur_testing_step, lbann::generic_data_reader::get_rank, lbann::generic_data_reader::get_num_parallel_readers, lbann::model::get_comm, lbann::lbann_comm::get_model_rank, lbann::lbann_comm::get_rank_in_model, _to_string, lbann::generic_data_reader::get_num_iterations_per_epoch, lbann::generic_data_reader::get_global_mini_batch_size, lbann::lbann_comm::get_num_models, lbann::generic_data_reader::get_mini_batch_size, lbann::generic_data_reader::get_stride_to_next_mini_batch, lbann::generic_data_reader::get_global_last_mini_batch_size, lbann::generic_data_reader::get_last_mini_batch_size, lbann::generic_data_reader::get_stride_to_last_mini_batch, lbann::generic_data_reader::get_base_offset, lbann::generic_data_reader::get_model_offset.
Referenced by copy, on_epoch_begin, on_validation_begin, on_test_begin.
std::string lbann::lbann_callback_debug_io::name() const override
Return this callback's name.