lbann::Layer
lbann_comm* lbann::Layer::m_comm
Reference to LBANN communicator.
Referenced by lbann::generic_input_layer::setup_data, lbann::generic_input_layer::fp_compute, lbann::input_layer< T_io_buffer, T_layout >::input_layer, lbann::target_layer< T_io_buffer, T_layout >::target_layer, get_comm, lbann::base_convolution_layer::setup_data, lbann::batch_normalization< T_layout >::setup_data, lbann::batch_normalization< T_layout >::fp_compute_cpu, lbann::batch_normalization< T_layout >::bp_compute_cpu, lbann::evaluation_layer< T_layout >::get_value, lbann::evaluation_layer< T_layout >::fp_compute, operator=, setup, setup_gpu, get_bp_output.
std::vector<int> lbann::Layer::m_neuron_dims
Dimensions of activation tensor. If a derived class has more than one activation tensor, it is responsible for its own interpretation.
Referenced by lbann::generic_input_layer::setup_dims, lbann::generic_input_layer::get_topo_description, lbann::generic_target_layer::setup_dims, lbann::reconstruction_layer< T_layout >::setup_dims, get_neuron_dims, fp_output_dims, lbann::base_convolution_layer::setup_data, lbann::base_convolution_layer::setup_gpu, lbann::base_convolution_layer::apply_convolution_im2col, lbann::base_convolution_layer::apply_transposed_convolution_im2col, lbann::base_convolution_layer::apply_bias_cpu, lbann::base_convolution_layer::compute_gradients_im2col, lbann::convolution_layer< T_layout >::get_description, lbann::convolution_layer< T_layout >::setup_dims, lbann::deconvolution_layer< T_layout >::get_description, lbann::deconvolution_layer< T_layout >::setup_dims, lbann::batch_normalization< T_layout >::setup_data, lbann::batch_normalization< T_layout >::fp_compute_gpu, lbann::batch_normalization< T_layout >::bp_compute_gpu, lbann::batch_normalization< T_layout >::fp_compute_cpu, lbann::batch_normalization< T_layout >::bp_compute_cpu, lbann::local_response_normalization_layer< T_layout >::fp_compute_cpu, lbann::local_response_normalization_layer< T_layout >::bp_compute_cpu, lbann::bernoulli_layer< T_layout >::bernoulli_layer, lbann::bernoulli_layer< T_layout >::setup_dims, lbann::concatenation_layer< T_layout >::setup_dims, lbann::concatenation_layer< T_layout >::fp_compute_cpu, lbann::concatenation_layer< T_layout >::bp_compute_cpu, lbann::concatenation_layer< T_layout >::fp_compute_gpu, lbann::concatenation_layer< T_layout >::bp_compute_gpu, lbann::constant_layer< T_layout >::constant_layer, lbann::constant_layer< T_layout >::setup_dims, lbann::gaussian_layer< T_layout >::gaussian_layer, lbann::gaussian_layer< T_layout >::setup_dims, lbann::pooling_layer< T_layout >::setup_dims, lbann::reshape_layer< T_layout >::reshape_layer, lbann::reshape_layer< T_layout >::setup_dims, lbann::slice_layer< T_layout >::setup_dims, lbann::slice_layer< T_layout >::get_neuron_dims, lbann::slice_layer< T_layout >::fp_output_dims, lbann::sum_layer< T_layout >::setup_dims, lbann::uniform_layer< T_layout >::uniform_layer, lbann::uniform_layer< T_layout >::setup_dims, lbann::unpooling_layer< T_layout >::setup_dims, lbann::unpooling_layer< T_layout >::fp_compute_im2col, lbann::unpooling_layer< T_layout >::bp_compute_im2col, Layer, operator=, setup_dims, setup_gpu, check_setup, fp_setup_data, bp_setup_data.
int lbann::Layer::m_num_neurons
Size of activation tensor.
Referenced by lbann::generic_input_layer::setup_dims, lbann::generic_input_layer::setup_data, lbann::generic_target_layer::setup_dims, lbann::generic_target_layer::setup_data, lbann::generic_target_layer::check_setup, lbann::reconstruction_layer< T_layout >::setup_dims, get_num_neurons, lbann::base_convolution_layer::apply_bias_cpu, lbann::base_convolution_layer::compute_gradients_im2col, lbann::convolution_layer< T_layout >::setup_dims, lbann::deconvolution_layer< T_layout >::setup_dims, lbann::batch_normalization< T_layout >::fp_compute_gpu, lbann::batch_normalization< T_layout >::fp_compute_cpu, lbann::batch_normalization< T_layout >::bp_compute_cpu, lbann::local_response_normalization_layer< T_layout >::fp_compute_cpu, lbann::local_response_normalization_layer< T_layout >::bp_compute_cpu, lbann::bernoulli_layer< T_layout >::bernoulli_layer, lbann::bernoulli_layer< T_layout >::setup_dims, lbann::concatenation_layer< T_layout >::setup_dims, lbann::constant_layer< T_layout >::constant_layer, lbann::constant_layer< T_layout >::setup_dims, lbann::gaussian_layer< T_layout >::gaussian_layer, lbann::gaussian_layer< T_layout >::setup_dims, lbann::pooling_layer< T_layout >::setup_dims, lbann::pooling_layer< T_layout >::fp_compute_im2col, lbann::pooling_layer< T_layout >::bp_compute_im2col, lbann::reshape_layer< T_layout >::reshape_layer, lbann::reshape_layer< T_layout >::setup_dims, lbann::uniform_layer< T_layout >::uniform_layer, lbann::uniform_layer< T_layout >::setup_dims, lbann::unpooling_layer< T_layout >::setup_dims, Layer, operator=, setup_dims, check_setup, fp_setup_data, bp_setup_data.
int lbann::Layer::m_num_neuron_dims
Number of dimensions of activation tensor.
Referenced by lbann::generic_input_layer::setup_dims, lbann::generic_target_layer::setup_dims, lbann::reconstruction_layer< T_layout >::setup_dims, get_num_neuron_dims, lbann::base_convolution_layer::setup_gpu, lbann::base_convolution_layer::compute_gradients_im2col, lbann::convolution_layer< T_layout >::setup_dims, lbann::deconvolution_layer< T_layout >::setup_dims, lbann::bernoulli_layer< T_layout >::bernoulli_layer, lbann::bernoulli_layer< T_layout >::setup_dims, lbann::constant_layer< T_layout >::constant_layer, lbann::constant_layer< T_layout >::setup_dims, lbann::gaussian_layer< T_layout >::gaussian_layer, lbann::gaussian_layer< T_layout >::setup_dims, lbann::pooling_layer< T_layout >::setup_dims, lbann::reshape_layer< T_layout >::reshape_layer, lbann::reshape_layer< T_layout >::setup_dims, lbann::uniform_layer< T_layout >::uniform_layer, lbann::uniform_layer< T_layout >::setup_dims, lbann::unpooling_layer< T_layout >::setup_dims, lbann::unpooling_layer< T_layout >::fp_compute_im2col, lbann::unpooling_layer< T_layout >::bp_compute_im2col, Layer, operator=, setup_dims.
std::vector<int> lbann::Layer::m_prev_neuron_dims
Dimensions of previous activation tensor. If a derived class has more than one previous activation tensor, it is responsible for its own interpretation.
Referenced by get_prev_neuron_dims, lbann::base_convolution_layer::setup_data, lbann::base_convolution_layer::apply_convolution_im2col, lbann::base_convolution_layer::apply_transposed_convolution_im2col, lbann::base_convolution_layer::compute_gradients_im2col, lbann::convolution_layer< T_layout >::setup_dims, lbann::deconvolution_layer< T_layout >::setup_dims, lbann::concatenation_layer< T_layout >::setup_dims, lbann::concatenation_layer< T_layout >::get_prev_neuron_dims, lbann::pooling_layer< T_layout >::setup_dims, lbann::pooling_layer< T_layout >::fp_compute_im2col, lbann::pooling_layer< T_layout >::bp_compute_im2col, lbann::slice_layer< T_layout >::fp_compute_cpu, lbann::slice_layer< T_layout >::bp_compute_cpu, lbann::slice_layer< T_layout >::fp_compute_gpu, lbann::slice_layer< T_layout >::bp_compute_gpu, lbann::unpooling_layer< T_layout >::setup_dims, lbann::unpooling_layer< T_layout >::fp_compute_im2col, lbann::unpooling_layer< T_layout >::bp_compute_im2col, Layer, operator=, setup_dims, setup_gpu, fp_setup_data, bp_setup_data.
int lbann::Layer::m_num_prev_neurons
Size of previous activation tensor.
Referenced by lbann::generic_target_layer::check_setup, lbann::reconstruction_layer< T_layout >::setup_dims, get_num_prev_neurons, lbann::base_convolution_layer::compute_gradients_im2col, lbann::unpooling_layer< T_layout >::setup_dims, lbann::unpooling_layer< T_layout >::fp_compute_im2col, lbann::unpooling_layer< T_layout >::bp_compute_im2col, Layer, operator=, setup_dims, fp_setup_data, bp_setup_data.
int lbann::Layer::m_num_prev_neuron_dims
Number of dimensions of previous activation tensor.
Referenced by get_num_prev_neuron_dims, lbann::base_convolution_layer::compute_gradients_im2col, lbann::pooling_layer< T_layout >::fp_compute_im2col, lbann::pooling_layer< T_layout >::bp_compute_im2col, lbann::unpooling_layer< T_layout >::setup_dims, Layer, operator=, setup_dims.
std::vector<AbsDistMat*> lbann::Layer::m_prev_activations
Previous activation matrices. Forward propagation inputs from each parent layer. These are typically matrix views where each column is a flattened tensor corresponding to a mini-batch sample. The matrices are owned by the layer.
Referenced by lbann::hadamard_layer< T_layout >::fp_compute, lbann::hadamard_layer< T_layout >::bp_compute, Layer, operator=, get_prev_activations, lbann::Layer::instantiate_matrices< data_layout::MODEL_PARALLEL >, lbann::Layer::instantiate_matrices< data_layout::DATA_PARALLEL >, setup_data, check_setup, deallocate_matrices.
std::vector<AbsDistMat*> lbann::Layer::m_activations
Activation matrices. Forward propagation outputs to each child layer. These are typically matrices where each column is a flattened tensor corresponding to a mini-batch sample. The matrices are owned by the layer.
Referenced by lbann::split_layer< T_layout >::fp_compute, Layer, operator=, summarize_matrices, get_activations, lbann::Layer::instantiate_matrices< data_layout::MODEL_PARALLEL >, lbann::Layer::instantiate_matrices< data_layout::DATA_PARALLEL >, setup_data, check_setup, deallocate_matrices.
std::vector<AbsDistMat*> lbann::Layer::m_prev_error_signals
Error signal matrices. Backward propagation inputs from each child layer. These are typically matrix views where each column is a flattened tensor corresponding to a mini-batch sample. The matrices are owned by the layer.
Referenced by lbann::split_layer< T_layout >::bp_compute, Layer, operator=, get_prev_error_signals, lbann::Layer::instantiate_matrices< data_layout::MODEL_PARALLEL >, lbann::Layer::instantiate_matrices< data_layout::DATA_PARALLEL >, setup_data, check_setup, deallocate_matrices, bp_setup_data.
std::vector<AbsDistMat*> lbann::Layer::m_error_signals
Error signal matrices. Backward propagation outputs to each parent layer. These are typically matrices where each column is a flattened tensor corresponding to a mini-batch sample. The matrices are owned by the layer.
Referenced by add_to_error_signal, lbann::hadamard_layer< T_layout >::bp_compute, Layer, operator=, summarize_matrices, get_error_signals, lbann::Layer::instantiate_matrices< data_layout::MODEL_PARALLEL >, lbann::Layer::instantiate_matrices< data_layout::DATA_PARALLEL >, setup_data, check_setup, deallocate_matrices.
std::vector<weights*> lbann::Layer::m_weights
References to layer weights.
Referenced by get_weights, lbann::base_convolution_layer::setup_data, lbann::base_convolution_layer::check_setup, lbann::base_convolution_layer::apply_convolution_cudnn, lbann::base_convolution_layer::apply_transposed_convolution_cudnn, lbann::base_convolution_layer::apply_bias_cudnn, lbann::base_convolution_layer::compute_gradients_cudnn, lbann::base_convolution_layer::apply_convolution_im2col, lbann::base_convolution_layer::apply_transposed_convolution_im2col, lbann::base_convolution_layer::apply_bias_cpu, lbann::base_convolution_layer::compute_gradients_im2col, lbann::convolution_layer< T_layout >::setup_data, lbann::deconvolution_layer< T_layout >::setup_data, lbann::batch_normalization< T_layout >::setup_data, lbann::batch_normalization< T_layout >::fp_compute_gpu, lbann::batch_normalization< T_layout >::bp_compute_gpu, lbann::batch_normalization< T_layout >::fp_compute_cpu, lbann::batch_normalization< T_layout >::bp_compute_cpu, operator=, forward_prop, back_prop, freeze, unfreeze, is_frozen, replace_weights, write_proto.
std::vector<const Layer*> lbann::Layer::m_parent_layers
References to parent layers.
Referenced by get_parent_layers, get_parent_names, lbann::concatenation_layer< T_layout >::get_description, lbann::concatenation_layer< T_layout >::setup_dims, lbann::hadamard_layer< T_layout >::get_description, lbann::sum_layer< T_layout >::get_description, lbann::sum_layer< T_layout >::setup_dims, operator=, setup_pointers, setup_dims, write_proto, fp_setup_data, bp_setup_data, get_bp_output, add_parent_layer, get_layer_pointers, set_layer_pointers.
std::vector<const Layer*> lbann::Layer::m_child_layers
References to child layers.
Referenced by get_child_layers, get_child_names, lbann::slice_layer< T_layout >::get_description, lbann::slice_layer< T_layout >::setup_dims, lbann::slice_layer< T_layout >::fp_output_dims, lbann::split_layer< T_layout >::get_description, operator=, setup_pointers, bp_setup_data, get_fp_output, get_bp_output, add_child_layer, get_layer_pointers, set_layer_pointers.
int lbann::Layer::m_expected_num_parent_layers
Expected number of parent layers. A negative value indicates no limit.
Referenced by lbann::generic_input_layer::generic_input_layer, get_expected_num_parent_layers, lbann::bernoulli_layer< T_layout >::bernoulli_layer, lbann::concatenation_layer< T_layout >::concatenation_layer, lbann::constant_layer< T_layout >::constant_layer, lbann::gaussian_layer< T_layout >::gaussian_layer, lbann::hadamard_layer< T_layout >::hadamard_layer, lbann::sum_layer< T_layout >::sum_layer, lbann::uniform_layer< T_layout >::uniform_layer, operator=, setup_pointers.
int lbann::Layer::m_expected_num_child_layers
Expected number of child layers. A negative value indicates no limit.
Referenced by lbann::generic_target_layer::generic_target_layer, get_expected_num_child_layers, lbann::dummy_layer< T_layout >::dummy_layer, lbann::evaluation_layer< T_layout >::evaluation_layer, lbann::slice_layer< T_layout >::slice_layer, lbann::split_layer< T_layout >::split_layer, operator=, setup_pointers.
model* lbann::Layer::m_model
Reference to model managing this layer.
Referenced by lbann::generic_input_layer::setup_data, lbann::generic_input_layer::fp_setup_data, lbann::generic_input_layer::fp_compute, lbann::generic_input_layer::update_compute, lbann::generic_input_layer::get_data_reader, lbann::generic_input_layer::get_num_parallel_readers, lbann::generic_input_layer::get_num_iterations_per_epoch, lbann::generic_input_layer::get_current_step_in_epoch, lbann::generic_input_layer::get_last_mini_batch_size, lbann::generic_input_layer::get_current_mini_batch_size, lbann::generic_input_layer::get_current_global_mini_batch_size, lbann::generic_input_layer::get_world_master_mini_batch_adjustment, lbann::generic_input_layer::get_current_world_master_mini_batch_adjustment, lbann::generic_input_layer::select_dataset, lbann::generic_target_layer::setup_data, lbann::generic_target_layer::fp_compute, lbann::generic_target_layer::update_compute, lbann::reconstruction_layer< T_layout >::summarize_stats, get_model, set_model, lbann::base_convolution_layer::setup_data, lbann::base_convolution_layer::compute_gradients_cudnn, lbann::base_convolution_layer::compute_gradients_im2col, lbann::batch_normalization< T_layout >::setup_data, lbann::batch_normalization< T_layout >::fp_compute_gpu, lbann::batch_normalization< T_layout >::bp_compute_gpu, lbann::batch_normalization< T_layout >::fp_compute_cpu, lbann::batch_normalization< T_layout >::bp_compute_cpu, lbann::dropout< T_layout >::fp_setup_data, lbann::dropout< T_layout >::fp_compute_cpu, lbann::dropout< T_layout >::bp_compute_cpu, lbann::dropout< T_layout >::fp_compute_gpu, lbann::dropout< T_layout >::bp_compute_gpu, lbann::selu_dropout< T_layout >::fp_compute, lbann::selu_dropout< T_layout >::bp_compute, lbann::bernoulli_layer< T_layout >::fp_compute, lbann::evaluation_layer< T_layout >::fp_compute, lbann::gaussian_layer< T_layout >::fp_compute, lbann::uniform_layer< T_layout >::fp_compute, operator=, forward_prop, back_prop, setup_data, setup_gpu, get_bp_output.
bool lbann::Layer::m_using_gpus
Whether current layer is using a GPU implementation.
Referenced by lbann::entrywise_activation_layer::fp_compute, lbann::entrywise_activation_layer::bp_compute, lbann::relu_layer< T_layout >::relu_layer, lbann::softmax_layer< T_layout >::softmax_layer, lbann::softmax_layer< T_layout >::operator=, using_gpus, lbann::convolution_layer< T_layout >::convolution_layer, lbann::convolution_layer< T_layout >::fp_compute, lbann::convolution_layer< T_layout >::bp_compute, lbann::deconvolution_layer< T_layout >::deconvolution_layer, lbann::deconvolution_layer< T_layout >::fp_compute, lbann::deconvolution_layer< T_layout >::bp_compute, lbann::batch_normalization< T_layout >::batch_normalization, lbann::batch_normalization< T_layout >::fp_compute, lbann::batch_normalization< T_layout >::bp_compute, lbann::dropout< T_layout >::dropout, lbann::dropout< T_layout >::setup_matrices, lbann::dropout< T_layout >::fp_compute, lbann::dropout< T_layout >::bp_compute, lbann::dropout< T_layout >::fp_setup_data, lbann::local_response_normalization_layer< T_layout >::local_response_normalization_layer, lbann::local_response_normalization_layer< T_layout >::fp_compute, lbann::local_response_normalization_layer< T_layout >::bp_compute, lbann::concatenation_layer< T_layout >::concatenation_layer, lbann::concatenation_layer< T_layout >::fp_compute, lbann::concatenation_layer< T_layout >::bp_compute, lbann::constant_layer< T_layout >::constant_layer, lbann::dummy_layer< T_layout >::dummy_layer, lbann::hadamard_layer< T_layout >::fp_compute, lbann::hadamard_layer< T_layout >::bp_compute, lbann::pooling_layer< T_layout >::pooling_layer, lbann::pooling_layer< T_layout >::fp_compute, lbann::pooling_layer< T_layout >::bp_compute, lbann::slice_layer< T_layout >::slice_layer, lbann::slice_layer< T_layout >::fp_compute, lbann::slice_layer< T_layout >::bp_compute, lbann::split_layer< T_layout >::split_layer, lbann::split_layer< T_layout >::fp_compute, lbann::split_layer< T_layout >::bp_compute, lbann::sum_layer< T_layout >::sum_layer, lbann::sum_layer< T_layout >::fp_compute, lbann::sum_layer< T_layout >::bp_compute, lbann::unpooling_layer< T_layout >::fp_compute, lbann::unpooling_layer< T_layout >::bp_compute, Layer, operator=, forward_prop, back_prop, clear_error_signals, setup, fp_setup_data, bp_setup_data, get_fp_output, get_bp_output.
cudnn::cudnn_manager* lbann::Layer::m_cudnn
Reference to cuDNN manager.
Referenced by lbann::relu_layer< T_layout >::relu_layer, lbann::relu_layer< T_layout >::fp_compute_gpu, lbann::relu_layer< T_layout >::bp_compute_gpu, lbann::softmax_layer< T_layout >::softmax_layer, lbann::softmax_layer< T_layout >::operator=, get_cudnn_manager, lbann::base_convolution_layer::base_convolution_layer, lbann::base_convolution_layer::setup_data, lbann::base_convolution_layer::setup_gpu, lbann::base_convolution_layer::apply_convolution_cudnn, lbann::base_convolution_layer::apply_transposed_convolution_cudnn, lbann::base_convolution_layer::apply_bias_cudnn, lbann::base_convolution_layer::compute_gradients_cudnn, lbann::convolution_layer< T_layout >::convolution_layer, lbann::deconvolution_layer< T_layout >::deconvolution_layer, lbann::batch_normalization< T_layout >::batch_normalization, lbann::batch_normalization< T_layout >::setup_data, lbann::batch_normalization< T_layout >::setup_gpu, lbann::batch_normalization< T_layout >::fp_compute_gpu, lbann::batch_normalization< T_layout >::bp_compute_gpu, lbann::dropout< T_layout >::dropout, lbann::dropout< T_layout >::setup_gpu, lbann::dropout< T_layout >::fp_compute_gpu, lbann::dropout< T_layout >::bp_compute_gpu, lbann::local_response_normalization_layer< T_layout >::local_response_normalization_layer, lbann::local_response_normalization_layer< T_layout >::fp_compute_cudnn, lbann::local_response_normalization_layer< T_layout >::bp_compute_cudnn, lbann::concatenation_layer< T_layout >::concatenation_layer, lbann::concatenation_layer< T_layout >::fp_compute_gpu, lbann::concatenation_layer< T_layout >::bp_compute_gpu, lbann::constant_layer< T_layout >::constant_layer, lbann::constant_layer< T_layout >::setup_gpu, lbann::dummy_layer< T_layout >::dummy_layer, lbann::pooling_layer< T_layout >::pooling_layer, lbann::pooling_layer< T_layout >::fp_compute_cudnn, lbann::pooling_layer< T_layout >::bp_compute_cudnn, lbann::slice_layer< T_layout >::slice_layer, lbann::slice_layer< T_layout >::fp_compute_gpu, lbann::slice_layer< T_layout >::bp_compute_gpu, lbann::split_layer< T_layout >::split_layer, lbann::split_layer< T_layout >::bp_compute, lbann::sum_layer< T_layout >::sum_layer, lbann::sum_layer< T_layout >::fp_compute, lbann::sum_layer< T_layout >::bp_compute, operator=, forward_prop, back_prop, setup_gpu, deallocate_matrices, fp_setup_data, bp_setup_data, get_fp_output, get_bp_output.
bool lbann::Layer::m_frozen
Avoid back prop if frozen
Referenced by lbann::base_convolution_layer::setup_data, lbann::batch_normalization< T_layout >::setup_data, operator=, update, freeze, unfreeze, is_frozen.
EvalType lbann::Layer::m_fp_time
Time spent in forward propagation.
Referenced by operator=, forward_prop, reset_counters, summarize_stats.
EvalType lbann::Layer::m_fp_compute_time
Time spent in the forward propagation computation.
Referenced by operator=, forward_prop, reset_counters.
EvalType lbann::Layer::m_bp_time
Time spent in backward propagation.
Referenced by operator=, back_prop, reset_counters, summarize_stats.
EvalType lbann::Layer::m_bp_compute_time
Time spent in the backward propagation computation.
Referenced by operator=, back_prop, reset_counters.
EvalType lbann::Layer::m_update_time
Time spent in updates.
Referenced by operator=, update, reset_counters, summarize_stats.
std::string lbann::Layer::m_name
Layer instance's name. Each layer in a model should have a unique, preferably human-readable, name.
Referenced by lbann::reconstruction_layer< T_layout >::summarize_stats, get_name, set_name, lbann::base_convolution_layer::setup_data, lbann::base_convolution_layer::check_setup, lbann::batch_normalization< T_layout >::setup_data, Layer, operator=, summarize_stats, summarize_matrices, get_prev_activations, get_activations, get_prev_error_signals, get_error_signals, setup_pointers, check_setup.
lbann::Layer::Layer(lbann_comm *comm)
References m_name, m_neuron_dims, m_num_neurons, m_num_neuron_dims, m_prev_neuron_dims, m_num_prev_neurons, m_num_prev_neuron_dims, m_using_gpus, reset_counters.
lbann::Layer::Layer(const Layer &other)
References m_prev_activations, m_activations, m_prev_error_signals, m_error_signals.
Layer & lbann::Layer::operator=(const Layer &other)
References m_comm, m_neuron_dims, m_num_neurons, m_num_neuron_dims, m_prev_neuron_dims, m_num_prev_neurons, m_num_prev_neuron_dims, m_weights, m_parent_layers, m_child_layers, m_expected_num_parent_layers, m_expected_num_child_layers, m_model, m_using_gpus, m_cudnn, m_frozen, m_fp_time, m_fp_compute_time, m_bp_time, m_bp_compute_time, m_update_time, m_name, deallocate_matrices, m_prev_activations, m_activations, m_prev_error_signals, m_error_signals.
Referenced by lbann::relu_layer< T_layout >::operator=, lbann::softmax_layer< T_layout >::operator=, lbann::generic_input_layer::operator=, lbann::generic_target_layer::operator=, lbann::base_convolution_layer::operator=, lbann::fully_connected_layer< T_layout >::operator=, lbann::batch_normalization< T_layout >::operator=, lbann::dropout< T_layout >::operator=, lbann::local_response_normalization_layer< T_layout >::operator=, lbann::selu_dropout< T_layout >::operator=, lbann::concatenation_layer< T_layout >::operator=, lbann::pooling_layer< T_layout >::operator=, lbann::slice_layer< T_layout >::operator=.
lbann::Layer::~Layer()
References deallocate_matrices.
virtual Layer* lbann::Layer::copy() const =0
Copy function. This function dynamically allocates memory for a layer instance and instantiates a copy. The caller is responsible for deallocating the instance.
Referenced by lbann::siamese_model::setup_layer_topology.
virtual std::string lbann::Layer::get_type() const =0
Get the layer type's name. A layer type name should be brief, human-readable description of the layer's mathematical operation.
Referenced by lbann::lbann_callback_debug::on_forward_prop_begin, lbann::lbann_callback_debug::on_forward_prop_end, lbann::lbann_callback_debug::on_backward_prop_begin, lbann::lbann_callback_debug::on_backward_prop_end, lbann::lbann_callback_debug::on_evaluate_forward_prop_begin, lbann::lbann_callback_debug::on_evaluate_forward_prop_end, lbann::lbann_callback_profiler::get_color, lbann::lbann_callback_profiler::on_forward_prop_begin, lbann::lbann_callback_profiler::on_forward_prop_end, lbann::lbann_callback_profiler::on_backward_prop_begin, lbann::lbann_callback_profiler::on_backward_prop_end, get_description, write_proto, lbann::model::print_layer_description.
std::string lbann::Layer::get_name() const
Get the layer instance's name. Each layer in a model should have a unique, preferably human-readable, name.
References m_name.
Referenced by lbann::reconstruction_layer< T_layout >::get_description, lbann::concatenation_layer< T_layout >::setup_dims, lbann::sum_layer< T_layout >::setup_dims, lbann::sum_layer< T_layout >::setup_data, lbann::lbann_callback_checknan::on_forward_prop_end, lbann::lbann_callback_checksmall::on_forward_prop_end, lbann::lbann_callback_debug::on_forward_prop_begin, lbann::lbann_callback_debug::on_forward_prop_end, lbann::lbann_callback_debug::on_backward_prop_begin, lbann::lbann_callback_debug::on_backward_prop_end, lbann::lbann_callback_debug::on_evaluate_forward_prop_begin, lbann::lbann_callback_debug::on_evaluate_forward_prop_end, lbann::lbann_callback_debug_io::print_fp_start, lbann::lbann_callback_dump_activations::on_forward_prop_end, lbann::lbann_callback_dump_minibatch_sample_indices::dump_to_file, lbann::lbann_callback_timeline::on_forward_prop_end, lbann::lbann_callback_timeline::on_backward_prop_end, get_description, write_proto, fp_setup_data, bp_setup_data, get_fp_output, get_bp_output, get_layer_names, lbann::model::print_layer_description, lbann::siamese_model::setup_layer_topology, lbann::proto::anonymous_namespace{layer_graph_factory.cpp}::setup_target_pointers, lbann::proto::anonymous_namespace{layer_graph_factory.cpp}::setup_reconstruction_pointers, lbann::proto::anonymous_namespace{layer_graph_factory.cpp}::setup_unpooling_pointers, lbann::proto::construct_layer_graph.
void lbann::Layer::set_name(const std::string name)
Set the layer instance's name. Each layer in a model should have a unique, preferably human-readable, name.
References m_name, get_description, get_topo_description, forward_prop, back_prop, update, clear_error_signals, summarize_stats, summarize_matrices, setup, check_setup, get_data_layout, get_data_layout_string.
Referenced by lbann::greedy_layerwise_autoencoder::set_phase, lbann::model::add_dummy_layers, lbann::model::add_split_layers, lbann::anonymous_namespace{recurrent.cpp}::unroll_input_layer, lbann::anonymous_namespace{recurrent.cpp}::add_placeholder_layers, lbann::siamese_model::setup_layer_topology, lbann::proto::construct_layer_graph.
std::string lbann::Layer::get_description() const
Get a human-readable description of the layer parameters.
References get_name, get_type.
Referenced by set_name.
std::string lbann::Layer::get_topo_description() const
Get a human-readable description of the activation tensors. Activation tensors are stored in distributed matrices where each column corresponds to a mini-batch sample. Within each column, the data is packed w.r.t. the last tensor dimension, then w.r.t. the penultimate dimension, and so on. 3D tensors are assumed to be 2D images in NCHW format.
References get_num_children, get_neuron_dims, get_activations.
Referenced by set_name, lbann::convolution_layer< T_layout >::get_topo_description, lbann::model::print_layer_description.
void lbann::Layer::forward_prop()
Forward propagation step. Apply a mathematical operation to the previous activations to obtain the activations.
References lbann::get_time, fp_setup_data, m_model, lbann::model::get_current_mini_batch_size, m_using_gpus, m_cudnn, fp_compute, m_fp_compute_time, m_weights, lbann::optimizer::add_gradient_source, m_fp_time.
Referenced by set_name, lbann::greedy_layerwise_autoencoder::forward_prop.
void lbann::Layer::back_prop()
Backward propagation step. Given the objective function gradients w.r.t. the activations (the previous error signals), compute the gradients w.r.t. the previous activations (the error signals) and w.r.t. the weights. This is essentially an application of the chain rule. Note that the objective function may have terms that are independent of the activations, so we add to the gradients rather than overwriting them. This means the error signals and weight gradients must be cleared before performing backward propagation (see the clear_error_signals function).
References lbann::get_time, bp_setup_data, m_model, lbann::model::get_current_mini_batch_size, m_using_gpus, m_cudnn, bp_compute, m_bp_compute_time, m_weights, m_bp_time.
Referenced by set_name, lbann::greedy_layerwise_autoencoder::backward_prop, lbann::model::backward_prop.
bool lbann::Layer::update()
Update step. Update the layer's internal members. Note that the optimization step for the weights happens elsewhere.
References m_frozen, lbann::get_time, update_compute, m_update_time.
Referenced by set_name.
void lbann::Layer::clear_error_signals(int mini_batch_size)
Set the error signal tensors to zero. The error signals are resized for the current mini-batch size.
References get_num_children, get_prev_error_signals, get_num_neurons, get_num_parents, get_error_signals, get_num_prev_neurons, m_using_gpus.
Referenced by set_name.
void lbann::Layer::summarize_stats(lbann_summary &summarizer, int step)
References m_name, lbann::lbann_summary::reduce_scalar, m_fp_time, m_bp_time, m_update_time, reset_counters, get_weights, lbann::optimizer::get_step_time, lbann::optimizer::reset_counters.
Referenced by lbann::reconstruction_layer< T_layout >::summarize_stats, set_name.
void lbann::Layer::summarize_matrices(lbann_summary &summarizer, int step)
References get_num_children, m_name, lbann::lbann_summary::reduce_mean, m_activations, lbann::lbann_summary::reduce_min, lbann::lbann_summary::reduce_max, lbann::lbann_summary::reduce_stdev, lbann::lbann_summary::reduce_2norm, get_num_parents, m_error_signals.
Referenced by set_name.
void lbann::Layer::setup()
Setup layer members. By default, this calls the setup_pointers, setup_dims, setup_matrices, setup_data, and setup_gpu (if needed) functions. Unless the setup_pointers function has been replaced in an inherited class, it is assumed that pointers to parent/child layers have already been initialized.If the layer has already been setup, this function should destroy all layer members and reinitialize them. However, it is not guaranteed that derived classes will obey this behavior. Caveat emptor.
References setup_pointers, setup_dims, setup_matrices, m_comm, lbann::lbann_comm::get_model_grid, setup_data, m_using_gpus, setup_gpu.
Referenced by set_name.
void lbann::Layer::check_setup()
Check that the setup is reasonable.
References get_num_parents, get_num_children, m_prev_activations, m_activations, m_name, m_prev_error_signals, m_error_signals, m_num_neurons, m_neuron_dims.
Referenced by lbann::generic_target_layer::check_setup, set_name, lbann::base_convolution_layer::check_setup.
virtual data_layout lbann::Layer::get_data_layout() const =0
Get data layout of the data tensors. We assume that the data layouts of the previous activations, activations, previous error signals, and error signals are the same. Each concrete layer that is templated on its data layout should override this function to return its template parameter.
Referenced by lbann::generic_input_layer::get_description, lbann::generic_target_layer::get_description, set_name, setup_matrices, setup_gpu, bp_setup_data.
std::string lbann::Layer::get_data_layout_string(data_layout d) const
Get a human-readable description of the data_layout
References DATA_PARALLEL, MODEL_PARALLEL.
Referenced by lbann::relu_layer< T_layout >::get_description, lbann::selu_layer< T_layout >::get_description, lbann::generic_input_layer::get_description, lbann::generic_target_layer::get_description, lbann::reconstruction_layer< T_layout >::get_description, set_name, lbann::convolution_layer< T_layout >::get_description, lbann::deconvolution_layer< T_layout >::get_description, lbann::batch_normalization< T_layout >::get_description, lbann::dropout< T_layout >::get_description, lbann::local_response_normalization_layer< T_layout >::get_description, lbann::bernoulli_layer< T_layout >::get_description, lbann::concatenation_layer< T_layout >::get_description, lbann::constant_layer< T_layout >::get_description, lbann::dummy_layer< T_layout >::get_description, lbann::evaluation_layer< T_layout >::get_description, lbann::gaussian_layer< T_layout >::get_description, lbann::hadamard_layer< T_layout >::get_description, lbann::pooling_layer< T_layout >::get_description, lbann::safe_inv_layer< T_layout >::get_description, lbann::slice_layer< T_layout >::get_description, lbann::split_layer< T_layout >::get_description, lbann::sum_layer< T_layout >::get_description, lbann::uniform_layer< T_layout >::get_description.
virtual std::vector<int> lbann::Layer::get_prev_neuron_dims(int parent_index=0) const
Get the dimensions of a previous activations tensor.
References m_prev_neuron_dims.
virtual int lbann::Layer::get_num_prev_neurons(int parent_index=0) const
Get the size of a previous activations tensor.
References m_num_prev_neurons.
Referenced by lbann::generic_target_layer::fp_setup_data, clear_error_signals, setup_data, setup_gpu, fp_setup_data, get_bp_output, lbann::model::print_layer_description.
virtual int lbann::Layer::get_num_prev_neuron_dims(int parent_index=0) const
Get the number of dimensions of a previous activations tensor.
References m_num_prev_neuron_dims.
virtual std::vector<int> lbann::Layer::get_neuron_dims(int child_index=0) const
Get the dimensions of an activations tensor.
References m_neuron_dims.
Referenced by lbann::reconstruction_layer< T_layout >::setup_dims, get_topo_description.
virtual int lbann::Layer::get_num_neurons(int child_index=0) const
Get the size of an activations tensor.
References m_num_neurons.
Referenced by lbann::reconstruction_layer< T_layout >::setup_dims, clear_error_signals, setup_data, setup_gpu, fp_setup_data, bp_setup_data, get_bp_output, lbann::model::print_layer_description.
virtual int lbann::Layer::get_num_neuron_dims(int child_index=0) const
Get the number of dimensions of an activations tensor.
References m_num_neuron_dims, reset_counters.
Referenced by lbann::reconstruction_layer< T_layout >::setup_dims.
void lbann::Layer::reset_counters()
Reset layer stat counters.
References m_fp_time, m_fp_compute_time, m_bp_time, m_bp_compute_time, m_update_time.
Referenced by get_num_neuron_dims, Layer, summarize_stats.
bool lbann::Layer::using_gpus() const
Whether the layer is using a GPU implementation.
References m_using_gpus.
Referenced by lbann::unpooling_layer< T_layout >::setup_pointers, bp_setup_data.
int lbann::Layer::get_expected_num_parent_layers() const
Get expected number of parent layers. A negative value indicates no limit.
References m_expected_num_parent_layers.
int lbann::Layer::get_expected_num_child_layers() const
Get expected number of child layers. A negative value indicates no limit.
References m_expected_num_child_layers.
model* lbann::Layer::get_model() const
Return the model that manages this layer.
References m_model.
void lbann::Layer::set_model(model *m)
Set the model that manages this layer.
References m_model.
virtual El::Matrix<El::Int>* lbann::Layer::get_sample_indices_per_mb()
Referenced by lbann::lbann_callback_check_dataset::add_to_set, lbann::lbann_callback_dump_minibatch_sample_indices::dump_to_file.
virtual bool lbann::Layer::saveToFile(int fd, const char *filename) const
virtual bool lbann::Layer::loadFromFile(int fd, const char *filename)
References saveToCheckpoint, loadFromCheckpoint, save_to_checkpoint_shared, load_from_checkpoint_shared, write_proto, get_fp_output, get_bp_output.
bool lbann::Layer::saveToCheckpoint(int fd, const char *filename, size_t *bytes) const
Referenced by lbann::generic_target_layer::saveToCheckpoint, loadFromFile.
bool lbann::Layer::loadFromCheckpoint(int fd, const char *filename, size_t *bytes)
Referenced by lbann::generic_target_layer::loadFromCheckpoint, loadFromFile.
bool lbann::Layer::save_to_checkpoint_shared(persist &p, bool val_end) const
Referenced by lbann::generic_target_layer::save_to_checkpoint_shared, loadFromFile.
bool lbann::Layer::load_from_checkpoint_shared(persist &p)
Referenced by lbann::generic_target_layer::load_from_checkpoint_shared, loadFromFile.
void lbann::Layer::write_proto(lbann_data::Layer *proto) const
Write layer to proto file
References get_name, get_type, m_parent_layers, m_weights.
Referenced by loadFromFile.
void lbann::Layer::get_fp_output(AbsDistMat &fp_output, const Layer *child) const
Send forward propagation output to a child layer. On output, fp_output is either a matrix view or copy of the appropriate activation tensor.
References m_child_layers, get_name, get_activations, m_using_gpus, m_cudnn.
Referenced by loadFromFile.
void lbann::Layer::get_bp_output(AbsDistMat &bp_output, const Layer *parent) const
Send backward propagation output to a parent layer. On output, bp_output is either a matrix view or copy of the appropriate error signal tensor.
References m_parent_layers, get_name, get_error_signals, m_using_gpus, m_cudnn, m_child_layers, get_activations, m_comm, lbann::lbann_comm::get_procs_per_model, m_model, lbann::model::get_max_mini_batch_size, get_num_neurons, get_num_prev_neurons.
Referenced by loadFromFile.
virtual std::vector<int> lbann::Layer::fp_output_dims(const Layer *child=nullptr) const
Get dimensions of forward propagation output to a child layer. Returns the dimensions of the appropriate activations tensor.
References m_neuron_dims.
virtual void lbann::Layer::add_to_error_signal(const AbsDistMat &error_signals, DataType scale=DataType(1), int parent_index=0)
Add to the layer's error signal.
References m_error_signals.
Referenced by lbann::kl_divergence::differentiate.
std::vector<const Layer*>& lbann::Layer::get_parent_layers()
Get parent layers.
References m_parent_layers.
Referenced by get_num_parents, clear_parent_layers, lbann::greedy_layerwise_autoencoder::restore_sequential_model, lbann::model::add_connected_layers, lbann::model::add_split_layers.
const std::vector<const Layer*>& lbann::Layer::get_parent_layers() const
Get parent layers. (const)
References m_parent_layers.
std::vector<const Layer*>& lbann::Layer::get_child_layers()
Get child layers.
References m_child_layers.
Referenced by get_num_children, clear_child_layers, lbann::greedy_layerwise_autoencoder::restore_sequential_model, lbann::model::add_connected_layers, lbann::kl_divergence::differentiate.
const std::vector<const Layer*>& lbann::Layer::get_child_layers() const
Get child layers. (const)
References m_child_layers.
int lbann::Layer::get_num_parents() const
Get number of parent layers.
References get_parent_layers.
Referenced by lbann::concatenation_layer< T_layout >::setup_pointers, lbann::concatenation_layer< T_layout >::fp_compute_cpu, lbann::concatenation_layer< T_layout >::bp_compute_cpu, lbann::concatenation_layer< T_layout >::fp_compute_gpu, lbann::concatenation_layer< T_layout >::bp_compute_gpu, lbann::hadamard_layer< T_layout >::setup_pointers, lbann::hadamard_layer< T_layout >::bp_compute, lbann::sum_layer< T_layout >::setup_data, lbann::sum_layer< T_layout >::fp_compute, lbann::sum_layer< T_layout >::bp_compute, summarize_matrices, clear_error_signals, setup_pointers, lbann::Layer::instantiate_matrices< data_layout::MODEL_PARALLEL >, lbann::Layer::instantiate_matrices< data_layout::DATA_PARALLEL >, setup_data, setup_gpu, check_setup, fp_setup_data, bp_setup_data.
int lbann::Layer::get_num_children() const
Get number of child layers.
References get_child_layers, get_layer_names.
Referenced by lbann::slice_layer< T_layout >::setup_pointers, lbann::slice_layer< T_layout >::fp_compute_cpu, lbann::slice_layer< T_layout >::bp_compute_cpu, lbann::slice_layer< T_layout >::fp_compute_gpu, lbann::slice_layer< T_layout >::bp_compute_gpu, get_topo_description, summarize_matrices, clear_error_signals, setup_pointers, lbann::Layer::instantiate_matrices< data_layout::MODEL_PARALLEL >, lbann::Layer::instantiate_matrices< data_layout::DATA_PARALLEL >, setup_data, setup_gpu, check_setup, fp_setup_data, bp_setup_data.
std::string lbann::Layer::get_child_names() const
References get_layer_names, m_child_layers.
std::string lbann::Layer::get_parent_names() const
References get_layer_names, m_parent_layers, add_parent_layer, add_child_layer.
void lbann::Layer::add_parent_layer(const Layer *parent)
Add a parent layer. Does nothing if parent is a null pointer, the same layer, or already a parent.
References m_parent_layers.
Referenced by get_parent_names, lbann::greedy_layerwise_autoencoder::set_phase, lbann::model::add_dummy_layers, lbann::model::add_split_layers, lbann::anonymous_namespace{recurrent.cpp}::unroll_input_layer, lbann::anonymous_namespace{recurrent.cpp}::add_placeholder_layers.
void lbann::Layer::add_child_layer(const Layer *child)
Add a child layer. Does nothing if child is a null pointer, the same layer, or already a child.
References m_child_layers.
Referenced by get_parent_names, lbann::model::add_split_layers, lbann::anonymous_namespace{recurrent.cpp}::unroll_input_layer.
void lbann::Layer::clear_parent_layers()
Remove all parent layers. Parent layers are not deallocated.
References get_parent_layers.
void lbann::Layer::clear_child_layers()
Remove all child layers. Child layers are not deallocated.
References get_child_layers, get_layer_pointers, set_layer_pointers.
std::vector< Layer * > lbann::Layer::get_layer_pointers()
Get list of pointers to other layers.
References m_parent_layers, m_child_layers.
Referenced by lbann::generic_target_layer::get_layer_pointers, clear_child_layers, lbann::unpooling_layer< T_layout >::get_layer_pointers.
void lbann::Layer::set_layer_pointers(std::vector< Layer *> layers)
Set list of pointers to other layers.
References m_parent_layers, m_child_layers.
Referenced by lbann::generic_target_layer::set_layer_pointers, clear_child_layers, lbann::unpooling_layer< T_layout >::set_layer_pointers.
std::vector<weights*>& lbann::Layer::get_weights()
Get references to weights.
References m_weights.
Referenced by set_weights, summarize_stats, replace_weights.
const std::vector<weights*>& lbann::Layer::get_weights() const
Get references to weights. (const)
References m_weights.
void lbann::Layer::set_weights(std::vector< weights *> w)
Set list of pointers to weights.
References get_weights, replace_weights, get_prev_activations, get_activations, get_prev_error_signals, get_error_signals, get_local_prev_activations, get_local_activations, get_local_prev_error_signals, get_local_error_signals.
void lbann::Layer::replace_weights(Layer *other_layer)
Replace weights with another Layer's weights
References get_weights, m_weights.
Referenced by set_weights.
AbsDistMat & lbann::Layer::get_prev_activations(int parent_index=0)
Get previous activation tensor.
References get_prev_activations.
Referenced by lbann::identity_layer< T_layout >::fp_compute, lbann::generic_target_layer::setup_matrices, lbann::generic_target_layer::get_prediction, set_weights, lbann::batch_normalization< T_layout >::fp_compute_gpu, lbann::batch_normalization< T_layout >::bp_compute_gpu, lbann::batch_normalization< T_layout >::fp_compute_cpu, lbann::batch_normalization< T_layout >::bp_compute_cpu, lbann::dropout< T_layout >::fp_compute_cpu, lbann::selu_dropout< T_layout >::fp_compute, lbann::concatenation_layer< T_layout >::setup_matrices, lbann::concatenation_layer< T_layout >::fp_compute_cpu, lbann::evaluation_layer< T_layout >::fp_compute, lbann::reshape_layer< T_layout >::fp_compute, lbann::slice_layer< T_layout >::setup_matrices, lbann::slice_layer< T_layout >::fp_compute_cpu, lbann::split_layer< T_layout >::fp_compute, lbann::sum_layer< T_layout >::fp_compute, get_prev_activations, get_local_prev_activations, fp_setup_data, bp_setup_data.
AbsDistMat & lbann::Layer::get_activations(int child_index=0)
Get activation tensor.
References get_activations.
Referenced by lbann::identity_layer< T_layout >::fp_compute, lbann::generic_input_layer::fp_compute, lbann::reconstruction_layer< T_layout >::fp_compute, set_weights, lbann::dropout< T_layout >::setup_matrices, lbann::dropout< T_layout >::fp_compute_cpu, lbann::selu_dropout< T_layout >::setup_matrices, lbann::selu_dropout< T_layout >::fp_compute, lbann::bernoulli_layer< T_layout >::fp_compute, lbann::concatenation_layer< T_layout >::fp_compute_cpu, lbann::constant_layer< T_layout >::setup_data, lbann::constant_layer< T_layout >::fp_compute, lbann::gaussian_layer< T_layout >::fp_compute, lbann::reshape_layer< T_layout >::fp_compute, lbann::slice_layer< T_layout >::fp_compute_cpu, lbann::sum_layer< T_layout >::fp_compute, lbann::uniform_layer< T_layout >::fp_compute, lbann::lbann_callback_checknan::on_forward_prop_end, lbann::lbann_callback_checksmall::on_forward_prop_end, lbann::lbann_callback_dump_activations::on_forward_prop_end, get_topo_description, get_activations, get_local_activations, fp_setup_data, bp_setup_data, get_fp_output, get_bp_output, lbann::kl_divergence::finish_evaluation, lbann::kl_divergence::differentiate.
AbsDistMat & lbann::Layer::get_prev_error_signals(int child_index=0)
Get previous error signal tensor.
References get_prev_error_signals.
Referenced by lbann::identity_layer< T_layout >::bp_compute, set_weights, lbann::dropout< T_layout >::bp_compute_cpu, lbann::selu_dropout< T_layout >::bp_compute, lbann::concatenation_layer< T_layout >::bp_compute_cpu, lbann::reshape_layer< T_layout >::bp_compute, lbann::slice_layer< T_layout >::bp_compute_cpu, lbann::sum_layer< T_layout >::bp_compute, get_prev_error_signals, get_local_prev_error_signals, clear_error_signals, bp_setup_data.
AbsDistMat & lbann::Layer::get_error_signals(int parent_index=0)
Get error signal tensor.
References get_error_signals.
Referenced by lbann::identity_layer< T_layout >::bp_compute, set_weights, lbann::dropout< T_layout >::bp_compute_cpu, lbann::selu_dropout< T_layout >::bp_compute, lbann::concatenation_layer< T_layout >::bp_compute_cpu, lbann::evaluation_layer< T_layout >::bp_compute, lbann::reshape_layer< T_layout >::bp_compute, lbann::slice_layer< T_layout >::bp_compute_cpu, lbann::split_layer< T_layout >::bp_compute, lbann::sum_layer< T_layout >::bp_compute, get_error_signals, get_local_error_signals, clear_error_signals, bp_setup_data, get_bp_output.
const AbsDistMat & lbann::Layer::get_prev_activations(int parent_index=0) const
Get previous activation tensor. (const)
References m_prev_activations, m_name.
const AbsDistMat & lbann::Layer::get_activations(int child_index=0) const
Get activation tensor. (const)
References m_activations, m_name.
const AbsDistMat & lbann::Layer::get_prev_error_signals(int child_index=0) const
Get previous error signal tensor. (const)
References m_prev_error_signals, m_name.
const AbsDistMat & lbann::Layer::get_error_signals(int parent_index=0) const
Get error signal tensor. (const)
References m_error_signals, m_name.
Mat & lbann::Layer::get_local_prev_activations(int parent_index=0)
Get local portion of previous activation tensor.
References get_prev_activations.
Referenced by lbann::entrywise_activation_layer::fp_compute_cpu, lbann::entrywise_activation_layer::bp_compute_cpu, set_weights, lbann::base_convolution_layer::apply_convolution_im2col, lbann::base_convolution_layer::apply_transposed_convolution_im2col, lbann::base_convolution_layer::compute_gradients_im2col, lbann::local_response_normalization_layer< T_layout >::fp_compute_cpu, lbann::local_response_normalization_layer< T_layout >::bp_compute_cpu, lbann::pooling_layer< T_layout >::fp_compute_im2col, lbann::safe_inv_layer< T_layout >::fp_compute, lbann::safe_inv_layer< T_layout >::bp_compute, lbann::unpooling_layer< T_layout >::fp_compute_im2col.
Mat & lbann::Layer::get_local_activations(int child_index=0)
Get local portion of activation tensor.
References get_activations.
Referenced by lbann::entrywise_activation_layer::fp_compute_cpu, lbann::generic_input_layer::fp_setup_data, set_weights, lbann::base_convolution_layer::apply_convolution_im2col, lbann::base_convolution_layer::apply_transposed_convolution_im2col, lbann::base_convolution_layer::apply_bias_cpu, lbann::batch_normalization< T_layout >::fp_compute_cpu, lbann::local_response_normalization_layer< T_layout >::fp_compute_cpu, lbann::local_response_normalization_layer< T_layout >::bp_compute_cpu, lbann::selu_dropout< T_layout >::fp_compute, lbann::hadamard_layer< T_layout >::fp_compute, lbann::pooling_layer< T_layout >::fp_compute_im2col, lbann::safe_inv_layer< T_layout >::fp_compute, lbann::unpooling_layer< T_layout >::fp_compute_im2col, lbann::kl_divergence::finish_evaluation.
Mat & lbann::Layer::get_local_prev_error_signals(int child_index=0)
Get local portion of previous error signal tensor.
References get_prev_error_signals.
Referenced by lbann::entrywise_activation_layer::bp_compute_cpu, set_weights, lbann::base_convolution_layer::apply_convolution_im2col, lbann::base_convolution_layer::apply_transposed_convolution_im2col, lbann::base_convolution_layer::compute_gradients_im2col, lbann::batch_normalization< T_layout >::bp_compute_cpu, lbann::local_response_normalization_layer< T_layout >::bp_compute_cpu, lbann::selu_dropout< T_layout >::bp_compute, lbann::hadamard_layer< T_layout >::bp_compute, lbann::pooling_layer< T_layout >::bp_compute_im2col, lbann::safe_inv_layer< T_layout >::bp_compute, lbann::unpooling_layer< T_layout >::bp_compute_im2col.
Mat & lbann::Layer::get_local_error_signals(int parent_index=0)
Get local portion of error signal tensor.
References get_error_signals.
Referenced by lbann::entrywise_activation_layer::bp_compute_cpu, set_weights, lbann::base_convolution_layer::apply_convolution_im2col, lbann::base_convolution_layer::apply_transposed_convolution_im2col, lbann::batch_normalization< T_layout >::bp_compute_cpu, lbann::local_response_normalization_layer< T_layout >::bp_compute_cpu, lbann::selu_dropout< T_layout >::bp_compute, lbann::pooling_layer< T_layout >::bp_compute_im2col, lbann::safe_inv_layer< T_layout >::bp_compute, lbann::unpooling_layer< T_layout >::bp_compute_im2col.
const Mat & lbann::Layer::get_local_prev_activations(int parent_index=0) const
Get local portion of previous activation tensor. (const)
References get_prev_activations.
const Mat & lbann::Layer::get_local_activations(int child_index=0) const
Get local portion of activation tensor. (const)
References get_activations.
const Mat & lbann::Layer::get_local_prev_error_signals(int child_index=0) const
Get local portion of previous error signal tensor. (const)
References get_prev_error_signals.
const Mat & lbann::Layer::get_local_error_signals(int parent_index=0) const
Get local portion of error signal tensor. (const)
References get_error_signals.
lbann_comm* lbann::Layer::get_comm() const
Get reference to LBANN communicator.
References m_comm.
cudnn::cudnn_manager* lbann::Layer::get_cudnn_manager() const
Get reference to cuDNN manager.
References m_cudnn, freeze, unfreeze, is_frozen.
Referenced by lbann::model::add_dummy_layers, lbann::model::add_split_layers.
void lbann::Layer::freeze()
References m_frozen, m_weights.
Referenced by get_cudnn_manager, lbann::proto::construct_layer_graph.
void lbann::Layer::unfreeze()
References m_frozen, m_weights.
Referenced by get_cudnn_manager.
bool lbann::Layer::is_frozen() const
References m_weights, m_frozen.
Referenced by get_cudnn_manager, lbann::base_convolution_layer::setup_data, lbann::batch_normalization< T_layout >::setup_data, lbann::model::print_layer_description.
std::string lbann::Layer::get_layer_names(const std::vector< const Layer *> &list)
Get names in a particular list of layers
References get_name.
Referenced by get_num_children, get_child_names, get_parent_names, lbann::slice_layer< T_layout >::setup_dims.
void lbann::Layer::fp_setup_data(int mini_batch_size)
Setup data for forward propagation. Base method gets previous activations from parent layers and resizes activations for the current mini-batch size.
References get_num_parents, get_prev_activations, get_num_prev_neurons, get_num_children, get_activations, get_num_neurons, m_using_gpus, m_cudnn, m_parent_layers, get_name, m_num_prev_neurons, m_num_neurons, m_prev_neuron_dims, m_neuron_dims.
Referenced by lbann::softmax_layer< T_layout >::fp_setup_data, lbann::generic_input_layer::fp_setup_data, lbann::generic_target_layer::fp_setup_data, lbann::dropout< T_layout >::fp_setup_data, forward_prop.
void lbann::Layer::bp_setup_data(int mini_batch_size)
Setup data for forward propagation. Base method gets previous error signals from child layers. The error signals are resized for the current mini-batch size in the clear_error_signals function.
References get_num_children, m_child_layers, m_using_gpus, get_prev_error_signals, m_prev_error_signals, get_num_neurons, get_name, m_num_neurons, m_num_prev_neurons, m_neuron_dims, m_prev_neuron_dims, get_num_parents, m_parent_layers, using_gpus, m_cudnn, get_error_signals, get_prev_activations, get_activations, get_data_layout.
Referenced by back_prop.
void lbann::Layer::setup_pointers()
Setup pointers to parent and child layers. Called by the setup function. The base method checks that the number of parents and children are valid. Pointers to the parent/child layers are assumed to be already initialized.
References m_expected_num_parent_layers, get_num_parents, m_name, m_parent_layers, m_expected_num_child_layers, get_num_children, m_child_layers.
Referenced by lbann::concatenation_layer< T_layout >::setup_pointers, lbann::hadamard_layer< T_layout >::setup_pointers, lbann::slice_layer< T_layout >::setup_pointers, setup.
void lbann::Layer::setup_dims()
Setup tensor dimensions Called by the setup function. The base method sets the dimensions of the activation tensors equal to the dimensions of the first previous activation tensor.
References m_parent_layers, m_prev_neuron_dims, m_num_prev_neuron_dims, m_num_prev_neurons, m_num_neurons, m_num_neuron_dims, m_neuron_dims.
Referenced by lbann::generic_input_layer::setup_dims, lbann::generic_target_layer::setup_dims, lbann::convolution_layer< T_layout >::setup_dims, lbann::deconvolution_layer< T_layout >::setup_dims, lbann::fully_connected_layer< T_layout >::setup_dims, lbann::bernoulli_layer< T_layout >::setup_dims, lbann::concatenation_layer< T_layout >::setup_dims, lbann::constant_layer< T_layout >::setup_dims, lbann::gaussian_layer< T_layout >::setup_dims, lbann::pooling_layer< T_layout >::setup_dims, lbann::reduction_layer< T_layout >::setup_dims, lbann::reshape_layer< T_layout >::setup_dims, lbann::slice_layer< T_layout >::setup_dims, lbann::sum_layer< T_layout >::setup_dims, lbann::uniform_layer< T_layout >::setup_dims, lbann::unpooling_layer< T_layout >::setup_dims, setup.
void lbann::Layer::setup_matrices(const El::Grid &grid)
Instantiate distributed matrices. If the layer has already been setup, this function should destroy all matrices and reinstantiate them. However, it is not guaranteed that derived classes will obey this behavior.
References deallocate_matrices, get_data_layout, MODEL_PARALLEL, DATA_PARALLEL.
Referenced by lbann::generic_target_layer::setup_matrices, lbann::batch_normalization< T_layout >::setup_matrices, lbann::dropout< T_layout >::setup_matrices, lbann::selu_dropout< T_layout >::setup_matrices, lbann::concatenation_layer< T_layout >::setup_matrices, lbann::slice_layer< T_layout >::setup_matrices, lbann::softmax_layer< T_layout >::setup_matrices, setup, lbann::fully_connected_layer< T_layout >::setup_matrices.
void lbann::Layer::setup_data()
Setup layer data. Called by the setup function. The base method sets the previous activation, activation, previous error signal, and error signal matrices to zero matrices with the proper dimensions. Matrix buffers are pinned if needed for GPU transfers.
References m_model, lbann::model::get_max_mini_batch_size, get_num_parents, m_prev_activations, get_num_prev_neurons, m_error_signals, get_num_children, m_activations, get_num_neurons, m_prev_error_signals.
Referenced by lbann::softmax_layer< T_layout >::setup_data, lbann::generic_input_layer::setup_data, lbann::generic_target_layer::setup_data, lbann::base_convolution_layer::setup_data, lbann::fully_connected_layer< T_layout >::setup_data, lbann::batch_normalization< T_layout >::setup_data, lbann::constant_layer< T_layout >::setup_data, lbann::sum_layer< T_layout >::setup_data, setup.
void lbann::Layer::setup_gpu()
Setup GPU objects. Called by the setup function if GPUs are enabled. The base method initializes GPU matrices for the previous activations, activations, previous error signals, and error signals. It also initializes cuDNN tensor descriptors.
References get_data_layout, DATA_PARALLEL, m_cudnn, m_comm, lbann::lbann_comm::get_procs_per_model, m_model, lbann::model::get_max_mini_batch_size, get_num_parents, get_num_children, get_num_prev_neurons, get_num_neurons, m_prev_neuron_dims, m_neuron_dims.
Referenced by lbann::relu_layer< T_layout >::setup_gpu, lbann::base_convolution_layer::setup_gpu, lbann::fully_connected_layer< T_layout >::setup_gpu, lbann::batch_normalization< T_layout >::setup_gpu, lbann::dropout< T_layout >::setup_gpu, lbann::local_response_normalization_layer< T_layout >::setup_gpu, lbann::constant_layer< T_layout >::setup_gpu, lbann::pooling_layer< T_layout >::setup_gpu, setup.
virtual void lbann::Layer::fp_compute()=0
Perform the computation for the forward propagation step.
Referenced by forward_prop.
virtual void lbann::Layer::bp_compute()=0
Perform the computation for the backward propagation step.
Referenced by back_prop.
virtual bool lbann::Layer::update_compute()
Perform the computation for the update step. Returns false if the layer must reset for a new training epoch.
Referenced by update.
void lbann::Layer::instantiate_matrices(const El::Grid &grid)
Instantiate distributed matrices.
void lbann::Layer::deallocate_matrices()
Deallocate distributed matrices.
References m_cudnn, m_prev_activations, m_activations, m_prev_error_signals, m_error_signals.
Referenced by operator=, ~Layer, setup_matrices.