lbann::lbann_callback_profiler
const int lbann::lbann_callback_profiler::num_colors
Referenced by get_color.
int lbann::lbann_callback_profiler::colors[num_colors][num_colors]
Referenced by on_epoch_begin, on_batch_begin, on_forward_prop_begin, on_backward_prop_begin, get_color.
lbann::lbann_callback_profiler::lbann_callback_profiler()
References operator=.
Referenced by copy.
lbann::lbann_callback_profiler::lbann_callback_profiler(const lbann_callback_profiler &)=default
lbann_callback_profiler& lbann::lbann_callback_profiler::operator=(const lbann_callback_profiler &)=default
Referenced by lbann_callback_profiler.
lbann_callback_profiler* lbann::lbann_callback_profiler::copy() const override
References lbann_callback_profiler, on_epoch_begin, on_epoch_end, on_batch_begin, on_batch_end, on_forward_prop_begin, on_forward_prop_end, on_backward_prop_begin, on_backward_prop_end.
void lbann::lbann_callback_profiler::on_epoch_begin(model *m) override
Called at the beginning of each epoch.
References anonymous_namespace{profiler.cpp}::prof_region_begin, colors.
Referenced by copy.
void lbann::lbann_callback_profiler::on_epoch_end(model *m) override
Called immediate after the end of each epoch.
References anonymous_namespace{profiler.cpp}::prof_region_end.
Referenced by copy.
void lbann::lbann_callback_profiler::on_batch_begin(model *m) override
Called at the beginning of a (mini-)batch.
References anonymous_namespace{profiler.cpp}::prof_region_begin, colors.
Referenced by copy.
void lbann::lbann_callback_profiler::on_batch_end(model *m) override
Called immediately after the end of a (mini-)batch.
References anonymous_namespace{profiler.cpp}::prof_region_end.
Referenced by copy.
void lbann::lbann_callback_profiler::on_forward_prop_begin(model *m) override
Called when a model begins forward propagation.
References anonymous_namespace{profiler.cpp}::prof_region_begin, colors.
Referenced by copy.
void lbann::lbann_callback_profiler::on_forward_prop_end(model *m) override
Called when a model ends forward propagation.
References anonymous_namespace{profiler.cpp}::prof_region_end.
Referenced by copy.
void lbann::lbann_callback_profiler::on_backward_prop_begin(model *m) override
Called when a model begins backward propagation.
References anonymous_namespace{profiler.cpp}::prof_region_begin, colors.
Referenced by copy.
void lbann::lbann_callback_profiler::on_backward_prop_end(model *m) override
Called when a model ends backward propagation.
References anonymous_namespace{profiler.cpp}::prof_region_end.
Referenced by copy.
void lbann::lbann_callback_profiler::on_forward_prop_begin(model *m, Layer *l) override
Called when a layer begins forward propagation.
References anonymous_namespace{profiler.cpp}::prof_region_begin, lbann::Layer::get_type, get_color.
void lbann::lbann_callback_profiler::on_forward_prop_end(model *m, Layer *l) override
Called when a layer ends forward propagation.
References anonymous_namespace{profiler.cpp}::prof_region_end, lbann::Layer::get_type.
void lbann::lbann_callback_profiler::on_backward_prop_begin(model *m, Layer *l) override
Called when a layer begins backward propagation.
References anonymous_namespace{profiler.cpp}::prof_region_begin, lbann::Layer::get_type, get_color.
void lbann::lbann_callback_profiler::on_backward_prop_end(model *m, Layer *l) override
Called when a layer ends backward propagation.
References anonymous_namespace{profiler.cpp}::prof_region_end, lbann::Layer::get_type.
std::string lbann::lbann_callback_profiler::name() const override
Return this callback's name.
int lbann::lbann_callback_profiler::get_color(Layer *l)
References lbann::Layer::get_type, colors, num_colors.
Referenced by on_forward_prop_begin, on_backward_prop_begin.