lbann::mean_absolute_deviation_loss
lbann::mean_absolute_deviation_loss::mean_absolute_deviation_loss(EvalType scale_factor=EvalType(1))
Default constructor.
References operator=, ~mean_absolute_deviation_loss.
Referenced by copy.
lbann::mean_absolute_deviation_loss::mean_absolute_deviation_loss(const mean_absolute_deviation_loss &other)=default
Copy constructor.
mean_absolute_deviation_loss& lbann::mean_absolute_deviation_loss::operator=(const mean_absolute_deviation_loss &other)=default
Copy assignment operator.
Referenced by mean_absolute_deviation_loss.
lbann::mean_absolute_deviation_loss::~mean_absolute_deviation_loss() override=default
Destructor.
Referenced by mean_absolute_deviation_loss.
mean_absolute_deviation_loss* lbann::mean_absolute_deviation_loss::copy() const override
Copy function.
References mean_absolute_deviation_loss.
std::string lbann::mean_absolute_deviation_loss::name() const override
Get the name of the objective function term.
void lbann::mean_absolute_deviation_loss::start_evaluate_compute(const AbsDistMat &prediction, const AbsDistMat &ground_truth) override
Compute the mean absolute deviation objective function. Given a prediction $\hat{y}$ and ground truth $y$, the mean absolute deviation is \[ MAD(\hat{y}, y) = \frac{1}{n} \lVert y - \hat{y} \rVert_1 \] This function updates the objective function value with the mean value of the mean absolute deviation across the mini-batch.
References finish_evaluate_compute, prediction, differentiate_compute.
EvalType lbann::mean_absolute_deviation_loss::finish_evaluate_compute(const AbsDistMat &prediction, const AbsDistMat &ground_truth) override
Finish evaluation of the loss function. This should not include the scale factor.
References lbann::objective_function_term::get_comm, lbann::lbann_comm::allreduce.
Referenced by start_evaluate_compute.
void lbann::mean_absolute_deviation_loss::differentiate_compute(const AbsDistMat &prediction, const AbsDistMat &ground_truth, AbsDistMat &gradient) override
Compute the mean absolution deviation gradient. The gradient is w.r.t. the prediction vector.
Referenced by start_evaluate_compute.