lbann::mean_absolute_deviation_metric
lbann::mean_absolute_deviation_metric::mean_absolute_deviation_metric(lbann_comm *comm)
Constructor.
References operator=, ~mean_absolute_deviation_metric.
Referenced by copy.
lbann::mean_absolute_deviation_metric::mean_absolute_deviation_metric(const mean_absolute_deviation_metric &other)=default
Copy constructor.
mean_absolute_deviation_metric& lbann::mean_absolute_deviation_metric::operator=(const mean_absolute_deviation_metric &other)=default
Copy assignment operator.
Referenced by mean_absolute_deviation_metric.
virtual lbann::mean_absolute_deviation_metric::~mean_absolute_deviation_metric()=default
Destructor.
Referenced by mean_absolute_deviation_metric.
mean_absolute_deviation_metric* lbann::mean_absolute_deviation_metric::copy() const override
Copy function.
References mean_absolute_deviation_metric.
std::string lbann::mean_absolute_deviation_metric::name() const override
Return a string name for this metric.
References evaluate_compute, prediction.
EvalType lbann::mean_absolute_deviation_metric::evaluate_compute(const AbsDistMat &prediction, const AbsDistMat &ground_truth) override
Computation to evaluate the metric function. This returns the sum of metric values across the mini-batch, not the mean value.
References lbann::metric::get_comm, lbann::lbann_comm::allreduce.
Referenced by name.