lbann::input_layer
lbann::input_layer< T_io_buffer, T_layout >::input_layer(lbann_comm *comm, int num_parallel_readers, std::map< execution_mode, generic_data_reader *> data_readers, bool data_set_spans_models=true, bool for_regression=false)
Todomake the map and vector references
References lbann::input_layer< T_io_buffer, T_layout >::validate_data_layout, lbann::input_layer< T_io_buffer, T_layout >::initialize_io_buffer, lbann::Layer::m_comm, lbann::generic_input_layer::io_buffer, lbann::generic_io_buffer::fetch_data_fn, lbann::generic_io_buffer::update_data_reader_fn, lbann::input_layer< T_io_buffer, T_layout >::operator=.
Referenced by lbann::input_layer< T_io_buffer, T_layout >::copy.
lbann::input_layer< T_io_buffer, T_layout >::input_layer(const input_layer &)=default
input_layer& lbann::input_layer< T_io_buffer, T_layout >::operator=(const input_layer &)=default
Referenced by lbann::input_layer< T_io_buffer, T_layout >::input_layer.
input_layer* lbann::input_layer< T_io_buffer, T_layout >::copy() const override
Copy function. This function dynamically allocates memory for a layer instance and instantiates a copy. The caller is responsible for deallocating the instance.
References lbann::input_layer< T_io_buffer, T_layout >::input_layer.
std::string lbann::input_layer< T_io_buffer, T_layout >::get_type() const override
Get the layer type's name. A layer type name should be brief, human-readable description of the layer's mathematical operation.
References lbann::generic_input_layer::io_buffer, lbann::generic_io_buffer::get_type, lbann::input_layer< T_io_buffer, T_layout >::validate_data_layout.
void lbann::input_layer< T_io_buffer, T_layout >::validate_data_layout()
Referenced by lbann::input_layer< T_io_buffer, T_layout >::input_layer, lbann::input_layer< T_io_buffer, T_layout >::get_type.
void lbann::input_layer< T_io_buffer, T_layout >::initialize_io_buffer(lbann_comm *comm, int num_parallel_readers, std::map< execution_mode, generic_data_reader *> data_readers)
References comm.
Referenced by lbann::input_layer< T_io_buffer, T_layout >::input_layer.
data_layout lbann::input_layer< T_io_buffer, T_layout >::get_data_layout() const override
Get data layout of the data tensors. We assume that the data layouts of the previous activations, activations, previous error signals, and error signals are the same. Each concrete layer that is templated on its data layout should override this function to return its template parameter.
void lbann::input_layer< partitioned_io_buffer, data_layout::MODEL_PARALLEL >::validate_data_layout()
void lbann::input_layer< partitioned_io_buffer, data_layout::DATA_PARALLEL >::validate_data_layout()
void lbann::input_layer< distributed_io_buffer, data_layout::MODEL_PARALLEL >::validate_data_layout()
void lbann::input_layer< distributed_io_buffer, data_layout::DATA_PARALLEL >::validate_data_layout()