lbann::lbann_comm
allreduce_algorithm
const El::mpi::Comm lbann::lbann_comm::world_comm
World communicator.
El::mpi::Comm lbann::lbann_comm::model_comm
Communicator for every process in this model.
Referenced by ~lbann_comm, split_models, model_barrier.
El::mpi::Comm lbann::lbann_comm::intermodel_comm
Communicator for every process with the same model rank.
Referenced by ~lbann_comm, split_models, intermodel_sum_matrix, intermodel_broadcast_matrix, intermodel_barrier, intermodel_allreduce.
El::mpi::Comm lbann::lbann_comm::node_comm
Communicator for every process in the same compute node.
Referenced by lbann_comm, ~lbann_comm, setup_node_comm.
Grid* lbann::lbann_comm::grid
Grid for this model.
Referenced by ~lbann_comm, split_models.
int lbann::lbann_comm::num_models
Number of models.
Referenced by split_models.
int lbann::lbann_comm::procs_per_model
Number of processors per model.
Referenced by lbann_comm, split_models.
int lbann::lbann_comm::model_rank
Rank of the model this process is in.
Referenced by split_models.
int lbann::lbann_comm::rank_in_model
Rank of this process within its model.
Referenced by split_models.
int lbann::lbann_comm::procs_per_node
Number of processers per compute node.
Referenced by lbann_comm, setup_threads.
int lbann::lbann_comm::rank_in_node
Rank of this process within its compute node.
Referenced by lbann_comm.
std::vector<int> lbann::lbann_comm::world_ranks_on_node
The list of world ranks that are on this compute node.
Referenced by setup_node_comm.
int lbann::lbann_comm::threads_per_proc
Default number of threads per process. This is the number of OpenMP threads to use for parallel regions, provided omp_set_num_threads has not been called or the num_threads directive has not been provided.
Referenced by setup_threads, reset_threads.
std::map<size_t, std::vector<uint8_t *> > lbann::lbann_comm::collective_bufs
Pre-allocated buffers for collectives.
Referenced by ~lbann_comm, get_collective_buffer.
allreduce_algorithm lbann::lbann_comm::default_allreduce_algo
Current default allreduce algorithm.
size_t lbann::lbann_comm::num_model_barriers
Referenced by model_barrier.
size_t lbann::lbann_comm::num_intermodel_barriers
Referenced by intermodel_barrier.
size_t lbann::lbann_comm::num_global_barriers
Referenced by global_barrier.
size_t lbann::lbann_comm::bytes_sent
Referenced by intermodel_sum_matrix, allreduce, nb_allreduce, recursive_doubling_allreduce_pow2, pe_ring_allreduce, ring_allreduce, rabenseifner_allreduce.
size_t lbann::lbann_comm::bytes_received
Referenced by intermodel_sum_matrix, allreduce, nb_allreduce, recursive_doubling_allreduce_pow2, pe_ring_allreduce, ring_allreduce, rabenseifner_allreduce.
size_t lbann::lbann_comm::ar_bytes_sent
Referenced by recursive_doubling_allreduce_pow2, pe_ring_allreduce, ring_allreduce, rabenseifner_allreduce.
size_t lbann::lbann_comm::ar_bytes_received
Referenced by recursive_doubling_allreduce_pow2, pe_ring_allreduce, ring_allreduce, rabenseifner_allreduce.
size_t lbann::lbann_comm::ar_rs_bytes_sent
Referenced by pe_ring_allreduce, ring_allreduce, rabenseifner_allreduce.
size_t lbann::lbann_comm::ar_rs_bytes_received
Referenced by pe_ring_allreduce, ring_allreduce, rabenseifner_allreduce.
size_t lbann::lbann_comm::ar_ag_bytes_sent
Referenced by pe_ring_allreduce, ring_allreduce, rabenseifner_allreduce.
size_t lbann::lbann_comm::ar_ag_bytes_received
Referenced by pe_ring_allreduce, ring_allreduce, rabenseifner_allreduce.
double lbann::lbann_comm::ar_time
Referenced by recursive_doubling_allreduce_pow2, pe_ring_allreduce, ring_allreduce, rabenseifner_allreduce.
double lbann::lbann_comm::ar_rs_time
Referenced by pe_ring_allreduce, ring_allreduce, rabenseifner_allreduce.
double lbann::lbann_comm::ar_ag_time
Referenced by pe_ring_allreduce, ring_allreduce, rabenseifner_allreduce.
double lbann::lbann_comm::ar_send_transform_time
Referenced by recursive_doubling_allreduce_pow2, pe_ring_allreduce, ring_allreduce, rabenseifner_allreduce.
double lbann::lbann_comm::ar_recv_transform_time
Referenced by pe_ring_allreduce, ring_allreduce, rabenseifner_allreduce.
double lbann::lbann_comm::ar_recv_apply_transform_time
Referenced by recursive_doubling_allreduce_pow2, pe_ring_allreduce, ring_allreduce, rabenseifner_allreduce.
double lbann::lbann_comm::ar_send_time
Referenced by recursive_doubling_allreduce_pow2, pe_ring_allreduce, ring_allreduce, rabenseifner_allreduce.
double lbann::lbann_comm::ar_recv_time
Referenced by recursive_doubling_allreduce_pow2, pe_ring_allreduce, ring_allreduce, rabenseifner_allreduce.
double lbann::lbann_comm::ar_rs_send_time
Referenced by pe_ring_allreduce, ring_allreduce, rabenseifner_allreduce.
double lbann::lbann_comm::ar_rs_recv_time
Referenced by pe_ring_allreduce, ring_allreduce, rabenseifner_allreduce.
double lbann::lbann_comm::ar_ag_send_time
Referenced by pe_ring_allreduce, ring_allreduce, rabenseifner_allreduce.
double lbann::lbann_comm::ar_ag_recv_time
Referenced by pe_ring_allreduce, ring_allreduce, rabenseifner_allreduce.
lbann::lbann_comm::lbann_comm(int procs_per_model=0, const El::mpi::Comm world=El::mpi::COMM_WORLD)
Init communicators for models each with procs_per_model processes, defaulting to every process in one model.
References split_models, procs_per_model, setup_node_comm, procs_per_node, node_comm, rank_in_node, setup_threads.
lbann::lbann_comm::lbann_comm(const lbann_comm &)=delete
Don't allow copying; it doesn't make sense for the communicator.
lbann_comm& lbann::lbann_comm::operator=(const lbann_comm &)=delete
Don't allow assignment; it doesn't make sense for the communicator.
lbann::lbann_comm::~lbann_comm()
References grid, model_comm, intermodel_comm, node_comm, collective_bufs.
void lbann::lbann_comm::split_models(int procs_per_model)
Split communicators so each model has procs_per_model processes. If you call this multiple times, it will invalidate existing grids and communicators.
References get_world_comm, procs_per_model, num_models, model_rank, rank_in_model, model_comm, intermodel_comm, grid.
Referenced by lbann_comm.
int lbann::lbann_comm::get_model_rank() const
Get which model this process is in.
Referenced by lbann::generic_input_layer::fp_compute, lbann::lbann_callback_check_init::on_train_begin, lbann::lbann_callback_checknan::dump_network, lbann::lbann_callback_debug::on_forward_prop_begin, lbann::lbann_callback_debug::on_forward_prop_end, lbann::lbann_callback_debug::on_backward_prop_begin, lbann::lbann_callback_debug::on_backward_prop_end, lbann::lbann_callback_debug::on_batch_evaluate_begin, lbann::lbann_callback_debug::on_batch_evaluate_end, lbann::lbann_callback_debug::on_evaluate_forward_prop_begin, lbann::lbann_callback_debug::on_evaluate_forward_prop_end, lbann::lbann_callback_debug_io::print_fp_start, lbann::lbann_callback_debug_io::print_phase_start, lbann::lbann_callback_dump_activations::on_forward_prop_end, lbann::lbann_callback_dump_activations::on_test_end, lbann::lbann_callback_dump_gradients::on_backward_prop_end, lbann::lbann_callback_dump_minibatch_sample_indices::dump_to_file, lbann::lbann_callback_dump_weights::dump_weights, lbann::lbann_callback_early_stopping::on_validation_end, lbann::lbann_callback_io::on_epoch_end, lbann::lbann_callback_io::on_test_end, lbann::lbann_callback_learning_rate::on_epoch_end, lbann::lbann_callback_ltfb::on_batch_begin, lbann::lbann_callback_timeline::on_train_end, lbann::lbann_callback_variable_minibatch::on_epoch_end, lbann::distributed_io_buffer::calculate_num_iterations_per_epoch_spanning_models, lbann::partitioned_io_buffer::calculate_num_iterations_per_epoch_spanning_models.
int lbann::lbann_comm::get_rank_in_model() const
Get the rank of this process in its model.
Referenced by lbann::lbann_callback_check_dataset::on_epoch_end, lbann::lbann_callback_check_dataset::on_validation_end, lbann::lbann_callback_check_dataset::on_test_end, lbann::lbann_callback_check_init::on_train_begin, lbann::lbann_callback_checknan::dump_network, lbann::lbann_callback_debug::on_forward_prop_begin, lbann::lbann_callback_debug::on_forward_prop_end, lbann::lbann_callback_debug::on_backward_prop_begin, lbann::lbann_callback_debug::on_backward_prop_end, lbann::lbann_callback_debug::on_batch_evaluate_begin, lbann::lbann_callback_debug::on_batch_evaluate_end, lbann::lbann_callback_debug::on_evaluate_forward_prop_begin, lbann::lbann_callback_debug::on_evaluate_forward_prop_end, lbann::lbann_callback_debug_io::on_forward_prop_begin, lbann::lbann_callback_debug_io::print_fp_start, lbann::lbann_callback_debug_io::print_phase_start, lbann::lbann_callback_debug_io::on_evaluate_forward_prop_begin, lbann::lbann_callback_dump_minibatch_sample_indices::dump_to_file, lbann::lbann_callback_io::on_epoch_end, lbann::lbann_callback_io::on_test_end, lbann::lbann_callback_timeline::on_train_end, lbann::pilot2_molecular_reader::load, lbann::generic_data_store::generic_data_store, lbann::distributed_io_buffer::fetch_to_local_matrix, lbann::distributed_io_buffer::distribute_from_local_matrix, lbann::distributed_io_buffer::is_data_set_processed, lbann::distributed_io_buffer::calculate_num_iterations_per_epoch, lbann::partitioned_io_buffer::fetch_to_local_matrix, lbann::partitioned_io_buffer::calculate_num_iterations_per_epoch_spanning_models, lbann::partitioned_io_buffer::calculate_num_iterations_per_epoch_single_model, lbann::init_random.
int lbann::lbann_comm::get_rank_in_world() const
Get my rank in COMM_WORLD.
Referenced by lbann::lbann_callback_hang::on_train_begin, lbann::lbann_callback_checknan::on_forward_prop_end, lbann::lbann_callback_checknan::on_backward_prop_end, lbann::lbann_callback_checknan::on_batch_end, lbann::lbann_callback_checksmall::on_forward_prop_end, lbann::lbann_callback_checksmall::on_backward_prop_end, lbann::lbann_callback_checksmall::on_batch_end.
int lbann::lbann_comm::get_world_rank(int model, int rank) const
Return the COMM_WORLD rank of the rank'th processor in model.
int lbann::lbann_comm::get_model_master() const
Return the rank of the master process in this model.
Referenced by lbann::lbann_callback_check_dataset::on_epoch_end.
int lbann::lbann_comm::get_intermodel_master() const
Return the rank of the inter-model master process.
Referenced by lbann::lbann_callback_print::report_results, lbann::lbann_callback_timer::timing_end.
int lbann::lbann_comm::get_world_master() const
Return the rank of the world master process.
Referenced by lbann::lbann_callback_print::report_results.
bool lbann::lbann_comm::am_model_master() const
Return true if this process is the master process in its model.
Referenced by lbann::lbann_callback_check_dataset::on_epoch_end, lbann::lbann_callback_check_reconstruction_error::on_epoch_end, lbann::lbann_callback_early_stopping::on_validation_end, lbann::lbann_callback_learning_rate::on_epoch_end, lbann::lbann_callback_ltfb::on_batch_begin, lbann::lbann_callback_print::report_results, lbann::lbann_callback_timer::timing_end, lbann::lbann_callback_variable_minibatch::on_epoch_end, lbann::distributed_io_buffer::compute_max_num_parallel_readers, lbann::partitioned_io_buffer::compute_max_num_parallel_readers.
bool lbann::lbann_comm::am_world_master() const
Return true if this process is the world master process.
Referenced by lbann::generic_data_reader::set_comm, lbann::lbann_callback_check_init::on_train_begin, lbann::lbann_callback_checkpoint::need_checkpoint, lbann::lbann_callback_checkpoint::checkpointShared, lbann::lbann_callback_checkpoint::restartShared, lbann::lbann_callback_gradient_check::on_test_begin, lbann::anonymous_namespace{callback_ltfb.cpp}::assign_partners, lbann::lbann_callback_ltfb::on_batch_begin, lbann::lbann_callback_print::setup, lbann::lbann_callback_print::on_epoch_begin, lbann::lbann_callback_print::report_results, lbann::lbann_callback_save_images::save_image, lbann::lbann_callback_save_model::on_epoch_end, lbann::lbann_callback_timer::timing_end, lbann::lbann_callback_variable_minibatch::on_train_begin, lbann::distributed_io_buffer::compute_max_num_parallel_readers, lbann::model::setup_layers, lbann::model::write_proto, lbann::recurrent_model::setup_layers, lbann::sequential_model::write_proto, lbann::siamese_model::setup_layers, lbann::proto::construct_callback, lbann::proto::construct_summarizer, lbann::proto::construct_layer_graph, has_motifs, expand_motifs, init_data_readers, set_num_parallel_readers, get_cmdline_overrides, print_parameters, print_help, save_session, lbann::weights::write_proto.
Grid& lbann::lbann_comm::get_model_grid()
Return a grid to use for this model.
Referenced by lbann::distributed_io_buffer::compute_max_num_parallel_readers, lbann::Layer::setup, lbann::weights_initializer::construct_matrix.
int lbann::lbann_comm::get_num_models() const
Return the total number of models.
Referenced by lbann::lbann_callback_check_init::on_train_begin, lbann::lbann_callback_debug_io::print_phase_start, lbann::lbann_callback_imcomm::on_train_begin, lbann::lbann_callback_imcomm::on_epoch_end, lbann::lbann_callback_imcomm::on_backward_prop_end, lbann::anonymous_namespace{callback_ltfb.cpp}::assign_partners, lbann::lbann_callback_print::report_results, lbann::lbann_callback_timer::timing_end, intermodel_allreduce, lbann::distributed_io_buffer::compute_max_num_parallel_readers, lbann::distributed_io_buffer::calculate_num_iterations_per_epoch_spanning_models, lbann::partitioned_io_buffer::calculate_num_iterations_per_epoch_spanning_models.
int lbann::lbann_comm::get_procs_per_model() const
Referenced by lbann::lbann_callback_check_dataset::on_epoch_end, lbann::anonymous_namespace{callback_ltfb.cpp}::assign_partners, lbann::data_reader_merge_samples::load_using_data_store, lbann::generic_data_store::generic_data_store, lbann::partitioned_io_buffer::compute_max_num_parallel_readers, lbann::partitioned_io_buffer::calculate_num_iterations_per_epoch_spanning_models, lbann::partitioned_io_buffer::calculate_num_iterations_per_epoch_single_model, lbann::Layer::setup_gpu, lbann::Layer::get_bp_output, set_num_parallel_readers.
int lbann::lbann_comm::get_procs_per_node() const
Return the number of processes in a compute node.
int lbann::lbann_comm::get_procs_in_world() const
Return the total number of ranks.
Referenced by save_session.
int lbann::lbann_comm::get_rank_in_node() const
Return the rank of this process within its compute node.
bool lbann::lbann_comm::is_world_rank_on_node(int rank) const
Return true if rank (in COMM_WORLD) is on this compute node.
int lbann::lbann_comm::get_default_threads_per_proc() const
Get default number of threads per process. This is the number of OpenMP threads to use for parallel regions, provided omp_set_num_threads has not been called or the num_threads directive has not been provided.
void lbann::lbann_comm::reset_threads()
Reset the number of threads per process to the default.
References threads_per_proc.
Referenced by setup_threads.
void lbann::lbann_comm::intermodel_sum_matrix(Mat &mat)
Perform a sum reduction of mat over the inter-model communicator.
References bytes_sent, intermodel_comm, bytes_received.
Referenced by lbann::lbann_callback_imcomm::on_epoch_end, lbann::lbann_callback_imcomm::on_backward_prop_end.
void lbann::lbann_comm::intermodel_sum_matrix(AbsDistMat &mat)
References allreduce, intermodel_comm.
void lbann::lbann_comm::intermodel_broadcast_matrix(Mat &mat, int root)
Broadcast mat over the inter-model communicator starting from root.
References intermodel_comm.
Referenced by lbann::lbann_callback_imcomm::on_train_begin.
void lbann::lbann_comm::intermodel_broadcast_matrix(AbsDistMat &mat, int root)
References intermodel_comm.
T lbann::lbann_comm::intermodel_broadcast(int root, T val={})
Inter-model broadcast, returns the broadcast value. Root process specifies root and val, other processes just root.
T lbann::lbann_comm::model_broadcast(int root, T val={})
Within-model broadcast, returns the broadcast value. Root process specifies root and val, other processes just root.
Referenced by lbann::generic_input_layer::fp_compute.
T lbann::lbann_comm::broadcast(int root, const El::mpi::Comm c)
Broadcast over an arbitrary communicator, returns the broadcast value (for non-root processes).
T lbann::lbann_comm::broadcast(int root, T val, const El::mpi::Comm c)
Broadcast over an arbitrary communicator, returns the broadcast value (for root processes).
void lbann::lbann_comm::model_gather(T snd, int root)
Within-model scalar gather (for non-root processes).
Referenced by lbann::lbann_callback_check_dataset::on_epoch_end.
void lbann::lbann_comm::model_gather(T snd, T *rcv)
Within-model scalar gather (for root processes).
void lbann::lbann_comm::model_gather(T *snd, int count, int root)
Within-model scalar-array gather (for non-root processes).
void lbann::lbann_comm::model_gather(T *snd, int count, T *rcv)
Within-model scalar-array gather (for root processes).
void lbann::lbann_comm::model_gatherv(T *snd, int count, int root)
Within-model variable-length-array gather (for non-root processes).
void lbann::lbann_comm::model_gatherv(T *snd, int count, T *rcv, int *rcv_counts, int *rcv_displacements)
void lbann::lbann_comm::intermodel_gather(T snd, int root)
Inter-model gather (for non-root processes).
Referenced by lbann::lbann_callback_print::report_results, lbann::lbann_callback_timer::timing_end.
void lbann::lbann_comm::intermodel_gather(T snd, std::vector< T > &rcv)
Inter-model gather (for root processes).
void lbann::lbann_comm::intermodel_gather(T *snd, int count, int root)
Inter-model scalar-array gather (for non-root processes).
void lbann::lbann_comm::intermodel_gather(T *snd, int count, T *rcv)
Inter-model scalar-array gather (for root processes).
void lbann::lbann_comm::gather(T snd, int root, const El::mpi::Comm c)
Scalar gather (for non-root processes).
Referenced by lbann::top_k_categorical_accuracy_metric::evaluate_compute.
void lbann::lbann_comm::gather(T snd, T *rcv, const El::mpi::Comm c)
Scalar gather (for root processes).
void lbann::lbann_comm::gather(T snd, std::vector< T > &rcv, const El::mpi::Comm c)
Scalar gather (for root processes).
void lbann::lbann_comm::gather(T *snd, int count, int root, const El::mpi::Comm c)
Scalar-array gather (for non-root processes).
void lbann::lbann_comm::gather(T *snd, int count, T *rcv, const El::mpi::Comm c)
Scalar-array gather (for root processes).
T lbann::lbann_comm::scatter(int root, const El::mpi::Comm c)
Scalar scatter (for non-root processes).
Referenced by lbann::anonymous_namespace{callback_ltfb.cpp}::assign_partners.
T lbann::lbann_comm::scatter(T *snd, const El::mpi::Comm c)
Scalar scatter (for root processes).
void lbann::lbann_comm::intermodel_reduce(T snd, int root, El::mpi::Op op=El::mpi::SUM)
Inter-model reduce (for non-root processes).
T lbann::lbann_comm::intermodel_reduce(T snd, El::mpi::Op op=El::mpi::SUM)
Inter-model reduce (for root processes).
void lbann::lbann_comm::model_reduce(T snd, int root, El::mpi::Op op=El::mpi::SUM)
Within-model reduce (for non-root processes).
T lbann::lbann_comm::model_reduce(T snd, El::mpi::Op op=El::mpi::SUM)
Within-model reduce (for root processes).
void lbann::lbann_comm::model_reduce(T *snd, int count, int root, El::mpi::Op op=El::mpi::SUM)
Within-model scalar array reduce (for non-root processes).
void lbann::lbann_comm::model_reduce(T *snd, int count, T *rcv, El::mpi::Op op=El::mpi::SUM)
Within-model scalar array reduce (for root processes).
void lbann::lbann_comm::reduce(T snd, int root, const El::mpi::Comm c, El::mpi::Op op=El::mpi::SUM)
Scalar reduce (for non-root processes).
T lbann::lbann_comm::reduce(T snd, const El::mpi::Comm c, El::mpi::Op op=El::mpi::SUM)
Scalar reduce (for root processes).
void lbann::lbann_comm::reduce(T *snd, int count, int root, const El::mpi::Comm c, El::mpi::Op op=El::mpi::SUM)
Scalar-array reduce (for non-root processes).
void lbann::lbann_comm::reduce(T *snd, int count, T *rcv, const El::mpi::Comm c, El::mpi::Op op=El::mpi::SUM)
Scalar-array reduce (for root processes).
T lbann::lbann_comm::intermodel_allreduce(T snd, El::mpi::Op op=El::mpi::SUM)
Inter-model all-reduce.
Referenced by lbann::lbann_quantizer::intermodel_sum_adaptive_quantized_impl, lbann::lbann_quantizer::intermodel_sum_onebit_quantized.
T lbann::lbann_comm::model_allreduce(T snd, El::mpi::Op op=El::mpi::SUM)
Within-model all-reduce.
Referenced by lbann::categorical_accuracy_metric::evaluate_compute, lbann::top_k_categorical_accuracy_metric::evaluate_compute.
void lbann::lbann_comm::model_allreduce(T *snd, int count, T *rcv, El::mpi::Op op=El::mpi::SUM)
Scalar array within-model all-reduce.
T lbann::lbann_comm::allreduce(T snd, const El::mpi::Comm c, El::mpi::Op op=El::mpi::SUM)
Scalar allreduce.
Referenced by lbann::batch_normalization< T_layout >::fp_compute_cpu, lbann::batch_normalization< T_layout >::bp_compute_cpu, intermodel_sum_matrix, nb_allreduce, lbann::boolean_accuracy_metric::evaluate_compute, lbann::boolean_false_negatives_metric::evaluate_compute, lbann::boolean_false_positives_metric::evaluate_compute, lbann::categorical_accuracy_metric::evaluate_compute, lbann::mean_absolute_deviation_metric::evaluate_compute, lbann::mean_absolute_deviation_loss::finish_evaluate_compute, lbann::mean_squared_error_metric::evaluate_compute, lbann::pearson_correlation_metric::evaluate_compute, lbann::kl_divergence::finish_evaluation, lbann::cross_entropy_with_uncertainty::finish_evaluate_compute, lbann::geom_negloglike::finish_evaluate_compute, lbann::mean_absolute_error_loss::finish_evaluate_compute, lbann::poisson_negloglike::finish_evaluate_compute, lbann::polya_negloglike::finish_evaluate_compute, lbann::group_lasso_weight_regularization::finish_evaluation, lbann::group_lasso_weight_regularization::compute_weight_regularization, lbann::l1_weight_regularization::finish_evaluation.
void lbann::lbann_comm::allreduce(T *snd, int count, T *rcv, const El::mpi::Comm c, El::mpi::Op op=El::mpi::SUM)
Scalar-array allreduce.
void lbann::lbann_comm::allreduce(T *data, int count, const El::mpi::Comm c, El::mpi::Op op=El::mpi::SUM)
In-place scalar-array allreduce.
References lbann::cnpy_utils::data.
void lbann::lbann_comm::allreduce(AbsDistMat &m, const El::mpi::Comm c, El::mpi::Op op=El::mpi::SUM, std::type_index t=std::type_index(typeid(Al::mpi_backend)))
Matrix allreduce.
References bytes_sent, comm, bytes_received.
void lbann::lbann_comm::nb_allreduce(AbsDistMat &m, const El::mpi::Comm c, Al::request &req, El::mpi::Op op=El::mpi::SUM, std::type_index t=std::type_index(typeid(Al::mpi_backend)))
Non-blocking matrix allreduce. If LBANN has not been built with Aluminum, then this calls a blocking matrix allreduce.
References bytes_sent, comm, lbann::Al::request::mpi_req, bytes_received, allreduce.
Referenced by lbann::evaluation_layer< T_layout >::fp_compute, lbann::mean_squared_error_loss::start_evaluate_compute, lbann::cross_entropy::start_evaluate_compute, lbann::l2_weight_regularization::start_evaluation, lbann::optimizer::start_gradient_staging_allreduce.
void lbann::lbann_comm::nb_allreduce(T *data, int count, const El::mpi::Comm c, Al::request &req, El::mpi::Op op=El::mpi::SUM)
Non-blocking in-place scalar-array allreduce. If LBANN has not been built with Aluminum, then this calls a blocking allreduce. This currently only supports host pointers (i.e. the MPI backend).
References lbann::Al::request::mpi_req, lbann::Al::dummy_backend::null_req, lbann::cnpy_utils::data.
void lbann::lbann_comm::wait(El::mpi::Request< T > &req)
Wait for a non-blocking request to complete.
Referenced by lbann::evaluation_layer< T_layout >::get_value, lbann::mean_squared_error_loss::finish_evaluate_compute, lbann::cross_entropy::finish_evaluate_compute, lbann::l2_weight_regularization::finish_evaluation, lbann::optimizer::get_gradient.
void lbann::lbann_comm::wait(Al::request &req)
Wait for a non-blocking request to complete.
References lbann::Al::request::mpi_req, lbann::Al::dummy_backend::null_req.
bool lbann::lbann_comm::test(Al::request &req)
Test whether a non-blocking request has completed; true if it has.
References lbann::Al::request::mpi_req, lbann::Al::dummy_backend::null_req.
void lbann::lbann_comm::intermodel_barrier()
Barrier among the inter-model processes.
References num_intermodel_barriers, barrier, intermodel_comm.
void lbann::lbann_comm::model_barrier()
Barrier among processes in this model.
References num_model_barriers, barrier, model_comm.
Referenced by lbann::lbann_callback_timeline::on_train_begin, lbann::distributed_io_buffer::distribute_from_local_matrix.
void lbann::lbann_comm::global_barrier()
Barrier among all processes.
References num_global_barriers, barrier, get_world_comm.
Referenced by lbann::lbann_callback_check_init::on_train_begin.
void lbann::lbann_comm::barrier(const El::mpi::Comm c)
Barrier on an arbitrary communicator.
Referenced by intermodel_barrier, model_barrier, global_barrier.
void lbann::lbann_comm::send(const T *data, int count, int model, int rank)
Send a buffer to rank in model.
Referenced by lbann::lbann_callback_check_init::on_train_begin, send.
void lbann::lbann_comm::send(const T *data, int count, int model)
void lbann::lbann_comm::send(const Mat &mat, int model, int rank)
References send, lbann::model.
void lbann::lbann_comm::send(const DistMat &mat, int model, int rank)
References send, lbann::model.
void lbann::lbann_comm::send(const Mat &mat, int model)
void lbann::lbann_comm::send(const DistMat &mat, int model)
void lbann::lbann_comm::nb_send(const T *data, int count, int model, int rank, El::mpi::Request< T > &req)
Corresponding non-blocking sends.
Referenced by nb_send.
void lbann::lbann_comm::nb_send(const T *data, int count, int model, El::mpi::Request< T > &req)
void lbann::lbann_comm::nb_send(const Mat &mat, int model, int rank, El::mpi::Request< DataType > &req)
References nb_send, lbann::model.
void lbann::lbann_comm::nb_send(const DistMat &mat, int model, int rank, El::mpi::Request< DataType > &req)
References nb_send, lbann::model.
void lbann::lbann_comm::nb_send(const Mat &mat, int model, El::mpi::Request< DataType > &req)
void lbann::lbann_comm::nb_send(const DistMat &mat, int model, El::mpi::Request< DataType > &req)
void lbann::lbann_comm::recv(T *data, int count, int model, int rank)
Corresponding receive to send.
Referenced by lbann::lbann_callback_check_init::on_train_begin, recv.
void lbann::lbann_comm::recv(T *data, int count, int model)
void lbann::lbann_comm::recv(Mat &mat, int model, int rank)
References recv, lbann::model.
void lbann::lbann_comm::recv(DistMat &mat, int model, int rank)
References recv, lbann::model.
void lbann::lbann_comm::recv(Mat &mat, int model)
void lbann::lbann_comm::recv(DistMat &mat, int model)
void lbann::lbann_comm::recv(T *data, int count)
As above, but receive from anyone.
void lbann::lbann_comm::recv(Mat &mat)
References recv.
void lbann::lbann_comm::recv(DistMat &mat)
References recv.
void lbann::lbann_comm::nb_recv(T *data, int count, int model, int rank, El::mpi::Request< T > &req)
Corresponding non-blocking receives.
Referenced by nb_recv.
void lbann::lbann_comm::nb_recv(T *data, int count, int model, El::mpi::Request< T > &req)
void lbann::lbann_comm::nb_recv(Mat &mat, int model, int rank, El::mpi::Request< DataType > &req)
References nb_recv, lbann::model.
void lbann::lbann_comm::nb_recv(DistMat &mat, int model, int rank, El::mpi::Request< DataType > &req)
References nb_recv, lbann::model.
void lbann::lbann_comm::nb_recv(Mat &mat, int model, El::mpi::Request< DataType > &req)
void lbann::lbann_comm::nb_recv(DistMat &mat, int model, El::mpi::Request< DataType > &req)
void lbann::lbann_comm::nb_recv(T *data, int count, El::mpi::Request< T > &req)
void lbann::lbann_comm::nb_recv(Mat &mat, El::mpi::Request< DataType > &req)
References nb_recv.
void lbann::lbann_comm::nb_recv(DistMat &mat, El::mpi::Request< DataType > &req)
References nb_recv.
void lbann::lbann_comm::sendrecv(const T *snd, int send_count, int send_model, int send_rank, T *rcv, int recv_count, int recv_model, int recv_rank)
Send/recv to/from ranks.
Referenced by lbann::anonymous_namespace{callback_ltfb.cpp}::exchange_weights.
void lbann::lbann_comm::sendrecv(const T *snd, int send_count, int send_model, T *rcv, int recv_count, int recv_model)
int lbann::lbann_comm::get_count(int model, int rank)
Determine the size (count) of an incoming message.
int lbann::lbann_comm::get_count(int model)
size_t lbann::lbann_comm::get_num_model_barriers() const
Return the number of model barriers performed.
Referenced by lbann::lbann_callback_summary::on_batch_end.
size_t lbann::lbann_comm::get_num_intermodel_barriers() const
Return the number of inter-model barriers performed.
Referenced by lbann::lbann_callback_summary::on_batch_end.
size_t lbann::lbann_comm::get_num_global_barriers() const
Return the number of global barriers performed.
Referenced by lbann::lbann_callback_summary::on_batch_end.
size_t lbann::lbann_comm::get_bytes_sent() const
Return the number of bytes sent.
Referenced by lbann::lbann_callback_summary::on_batch_end.
size_t lbann::lbann_comm::get_bytes_received() const
Return the number of bytes received.
Referenced by lbann::lbann_callback_summary::on_batch_end.
size_t lbann::lbann_comm::get_ar_bytes_sent() const
Return the number of bytes sent in allreduces.
Referenced by lbann::lbann_callback_imcomm::do_summary.
size_t lbann::lbann_comm::get_ar_bytes_received() const
Return the number of bytes received in allreduces.
Referenced by lbann::lbann_callback_imcomm::do_summary.
size_t lbann::lbann_comm::get_ar_rs_bytes_sent() const
Return the number of bytes sent in allreduce reduce-scatters.
Referenced by lbann::lbann_callback_imcomm::do_summary.
size_t lbann::lbann_comm::get_ar_rs_bytes_received() const
Return the number of bytes received in allreduce reduce-scatters.
Referenced by lbann::lbann_callback_imcomm::do_summary.
size_t lbann::lbann_comm::get_ar_ag_bytes_sent() const
Return the number of bytes sent in allreduce allgathers.
Referenced by lbann::lbann_callback_imcomm::do_summary.
size_t lbann::lbann_comm::get_ar_ag_bytes_received() const
Return the number of bytes received in allreduce allgathers.
Referenced by lbann::lbann_callback_imcomm::do_summary.
double lbann::lbann_comm::get_ar_time() const
Return the time spent in allreduces.
double lbann::lbann_comm::get_ar_rs_time() const
Return the time spent in allreduce reduce-scatters.
double lbann::lbann_comm::get_ar_ag_time() const
Return the time spent in allreduce allgathers.
double lbann::lbann_comm::get_ar_send_transform_time() const
Return the time spent in allreduce send transforms.
Referenced by lbann::lbann_callback_imcomm::do_summary.
double lbann::lbann_comm::get_ar_recv_transform_time() const
Return the time spent in allreduce receive transforms.
Referenced by lbann::lbann_callback_imcomm::do_summary.
double lbann::lbann_comm::get_ar_recv_apply_transform_time() const
Return the time spent in allreduce receive/apply transforms.
Referenced by lbann::lbann_callback_imcomm::do_summary.
double lbann::lbann_comm::get_ar_send_time() const
Return the time spent sending in allreduces.
double lbann::lbann_comm::get_ar_recv_time() const
Return the time spent receiving in allreduces.
double lbann::lbann_comm::get_ar_rs_send_time() const
Return the time spent sending in allreduce reduce-scatters.
double lbann::lbann_comm::get_ar_rs_recv_time() const
Return the time spent receiving in allreduce reduce-scatters.
double lbann::lbann_comm::get_ar_ag_send_time() const
Return the time spent sending in allreduce allgathers.
double lbann::lbann_comm::get_ar_ag_recv_time() const
Return the time spent receiving in allreduce allgathers.
void lbann::lbann_comm::reset_stats_counters()
Referenced by lbann::lbann_callback_imcomm::do_summary, lbann::lbann_callback_summary::on_batch_end, lbann::lbann_callback_summary::on_test_end.
allreduce_algorithm lbann::lbann_comm::get_default_allreduce_algorithm() const
Get the default allreduce algorithm to use (may be DYNAMIC).
Referenced by intermodel_allreduce.
void lbann::lbann_comm::set_default_allreduce_algorithm(allreduce_algorithm algo)
Set the default allreduce algorithm to algo. Do not set it to DEFAULT.
References comm.
void lbann::lbann_comm::intermodel_allreduce(Mat &mat, int max_recv_count, std::function< uint8_t *(Mat &, El::IR, El::IR, int &, bool, int)> send_transform, std::function< int(uint8_t *, Mat &)> recv_transform, std::function< int(uint8_t *, Mat &, bool)> recv_apply_transform, const allreduce_options opts)
Do a custom allreduce on mat on the intermodel communicator. This selects the allreduce algorithm to use based on the size of mat. All counts/sizes are in bytes. mat The matrix to allreduce. max_recv_count An upper bound on the size of data that will be received in any step; this will be the size of receive buffers used in the allreduce. send_transform A function that takes a range of a matrix and applies a transformation to it. The return value is a pointer to a buffer containing the transformed data, which will be sent. The int& param should be set to the count of how many elements are in the buffer. The boolean parameter indicates whether the matrix is constant between different calls to send_transform; if true, the function may be able to take advantage of this. The int parameter gives a count of how many times send_transform has been called concurrently, starting from 0. recv_transform A function that takes a pointer to a buffer and a matrix and applies a transform to the buffer, storing the result in the matrix. The buffer will be data transformed with send_transform and received from another rank. The return value is the actual count of the received data (i.e. the count that the data was sent using). recv_apply_transform A function like recv_transform except that the transformed data should be combined (applied, reduced) with the current data in the matrix argument. A boolean parameter indicates that no_local_trans was true and the data was not transformed. options Various allreduce options.
References lbann::lbann_comm::allreduce_options::algo, DEFAULT, get_default_allreduce_algorithm, get_num_models, DYNAMIC, RECURSIVE_DOUBLING, PAIRWISE_EXCHANGE_RING, recursive_doubling_allreduce_pow2, intermodel_comm, pe_ring_allreduce, RING, ring_allreduce, RABENSEIFNER, rabenseifner_allreduce.
void lbann::lbann_comm::recursive_doubling_allreduce_pow2(const El::mpi::Comm comm, Mat &mat, int max_recv_count, std::function< uint8_t *(Mat &, El::IR, El::IR, int &, bool, int)> send_transform, std::function< int(uint8_t *, Mat &, bool)> recv_apply_transform, const allreduce_options opts)
A recursive-doubling allreduce. This implementation only works for a power-of-2 number of processes.
References lbann::get_time, get_collective_buffer, lbann::lbann_comm::allreduce_options::no_local_trans, is_rank_node_local, ar_send_transform_time, bytes_sent, ar_bytes_sent, ar_send_time, ar_recv_time, ar_recv_apply_transform_time, bytes_received, ar_bytes_received, ar_time.
Referenced by intermodel_allreduce.
void lbann::lbann_comm::pe_ring_allreduce(const El::mpi::Comm comm, Mat &mat, int max_recv_count, std::function< uint8_t *(Mat &, El::IR, El::IR, int &, bool, int)> send_transform, std::function< int(uint8_t *, Mat &)> recv_transform, std::function< int(uint8_t *, Mat &, bool)> recv_apply_transform, const allreduce_options opts)
An allreduce based on a pairwise-exchange reduce-scatter followed by a ring-based allgather. num_reduces If >1, performs up to num_reduces reduces concurrently in the reduce-scatter phase.
References lbann::get_time, lbann::lbann_comm::allreduce_options::max_reduces, get_collective_buffer, lbann::lbann_comm::allreduce_options::no_local_trans, is_rank_node_local, ar_recv_time, ar_rs_recv_time, ar_send_transform_time, bytes_sent, ar_bytes_sent, ar_rs_bytes_sent, ar_send_time, ar_rs_send_time, ar_recv_apply_transform_time, bytes_received, ar_bytes_received, ar_rs_bytes_received, ar_rs_time, ar_ag_bytes_sent, lbann::lbann_comm::allreduce_options::id_recv, ar_ag_send_time, ar_ag_recv_time, ar_recv_transform_time, ar_ag_bytes_received, ar_ag_time, ar_time.
Referenced by intermodel_allreduce.
void lbann::lbann_comm::ring_allreduce(const El::mpi::Comm comm, Mat &mat, int max_recv_count, std::function< uint8_t *(Mat &, El::IR, El::IR, int &, bool, int)> send_transform, std::function< int(uint8_t *, Mat &)> recv_transform, std::function< int(uint8_t *, Mat &, bool)> recv_apply_transform, const allreduce_options opts)
An allreduce using ring-based reduce-scatter and allgather.
References lbann::get_time, get_collective_buffer, lbann::lbann_comm::allreduce_options::no_local_trans, is_rank_node_local, ar_send_transform_time, bytes_sent, ar_bytes_sent, ar_rs_bytes_sent, ar_send_time, ar_recv_time, ar_rs_send_time, ar_rs_recv_time, ar_recv_apply_transform_time, bytes_received, ar_bytes_received, ar_rs_bytes_received, ar_rs_time, ar_ag_bytes_sent, lbann::lbann_comm::allreduce_options::id_recv, ar_ag_send_time, ar_ag_recv_time, ar_recv_transform_time, ar_ag_bytes_received, ar_ag_time, ar_time.
Referenced by intermodel_allreduce.
void lbann::lbann_comm::rabenseifner_allreduce(const El::mpi::Comm comm, Mat &mat, int max_recv_count, std::function< uint8_t *(Mat &, El::IR, El::IR, int &, bool, int)> send_transform, std::function< int(uint8_t *, Mat &)> recv_transform, std::function< int(uint8_t *, Mat &, bool)> recv_apply_transform, const allreduce_options opts)
An allreduce using a recursive-halving reduce-scatter followed by a recursive-doubling allgather.
References lbann::get_time, get_collective_buffer, lbann::lbann_comm::allreduce_options::no_local_trans, is_rank_node_local, ar_send_transform_time, bytes_sent, ar_bytes_sent, ar_rs_bytes_sent, ar_send_time, ar_recv_time, ar_rs_send_time, ar_rs_recv_time, ar_recv_apply_transform_time, bytes_received, ar_bytes_received, ar_rs_bytes_received, ar_rs_time, lbann::lbann_comm::allreduce_options::id_recv, ar_ag_bytes_sent, ar_ag_send_time, ar_ag_recv_time, ar_recv_transform_time, ar_ag_bytes_received, ar_ag_time, ar_time.
Referenced by intermodel_allreduce.
El::mpi::Comm lbann::lbann_comm::get_intermodel_comm() const
Return the intermodel communicator.
El::mpi::Comm lbann::lbann_comm::get_model_comm() const
Return the model communicator.
Referenced by lbann::pilot2_molecular_reader::load.
const El::mpi::Comm lbann::lbann_comm::get_world_comm() const
Return the world communicator.
Referenced by lbann::anonymous_namespace{callback_ltfb.cpp}::assign_partners, split_models, global_barrier, setup_node_comm.
bool lbann::lbann_comm::is_rank_node_local(int rank, const El::mpi::Comm comm) const
Return true if rank (in comm) is on the local node.
Referenced by recursive_doubling_allreduce_pow2, pe_ring_allreduce, ring_allreduce, rabenseifner_allreduce.
static bool lbann::lbann_comm::is_sendable(const Mat &mat)
Return true if mat can be transmitted.
static bool lbann::lbann_comm::is_sendable(const AbsDistMat &dist_mat)
Return true if the local portion of dist_mat can be transmitted.
void lbann::lbann_comm::setup_node_comm()
Setup communicator for processes in the same compute node.
References checkMPI, get_world_comm, node_comm, world_ranks_on_node.
Referenced by lbann_comm.
void lbann::lbann_comm::setup_threads()
Initialize the default number of threads per process. This is the number of OpenMP threads to use for parallel regions, provided omp_set_num_threads has not been called or the num_threads directive has not been provided. If the environment variable OMP_NUM_THREADS is defined, it's value is used for the default. Otherwise, then the default is the number of hardware cores per node divided by the number of processes per node.
References threads_per_proc, procs_per_node, reset_threads.
Referenced by lbann_comm.
uint8_t * lbann::lbann_comm::get_collective_buffer(size_t size, size_t idx=0)
Return a buffer from collective_bufs, allocating it if needed. size The size of the buffer (in bytes). idx The index of the buffer (default 0).
References collective_bufs, comm.
Referenced by recursive_doubling_allreduce_pow2, pe_ring_allreduce, ring_allreduce, rabenseifner_allreduce.