lbann::generic_target_layer
generic_input_layer* lbann::generic_target_layer::m_paired_input_layer
Referenced by operator=, get_paired_input_layer.
generic_io_buffer* lbann::generic_target_layer::io_buffer
Referenced by operator=, ~generic_target_layer, initialize_io_buffer, lbann::target_layer< T_io_buffer, T_layout >::target_layer, lbann::target_layer< T_io_buffer, T_layout >::get_type.
AbsDistMat* lbann::generic_target_layer::m_ground_truth
Ground truth matrix.
Referenced by operator=, ~generic_target_layer, setup_matrices, get_ground_truth, lbann::reconstruction_layer< T_layout >::fp_compute.
lbann::generic_target_layer::generic_target_layer(lbann_comm *comm, generic_input_layer *input_layer, std::map< execution_mode, generic_data_reader *> data_readers, bool for_regression=false)
References lbann::Layer::m_expected_num_child_layers.
lbann::generic_target_layer::generic_target_layer(const generic_target_layer &other)
generic_target_layer& lbann::generic_target_layer::operator=(const generic_target_layer &other)
References lbann::Layer::operator=, m_paired_input_layer, io_buffer, m_ground_truth.
lbann::generic_target_layer::~generic_target_layer() override
References io_buffer, m_ground_truth, initialize_io_buffer, comm.
void lbann::generic_target_layer::initialize_io_buffer(lbann_comm *comm, int num_parallel_readers, std::map< execution_mode, generic_data_reader *> data_readers)
Referenced by ~generic_target_layer.
generic_input_layer* lbann::generic_target_layer::get_paired_input_layer() const
References m_paired_input_layer.
void lbann::generic_target_layer::set_paired_input_layer(generic_input_layer *input_layer)
Referenced by lbann::proto::anonymous_namespace{layer_graph_factory.cpp}::setup_target_pointers.
std::string lbann::generic_target_layer::get_description() const override
Returns description of ctor params
References get_topo_description, lbann::generic_io_buffer::get_type, lbann::Layer::get_data_layout_string, lbann::Layer::get_data_layout.
void lbann::generic_target_layer::setup_matrices(const El::Grid &grid) override
Instantiate distributed matrices. If the layer has already been setup, this function should destroy all matrices and reinstantiate them. However, it is not guaranteed that derived classes will obey this behavior.
References lbann::Layer::setup_matrices, m_ground_truth, lbann::Layer::get_prev_activations.
void lbann::generic_target_layer::setup_dims() override
Setup tensor dimensions Called by the setup function. The base method sets the dimensions of the activation tensors equal to the dimensions of the first previous activation tensor.
References lbann::Layer::setup_dims, lbann::io_layer::is_for_regression, lbann::Layer::m_num_neurons, get_linearized_response_size, lbann::Layer::m_num_neuron_dims, lbann::Layer::m_neuron_dims, get_linearized_label_size.
Referenced by lbann::reconstruction_layer< T_layout >::setup_dims.
void lbann::generic_target_layer::setup_data() override
Setup layer data. Called by the setup function. The base method sets the previous activation, activation, previous error signal, and error signal matrices to zero matrices with the proper dimensions. Matrix buffers are pinned if needed for GPU transfers.
References lbann::Layer::setup_data, lbann::Layer::m_model, lbann::model::get_max_mini_batch_size, lbann::generic_io_buffer::setup_data, lbann::Layer::m_num_neurons.
void lbann::generic_target_layer::check_setup() override
Check that the setup is reasonable.
References lbann::Layer::check_setup, lbann::Layer::m_num_prev_neurons, lbann::Layer::m_num_neurons.
void lbann::generic_target_layer::fp_setup_data(int mini_batch_size) override
Setup data for forward propagation. Base method gets previous activations from parent layers and resizes activations for the current mini-batch size.
References lbann::Layer::fp_setup_data, lbann::Layer::get_num_prev_neurons, lbann::generic_io_buffer::set_local_matrix_bypass, lbann::generic_io_buffer::set_std_matrix_view.
void lbann::generic_target_layer::fp_compute() override
Perform the computation for the forward propagation step.
References lbann::Layer::m_model, lbann::model::get_execution_mode, lbann::generic_io_buffer::fetch_to_local_matrix, lbann::generic_input_layer::get_data_reader, update_num_samples_processed, lbann::model::get_current_mini_batch_size, lbann::distributed_io_buffer::distribute_from_local_matrix.
void lbann::generic_target_layer::bp_compute() override
Perform the computation for the backward propagation step.
bool lbann::generic_target_layer::update_compute() override
Perform the computation for the update step. Returns false if the layer must reset for a new training epoch.
References lbann::generic_io_buffer::is_data_set_processed, lbann::generic_input_layer::get_data_reader, lbann::Layer::m_model, lbann::model::get_execution_mode.
dataset& lbann::generic_target_layer::get_dataset(execution_mode m) override
Return the dataset for the given execution mode.
References lbann::generic_input_layer::get_dataset.
const dataset& lbann::generic_target_layer::get_dataset(execution_mode m) const override
References lbann::generic_input_layer::get_dataset.
dataset& lbann::generic_target_layer::select_dataset() override
Return the dataset associated with the current execution mode.
References lbann::generic_input_layer::select_dataset.
const dataset& lbann::generic_target_layer::select_dataset() const override
References lbann::generic_input_layer::select_dataset.
dataset* lbann::generic_target_layer::select_first_valid_dataset() override
Return the first dataset with a valid (non-null) datareader. Returns null if none are valid.
References lbann::generic_input_layer::select_first_valid_dataset.
generic_data_reader* lbann::generic_target_layer::select_data_reader() const override
Return the data reader associated with the current execution mode.
References lbann::generic_input_layer::select_data_reader.
long lbann::generic_target_layer::update_num_samples_processed(long num_samples) override
Update the number of samples processed for the current execution mode.
References lbann::generic_input_layer::update_num_samples_processed.
Referenced by fp_compute.
El::Matrix<El::Int>* lbann::generic_target_layer::get_sample_indices_per_mb() override
Return the sample indices fetched in the current mini-batch.
References lbann::generic_input_layer::get_sample_indices_per_mb.
const std::vector<int> lbann::generic_target_layer::get_data_dims() const override
Get the dimensions of the underlying data.
References lbann::generic_input_layer::get_data_dims.
std::string lbann::generic_target_layer::get_topo_description() const override
Get a human-readable description of the activation tensors. Activation tensors are stored in distributed matrices where each column corresponds to a mini-batch sample. Within each column, the data is packed w.r.t. the last tensor dimension, then w.r.t. the penultimate dimension, and so on. 3D tensors are assumed to be 2D images in NCHW format.
References lbann::generic_input_layer::get_topo_description.
Referenced by get_description.
long lbann::generic_target_layer::get_linearized_data_size() const override
Get the linearized size of the underlying data.
References lbann::generic_input_layer::get_linearized_data_size.
Referenced by lbann::proto::construct_layer.
long lbann::generic_target_layer::get_linearized_label_size() const override
Get the linearized size of the labels for the underlying data.
References lbann::generic_input_layer::get_linearized_label_size.
Referenced by setup_dims.
long lbann::generic_target_layer::get_linearized_response_size() const override
References lbann::generic_input_layer::get_linearized_response_size.
Referenced by setup_dims.
long lbann::generic_target_layer::get_num_samples_trained() const override
References lbann::generic_input_layer::get_num_samples_trained.
long lbann::generic_target_layer::get_num_samples_tested() const override
References lbann::generic_input_layer::get_num_samples_tested.
long lbann::generic_target_layer::get_total_num_training_samples() const override
References lbann::generic_input_layer::get_total_num_training_samples.
long lbann::generic_target_layer::get_total_num_testing_samples() const override
References lbann::generic_input_layer::get_total_num_testing_samples.
bool lbann::generic_target_layer::at_new_epoch() const override
References lbann::generic_input_layer::at_new_epoch.
bool lbann::generic_target_layer::is_execution_mode_valid(execution_mode mode) const override
References lbann::generic_input_layer::is_execution_mode_valid.
virtual AbsDistMat& lbann::generic_target_layer::get_prediction()
References lbann::Layer::get_prev_activations.
Referenced by lbann::metric::evaluate.
virtual const AbsDistMat& lbann::generic_target_layer::get_prediction() const
References lbann::Layer::get_prev_activations.
virtual AbsDistMat& lbann::generic_target_layer::get_ground_truth()
References m_ground_truth.
Referenced by lbann::metric::evaluate.
virtual const AbsDistMat& lbann::generic_target_layer::get_ground_truth() const
References m_ground_truth.
std::vector<Layer*> lbann::generic_target_layer::get_layer_pointers() override
Get list of pointers to other layers.
References lbann::Layer::get_layer_pointers.
Referenced by lbann::reconstruction_layer< T_layout >::get_layer_pointers.
void lbann::generic_target_layer::set_layer_pointers(std::vector< Layer *> layers) override
Set list of pointers to other layers.
References lbann::Layer::set_layer_pointers.
Referenced by lbann::reconstruction_layer< T_layout >::set_layer_pointers.
bool lbann::generic_target_layer::saveToCheckpoint(int fd, const char *filename, size_t *bytes) const override
References lbann::Layer::saveToCheckpoint.
bool lbann::generic_target_layer::loadFromCheckpoint(int fd, const char *filename, size_t *bytes) override
References lbann::Layer::loadFromCheckpoint.
bool lbann::generic_target_layer::save_to_checkpoint_shared(persist &p, bool val_end) const override
References lbann::Layer::save_to_checkpoint_shared.
bool lbann::generic_target_layer::load_from_checkpoint_shared(persist &p) override
References lbann::Layer::load_from_checkpoint_shared.
void lbann::generic_target_layer::initialize_io_buffer(lbann_comm *comm, int num_parallel_readers, std::map< execution_mode, generic_data_reader *> data_readers)
References io_buffer.
void lbann::generic_target_layer::initialize_io_buffer(lbann_comm *comm, int num_parallel_readers, std::map< execution_mode, generic_data_reader *> data_readers)
References io_buffer.