lbann::data_reader_multi_images
using lbann::data_reader_multi_images::img_src_t = std::vector<std::string>
using lbann::data_reader_multi_images::sample_t = std::pair<img_src_t, label_t>
std::vector<sample_t> lbann::data_reader_multi_images::m_image_list
list of image files and labels
Referenced by get_image_list, get_sample, operator=, fetch_datum, fetch_label, get_image_list_of_current_mb, load.
unsigned int lbann::data_reader_multi_images::m_num_img_srcs
The number of image sources or the number of siamese heads. e.g., 2.
Referenced by get_linearized_data_size, get_data_dims, get_num_img_srcs, lbann::data_reader_mnist_siamese::set_defaults, operator=, set_defaults, set_input_params, create_datum_views, fetch_datum, read_text_stream, lbann::data_reader_triplet::set_defaults, lbann::data_reader_triplet::fetch_datum.
lbann::data_reader_multi_images::data_reader_multi_images(bool shuffle)=delete
Referenced by copy.
lbann::data_reader_multi_images::data_reader_multi_images(const std::shared_ptr< cv_process > &pp, bool shuffle=true)
References set_defaults.
lbann::data_reader_multi_images::data_reader_multi_images(const data_reader_multi_images &)
data_reader_multi_images & lbann::data_reader_multi_images::operator=(const data_reader_multi_images &)
References lbann::imagenet_reader::operator=, m_image_list, m_num_img_srcs.
Referenced by lbann::data_reader_mnist_siamese::operator=, lbann::data_reader_triplet::operator=.
lbann::data_reader_multi_images::~data_reader_multi_images() override
data_reader_multi_images* lbann::data_reader_multi_images::copy() const override
References data_reader_multi_images.
std::string lbann::data_reader_multi_images::get_type() const override
Return this data_reader's type
References set_input_params, load.
Referenced by set_input_params, fetch_datum.
void lbann::data_reader_multi_images::set_input_params(const int width, const int height, const int num_ch, const int num_labels, const int num_img_srcs)
Set up imagenet specific input parameters If argument is set to 0, then this method does not change the value of the corresponding parameter. However, width and height can only be both zero or both non-zero.
References lbann::image_data_reader::set_input_params, m_num_img_srcs, get_type.
Referenced by get_type, set_input_params, lbann::data_reader_triplet::set_input_params, init_image_data_reader.
void lbann::data_reader_multi_images::set_input_params(const int width, const int height, const int num_ch, const int num_labels) override
Set up imagenet specific input parameters If argument is set to 0, then this method does not change the value of the corresponding parameter. However, width and height can only be both zero or both non-zero.
References set_input_params.
void lbann::data_reader_multi_images::load() override
Load the dataset. Each data reader implementation should implement this to initialize its internal data structures, determine the number of samples and their dimensionality (if needed), and set up and shuffle samples.
References m_image_list, lbann::generic_data_reader::get_data_filename, load_list, lbann::generic_data_reader::m_shuffled_indices, lbann::generic_data_reader::select_subset_of_data.
Referenced by get_type.
int lbann::data_reader_multi_images::get_linearized_data_size() const override
Get the total number of channel values in a sample of image(s).
References lbann::image_data_reader::m_image_linearized_size, m_num_img_srcs.
const std::vector<int> lbann::data_reader_multi_images::get_data_dims() const override
Get the dimensions of the data.
References m_num_img_srcs, lbann::image_data_reader::m_image_num_channels, lbann::image_data_reader::m_image_height, lbann::image_data_reader::m_image_width, get_image_list_of_current_mb.
std::vector< data_reader_multi_images::sample_t > lbann::data_reader_multi_images::get_image_list_of_current_mb() const
Return the sample list of current minibatch.
References lbann::generic_data_reader::m_mini_batch_size, lbann::generic_data_reader::m_indices_fetched_per_mb, m_image_list.
Referenced by get_data_dims.
const std::vector<sample_t>& lbann::data_reader_multi_images::get_image_list() const
Allow read-only access to the entire sample list.
References m_image_list.
sample_t lbann::data_reader_multi_images::get_sample(size_t idx) const
References m_image_list.
Referenced by lbann::data_store_multi_images::get_sample.
unsigned int lbann::data_reader_multi_images::get_num_img_srcs() const
The number of image sources or the number of siamese heads. e.g., 2; this method is added to support data_store functionality
References m_num_img_srcs, setup_data_store, set_defaults, create_datum_views, fetch_datum, fetch_label, read_text_stream, load_list.
Referenced by lbann::data_store_multi_images::setup.
void lbann::data_reader_multi_images::setup_data_store(model *m) override
sets up a data_store.
References lbann::generic_data_reader::m_data_store, lbann::generic_data_store::setup.
Referenced by get_num_img_srcs.
void lbann::data_reader_multi_images::set_defaults() override
Set the default values for the width, the height, the number of channels, and the number of labels of an image.
References lbann::image_data_reader::m_image_width, lbann::image_data_reader::m_image_height, lbann::image_data_reader::m_image_num_channels, lbann::image_data_reader::set_linearized_image_size, lbann::image_data_reader::m_num_labels, m_num_img_srcs.
Referenced by get_num_img_srcs, data_reader_multi_images.
std::vector<::Mat > lbann::data_reader_multi_images::create_datum_views(::Mat &X, const int mb_idx) const
References m_num_img_srcs, lbann::image_data_reader::m_image_linearized_size.
Referenced by get_num_img_srcs, lbann::data_reader_mnist_siamese::fetch_labels, fetch_datum, lbann::data_reader_triplet::fetch_datum.
bool lbann::data_reader_multi_images::fetch_datum(::Mat &X, int data_id, int mb_idx, int tid) override
References create_datum_views, m_image_list, m_num_img_srcs, lbann::generic_data_reader::get_file_dir, lbann::generic_data_reader::m_data_store, lbann::generic_data_store::get_data_buf, lbann::image_utils::load_image, lbann::imagenet_reader::m_pps, get_type, lbann::image_data_reader::m_image_linearized_size.
Referenced by lbann::data_reader_mnist_siamese::get_type, get_num_img_srcs.
bool lbann::data_reader_multi_images::fetch_label(::Mat &Y, int data_id, int mb_idx, int tid) override
References m_image_list.
Referenced by lbann::data_reader_mnist_siamese::get_type, get_num_img_srcs.
bool lbann::data_reader_multi_images::read_text_stream(std::istream &text_stream, std::vector< sample_t > &list)
References m_num_img_srcs.
Referenced by get_num_img_srcs, load_list.
bool lbann::data_reader_multi_images::load_list(const std::string file_name, std::vector< sample_t > &list, const bool fetch_list_at_once=false)
References read_text_stream.
Referenced by get_num_img_srcs, load.