lbann::lbann_callback_check_dataset
std::string lbann::lbann_callback_check_dataset::m_basename
Basename for writing files.
std::set<long> lbann::lbann_callback_check_dataset::training_set
Referenced by on_forward_prop_end, on_epoch_end.
std::set<long> lbann::lbann_callback_check_dataset::validation_set
Referenced by on_evaluate_forward_prop_end, on_validation_end.
std::set<long> lbann::lbann_callback_check_dataset::testing_set
Referenced by on_evaluate_forward_prop_end, on_test_end.
lbann::lbann_callback_check_dataset::lbann_callback_check_dataset()
basename The basename for writing files.
References operator=.
Referenced by copy.
lbann::lbann_callback_check_dataset::lbann_callback_check_dataset(const lbann_callback_check_dataset &)=default
lbann_callback_check_dataset& lbann::lbann_callback_check_dataset::operator=(const lbann_callback_check_dataset &)=default
Referenced by lbann_callback_check_dataset.
lbann_callback_check_dataset* lbann::lbann_callback_check_dataset::copy() const override
References lbann_callback_check_dataset, on_forward_prop_end, on_evaluate_forward_prop_end, on_epoch_end, on_validation_end, on_test_end, add_to_set.
void lbann::lbann_callback_check_dataset::on_forward_prop_end(model *m, Layer *l) override
Called when a layer ends forward propagation.
References add_to_set, lbann::model::get_cur_step, training_set.
Referenced by copy.
void lbann::lbann_callback_check_dataset::on_evaluate_forward_prop_end(model *m, Layer *l) override
Called when a layer ends forward propagation for evaluation (validation / testing).
References lbann::model::get_execution_mode, validation, add_to_set, lbann::model::get_cur_validation_step, validation_set, testing, lbann::model::get_cur_testing_step, testing_set.
Referenced by copy.
void lbann::lbann_callback_check_dataset::on_epoch_end(model *m) override
Called immediate after the end of each epoch.
References comm, lbann::model::get_comm, lbann::lbann_comm::get_rank_in_model, training_set, lbann::model::get_layers, LBANN_ERROR, lbann::lbann_comm::get_procs_per_model, lbann::lbann_comm::am_model_master, lbann::lbann_comm::model_gather, lbann::lbann_comm::get_model_master, lbann::generic_input_layer::get_num_iterations_per_epoch, training, lbann::model::get_max_mini_batch_size.
Referenced by copy.
void lbann::lbann_callback_check_dataset::on_validation_end(model *m) override
Called immediately after the end of validation.
References lbann::model::get_comm, lbann::lbann_comm::get_rank_in_model, validation_set.
Referenced by copy.
void lbann::lbann_callback_check_dataset::on_test_end(model *m) override
Called immediately after the end of testing.
References lbann::model::get_comm, lbann::lbann_comm::get_rank_in_model, testing_set.
Referenced by copy.
void lbann::lbann_callback_check_dataset::add_to_set(model *m, Layer *l, int64_t step, std::set< long > &set)
References lbann::Layer::get_sample_indices_per_mb.
Referenced by copy, on_forward_prop_end, on_evaluate_forward_prop_end.
std::string lbann::lbann_callback_check_dataset::name() const override
Return this callback's name.