lbann::generic_data_store
generic_data_reader* lbann::generic_data_store::m_reader
Referenced by lbann::data_store_csv::setup, lbann::data_store_csv::exchange_data, lbann::data_store_image::get_data_buf, lbann::data_store_imagenet::setup, lbann::data_store_imagenet::test_data, lbann::data_store_imagenet::test_file_sizes, lbann::data_store_imagenet::read_files, lbann::data_store_imagenet::get_file_sizes, lbann::data_store_imagenet_patches::setup, lbann::data_store_merge_features::~data_store_merge_features, lbann::data_store_merge_samples::setup, lbann::data_store_multi_images::get_sample, lbann::data_store_multi_images::setup, lbann::data_store_pilot2_molecular::setup, lbann::data_store_pilot2_molecular::exchange_data, lbann::data_store_triplet::get_sample, lbann::data_store_triplet::setup, setup.
lbann_comm* lbann::generic_data_store::m_comm
Referenced by generic_data_store.
std::string lbann::generic_data_store::m_name
Referenced by get_name, set_name.
size_t lbann::generic_data_store::m_num_global_indices
number of indices that m_reader owns (in a global sense); equal to m_shuffled_indices->size()
Referenced by lbann::data_store_imagenet::get_file_sizes, lbann::data_store_multi_images::get_file_sizes, lbann::data_store_pilot2_molecular::construct_data_store.
const std::vector<std::vector<int> >* lbann::generic_data_store::m_my_minibatch_indices
the indices that will be used locally; the inner j-th vector contains indices referenced during the j-th call to generic_data_reader::fetch_data(...)
Referenced by get_minibatch_index_vector, setup.
std::vector<int> lbann::generic_data_store::m_my_minibatch_indices_v
contains a concatenation of the indices in m_my_minibatch_indices
Referenced by lbann::data_store_pilot2_molecular::clear_minibatch_indices, lbann::data_store_pilot2_molecular::add_minibatch_index, lbann::data_store_image::exchange_data, lbann::data_store_imagenet::test_data, lbann::data_store_imagenet::read_files, lbann::data_store_merge_features::~data_store_merge_features, lbann::data_store_merge_samples::setup, lbann::data_store_multi_images::extended_testing, get_minibatch_index_vector, exchange_mb_counts, exchange_mb_indices.
std::vector<int> lbann::generic_data_store::m_mb_counts
m_mb_counts[j] contains the number of indices passed to data_reader::fetch_data in one epoch
Referenced by exchange_mb_counts, exchange_mb_indices.
std::vector<std::vector<int> > lbann::generic_data_store::m_all_minibatch_indices
m_all_minibatch_indices[j] will contain all indices that will be passed to data_reader::fetch_data in one epoch, for all processors
Referenced by lbann::data_store_csv::get_my_indices, lbann::data_store_csv::get_indices, lbann::data_store_image::exchange_data, lbann::data_store_pilot2_molecular::get_required_molecules, exchange_mb_indices.
std::vector<int> lbann::generic_data_store::m_num_samples
m_num_samples[j] contains the number of samples (datastore indices) that are owned by P_j
Referenced by get_my_datastore_indices.
std::unordered_set<int> lbann::generic_data_store::m_my_datastore_indices
the indices that this processor owns;
Referenced by lbann::data_store_csv::populate_datastore, lbann::data_store_image::allocate_memory, lbann::data_store_image::exchange_data, lbann::data_store_imagenet::read_files, lbann::data_store_imagenet::get_file_sizes, lbann::data_store_multi_images::get_file_sizes, lbann::data_store_multi_images::read_files, get_my_datastore_indices.
size_t lbann::generic_data_store::m_num_readers
Referenced by lbann::data_store_image::exchange_file_sizes, setup.
int lbann::generic_data_store::m_rank
this processor's rank
Referenced by lbann::data_store_csv::get_data_buf_DataType, lbann::data_store_csv::exchange_data, lbann::data_store_csv::populate_datastore, lbann::data_store_imagenet::setup, lbann::data_store_imagenet::test_data, lbann::data_store_imagenet::test_file_sizes, lbann::data_store_imagenet::get_file_sizes, lbann::data_store_imagenet_patches::setup, lbann::data_store_merge_features::~data_store_merge_features, lbann::data_store_merge_samples::setup, lbann::data_store_multi_images::setup, lbann::data_store_multi_images::get_file_sizes, lbann::data_store_multi_images::extended_testing, lbann::data_store_pilot2_molecular::setup, lbann::data_store_pilot2_molecular::exchange_data, lbann::data_store_triplet::setup, generic_data_store, get_my_datastore_indices.
int lbann::generic_data_store::m_np
number of procs in the model
Referenced by get_index_owner, lbann::data_store_csv::setup, lbann::data_store_csv::exchange_data, lbann::data_store_image::exchange_data, lbann::data_store_image::exchange_file_sizes, lbann::data_store_pilot2_molecular::exchange_data, generic_data_store, get_my_datastore_indices, exchange_mb_counts, exchange_mb_indices.
size_t lbann::generic_data_store::m_epoch
Referenced by set_shuffled_indices.
bool lbann::generic_data_store::m_in_memory
Referenced by lbann::data_store_csv::setup, lbann::data_store_image::setup, lbann::data_store_imagenet::setup, lbann::data_store_merge_features::~data_store_merge_features, lbann::data_store_merge_samples::setup, lbann::data_store_multi_images::setup, lbann::data_store_pilot2_molecular::setup, lbann::data_store_triplet::setup.
bool lbann::generic_data_store::m_master
Referenced by lbann::data_store_csv::setup, lbann::data_store_csv::get_data_buf_DataType, lbann::data_store_csv::exchange_data, lbann::data_store_image::setup, lbann::data_store_image::exchange_data, lbann::data_store_imagenet::test_file_sizes, lbann::data_store_imagenet::get_file_sizes, lbann::data_store_multi_images::get_file_sizes, lbann::data_store_multi_images::extended_testing, lbann::data_store_pilot2_molecular::setup, generic_data_store, setup.
const std::vector<int>* lbann::generic_data_store::m_shuffled_indices
Referenced by set_num_global_indices, lbann::data_store_csv::get_indices, lbann::data_store_pilot2_molecular::build_nabor_map, get_my_datastore_indices, set_shuffled_indices.
model* lbann::generic_data_store::m_model
Referenced by setup.
std::string lbann::generic_data_store::m_dir
base directory for data
Referenced by lbann::data_store_imagenet::test_data, lbann::data_store_imagenet::test_file_sizes, lbann::data_store_imagenet::read_files, lbann::data_store_imagenet::get_file_sizes, lbann::data_store_multi_images::get_file_sizes, lbann::data_store_multi_images::read_files, lbann::data_store_multi_images::extended_testing, get_file_size.
bool lbann::generic_data_store::m_extended_testing
conduct extensive testing
Referenced by lbann::data_store_csv::get_data_buf_DataType, lbann::data_store_image::setup, generic_data_store.
bool lbann::generic_data_store::m_collect_minibatch_indices
Referenced by setup.
MPI_Comm lbann::generic_data_store::m_mpi_comm
Referenced by lbann::data_store_csv::setup, lbann::data_store_csv::exchange_data, lbann::data_store_image::exchange_data, lbann::data_store_image::exchange_file_sizes, lbann::data_store_pilot2_molecular::build_nabor_map, lbann::data_store_pilot2_molecular::exchange_data, exchange_mb_counts, exchange_mb_indices.
lbann::generic_data_store::generic_data_store(generic_data_reader *reader, model *m)
ctor
References m_comm, m_rank, lbann::lbann_comm::get_rank_in_model, m_np, lbann::lbann_comm::get_procs_per_model, set_name, options::get, m_master, options::has_bool, options::get_bool, m_extended_testing.
lbann::generic_data_store::generic_data_store(const generic_data_store &)=default
copy ctor
generic_data_store& lbann::generic_data_store::operator=(const generic_data_store &)=default
operator=
virtual lbann::generic_data_store::~generic_data_store()
dtor
References copy, setup, set_shuffled_indices.
virtual generic_data_store* lbann::generic_data_store::copy() const =0
Referenced by ~generic_data_store.
void lbann::generic_data_store::setup()
called by generic_data_reader::setup_data_store
References set_shuffled_indices, m_reader, lbann::generic_data_reader::get_shuffled_indices, set_num_global_indices, m_num_readers, lbann::generic_data_reader::get_num_parallel_readers, m_master, lbann::generic_data_reader::get_type, m_collect_minibatch_indices, lbann::generic_data_reader::set_save_minibatch_entries, lbann::generic_data_reader::get_role, m_model, lbann::model::collect_indices, training, validation, testing, m_my_minibatch_indices, lbann::generic_data_reader::get_minibatch_indices.
Referenced by ~generic_data_store, lbann::csv_reader::setup_data_store, lbann::imagenet_reader::setup_data_store, lbann::imagenet_reader_patches::setup_data_store, lbann::data_reader_merge_features::setup_data_store, lbann::data_reader_multi_images::setup_data_store, lbann::pilot2_molecular_reader::setup_data_store, lbann::data_reader_triplet::setup_data_store, lbann::data_store_csv::setup, lbann::data_store_image::setup, lbann::data_store_merge_features::~data_store_merge_features, lbann::data_store_merge_samples::setup, lbann::data_store_pilot2_molecular::setup.
void lbann::generic_data_store::set_shuffled_indices(const std::vector< int > *indices)
called by generic_data_reader::update
References m_shuffled_indices, m_epoch, exchange_data.
Referenced by ~generic_data_store, lbann::generic_data_reader::update, setup.
virtual void lbann::generic_data_store::get_data_buf(int data_id, std::vector< unsigned char > *&buf, int multi_idx=0)
called by various image data readers
Referenced by lbann::imagenet_reader::fetch_datum, lbann::imagenet_reader_patches::fetch_datum, lbann::data_reader_multi_images::fetch_datum, lbann::pilot2_molecular_reader::fetch_datum, lbann::data_reader_triplet::fetch_datum.
virtual void lbann::generic_data_store::get_data_buf(int data_id, int tid, std::vector< double > *&buf)
virtual void lbann::generic_data_store::get_data_buf_DataType(int data_id, std::vector< DataType > *&buf)
Referenced by lbann::csv_reader::fetch_datum.
const std::string& lbann::generic_data_store::get_name() const
References m_name.
Referenced by lbann::data_store_multi_images::get_file_sizes.
void lbann::generic_data_store::set_name(std::string name)
References m_name.
Referenced by lbann::data_store_multi_images::data_store_multi_images, lbann::data_store_triplet::data_store_triplet, lbann::data_store_csv::data_store_csv, lbann::data_store_image::setup, lbann::data_store_imagenet::setup, lbann::data_store_imagenet_patches::setup, lbann::data_store_merge_features::data_store_merge_features, lbann::data_store_merge_samples::data_store_merge_samples, lbann::data_store_multi_images::setup, lbann::data_store_pilot2_molecular::data_store_pilot2_molecular, lbann::data_store_triplet::setup, generic_data_store.
size_t lbann::generic_data_store::get_file_size(std::string dir, std::string fn)
returns the number of bytes in dir/fn; it's OK if dir = ""
References m_dir.
Referenced by lbann::data_store_imagenet::test_file_sizes, lbann::data_store_imagenet::get_file_sizes, lbann::data_store_multi_images::get_file_sizes.
void lbann::generic_data_store::set_num_global_indices()
References m_shuffled_indices.
Referenced by setup.
void lbann::generic_data_store::get_minibatch_index_vector()
fills in m_my_minibatch_indices_v
References m_my_minibatch_indices, m_my_minibatch_indices_v.
Referenced by lbann::data_store_csv::setup, lbann::data_store_image::setup, lbann::data_store_merge_features::~data_store_merge_features, lbann::data_store_merge_samples::setup, lbann::data_store_pilot2_molecular::setup.
void lbann::generic_data_store::exchange_mb_counts()
fills in m_mb_counts
References m_my_minibatch_indices_v, m_mb_counts, m_np, m_mpi_comm.
Referenced by exchange_mb_indices.
void lbann::generic_data_store::exchange_mb_indices()
fills in m_all_minibatch_indices
References exchange_mb_counts, m_np, m_mb_counts, m_my_minibatch_indices_v, m_mpi_comm, m_all_minibatch_indices.
Referenced by lbann::data_store_csv::setup, lbann::data_store_image::setup, lbann::data_store_pilot2_molecular::setup.
void lbann::generic_data_store::get_my_datastore_indices()
fills in m_my_datastore_indices and m_num_samples
References m_num_samples, m_np, m_shuffled_indices, m_rank, m_my_datastore_indices.
Referenced by lbann::data_store_csv::setup, lbann::data_store_image::setup.
virtual void lbann::generic_data_store::exchange_data()=0
Referenced by set_shuffled_indices.
int lbann::generic_data_store::get_index_owner(int idx)
returns the processor that owns the data associated with the index
References m_np.
Referenced by lbann::data_store_csv::exchange_data, lbann::data_store_image::exchange_data.
virtual void lbann::generic_data_store::extended_testing()
Referenced by lbann::data_store_image::setup.