lbann::data_reader_triplet
using lbann::data_reader_triplet::label_t = offline_patches_npz::label_t
using lbann::data_reader_triplet::sample_t = offline_patches_npz::sample_t
offline_patches_npz lbann::data_reader_triplet::m_samples
Referenced by get_sample, operator=, fetch_datum, fetch_label, get_image_list_of_current_mb, get_image_list, load.
lbann::data_reader_triplet::data_reader_triplet(const std::shared_ptr< cv_process > &pp, bool shuffle=true)
References set_defaults.
Referenced by copy.
lbann::data_reader_triplet::data_reader_triplet(const data_reader_triplet &)
data_reader_triplet & lbann::data_reader_triplet::operator=(const data_reader_triplet &)
References lbann::data_reader_multi_images::operator=, m_samples.
lbann::data_reader_triplet::~data_reader_triplet() override
data_reader_triplet* lbann::data_reader_triplet::copy() const override
References data_reader_triplet.
std::string lbann::data_reader_triplet::get_type() const override
Return this data_reader's type
References set_input_params, load, get_image_list_of_current_mb, get_image_list.
Referenced by fetch_datum, load.
void lbann::data_reader_triplet::set_input_params(const int width, const int height, const int num_ch, const int num_labels) override
Set up imagenet specific input parameters If argument is set to 0, then this method does not change the value of the corresponding parameter. However, width and height can only be both zero or both non-zero.Same as the parent class method except the default value of the last argument, num_img_srcs, which is 3 here.
References lbann::data_reader_multi_images::set_input_params.
Referenced by get_type.
void lbann::data_reader_triplet::load() override
Load the dataset. Each data reader implementation should implement this to initialize its internal data structures, determine the number of samples and their dimensionality (if needed), and set up and shuffle samples.
References lbann::generic_data_reader::get_data_filename, m_samples, lbann::offline_patches_npz::load, lbann::generic_data_reader::m_first_n, get_type, lbann::offline_patches_npz::get_num_samples, lbann::generic_data_reader::set_use_percent, lbann::generic_data_reader::set_absolute_sample_count, lbann::generic_data_reader::m_shuffled_indices, lbann::generic_data_reader::select_subset_of_data.
Referenced by get_type.
std::vector< data_reader_triplet::sample_t > lbann::data_reader_triplet::get_image_list_of_current_mb() const
Return the sample list of current minibatch.
References lbann::generic_data_reader::m_mini_batch_size, lbann::generic_data_reader::m_indices_fetched_per_mb, m_samples, lbann::offline_patches_npz::get_sample.
Referenced by get_type.
std::vector< data_reader_triplet::sample_t > lbann::data_reader_triplet::get_image_list() const
Allow read-only access to the entire sample list.
References m_samples, lbann::offline_patches_npz::get_num_samples, lbann::offline_patches_npz::get_sample.
Referenced by get_type.
sample_t lbann::data_reader_triplet::get_sample(size_t idx) const
References m_samples, lbann::offline_patches_npz::get_sample, setup_data_store, set_defaults, fetch_datum, fetch_label.
Referenced by lbann::data_store_triplet::get_sample.
void lbann::data_reader_triplet::setup_data_store(model *m) override
sets up a data_store.
References lbann::generic_data_reader::m_data_store, lbann::generic_data_store::setup.
Referenced by get_sample.
void lbann::data_reader_triplet::set_defaults() override
Set the default values for the width, the height, the number of channels, and the number of labels of an image.
References lbann::image_data_reader::m_image_width, lbann::image_data_reader::m_image_height, lbann::image_data_reader::m_image_num_channels, lbann::image_data_reader::set_linearized_image_size, lbann::image_data_reader::m_num_labels, lbann::data_reader_multi_images::m_num_img_srcs.
Referenced by get_sample, data_reader_triplet.
bool lbann::data_reader_triplet::fetch_datum(::Mat &X, int data_id, int mb_idx, int tid) override
References lbann::data_reader_multi_images::create_datum_views, m_samples, lbann::offline_patches_npz::get_sample, lbann::data_reader_multi_images::m_num_img_srcs, lbann::generic_data_reader::get_file_dir, lbann::generic_data_reader::m_data_store, lbann::generic_data_store::get_data_buf, lbann::image_utils::load_image, lbann::imagenet_reader::m_pps, get_type, lbann::image_data_reader::m_image_linearized_size.
Referenced by get_sample.
bool lbann::data_reader_triplet::fetch_label(::Mat &Y, int data_id, int mb_idx, int tid) override
References m_samples, lbann::offline_patches_npz::get_label.
Referenced by get_sample.