lbann::numpy_reader
int lbann::numpy_reader::m_num_samples
Number of samples.
Referenced by operator=, load.
int lbann::numpy_reader::m_num_features
Number of features in each sample.
Referenced by get_linearized_data_size, operator=, load, fetch_datum, fetch_label, fetch_response.
int lbann::numpy_reader::m_num_labels
Number of label classes.
Referenced by get_num_labels, get_linearized_label_size, operator=, load.
bool lbann::numpy_reader::m_has_labels
Whether to fetch a label from the last column.
Referenced by set_has_labels, get_data_dims, operator=, load, fetch_datum, fetch_label.
bool lbann::numpy_reader::m_has_responses
Whether to fetch a response from the last column.
Referenced by set_has_responses, get_data_dims, operator=, load, fetch_datum, fetch_response.
cnpy::NpyArray lbann::numpy_reader::m_data
Underlying numpy data. Note raw data is managed with shared smart pointer semantics (relevant for copying).
Referenced by get_data_dims, operator=, load, fetch_datum, fetch_label, fetch_response.
lbann::numpy_reader::numpy_reader(bool shuffle=true)
Referenced by copy.
lbann::numpy_reader::numpy_reader(const numpy_reader &)
numpy_reader & lbann::numpy_reader::operator=(const numpy_reader &)
References lbann::generic_data_reader::operator=, m_num_samples, m_num_features, m_num_labels, m_has_labels, m_has_responses, m_data.
lbann::numpy_reader::~numpy_reader() override
numpy_reader* lbann::numpy_reader::copy() const override
References numpy_reader.
std::string lbann::numpy_reader::get_type() const override
Return this data_reader's type
void lbann::numpy_reader::set_has_labels(bool b)
Set whether to fetch labels.
References m_has_labels.
void lbann::numpy_reader::set_has_responses(bool b)
Set whether to fetch responses.
References m_has_responses, load.
void lbann::numpy_reader::load() override
Load the dataset. Each data reader implementation should implement this to initialize its internal data structures, determine the number of samples and their dimensionality (if needed), and set up and shuffle samples.
References lbann::generic_data_reader::get_data_filename, m_data, m_num_samples, m_num_features, m_has_labels, m_has_responses, lbann::cnpy_utils::data, m_num_labels, lbann::generic_data_reader::m_shuffled_indices, lbann::generic_data_reader::select_subset_of_data.
Referenced by set_has_responses.
int lbann::numpy_reader::get_num_labels() const override
Return the number of labels (classes) in this dataset.
References m_num_labels.
int lbann::numpy_reader::get_linearized_data_size() const override
Get the linearized size (i.e. number of elements) in a sample.
References m_num_features.
int lbann::numpy_reader::get_linearized_label_size() const override
Get the linearized size (i.e. number of elements) in a label.
References m_num_labels.
const std::vector<int> lbann::numpy_reader::get_data_dims() const override
Get the dimensions of the data.
References m_data, m_has_labels, m_has_responses, fetch_datum, fetch_label, fetch_response.
bool lbann::numpy_reader::fetch_datum(Mat &X, int data_id, int mb_idx, int tid) override
Fetch a single sample into a matrix. X The matrix to load data into. data_id The index of the datum to fetch. mb_idx The index within the mini-batch.
References m_num_features, m_has_labels, m_has_responses, m_data, lbann::cnpy_utils::data.
Referenced by get_data_dims.
bool lbann::numpy_reader::fetch_label(Mat &Y, int data_id, int mb_idx, int tid) override
Fetch a single label into a matrix. Y The matrix to load data into. data_id The index of the datum to fetch. mb_idx The index within the mini-batch.
References m_has_labels, m_data, lbann::cnpy_utils::data, m_num_features.
Referenced by get_data_dims.
bool lbann::numpy_reader::fetch_response(Mat &Y, int data_id, int mb_idx, int tid) override
Fetch a single response into a matrix. Y The matrix to load data into. data_id The index of the datum to fetch. mb_idx The index within the mini-batch.
References m_has_responses, m_data, lbann::cnpy_utils::data, m_num_features.
Referenced by get_data_dims.