lbann::categorical_accuracy_metric
AbsDistMat* lbann::categorical_accuracy_metric::m_prediction_values
Maximum values in columns of prediction matrix.
Referenced by categorical_accuracy_metric, operator=, ~categorical_accuracy_metric, setup, evaluate_compute.
std::vector<int> lbann::categorical_accuracy_metric::m_prediction_indices
Indices of maximum values in columns of prediction matrix.
Referenced by operator=, setup, evaluate_compute.
lbann::categorical_accuracy_metric::categorical_accuracy_metric(lbann_comm *comm)
Constructor.
Referenced by copy.
lbann::categorical_accuracy_metric::categorical_accuracy_metric(const categorical_accuracy_metric &other)
Copy constructor.
References m_prediction_values.
categorical_accuracy_metric & lbann::categorical_accuracy_metric::operator=(const categorical_accuracy_metric &other)
Copy assignment operator.
References lbann::metric::operator=, m_prediction_values, m_prediction_indices.
lbann::categorical_accuracy_metric::~categorical_accuracy_metric()
Destructor.
References m_prediction_values.
categorical_accuracy_metric* lbann::categorical_accuracy_metric::copy() const override
Copy function.
References categorical_accuracy_metric.
std::string lbann::categorical_accuracy_metric::name() const override
Return a string name for this metric.
std::string lbann::categorical_accuracy_metric::get_unit() const override
Return "%" as a display unit.
References setup, evaluate_compute, prediction.
void lbann::categorical_accuracy_metric::setup(model &m) override
Setup metric.
References lbann::metric::setup, lbann::metric::get_target_layer, m_prediction_values, lbann::model::get_max_mini_batch_size, m_prediction_indices.
Referenced by get_unit.
EvalType lbann::categorical_accuracy_metric::evaluate_compute(const AbsDistMat &prediction, const AbsDistMat &ground_truth) override
Computation to evaluate the metric function. This returns the sum of metric values across the mini-batch, not the mean value.
References m_prediction_values, m_prediction_indices, lbann::metric::get_comm, lbann::lbann_comm::allreduce, lbann::lbann_comm::model_allreduce.
Referenced by get_unit.