lbann::lbann_callback_io
std::unordered_set<Layer *> lbann::lbann_callback_io::m_layer_indices
Indicies of layers to monitor.
Referenced by on_epoch_end, on_test_end.
lbann::lbann_callback_io::lbann_callback_io()
Referenced by copy.
lbann::lbann_callback_io::lbann_callback_io(const lbann_callback_io &)=default
lbann_callback_io& lbann::lbann_callback_io::operator=(const lbann_callback_io &)=default
lbann_callback_io* lbann::lbann_callback_io::copy() const override
References lbann_callback_io, on_epoch_end, on_test_end.
lbann::lbann_callback_io::lbann_callback_io(std::unordered_set< Layer *> layers)
Only apply to specific layers.
void lbann::lbann_callback_io::on_epoch_end(model *m) override
Report how much I/O has occured per data reader
References comm, lbann::model::get_comm, lbann::model::get_layers, m_layer_indices, lbann::lbann_comm::get_model_rank, lbann::lbann_comm::get_rank_in_model, lbann::model::get_cur_epoch.
Referenced by copy.
void lbann::lbann_callback_io::on_test_end(model *m) override
Called immediately after the end of testing.
References comm, lbann::model::get_comm, lbann::model::get_layers, m_layer_indices, lbann::lbann_comm::get_model_rank, lbann::lbann_comm::get_rank_in_model, lbann::model::get_cur_epoch.
Referenced by copy.
std::string lbann::lbann_callback_io::name() const override
Return this callback's name.