lbann::lbann_callback_learning_rate
std::unordered_set<weights *> lbann::lbann_callback_learning_rate::m_weights
Weights to update.
Referenced by setup, on_epoch_end, on_backward_prop_end, lbann::lbann_callback_linear_growth_learning_rate::setup.
float lbann::lbann_callback_learning_rate::m_cur_global_lr
This should be maintained by all learning rate schedule implementations as the current global learning rate. This enables coordination among different schedules, particularly ones that work on a per-optimizer basis.
Referenced by global_schedule, setup, on_epoch_end, lbann::lbann_callback_step_learning_rate::global_schedule, lbann::lbann_callback_adaptive_learning_rate::global_schedule, lbann::lbann_callback_drop_fixed_learning_rate::global_schedule, lbann::lbann_callback_linear_growth_learning_rate::setup, lbann::lbann_callback_linear_growth_learning_rate::global_schedule, lbann::lbann_callback_poly_learning_rate::global_schedule, lbann::lbann_callback_poly_learning_rate::optimizer_schedule, lbann::lbann_callback_optimizerwise_adaptive_learning_rate::optimizer_schedule.
lbann::lbann_callback_learning_rate::lbann_callback_learning_rate()
lbann::lbann_callback_learning_rate::lbann_callback_learning_rate(const lbann_callback_learning_rate &)=default
lbann_callback_learning_rate& lbann::lbann_callback_learning_rate::operator=(const lbann_callback_learning_rate &)=default
lbann::lbann_callback_learning_rate::lbann_callback_learning_rate(std::unordered_set< weights *> weights_list)
Only apply to specific weights.
void lbann::lbann_callback_learning_rate::setup(model *m) override
Do some initialization.
References m_weights, lbann::model::get_weights, m_cur_global_lr, lbann::optimizer::get_learning_rate.
Referenced by lbann::lbann_callback_linear_growth_learning_rate::copy, lbann::lbann_callback_poly_learning_rate::copy, lbann::lbann_callback_linear_growth_learning_rate::setup, lbann::lbann_callback_poly_learning_rate::setup.
void lbann::lbann_callback_learning_rate::on_epoch_end(model *m) override
Apply global learning rate schedules.
References global_schedule, m_cur_global_lr, comm, lbann::model::get_comm, lbann::lbann_comm::am_model_master, lbann::lbann_comm::get_model_rank, lbann::model::get_cur_epoch, m_weights, lbann::optimizer::get_learning_rate, lbann::optimizer::set_learning_rate.
void lbann::lbann_callback_learning_rate::on_backward_prop_end(model *m) override
Apply local/per-optimizer learning rate schedules.
References m_weights, lbann::optimizer::get_learning_rate, optimizer_schedule, lbann::optimizer::set_learning_rate.
virtual float lbann::lbann_callback_learning_rate::global_schedule(model *m)
This is called at the end of every epoch to update the learning rate for every optimizer. Adjustments should be made based on the current global learning rate. The returned learning rate will be used to automatically update the current global learning rate.
References m_cur_global_lr.
Referenced by lbann::lbann_callback_step_learning_rate::name, lbann::lbann_callback_adaptive_learning_rate::name, lbann::lbann_callback_drop_fixed_learning_rate::name, lbann::lbann_callback_linear_growth_learning_rate::name, lbann::lbann_callback_poly_learning_rate::name, on_epoch_end.
virtual float lbann::lbann_callback_learning_rate::optimizer_schedule(model *m, optimizer &opt)
This is called at the end of every training mini-batch to update the learning rate for optimizer opt. The current global learning rate is not updated automatically based on this method.
References lbann::optimizer::get_learning_rate.
Referenced by lbann::lbann_callback_poly_learning_rate::name, lbann::lbann_callback_optimizerwise_adaptive_learning_rate::name, on_backward_prop_end.