lbann::cross_entropy_with_uncertainty
AbsDistMat* lbann::cross_entropy_with_uncertainty::m_prediction_sums
Workspace.
Referenced by cross_entropy_with_uncertainty, operator=, ~cross_entropy_with_uncertainty, setup, finish_evaluate_compute, differentiate_compute.
lbann::cross_entropy_with_uncertainty::cross_entropy_with_uncertainty(EvalType scale_factor=EvalType(1))
Default constructor.
Referenced by copy.
lbann::cross_entropy_with_uncertainty::cross_entropy_with_uncertainty(const cross_entropy_with_uncertainty &other)
Copy constructor.
References m_prediction_sums.
cross_entropy_with_uncertainty & lbann::cross_entropy_with_uncertainty::operator=(const cross_entropy_with_uncertainty &other)
Copy assignment operator.
References lbann::loss_function::operator=, m_prediction_sums.
lbann::cross_entropy_with_uncertainty::~cross_entropy_with_uncertainty() override
Destructor.
References m_prediction_sums.
cross_entropy_with_uncertainty* lbann::cross_entropy_with_uncertainty::copy() const override
Copy function.
References cross_entropy_with_uncertainty.
std::string lbann::cross_entropy_with_uncertainty::name() const override
Get the name of the objective function term.
References setup.
void lbann::cross_entropy_with_uncertainty::setup(model &m) override
Setup cross entropy term.
References lbann::loss_function::setup, lbann::loss_function::m_gradient, m_prediction_sums.
Referenced by name.
void lbann::cross_entropy_with_uncertainty::start_evaluate_compute(const AbsDistMat &prediction, const AbsDistMat &ground_truth) override
Compute the cross entropy objective function. Given a predicted distribution $y$ and ground truth distribution $\hat{y}$, the cross entropy is \[ CE(y,\hat{y}) = - \sum\limits_{i} \hat{y}_i \log y_i \] This function updates the objective function value with the mean cross entropy across the mini-batch. Note that each column of the predictions matrix should have non-negative entries that add up to one.
References finish_evaluate_compute, prediction, differentiate_compute.
EvalType lbann::cross_entropy_with_uncertainty::finish_evaluate_compute(const AbsDistMat &prediction, const AbsDistMat &ground_truth) override
Finish evaluation of the loss function. This should not include the scale factor.
References m_prediction_sums, lbann::objective_function_term::get_comm, lbann::lbann_comm::allreduce.
Referenced by start_evaluate_compute.
void lbann::cross_entropy_with_uncertainty::differentiate_compute(const AbsDistMat &prediction, const AbsDistMat &ground_truth, AbsDistMat &gradient) override
Compute the gradient of the cross entropy objective function. Given a predicted distribution $y$ and ground truth distribution $\hat{y}$, the gradient of the cross entropy is \[ \nabla_y CE (y,\hat{y}) = - \hat{y} . / y \]
References m_prediction_sums.
Referenced by start_evaluate_compute.