lbann::image_data_reader
using lbann::image_data_reader::img_src_t = std::string
using lbann::image_data_reader::label_t = int
using lbann::image_data_reader::sample_t = std::pair<img_src_t, label_t>
std::string lbann::image_data_reader::m_image_dir
where images are stored
Referenced by operator=.
std::vector<sample_t> lbann::image_data_reader::m_image_list
list of image files and labels
Referenced by get_image_list, get_sample, operator=, fetch_label, load, get_image_list_of_current_mb, lbann::imagenet_reader::fetch_datum, lbann::imagenet_reader_org::fetch_datum, lbann::imagenet_reader_patches::fetch_datum.
int lbann::image_data_reader::m_image_width
image width
Referenced by get_image_width, get_data_dims, save_image, lbann::imagenet_reader_patches::get_data_dims, lbann::data_reader_multi_images::get_data_dims, lbann::cifar10_reader::set_defaults, lbann::cifar10_reader::fetch_datum, operator=, set_linearized_image_size, set_defaults, set_input_params, lbann::imagenet_reader::set_defaults, lbann::imagenet_reader::replicate_processor, lbann::imagenet_reader_org::set_defaults, lbann::imagenet_reader_org::fetch_datum, lbann::imagenet_reader_patches::set_defaults, lbann::imagenet_reader_patches::replicate_processor, lbann::mnist_reader::set_defaults, lbann::mnist_reader::fetch_datum, lbann::data_reader_mnist_siamese::set_defaults, lbann::data_reader_multi_images::set_defaults, lbann::data_reader_triplet::set_defaults.
int lbann::image_data_reader::m_image_height
image height
Referenced by get_image_height, get_data_dims, save_image, lbann::imagenet_reader_patches::get_data_dims, lbann::data_reader_multi_images::get_data_dims, lbann::cifar10_reader::set_defaults, lbann::cifar10_reader::fetch_datum, operator=, set_linearized_image_size, set_defaults, set_input_params, lbann::imagenet_reader::set_defaults, lbann::imagenet_reader::replicate_processor, lbann::imagenet_reader_org::set_defaults, lbann::imagenet_reader_org::fetch_datum, lbann::imagenet_reader_patches::set_defaults, lbann::imagenet_reader_patches::replicate_processor, lbann::mnist_reader::set_defaults, lbann::mnist_reader::fetch_datum, lbann::data_reader_mnist_siamese::set_defaults, lbann::data_reader_multi_images::set_defaults, lbann::data_reader_triplet::set_defaults.
int lbann::image_data_reader::m_image_num_channels
number of image channels
Referenced by get_image_num_channels, get_data_dims, save_image, lbann::imagenet_reader_patches::get_data_dims, lbann::data_reader_multi_images::get_data_dims, lbann::cifar10_reader::set_defaults, lbann::cifar10_reader::fetch_datum, operator=, set_linearized_image_size, set_defaults, set_input_params, lbann::imagenet_reader::set_defaults, lbann::imagenet_reader_org::set_defaults, lbann::imagenet_reader_org::fetch_datum, lbann::imagenet_reader_patches::set_defaults, lbann::mnist_reader::set_defaults, lbann::data_reader_mnist_siamese::set_defaults, lbann::data_reader_multi_images::set_defaults, lbann::data_reader_triplet::set_defaults.
int lbann::image_data_reader::m_image_linearized_size
linearized image size
Referenced by get_linearized_data_size, lbann::imagenet_reader_patches::get_linearized_data_size, lbann::data_reader_multi_images::get_linearized_data_size, operator=, set_linearized_image_size, lbann::imagenet_reader::fetch_datum, lbann::imagenet_reader_org::allocate_pixel_bufs, lbann::imagenet_reader_org::fetch_datum, lbann::imagenet_reader_patches::create_datum_views, lbann::imagenet_reader_patches::fetch_datum, lbann::imagenet_reader_single::fetch_datum, lbann::data_reader_mnist_siamese::fetch_labels, lbann::data_reader_multi_images::create_datum_views, lbann::data_reader_multi_images::fetch_datum, lbann::data_reader_triplet::fetch_datum.
int lbann::image_data_reader::m_num_labels
number of labels
Referenced by get_num_labels, get_linearized_label_size, lbann::cifar10_reader::set_defaults, operator=, set_defaults, set_input_params, lbann::imagenet_reader::set_defaults, lbann::imagenet_reader_org::set_defaults, lbann::imagenet_reader_patches::set_defaults, lbann::imagenet_reader_patches::replicate_processor, lbann::mnist_reader::set_defaults, lbann::data_reader_mnist_siamese::set_defaults, lbann::data_reader_multi_images::set_defaults, lbann::data_reader_triplet::set_defaults.
lbann::image_data_reader::image_data_reader(bool shuffle=true)
References set_defaults.
lbann::image_data_reader::image_data_reader(const image_data_reader &)
image_data_reader & lbann::image_data_reader::operator=(const image_data_reader &)
References lbann::generic_data_reader::operator=, m_image_dir, m_image_list, m_image_width, m_image_height, m_image_num_channels, m_image_linearized_size, m_num_labels.
Referenced by lbann::imagenet_reader::operator=, lbann::imagenet_reader_patches::operator=.
void lbann::image_data_reader::set_input_params(const int width=0, const int height=0, const int num_ch=0, const int num_labels=0)
Set up imagenet specific input parameters If argument is set to 0, then this method does not change the value of the corresponding parameter. However, width and height can only be both zero or both non-zero.
References m_image_width, m_image_height, m_image_num_channels, set_linearized_image_size, m_num_labels.
Referenced by lbann::imagenet_reader_org::set_input_params, lbann::data_reader_multi_images::set_input_params.
void lbann::image_data_reader::load() override
Load the dataset. Each data reader implementation should implement this to initialize its internal data structures, determine the number of samples and their dimensionality (if needed), and set up and shuffle samples.
References lbann::generic_data_reader::get_data_filename, m_image_list, lbann::generic_data_reader::m_shuffled_indices, lbann::generic_data_reader::select_subset_of_data.
int lbann::image_data_reader::get_num_labels() const override
Return the number of labels (classes) in this dataset.
References m_num_labels.
virtual int lbann::image_data_reader::get_image_width() const
References m_image_width.
virtual int lbann::image_data_reader::get_image_height() const
References m_image_height.
virtual int lbann::image_data_reader::get_image_num_channels() const
References m_image_num_channels.
int lbann::image_data_reader::get_linearized_data_size() const override
Get the total number of channel values in a sample of image(s).
References m_image_linearized_size.
Referenced by lbann::cifar10_reader::load.
int lbann::image_data_reader::get_linearized_label_size() const override
Get the linearized size (i.e. number of elements) in a label.
References m_num_labels.
const std::vector<int> lbann::image_data_reader::get_data_dims() const override
Get the dimensions of the data.
References m_image_num_channels, m_image_height, m_image_width.
void lbann::image_data_reader::save_image(Mat &pixels, const std::string filename, bool do_scale=true) override
Save pixels to an image. The implementing data reader is responsible for handling format detection, conversion, etc.
References lbann::lbann_image_preprocessor::internal_save_image, m_image_height, m_image_width, m_image_num_channels, get_image_list_of_current_mb.
std::vector< image_data_reader::sample_t > lbann::image_data_reader::get_image_list_of_current_mb() const
Return the sample list of current minibatch.
References lbann::generic_data_reader::m_mini_batch_size, lbann::generic_data_reader::m_indices_fetched_per_mb, m_image_list.
Referenced by save_image.
const std::vector<sample_t>& lbann::image_data_reader::get_image_list() const
Allow read-only access to the entire sample list.
References m_image_list.
Referenced by lbann::data_store_imagenet::test_data, lbann::data_store_imagenet::test_file_sizes, lbann::data_store_imagenet::read_files, lbann::data_store_imagenet::get_file_sizes.
sample_t lbann::image_data_reader::get_sample(const size_t idx) const
Returns idx-th sample in the initial loading order. The second argument is only to facilitate overloading, and not to be used by users.
References m_image_list, set_defaults, fetch_label, set_linearized_image_size.
void lbann::image_data_reader::set_defaults()
Set the default values for the width, the height, the number of channels, and the number of labels of an image.
References m_image_width, m_image_height, m_image_num_channels, set_linearized_image_size, m_num_labels.
Referenced by get_sample, image_data_reader.
bool lbann::image_data_reader::fetch_label(Mat &Y, int data_id, int mb_idx, int tid) override
Fetch a single label into a matrix. Y The matrix to load data into. data_id The index of the datum to fetch. mb_idx The index within the mini-batch.
References m_image_list.
Referenced by get_sample.
void lbann::image_data_reader::set_linearized_image_size()
References m_image_linearized_size, m_image_width, m_image_height, m_image_num_channels.
Referenced by get_sample, lbann::cifar10_reader::set_defaults, set_defaults, set_input_params, lbann::imagenet_reader::set_defaults, lbann::imagenet_reader::replicate_processor, lbann::imagenet_reader_org::set_defaults, lbann::imagenet_reader_patches::set_defaults, lbann::imagenet_reader_patches::replicate_processor, lbann::mnist_reader::set_defaults, lbann::data_reader_mnist_siamese::set_defaults, lbann::data_reader_multi_images::set_defaults, lbann::data_reader_triplet::set_defaults.