lbann::metric
lbann_comm* lbann::metric::m_comm
LBANN communicator.
const generic_target_layer* lbann::metric::m_target_layer
Pointer to target layer.
Referenced by setup, evaluate, get_target_layer, get_layer_pointers, set_layer_pointers.
std::map<execution_mode,metric_statistics> lbann::metric::m_statistics
Metric statistics.
Referenced by evaluate, get_mean_value, get_statistics_num_samples, save_to_checkpoint_shared, load_from_checkpoint_shared.
double lbann::metric::m_evaluate_time
Runtime for the metric evaluation.
Referenced by evaluate.
lbann::metric::metric(lbann_comm *comm)
Constructor.
lbann::metric::metric(const metric &other)=default
Copy constructor.
metric& lbann::metric::operator=(const metric &other)=default
Copy assignment operator.
Referenced by lbann::categorical_accuracy_metric::operator=, lbann::pearson_correlation_metric::operator=.
virtual lbann::metric::~metric()=default
Destructor.
virtual metric* lbann::metric::copy() const =0
Copy function.
virtual std::string lbann::metric::name() const =0
Return a string name for this metric.
virtual std::string lbann::metric::get_unit() const
Return a display unit for this metric. Default is an empty string. This is overriden if the metric has units, e.g. "%" or "sec".
References lbann::anonymous_namespace{callback_ltfb.cpp}::evaluate.
void lbann::metric::setup(model &m)
Setup metric.
References m_target_layer, lbann::model::get_layers.
Referenced by lbann::categorical_accuracy_metric::setup, lbann::pearson_correlation_metric::setup.
EvalType lbann::metric::evaluate(execution_mode mode, int mini_batch_size)
Evaluate the metric value. This function takes the model's current mini-batch size. If multiple models are being trained, the current mini-batch size may be different from the effective mini-batch size. The result is stored in history.
References m_target_layer, lbann::get_time, evaluate_compute, lbann::generic_target_layer::get_prediction, lbann::generic_target_layer::get_ground_truth, m_evaluate_time, m_statistics.
void lbann::metric::reset_statistics()
Clear all statistics.
void lbann::metric::reset_statistics(execution_mode mode)
Clear statistics for an execution mode.
EvalType lbann::metric::get_mean_value(execution_mode mode) const
Get mean metric value. If mini-batch sizes are not identical, the mean is over the sample values rather than over the mini-batch mean values.
References m_statistics.
int lbann::metric::get_statistics_num_samples(execution_mode mode) const
Get number of samples for statistics.
References m_statistics.
void lbann::metric::set_target_layer(const generic_target_layer *target)
Set pointer to target layer.
const generic_target_layer & lbann::metric::get_target_layer() const
Get target layer.
References m_target_layer.
Referenced by lbann::categorical_accuracy_metric::setup, lbann::pearson_correlation_metric::setup.
std::vector< Layer * > lbann::metric::get_layer_pointers() const
Get list of pointers to layers.
References m_target_layer.
void lbann::metric::set_layer_pointers(std::vector< Layer *> layers)
Set list of pointers to layers.
References m_target_layer.
double lbann::metric::get_evaluate_time() const
Get the time spent in evaluation for this metric.
void lbann::metric::reset_counters()
Reset timing counters.
References prediction.
bool lbann::metric::save_to_checkpoint_shared(persist &p)
Save metric state to checkpoint.
References lbann::persist::get_rank, m_statistics, training, validation, testing.
bool lbann::metric::load_from_checkpoint_shared(persist &p)
Load metric state from checkpoint.
References lbann::persist::get_rank, m_statistics, training, validation, testing.
virtual EvalType lbann::metric::evaluate_compute(const AbsDistMat &prediction, const AbsDistMat &ground_truth)=0
Computation to evaluate the metric function. This should return the sum of metric values across the mini-batch, not the mean value.
Referenced by evaluate.
lbann_comm& lbann::metric::get_comm()
Get LBANN communicator.
Referenced by lbann::boolean_accuracy_metric::evaluate_compute, lbann::boolean_false_negatives_metric::evaluate_compute, lbann::boolean_false_positives_metric::evaluate_compute, lbann::categorical_accuracy_metric::evaluate_compute, lbann::mean_absolute_deviation_metric::evaluate_compute, lbann::mean_squared_error_metric::evaluate_compute, lbann::pearson_correlation_metric::evaluate_compute, lbann::top_k_categorical_accuracy_metric::evaluate_compute.