lbann::ascii_reader
int lbann::ascii_reader::m_sequence_length
Length of text sequence.
Referenced by get_linearized_data_size, get_linearized_label_size, get_data_dims, fetch_datum, fetch_label, load.
int lbann::ascii_reader::m_file_size
Size of data file in bytes.
Referenced by fetch_datum, fetch_label, load.
lbann::ascii_reader::ascii_reader(int sequence_length=1, bool shuffle=true)
Referenced by copy.
lbann::ascii_reader::ascii_reader(const ascii_reader &)=default
ascii_reader& lbann::ascii_reader::operator=(const ascii_reader &)=default
lbann::ascii_reader::~ascii_reader() override=default
ascii_reader* lbann::ascii_reader::copy() const override
References ascii_reader.
std::string lbann::ascii_reader::get_type() const override
Return this data_reader's type
References load.
void lbann::ascii_reader::load() override
Load the dataset. Each data reader implementation should implement this to initialize its internal data structures, determine the number of samples and their dimensionality (if needed), and set up and shuffle samples.
References lbann::generic_data_reader::m_file_dir, lbann::generic_data_reader::get_file_dir, lbann::generic_data_reader::get_data_filename, m_file_size, lbann::generic_data_reader::m_shuffled_indices, m_sequence_length, lbann::generic_data_reader::is_master, lbann::generic_data_reader::select_subset_of_data.
Referenced by get_type.
int lbann::ascii_reader::get_linearized_data_size() const override
Get the linearized size (i.e. number of elements) in a sample.
References m_sequence_length.
int lbann::ascii_reader::get_linearized_label_size() const override
Get the linearized size (i.e. number of elements) in a label.
References m_sequence_length.
const std::vector<int> lbann::ascii_reader::get_data_dims() const override
Get the dimensions of the data.
References m_sequence_length, fetch_datum, fetch_label.
bool lbann::ascii_reader::fetch_datum(Mat &X, int data_id, int mb_idx, int tid) override
Fetch a single sample into a matrix. X The matrix to load data into. data_id The index of the datum to fetch. mb_idx The index within the mini-batch.
References m_sequence_length, m_file_size, lbann::generic_data_reader::get_file_dir, lbann::generic_data_reader::get_data_filename.
Referenced by get_data_dims.
bool lbann::ascii_reader::fetch_label(Mat &Y, int data_id, int mb_idx, int tid) override
Fetch a single label into a matrix. Y The matrix to load data into. data_id The index of the datum to fetch. mb_idx The index within the mini-batch.
References m_sequence_length, m_file_size, lbann::generic_data_reader::get_file_dir, lbann::generic_data_reader::get_data_filename.
Referenced by get_data_dims.