lbann::lbann_callback_checkpoint
std::string lbann::lbann_callback_checkpoint::m_checkpoint_dir
Referenced by set_checkpoint_dir, checkpointShared, restartShared.
int lbann::lbann_callback_checkpoint::m_checkpoint_epochs
Referenced by set_checkpoint_epochs, need_checkpoint.
int lbann::lbann_callback_checkpoint::m_checkpoint_steps
Referenced by set_checkpoint_steps, need_checkpoint.
EvalType lbann::lbann_callback_checkpoint::m_checkpoint_secs
Referenced by set_checkpoint_secs, need_checkpoint.
bool lbann::lbann_callback_checkpoint::m_checkpoint_per_rank
Referenced by set_checkpoint_per_rank, checkpointShared, restartShared.
EvalType lbann::lbann_callback_checkpoint::m_checkpoint_last
Referenced by need_checkpoint, checkpointShared.
bool lbann::lbann_callback_checkpoint::m_epoch_end
Referenced by setup, on_epoch_end, need_checkpoint.
bool lbann::lbann_callback_checkpoint::m_val_end
Referenced by setup, on_epoch_end, on_validation_end, need_checkpoint, checkpointShared.
lbann::lbann_callback_checkpoint::lbann_callback_checkpoint(std::string checkpoint_dir, int checkpoint_epochs, int checkpoint_steps, int checkpoint_secs, bool checkpoint_per_rank)
checkpoint_dir directory to save checkpoint files checkpoint_epochs interval to checkpoint checkpoint_steps interval to checkpoint checkpoint_secs interval to checkpoint checkpoint_per_rank true to save/load a file per mpi rank
References operator=.
Referenced by copy.
lbann::lbann_callback_checkpoint::lbann_callback_checkpoint(const lbann_callback_checkpoint &)=default
lbann_callback_checkpoint& lbann::lbann_callback_checkpoint::operator=(const lbann_callback_checkpoint &)=default
Referenced by lbann_callback_checkpoint.
lbann_callback_checkpoint* lbann::lbann_callback_checkpoint::copy() const override
References lbann_callback_checkpoint, setup, on_epoch_end, on_batch_end, on_validation_end.
void lbann::lbann_callback_checkpoint::setup(model *m) override
Called once to set up the callback (after all layers are set up).
References m_epoch_end, m_val_end, restartShared.
Referenced by copy.
void lbann::lbann_callback_checkpoint::on_epoch_end(model *m) override
Called immediate after the end of each epoch.
References m_epoch_end, m_val_end, need_checkpoint, checkpointShared.
Referenced by copy.
void lbann::lbann_callback_checkpoint::on_batch_end(model *m) override
Called immediately after the end of a (mini-)batch.
References need_checkpoint, checkpointShared.
Referenced by copy.
void lbann::lbann_callback_checkpoint::on_validation_end(model *m) override
Called immediately after the end of validation.
References m_val_end, need_checkpoint, checkpointShared.
Referenced by copy.
void lbann::lbann_callback_checkpoint::set_checkpoint_dir(std::string dir)
References m_checkpoint_dir.
void lbann::lbann_callback_checkpoint::set_checkpoint_epochs(int epochs)
References m_checkpoint_epochs.
void lbann::lbann_callback_checkpoint::set_checkpoint_steps(int steps)
References m_checkpoint_steps.
void lbann::lbann_callback_checkpoint::set_checkpoint_secs(EvalType secs)
References m_checkpoint_secs.
void lbann::lbann_callback_checkpoint::set_checkpoint_per_rank(bool per_rank)
References m_checkpoint_per_rank, need_checkpoint, checkpointShared, restartShared.
bool lbann::lbann_callback_checkpoint::need_checkpoint(model *m)
References m_checkpoint_epochs, m_checkpoint_steps, m_checkpoint_secs, comm, lbann::model::get_comm, m_epoch_end, m_val_end, lbann::model::get_cur_epoch, lbann::model::get_cur_step, lbann::lbann_comm::am_world_master, m_checkpoint_last.
Referenced by set_checkpoint_per_rank, on_epoch_end, on_validation_end, on_batch_end.
bool lbann::lbann_callback_checkpoint::checkpointShared(model *m)
References m_checkpoint_dir, comm, lbann::model::get_comm, lbann::model::get_cur_epoch, lbann::model::get_cur_step, lbann::lbann_comm::am_world_master, lbann::makedir, lbann::persist::open_checkpoint, m_checkpoint_per_rank, m_val_end, lbann::model::save_to_checkpoint_shared, lbann::persist::close_checkpoint, lbann::persist::get_bytes, lbann::write_latest, m_checkpoint_last.
Referenced by set_checkpoint_per_rank, on_epoch_end, on_validation_end, on_batch_end.
bool lbann::lbann_callback_checkpoint::restartShared(model *m)
References m_checkpoint_dir, comm, lbann::model::get_comm, lbann::lbann_comm::am_world_master, lbann::read_latest, lbann::persist::open_restart, m_checkpoint_per_rank, lbann::model::load_from_checkpoint_shared, lbann::persist::close_restart, lbann::persist::get_bytes.
Referenced by set_checkpoint_per_rank, setup.
std::string lbann::lbann_callback_checkpoint::name() const override
Return this callback's name.