lbann::partitioned_io_buffer
Mat* lbann::partitioned_io_buffer::M_local
Referenced by set_local_matrix_bypass, fetch_to_local_matrix.
lbann::partitioned_io_buffer::partitioned_io_buffer(lbann_comm *comm, int num_parallel_readers, std::map< execution_mode, generic_data_reader *> data_readers)
Referenced by copy.
lbann::partitioned_io_buffer::partitioned_io_buffer(const partitioned_io_buffer &)=default
partitioned_io_buffer& lbann::partitioned_io_buffer::operator=(const partitioned_io_buffer &)=default
lbann::partitioned_io_buffer::~partitioned_io_buffer() override
partitioned_io_buffer* lbann::partitioned_io_buffer::copy() const override
References partitioned_io_buffer.
std::string lbann::partitioned_io_buffer::get_type() const override
Return this buffer's type, e.g: "partitioned_io_buffer," "distributed_io_buffer," etc.
void lbann::partitioned_io_buffer::set_local_matrix_bypass(Mat *m) override
References M_local.
void lbann::partitioned_io_buffer::set_std_matrix_view(El::Int cur_mini_batch_size) override
void lbann::partitioned_io_buffer::setup_data(El::Int num_neurons, El::Int max_minibatch_size) override
References fetch_to_local_matrix, distribute_from_local_matrix, is_data_set_processed, calculate_num_iterations_per_epoch_spanning_models, calculate_num_iterations_per_epoch_single_model, compute_max_num_parallel_readers.
int lbann::partitioned_io_buffer::fetch_to_local_matrix(generic_data_reader *data_reader, execution_mode mode) override
References lbann::generic_data_reader::get_num_parallel_readers, lbann::generic_io_buffer::m_comm, lbann::lbann_comm::get_rank_in_model, M_local.
Referenced by setup_data.
void lbann::partitioned_io_buffer::distribute_from_local_matrix(AbsDistMat &Ms, generic_data_reader *data_reader, execution_mode mode) override
Referenced by setup_data.
bool lbann::partitioned_io_buffer::is_data_set_processed(generic_data_reader *data_reader, execution_mode mode) override
References lbann::generic_data_reader::get_num_iterations_per_epoch, lbann::generic_data_reader::get_current_step_in_epoch.
Referenced by setup_data.
void lbann::partitioned_io_buffer::calculate_num_iterations_per_epoch_spanning_models(int max_mini_batch_size, generic_data_reader *data_reader) override
References lbann::generic_data_reader::get_num_data, compute_max_num_parallel_readers, lbann::generic_io_buffer::m_comm, lbann::lbann_comm::get_procs_per_model, lbann::generic_data_reader::set_num_parallel_readers, lbann::lbann_comm::get_num_models, lbann::lbann_comm::get_rank_in_model, lbann::lbann_comm::get_model_rank, lbann::generic_data_reader::set_mini_batch_size, lbann::generic_data_reader::set_stride_to_next_mini_batch, lbann::generic_data_reader::set_sample_stride, lbann::generic_data_reader::set_iteration_stride, lbann::generic_data_reader::set_base_offset, lbann::generic_data_reader::set_model_offset, lbann::generic_data_reader::set_initial_position, lbann::generic_data_reader::set_global_mini_batch_size, lbann::generic_data_reader::set_last_mini_batch_size, lbann::generic_data_reader::set_global_last_mini_batch_size, lbann::generic_data_reader::set_num_iterations_per_epoch, lbann::generic_data_reader::get_last_mini_batch_size, lbann::generic_data_reader::set_stride_to_last_mini_batch, lbann::generic_data_reader::get_stride_to_next_mini_batch, lbann::generic_data_reader::get_base_offset, lbann::generic_data_reader::get_model_offset.
Referenced by setup_data.
void lbann::partitioned_io_buffer::calculate_num_iterations_per_epoch_single_model(int max_mini_batch_size, generic_data_reader *data_reader) override
References lbann::generic_data_reader::get_num_data, compute_max_num_parallel_readers, lbann::generic_io_buffer::m_comm, lbann::lbann_comm::get_procs_per_model, lbann::generic_data_reader::set_num_parallel_readers, lbann::lbann_comm::get_rank_in_model, lbann::generic_data_reader::set_mini_batch_size, lbann::generic_data_reader::set_stride_to_next_mini_batch, lbann::generic_data_reader::set_sample_stride, lbann::generic_data_reader::set_iteration_stride, lbann::generic_data_reader::set_base_offset, lbann::generic_data_reader::set_model_offset, lbann::generic_data_reader::set_initial_position, lbann::generic_data_reader::set_num_iterations_per_epoch, lbann::generic_data_reader::set_last_mini_batch_size, lbann::generic_data_reader::set_stride_to_last_mini_batch, lbann::generic_data_reader::get_stride_to_next_mini_batch, lbann::generic_data_reader::set_global_mini_batch_size, lbann::generic_data_reader::set_global_last_mini_batch_size.
Referenced by setup_data.
int lbann::partitioned_io_buffer::compute_max_num_parallel_readers(long data_set_size, int mini_batch_size, int requested_num_parallel_readers) const override
References lbann::generic_io_buffer::m_comm, lbann::lbann_comm::get_procs_per_model, lbann::lbann_comm::am_model_master.
Referenced by setup_data, calculate_num_iterations_per_epoch_spanning_models, calculate_num_iterations_per_epoch_single_model.