lbann::io_layer
bool lbann::io_layer::m_data_set_spans_models
Referenced by lbann::generic_input_layer::setup_data.
bool lbann::io_layer::m_for_regression
Referenced by is_for_regression.
lbann::io_layer::io_layer(lbann_comm *comm, bool data_set_spans_models=true, bool for_regression=false)
References get_dataset, select_dataset, select_first_valid_dataset, select_data_reader, update_num_samples_processed, get_sample_indices_per_mb, get_data_dims, get_topo_description, get_linearized_data_size, get_linearized_label_size, get_linearized_response_size, get_num_samples_trained, get_num_samples_tested, get_total_num_training_samples, get_total_num_testing_samples, at_new_epoch, is_execution_mode_valid, lbann::persist::get_rank, lbann::persist::write_uint64, lbann::train, lbann::persist::read_uint64.
virtual dataset& lbann::io_layer::get_dataset(execution_mode m)=0
Return the dataset for the given execution mode.
Referenced by io_layer.
virtual const dataset& lbann::io_layer::get_dataset(execution_mode m) const =0
virtual dataset& lbann::io_layer::select_dataset()=0
Return the dataset associated with the current execution mode.
Referenced by io_layer.
virtual const dataset& lbann::io_layer::select_dataset() const =0
virtual dataset* lbann::io_layer::select_first_valid_dataset()=0
Return the first dataset with a valid (non-null) datareader. Returns null if none are valid.
Referenced by io_layer.
virtual generic_data_reader* lbann::io_layer::select_data_reader() const =0
Return the data reader associated with the current execution mode.
Referenced by io_layer.
virtual long lbann::io_layer::update_num_samples_processed(long num_samples)=0
Update the number of samples processed for the current execution mode.
Referenced by io_layer.
El::Matrix<El::Int>* lbann::io_layer::get_sample_indices_per_mb() override=0
Return the sample indices fetched in the current mini-batch.
Referenced by io_layer.
virtual const std::vector<int> lbann::io_layer::get_data_dims() const =0
Get the dimensions of the underlying data.
Referenced by io_layer.
std::string lbann::io_layer::get_topo_description() const override=0
Get a human-readable description of the activation tensors. Activation tensors are stored in distributed matrices where each column corresponds to a mini-batch sample. Within each column, the data is packed w.r.t. the last tensor dimension, then w.r.t. the penultimate dimension, and so on. 3D tensors are assumed to be 2D images in NCHW format.
Referenced by io_layer.
virtual long lbann::io_layer::get_linearized_data_size() const =0
Get the linearized size of the underlying data.
Referenced by io_layer.
virtual long lbann::io_layer::get_linearized_label_size() const =0
Get the linearized size of the labels for the underlying data.
Referenced by io_layer.
virtual long lbann::io_layer::get_linearized_response_size() const =0
Referenced by io_layer.
virtual long lbann::io_layer::get_num_samples_trained() const =0
Referenced by io_layer.
virtual long lbann::io_layer::get_num_samples_tested() const =0
Referenced by io_layer.
virtual long lbann::io_layer::get_total_num_training_samples() const =0
Referenced by io_layer.
virtual long lbann::io_layer::get_total_num_testing_samples() const =0
Referenced by io_layer.
virtual bool lbann::io_layer::at_new_epoch() const =0
Referenced by io_layer.
virtual bool lbann::io_layer::is_execution_mode_valid(execution_mode mode) const =0
Referenced by io_layer.
bool lbann::io_layer::is_for_regression() const
References m_for_regression.
Referenced by lbann::generic_input_layer::get_linearized_label_size, lbann::generic_input_layer::get_linearized_response_size, lbann::generic_target_layer::setup_dims, lbann::target_layer< T_io_buffer, T_layout >::target_layer, lbann::proto::anonymous_namespace{layer_graph_factory.cpp}::setup_target_pointers.