lbann::objective_function_term
EvalType lbann::objective_function_term::m_scale_factor
Scaling factor for objective function term.
Referenced by lbann::kl_divergence::finish_evaluation, lbann::kl_divergence::differentiate, lbann::layer_term::setup, lbann::layer_term::finish_evaluation, lbann::layer_term::differentiate, lbann::loss_function::finish_evaluation, lbann::loss_function::differentiate, objective_function_term, lbann::group_lasso_weight_regularization::finish_evaluation, lbann::group_lasso_weight_regularization::compute_weight_regularization, lbann::l1_weight_regularization::finish_evaluation, lbann::l1_weight_regularization::compute_weight_regularization, lbann::l2_weight_regularization::start_evaluation, lbann::l2_weight_regularization::finish_evaluation, lbann::l2_weight_regularization::compute_weight_regularization.
std::vector<Layer*> lbann::objective_function_term::m_layers
Layers used to compute objective function term.
Referenced by get_layer_pointers, set_layer_pointers, lbann::layer_term::set_evaluation_layer, lbann::layer_term::setup, lbann::layer_term::finish_evaluation, lbann::layer_term::differentiate, lbann::loss_function::set_target_layer, lbann::loss_function::setup, lbann::loss_function::start_evaluation, lbann::loss_function::finish_evaluation, lbann::loss_function::differentiate, lbann::group_lasso_weight_regularization::setup, lbann::l1_weight_regularization::setup, lbann::l2_weight_regularization::setup.
std::vector<weights*> lbann::objective_function_term::m_weights
Weights used to compute objective function term.
Referenced by get_weights_pointers, set_weights_pointers, lbann::loss_function::setup, lbann::group_lasso_weight_regularization::setup, lbann::group_lasso_weight_regularization::finish_evaluation, lbann::group_lasso_weight_regularization::compute_weight_regularization, lbann::l1_weight_regularization::setup, lbann::l1_weight_regularization::finish_evaluation, lbann::l1_weight_regularization::compute_weight_regularization, lbann::l2_weight_regularization::setup, lbann::l2_weight_regularization::start_evaluation, lbann::l2_weight_regularization::finish_evaluation, lbann::l2_weight_regularization::compute_weight_regularization.
lbann_comm* lbann::objective_function_term::m_comm
LBANN communicator.
Referenced by get_comm, setup.
lbann::objective_function_term::objective_function_term(EvalType scale_factor=EvalType(1))
Default constructor.
References m_scale_factor.
lbann::objective_function_term::objective_function_term(const objective_function_term &other)=default
Copy constructor.
objective_function_term& lbann::objective_function_term::operator=(const objective_function_term &other)=default
Copy assignment operator.
Referenced by lbann::loss_function::operator=.
virtual lbann::objective_function_term::~objective_function_term()=default
Destructor.
virtual objective_function_term* lbann::objective_function_term::copy() const =0
Copy function.
virtual std::string lbann::objective_function_term::name() const =0
Get the name of the objective function term.
void lbann::objective_function_term::setup(model &m)
Setup objective function term.
References m_comm, lbann::model::get_comm.
Referenced by lbann::kl_divergence::setup, lbann::layer_term::setup, lbann::loss_function::setup, lbann::group_lasso_weight_regularization::setup, lbann::l1_weight_regularization::setup, lbann::l2_weight_regularization::setup.
virtual void lbann::objective_function_term::start_evaluation()=0
Start evaluation of the objective function term. This should include the scaling factor. The result is not available until finish_evaluation has been called.
virtual EvalType lbann::objective_function_term::finish_evaluation()=0
Complete evaluation of the objective function term.
virtual void lbann::objective_function_term::differentiate()=0
Compute the gradient of the objective function term. The gradient is computed w.r.t. the objective function term inputs. This should include the scaling factor.
virtual void lbann::objective_function_term::compute_weight_regularization()=0
Compute the gradient of the weight regularization term. The gradient is computed w.r.t. the weights.
bool lbann::objective_function_term::save_to_checkpoint_shared(lbann::persist &p)
bool lbann::objective_function_term::load_from_checkpoint_shared(lbann::persist &p)
std::vector<Layer*> lbann::objective_function_term::get_layer_pointers() const
Get list of pointers to layers.
References m_layers.
void lbann::objective_function_term::set_layer_pointers(std::vector< Layer *> layers)
Set list of pointers to layers.
References m_layers.
std::vector<weights*> lbann::objective_function_term::get_weights_pointers() const
Get list of pointers to weights.
References m_weights.
void lbann::objective_function_term::set_weights_pointers(std::vector< weights *> w)
Set list of pointers to weights.
References m_weights.
lbann_comm& lbann::objective_function_term::get_comm()
Get LBANN communicator.
References m_comm.
Referenced by lbann::mean_absolute_deviation_loss::finish_evaluate_compute, lbann::mean_squared_error_loss::start_evaluate_compute, lbann::mean_squared_error_loss::finish_evaluate_compute, lbann::kl_divergence::finish_evaluation, lbann::cross_entropy::start_evaluate_compute, lbann::cross_entropy::finish_evaluate_compute, lbann::cross_entropy_with_uncertainty::finish_evaluate_compute, lbann::geom_negloglike::finish_evaluate_compute, lbann::mean_absolute_error_loss::finish_evaluate_compute, lbann::poisson_negloglike::finish_evaluate_compute, lbann::polya_negloglike::finish_evaluate_compute, lbann::group_lasso_weight_regularization::finish_evaluation, lbann::group_lasso_weight_regularization::compute_weight_regularization, lbann::l1_weight_regularization::finish_evaluation, lbann::l2_weight_regularization::start_evaluation, lbann::l2_weight_regularization::finish_evaluation.