lbann::imagenet_reader_patches
int lbann::imagenet_reader_patches::m_num_patches
number of patches extracted
Referenced by get_linearized_data_size, get_data_dims, imagenet_reader_patches, operator=, set_defaults, replicate_processor, create_datum_views.
std::vector<std::unique_ptr<cv_process_patches> > lbann::imagenet_reader_patches::m_pps
preprocessor for patches duplicated for each omp thread
Referenced by imagenet_reader_patches, operator=, replicate_processor, fetch_datum.
lbann::imagenet_reader_patches::imagenet_reader_patches(bool shuffle)=delete
Referenced by copy.
lbann::imagenet_reader_patches::imagenet_reader_patches(const std::shared_ptr< cv_process_patches > &pp, bool shuffle=true)
References set_defaults, get_type, replicate_processor.
lbann::imagenet_reader_patches::imagenet_reader_patches(const imagenet_reader_patches &)
References m_pps, get_type, m_num_patches, replicate_processor.
imagenet_reader_patches & lbann::imagenet_reader_patches::operator=(const imagenet_reader_patches &)
References lbann::image_data_reader::operator=, m_pps, get_type, m_num_patches, replicate_processor.
lbann::imagenet_reader_patches::~imagenet_reader_patches() override
imagenet_reader_patches* lbann::imagenet_reader_patches::copy() const override
References imagenet_reader_patches.
std::string lbann::imagenet_reader_patches::get_type() const override
Return this data_reader's type
Referenced by imagenet_reader_patches, operator=, replicate_processor, fetch_datum.
int lbann::imagenet_reader_patches::get_linearized_data_size() const override
Get the total number of channel values in a sample of image(s).
References lbann::image_data_reader::m_image_linearized_size, m_num_patches.
const std::vector<int> lbann::imagenet_reader_patches::get_data_dims() const override
Get the dimensions of the data.
References m_num_patches, lbann::image_data_reader::m_image_num_channels, lbann::image_data_reader::m_image_height, lbann::image_data_reader::m_image_width, setup_data_store, set_defaults, replicate_processor, create_datum_views, fetch_datum.
void lbann::imagenet_reader_patches::setup_data_store(model *m) override
sets up a data_store.
References lbann::generic_data_reader::m_data_store, lbann::generic_data_store::setup.
Referenced by get_data_dims.
void lbann::imagenet_reader_patches::set_defaults() override
Set the default values for the width, the height, the number of channels, and the number of labels of an image.
References lbann::image_data_reader::m_image_width, lbann::image_data_reader::m_image_height, lbann::image_data_reader::m_image_num_channels, lbann::image_data_reader::set_linearized_image_size, lbann::image_data_reader::m_num_labels, m_num_patches.
Referenced by get_data_dims, imagenet_reader_patches.
bool lbann::imagenet_reader_patches::replicate_processor(const cv_process_patches &pp)
Replicate image processor for each OpenMP thread.
References m_pps, get_type, m_num_patches, lbann::image_data_reader::m_image_width, lbann::image_data_reader::m_image_height, lbann::image_data_reader::set_linearized_image_size, lbann::image_data_reader::m_num_labels.
Referenced by get_data_dims, imagenet_reader_patches, operator=.
std::vector<::Mat > lbann::imagenet_reader_patches::create_datum_views(::Mat &X, const int mb_idx) const
References m_num_patches, lbann::image_data_reader::m_image_linearized_size.
Referenced by get_data_dims, fetch_datum.
bool lbann::imagenet_reader_patches::fetch_datum(::Mat &X, int data_id, int mb_idx, int tid) override
References lbann::generic_data_reader::get_file_dir, lbann::image_data_reader::m_image_list, create_datum_views, lbann::generic_data_reader::m_data_store, lbann::generic_data_store::get_data_buf, lbann::image_utils::load_image, m_pps, get_type, lbann::image_data_reader::m_image_linearized_size.
Referenced by get_data_dims.