lbann::cross_entropy
EvalType lbann::cross_entropy::m_sum
Sum of the cross-entropy terms.
Referenced by start_evaluate_compute, finish_evaluate_compute.
Al::request lbann::cross_entropy::m_allreduce_req
Non-blocking allreduce request.
Referenced by start_evaluate_compute, finish_evaluate_compute.
lbann::cross_entropy::cross_entropy(EvalType scale_factor=EvalType(1))
Default constructor.
References operator=, ~cross_entropy.
Referenced by copy.
lbann::cross_entropy::cross_entropy(const cross_entropy &other)=default
Copy constructor.
cross_entropy& lbann::cross_entropy::operator=(const cross_entropy &other)=default
Copy assignment operator.
Referenced by cross_entropy.
lbann::cross_entropy::~cross_entropy() override=default
Destructor.
Referenced by cross_entropy.
cross_entropy* lbann::cross_entropy::copy() const override
Copy function.
References cross_entropy.
std::string lbann::cross_entropy::name() const override
Get the name of the objective function term.
References start_evaluate_compute, prediction, finish_evaluate_compute, differentiate_compute.
void lbann::cross_entropy::start_evaluate_compute(const AbsDistMat &prediction, const AbsDistMat &ground_truth) override
Compute the cross entropy objective function. Given a predicted distribution $y$ and ground truth distribution $\hat{y}$, the cross entropy is \[ CE(y,\hat{y}) = - \sum\limits_{i} \hat{y}_i \log y_i \] This function updates the objective function value with the mean cross entropy across the mini-batch. Note that each column of the predictions and ground truth matrices should have non-negative entries that add up to one.
References m_sum, lbann::objective_function_term::get_comm, lbann::lbann_comm::nb_allreduce, m_allreduce_req.
Referenced by name.
EvalType lbann::cross_entropy::finish_evaluate_compute(const AbsDistMat &prediction, const AbsDistMat &ground_truth) override
Finish evaluation of the loss function. This should not include the scale factor.
References lbann::objective_function_term::get_comm, lbann::lbann_comm::wait, m_allreduce_req, m_sum.
Referenced by name.
void lbann::cross_entropy::differentiate_compute(const AbsDistMat &prediction, const AbsDistMat &ground_truth, AbsDistMat &gradient) override
Compute the gradient of the cross entropy objective function. Given a predicted distribution $y$ and ground truth distribution $\hat{y}$, the gradient of the cross entropy is \[ \nabla_y CE (y,\hat{y}) = - \hat{y} . / y \]
Referenced by name.