lbann::mean_squared_error_metric
lbann::mean_squared_error_metric::mean_squared_error_metric(lbann_comm *comm)
Constructor.
References operator=, ~mean_squared_error_metric.
Referenced by copy.
lbann::mean_squared_error_metric::mean_squared_error_metric(const mean_squared_error_metric &other)=default
Copy constructor.
mean_squared_error_metric& lbann::mean_squared_error_metric::operator=(const mean_squared_error_metric &other)=default
Copy assignment operator.
Referenced by mean_squared_error_metric.
virtual lbann::mean_squared_error_metric::~mean_squared_error_metric()=default
Destructor.
Referenced by mean_squared_error_metric.
mean_squared_error_metric* lbann::mean_squared_error_metric::copy() const override
Copy function.
References mean_squared_error_metric.
std::string lbann::mean_squared_error_metric::name() const override
Return a string name for this metric.
References evaluate_compute, prediction.
EvalType lbann::mean_squared_error_metric::evaluate_compute(const AbsDistMat &prediction, const AbsDistMat &ground_truth) override
Computation to evaluate the metric function. This returns the sum of metric values across the mini-batch, not the mean value.
References lbann::metric::get_comm, lbann::lbann_comm::allreduce.
Referenced by name.