lbann::group_lasso_weight_regularization
lbann::group_lasso_weight_regularization::group_lasso_weight_regularization(EvalType scale_factor=EvalType(1))
Default constructor.
References operator=, ~group_lasso_weight_regularization.
Referenced by copy.
lbann::group_lasso_weight_regularization::group_lasso_weight_regularization(const group_lasso_weight_regularization &other)=default
Copy constructor.
group_lasso_weight_regularization& lbann::group_lasso_weight_regularization::operator=(const group_lasso_weight_regularization &other)=default
Copy assignment operator.
Referenced by group_lasso_weight_regularization.
lbann::group_lasso_weight_regularization::~group_lasso_weight_regularization() override=default
Destructor.
Referenced by group_lasso_weight_regularization.
group_lasso_weight_regularization* lbann::group_lasso_weight_regularization::copy() const override
Copy function.
References group_lasso_weight_regularization.
std::string lbann::group_lasso_weight_regularization::name() const override
Get the name of the objective function term.
References setup, start_evaluation, finish_evaluation.
void lbann::group_lasso_weight_regularization::setup(model &m) override
Setup group lasso regularization term.
References lbann::objective_function_term::setup, lbann::objective_function_term::m_layers, lbann::objective_function_term::m_weights, lbann::model::get_weights.
Referenced by name.
void lbann::group_lasso_weight_regularization::start_evaluation() override
Start evaluation of the objective function term. This should include the scaling factor. The result is not available until finish_evaluation has been called.
Referenced by name.
EvalType lbann::group_lasso_weight_regularization::finish_evaluation() override
Get the value of the group lasso regularization term.
References lbann::objective_function_term::m_scale_factor, lbann::objective_function_term::m_weights, lbann::objective_function_term::get_comm, lbann::lbann_comm::allreduce.
Referenced by name.
void lbann::group_lasso_weight_regularization::differentiate() override
Weight regularization terms are not applied to the objective functions w.r.t. the activations
References compute_weight_regularization.
void lbann::group_lasso_weight_regularization::compute_weight_regularization() override
Compute the gradient of the group lasso regularization term. The gradient is computed w.r.t. the weights.
References lbann::objective_function_term::m_scale_factor, lbann::objective_function_term::m_weights, lbann::objective_function_term::get_comm, lbann::lbann_comm::allreduce.
Referenced by differentiate.