lbann::l2_weight_regularization
std::vector<EvalType> lbann::l2_weight_regularization::m_sqsums
Holds intermediate terms for each weights.
Referenced by setup, start_evaluation, finish_evaluation.
std::vector<Al::request> lbann::l2_weight_regularization::m_allreduce_reqs
Holds an allreduce request for each weights.
Referenced by setup, start_evaluation, finish_evaluation.
std::vector<bool> lbann::l2_weight_regularization::m_allreduce_started
Whether an allreduce is needed for each weights.
Referenced by setup, start_evaluation, finish_evaluation.
lbann::l2_weight_regularization::l2_weight_regularization(EvalType scale_factor=EvalType(1))
Referenced by copy.
l2_weight_regularization* lbann::l2_weight_regularization::copy() const override
Copy function.
References l2_weight_regularization.
std::string lbann::l2_weight_regularization::name() const override
Get the name of the objective function term.
References setup, start_evaluation, finish_evaluation.
void lbann::l2_weight_regularization::setup(model &m) override
Setup objective function term.
References lbann::objective_function_term::setup, lbann::objective_function_term::m_layers, LBANN_ERROR, lbann::objective_function_term::m_weights, lbann::model::get_weights, m_sqsums, m_allreduce_started, m_allreduce_reqs.
Referenced by name.
void lbann::l2_weight_regularization::start_evaluation() override
Start evaluation of the objective function term. This should include the scaling factor. The result is not available until finish_evaluation has been called.
References lbann::objective_function_term::m_scale_factor, lbann::objective_function_term::m_weights, m_sqsums, m_allreduce_started, anonymous_namespace{l2.cpp}::sum_of_squares, lbann::objective_function_term::get_comm, lbann::lbann_comm::nb_allreduce, m_allreduce_reqs.
Referenced by name.
EvalType lbann::l2_weight_regularization::finish_evaluation() override
Complete evaluation of the objective function term.
References lbann::objective_function_term::m_scale_factor, lbann::objective_function_term::m_weights, m_allreduce_started, lbann::objective_function_term::get_comm, lbann::lbann_comm::wait, m_allreduce_reqs, m_sqsums.
Referenced by name.
void lbann::l2_weight_regularization::differentiate() override
Compute the gradient w.r.t. the activations. L2 weight regularization is independent of the activations.
References compute_weight_regularization.
void lbann::l2_weight_regularization::compute_weight_regularization() override
Compute the gradient w.r.t. the weights. The gradient w.r.t. the weights is \[ \nabla_w L2(w) = w \]
References lbann::objective_function_term::m_scale_factor, lbann::objective_function_term::m_weights.
Referenced by differentiate.