lbann::data_store_imagenet
lbann::data_store_imagenet::data_store_imagenet(generic_data_reader *reader, model *m)
ctor
References operator=.
Referenced by copy.
lbann::data_store_imagenet::data_store_imagenet(const data_store_imagenet &)=default
copy ctor
data_store_imagenet& lbann::data_store_imagenet::operator=(const data_store_imagenet &)=default
operator=
Referenced by data_store_imagenet.
data_store_imagenet* lbann::data_store_imagenet::copy() const override
References data_store_imagenet.
lbann::data_store_imagenet::~data_store_imagenet() override
dtor
References setup, get_file_sizes, test_data, test_file_sizes, read_files.
void lbann::data_store_imagenet::setup() override
called by generic_data_reader::setup_data_store
References lbann::get_time, lbann::generic_data_store::m_rank, lbann::generic_data_store::m_reader, lbann::generic_data_reader::get_role, lbann::generic_data_store::set_name, options::get, options::has_bool, options::get_bool, options::set_option, lbann::generic_data_store::m_in_memory, lbann::data_store_image::setup, test_file_sizes, test_data.
Referenced by ~data_store_imagenet, lbann::data_store_imagenet_patches::setup, lbann::data_store_multi_images::setup.
void lbann::data_store_imagenet::get_file_sizes() override
fills in m_file_sizes
References lbann::generic_data_store::m_master, lbann::generic_data_store::m_reader, lbann::image_data_reader::get_image_list, lbann::generic_data_store::m_my_datastore_indices, lbann::generic_data_store::get_file_size, lbann::generic_data_store::m_dir, lbann::generic_data_store::m_rank, lbann::data_store_image::exchange_file_sizes, lbann::generic_data_store::m_num_global_indices.
Referenced by ~data_store_imagenet.
void lbann::data_store_imagenet::test_data()
for use during development and testing
References lbann::generic_data_store::m_reader, lbann::image_data_reader::get_image_list, lbann::generic_data_store::m_my_minibatch_indices_v, lbann::generic_data_store::m_dir, lbann::data_store_image::get_data_buf, lbann::generic_data_store::m_rank, lbann::generic_data_reader::get_role.
Referenced by ~data_store_imagenet, setup.
void lbann::data_store_imagenet::test_file_sizes()
for use during development and testing
References lbann::generic_data_store::m_master, lbann::generic_data_store::m_rank, lbann::generic_data_store::m_reader, lbann::image_data_reader::get_image_list, lbann::data_store_image::m_file_sizes, lbann::generic_data_store::get_file_size, lbann::generic_data_store::m_dir, lbann::generic_data_reader::get_role.
Referenced by ~data_store_imagenet, setup.
void lbann::data_store_imagenet::read_files() override
reads all files assigned to this processor into memory (m_data)
References lbann::generic_data_store::m_reader, lbann::image_data_reader::get_image_list, lbann::generic_data_store::m_my_datastore_indices, lbann::data_store_image::m_offsets, lbann::data_store_image::m_file_sizes, lbann::data_store_image::m_data, lbann::generic_data_store::m_my_minibatch_indices_v, lbann::data_store_image::load_file, lbann::generic_data_store::m_dir.
Referenced by ~data_store_imagenet.