lbann::lbann_quantizer
using lbann::lbann_quantizer::uqtype = El::Unsigned
We require that sizeof(DataType) <= sizeof(qtype) == sizeof(uqtype).
using lbann::lbann_quantizer::qtype = El::Int
using lbann::lbann_quantizer::QuantizedMatrix = El::Matrix<qtype>
This represents a quantized version of a matrix. Each column is quantized separately. The first two entries are floats representing the positive and negative averages for the column (used in dequantizion). The rest is one-bit quantized entries. Quantization is by column to keep averages nice and because Elemental uses column-major ordering.
using lbann::lbann_quantizer::ThreshQuantized = std::vector<uqtype>
using lbann::lbann_quantizer::ThreshQuantized32 = std::vector<uint32_t>
using lbann::lbann_quantizer::ThreshQuantized64 = std::vector<uint64_t>
const size_t lbann::lbann_quantizer::NUM_BITS
Number of bits per quantized word.
Referenced by onebit_quantize, onebit_unquantize, onebit_unquantize_add.
const El::Int lbann::lbann_quantizer::NUM_THRESHOLD_SAMPLES
Number of samples to use in proportion_threshold.
Referenced by proportion_threshold.
const El::Int lbann::lbann_quantizer::NUM_RECON_SAMPLES
Number of samples to use in col_reconstruction.
Referenced by col_reconstruction.
const El::Int lbann::lbann_quantizer::NUM_ONEBIT_SAMPLES
Samples to use to approximate column averages in onebit quantization.
Referenced by onebit_quantize.
const int lbann::lbann_quantizer::HEADER_FACTOR
Factor used when computing header lengths in adaptive quantization.
Referenced by adaptive_quantize, adaptive_unquantize, adaptive_unquantize_add, adaptive_quantize_replace, adaptive_bound, adaptive_quantize_slice, intermodel_sum_adaptive_quantized_impl.
const El::Int lbann::lbann_quantizer::MAX_QUANTIZED_EXCESS
Max factor by which adaptive quantization can exceed optimal amount.
Referenced by adaptive_bound, intermodel_sum_adaptive_quantized_impl.
double lbann::lbann_quantizer::proportion_time
Time spent in proportion_threshold.
Referenced by get_proportion_time, reset_counters, proportion_threshold.
size_t lbann::lbann_quantizer::quantized_count
Most recent number of quantized entries.
Referenced by reset_counters, get_quantized_count, adaptive_quantize, adaptive_quantize_replace.
lbann::lbann_quantizer::lbann_quantizer()
References reset_counters.
lbann::lbann_quantizer::~lbann_quantizer()
void lbann::lbann_quantizer::onebit_quantize(const Mat &mat, QuantizedMatrix &qmat, Mat &qerror, bool sample=true)
Quantize a matrix with onebit quantization. qerror needs to be initialized with: Zeros(qerror, mat.Height(), mat.Width()). mat The matrix to quantize. qmat The output quantized matrix (will be resized). qerror Running quantization error. sample Whether to use samples to approximate averages.
References get_onebit_quantized_matrix_height, NUM_ONEBIT_SAMPLES, lbann::get_fast_generator, lbann::fast_rand_int, NUM_BITS.
Referenced by onebit_quantize, intermodel_sum_onebit_quantized.
void lbann::lbann_quantizer::onebit_quantize(const DistMat &mat, QuantizedMatrix &qmat, Mat &qerror, bool sample=true)
References onebit_quantize.
void lbann::lbann_quantizer::onebit_unquantize(const QuantizedMatrix &qmat, Mat &mat)
Unquantize a onebit-quantized matrix.. qmat The matrix to unquantize. mat The output unquantized matrix.
References NUM_BITS.
Referenced by onebit_unquantize, intermodel_sum_onebit_quantized.
void lbann::lbann_quantizer::onebit_unquantize(const QuantizedMatrix &qmat, DistMat &mat)
References onebit_unquantize.
void lbann::lbann_quantizer::intermodel_sum_onebit_quantized(lbann_comm *comm, Mat &mat, Mat &qerror)
Do a sum reduction of mat over comm's inter-model communicator, with all communication being quantized. im_querror is a separate quantization error matrix that should be passed in each time this is called. This implements the allreduce using a ring-based reduce-scatter followed by a ring-based allgather. Matrices are sent quantized, are unquantized for the reduction, then the reduced matrix is requantized for the allgather. If do_adagrad is true, this scales the inter-mediate unquantized result as in AdaGrad, and uses gradhist to store the gradient history. If used, you should use SGD as the optimizer for those layers to avoid applying AdaGrad twice.
References onebit_quantize, onebit_unquantize, get_onebit_quantized_matrix_height, onebit_unquantize_add, lbann::lbann_comm::allreduce_options::max_reduces, lbann::lbann_comm::intermodel_allreduce.
Referenced by lbann::lbann_callback_imcomm::on_backward_prop_end, intermodel_sum_onebit_quantized.
void lbann::lbann_quantizer::intermodel_sum_onebit_quantized(lbann_comm *comm, DistMat &mat, Mat &qerror)
References intermodel_sum_onebit_quantized.
void lbann::lbann_quantizer::threshold_quantize(const Mat &mat, ThreshQuantized &q, Mat &qerror, DataType pos_thresh, DataType neg_thresh, bool delta=false)
Threshold and quantize a matrix. qerror needs to be initialized with: Zeros(qerror, mat.Height(), mat.Width())). mat The matrix to quantize. q The output list of quantized entries. qerror Running quantization error. pos_thresh The positive threshold level. neg_thresh The negative threshold level. delta Whether to do delta encoding (default false).
Referenced by threshold_quantize.
void lbann::lbann_quantizer::threshold_quantize(const DistMat &mat, ThreshQuantized &q, Mat &qerror, DataType pos_thresh, DataType neg_thresh, bool delta=false)
References threshold_quantize.
void lbann::lbann_quantizer::threshold_unquantize(const ThreshQuantized &q, Mat &mat, DataType pos_thresh, DataType neg_thresh, bool delta=false)
Unquantize a thresholded-and-quantized matrix. q The quantized matrix. mat The output unquantized matrix. pos_thresh The positive threshold value. neg_thresh The negative negative value. delta Whether q was quantized with delta encoding (default false).
Referenced by threshold_unquantize.
void lbann::lbann_quantizer::threshold_unquantize(const ThreshQuantized &q, DistMat &mat, DataType pos_thresh, DataType neg_thresh, bool delta=false)
References threshold_unquantize.
void lbann::lbann_quantizer::intermodel_sum_threshold_quantized(lbann_comm *comm, Mat &mat, Mat &qerror, DataType pos_thresh, DataType neg_thresh)
As with intermodel_sum_onebit_quantized, but use threshold quantization.
Referenced by lbann::lbann_callback_imcomm::on_backward_prop_end, intermodel_sum_threshold_quantized.
void lbann::lbann_quantizer::intermodel_sum_threshold_quantized(lbann_comm *comm, DistMat &mat, Mat &qerror, DataType pos_thresh, DataType neg_thresh)
References intermodel_sum_threshold_quantized.
void lbann::lbann_quantizer::adaptive_quantize(const Mat &mat, std::vector< rowT > &q, Mat &qerror, int proportion)
Adaptively quantize a matrix. qerror needs to be initialized with: Zeros(qerror, mat.Height(), mat.Width()). mat The matrix to quantize. q The output list of quantized entries. qerror Running quantization error. proportion Quantize one in proportion of the values.
References HEADER_FACTOR, get_adaptive_quantization_threads, proportion_threshold, col_reconstruction, lbann::lbann_quantizer::adaptive_reconstructions::pos_recon, lbann::lbann_quantizer::adaptive_reconstructions::neg_recon, lbann::lbann_quantizer::adaptive_thresholds::pos_thresh, lbann::lbann_quantizer::adaptive_thresholds::neg_thresh, get_adaptive_quantization_copy_threads, quantized_count.
void lbann::lbann_quantizer::adaptive_quantize(const DistMat &mat, std::vector< rowT > &q, Mat &qerror, int proportion)
void lbann::lbann_quantizer::adaptive_unquantize(const rowT *q, Mat &mat)
Unquantize an adaptively-quantized matrix. q The quantizd matrix. mat The output unquantized matrix.
References HEADER_FACTOR, get_adaptive_quantization_threads.
void lbann::lbann_quantizer::adaptive_unquantize(const rowT *q, DistMat &mat)
void lbann::lbann_quantizer::intermodel_sum_adaptive_quantized(lbann_comm *comm, Mat &mat, Mat &qerror, int proportion)
As with intermodel_sum_onebit_quantized, but use adaptive quantization.
References comm.
Referenced by lbann::lbann_callback_imcomm::on_backward_prop_end, intermodel_sum_adaptive_quantized.
void lbann::lbann_quantizer::intermodel_sum_adaptive_quantized(lbann_comm *comm, DistMat &mat, Mat &qerror, int proportion)
References intermodel_sum_adaptive_quantized.
lbann_quantizer::adaptive_thresholds lbann::lbann_quantizer::proportion_threshold(const Mat &mat, const Mat &qerror, int proportion, bool sample=true)
Compute positive and negative thresholds such that only one in proportion of values in mat are >= to the positive threshold or <= to the negative threshold. mat The matrix to compute threshold values for. qerror The accumulated quantization error in mat. proportion Proportion of entries to keep. sample Whether to approximate stats by randomly sampling mat. The threshold values.
References lbann::get_time, NUM_THRESHOLD_SAMPLES, lbann::get_fast_generator, lbann::fast_rand_int, proportion_time.
Referenced by adaptive_quantize, adaptive_quantize_replace.
lbann_quantizer::adaptive_reconstructions lbann::lbann_quantizer::col_reconstruction(const Mat &mat, const Mat &qerror, El::Int col, const adaptive_thresholds threshes, bool sample=true)
Compute reconstruction values for col. mat The matrix to compute reconstruction values for. qerror The accumulated quantization error in mat. col The column to compute reconstruction values for. ainfo Adaptive quantization info with thresholds filled in. sample Whether to approximate stats by randomly sampling mat. Adaptive reconstruction values.
References NUM_RECON_SAMPLES, lbann::lbann_quantizer::adaptive_thresholds::pos_thresh, lbann::lbann_quantizer::adaptive_thresholds::neg_thresh, lbann::get_fast_generator, lbann::fast_rand_int_pow2, lbann::fast_rand_int.
Referenced by adaptive_quantize, adaptive_quantize_replace.
double lbann::lbann_quantizer::get_proportion_time() const
References proportion_time.
void lbann::lbann_quantizer::reset_counters()
Reset recorded counters.
References proportion_time, quantized_count.
Referenced by lbann::lbann_callback_imcomm::do_summary, lbann_quantizer.
size_t lbann::lbann_quantizer::get_quantized_count() const
Return the most recent number of quantized entries.
References quantized_count.
Referenced by lbann::lbann_callback_imcomm::do_summary.
El::Int lbann::lbann_quantizer::get_onebit_quantized_matrix_height(const Mat &mat) const
Return the height of mat after quantization with onebit_quantize().
References onebit_unquantize_add, threshold_unquantize_apply, lbann::lbann_quantizer::adaptive_thresholds::pos_thresh, lbann::lbann_quantizer::adaptive_thresholds::neg_thresh, threshold_quantize_apply, adaptive_unquantize_add, adaptive_quantize_replace, adaptive_bound, adaptive_quantize_slice, intermodel_sum_adaptive_quantized_impl, comm.
Referenced by onebit_quantize, intermodel_sum_onebit_quantized.
void lbann::lbann_quantizer::onebit_unquantize_add(const QuantizedMatrix &qmat, Mat &mat)
Variant of unquantize that adds its entries.
References NUM_BITS.
Referenced by get_onebit_quantized_matrix_height, intermodel_sum_onebit_quantized.
void lbann::lbann_quantizer::threshold_unquantize_apply(const ThreshQuantized &q, Mat &mat, DataType pos_thresh, DataType neg_thresh, std::vector< El::Unsigned > &positions, bool delta=false)
Do threshold unquantization from arbitrary locations, adding the unquantized values to existing ones instead of replacing them, and storing the locations applied.
Referenced by get_onebit_quantized_matrix_height.
void lbann::lbann_quantizer::threshold_quantize_apply(const Mat &mat, ThreshQuantized &q, Mat &qerror, DataType pos_thresh, DataType neg_thresh, std::vector< El::Unsigned > &positions, bool delta=false)
Quantize only the locations in mat in positions; the companion of threshold_unquantize_apply.
Referenced by get_onebit_quantized_matrix_height.
void lbann::lbann_quantizer::adaptive_unquantize_add(const rowT *q, Mat &mat)
Variant of adaptive_unquantize that adds its entries.
References HEADER_FACTOR, get_adaptive_quantization_threads.
Referenced by get_onebit_quantized_matrix_height.
void lbann::lbann_quantizer::adaptive_quantize_replace(Mat &mat, std::vector< rowT > &q, Mat &qerror, int proportion)
Variant of adaptive_quantize that also replaces entries in mat with their quantized version. This is equivalent to: adaptive_quantize(mat, q, qerror, proportion); adaptive_unquantize(q, mat);
References HEADER_FACTOR, get_adaptive_quantization_threads, proportion_threshold, col_reconstruction, lbann::lbann_quantizer::adaptive_reconstructions::pos_recon, lbann::lbann_quantizer::adaptive_reconstructions::neg_recon, lbann::lbann_quantizer::adaptive_thresholds::pos_thresh, lbann::lbann_quantizer::adaptive_thresholds::neg_thresh, get_adaptive_quantization_copy_threads, quantized_count.
Referenced by get_onebit_quantized_matrix_height.
void lbann::lbann_quantizer::adaptive_bound(const Mat &mat, Mat &qerror, std::vector< rowT > &q, int proportion)
Ensure that q is no more than a factor of MAX_QUANTIZED_EXCESS larger than optimal.
References HEADER_FACTOR, MAX_QUANTIZED_EXCESS.
Referenced by get_onebit_quantized_matrix_height.
void lbann::lbann_quantizer::adaptive_quantize_slice(const std::vector< rowT > &q, const Mat &mat, Mat &qerror, std::vector< rowT > &slice, colT start, colT end, int proportion)
References HEADER_FACTOR.
Referenced by get_onebit_quantized_matrix_height.
void lbann::lbann_quantizer::intermodel_sum_adaptive_quantized_impl(lbann_comm *comm, Mat &mat, Mat &qerror, int proportion)
References HEADER_FACTOR, MAX_QUANTIZED_EXCESS, lbann::lbann_comm::allreduce_options::max_reduces, lbann::lbann_comm::intermodel_allreduce.
Referenced by get_onebit_quantized_matrix_height.
int lbann::lbann_quantizer::get_adaptive_quantization_threads(El::Int width)
Return the number of threads adaptive quantization should use for a matrix with the given width. This number of threads is empirically determined. TodoMake this configurable at compile time.
Referenced by get_adaptive_quantization_copy_threads, adaptive_quantize, adaptive_unquantize, adaptive_unquantize_add, adaptive_quantize_replace.
int lbann::lbann_quantizer::get_adaptive_quantization_copy_threads(El::Int width)
Return the number of threads adaptive quantization uses in its copy loop. This is empirically determined. width The width of the matrix being quantized. TodoMake this configurable at compile time. If this and get_adaptive_quantization_threads return different values for the same width, OpenMP may reap its threads and add additional overhead when invoking a parallel region with more threads.
References get_adaptive_quantization_threads.
Referenced by adaptive_quantize, adaptive_quantize_replace.