lbann::convolution_layer
friend class lbann_callback_imcomm
std::string lbann::convolution_layer< T_layout >::get_description() const override
kernel tensor is output channels, input channels, conv dimension (w x h)
Returns description of ctor params
References lbann::convolution_layer< T_layout >::get_topo_description, lbann::base_convolution_layer::m_pads, lbann::base_convolution_layer::m_strides, lbann::Layer::m_neuron_dims, lbann::base_convolution_layer::m_bias_scaling_factor, lbann::Layer::get_data_layout_string, lbann::convolution_layer< T_layout >::get_data_layout.
std::string lbann::convolution_layer< T_layout >::get_topo_description() const override
Get a human-readable description of the activation tensors. Activation tensors are stored in distributed matrices where each column corresponds to a mini-batch sample. Within each column, the data is packed w.r.t. the last tensor dimension, then w.r.t. the penultimate dimension, and so on. 3D tensors are assumed to be 2D images in NCHW format.
References lbann::Layer::get_topo_description, lbann::base_convolution_layer::m_kernel_dims.
Referenced by lbann::convolution_layer< T_layout >::get_description.
lbann::convolution_layer< T_layout >::convolution_layer(lbann_comm *comm, int num_data_dims, int num_output_channels, int conv_dim, int pad, int stride, bool has_bias=true, cudnn::cudnn_manager *cudnn=nullptr)
Referenced by lbann::convolution_layer< T_layout >::copy.
lbann::convolution_layer< T_layout >::convolution_layer(lbann_comm *comm, int num_data_dims, int num_output_channels, std::vector< int > conv_dims, std::vector< int > pads, std::vector< int > strides, bool has_bias=true, cudnn::cudnn_manager *cudnn=nullptr)
References DATA_PARALLEL, lbann::Layer::m_cudnn, lbann::Layer::m_using_gpus.
convolution_layer* lbann::convolution_layer< T_layout >::copy() const override
Copy function. This function dynamically allocates memory for a layer instance and instantiates a copy. The caller is responsible for deallocating the instance.
References lbann::convolution_layer< T_layout >::convolution_layer.
std::string lbann::convolution_layer< T_layout >::get_type() const override
Get the layer type's name. A layer type name should be brief, human-readable description of the layer's mathematical operation.
data_layout lbann::convolution_layer< T_layout >::get_data_layout() const override
Get data layout of the data tensors. We assume that the data layouts of the previous activations, activations, previous error signals, and error signals are the same. Each concrete layer that is templated on its data layout should override this function to return its template parameter.
Referenced by lbann::convolution_layer< T_layout >::get_description.
void lbann::convolution_layer< T_layout >::setup_dims() override
Setup tensor dimensions Called by the setup function. The base method sets the dimensions of the activation tensors equal to the dimensions of the first previous activation tensor.
References lbann::Layer::setup_dims, lbann::base_convolution_layer::m_kernel_dims, lbann::Layer::m_prev_neuron_dims, lbann::Layer::m_num_neuron_dims, lbann::Layer::m_neuron_dims, lbann::base_convolution_layer::m_pads, lbann::base_convolution_layer::m_strides, lbann::Layer::m_num_neurons, lbann::base_convolution_layer::m_kernel_size.
void lbann::convolution_layer< T_layout >::setup_data() override
Setup layer data. The kernel weights are setup in the convolution and deconvolution classes.
References lbann::base_convolution_layer::setup_data, lbann::Layer::m_weights, lbann::base_convolution_layer::m_kernel_dims, lbann::base_convolution_layer::m_kernel_gradient.
void lbann::convolution_layer< T_layout >::fp_compute() override
Perform the computation for the forward propagation step.
References lbann::Layer::m_using_gpus, lbann::base_convolution_layer::apply_convolution_cudnn, lbann::base_convolution_layer::apply_bias_cudnn, lbann::base_convolution_layer::apply_convolution_im2col, lbann::base_convolution_layer::apply_bias_cpu.
void lbann::convolution_layer< T_layout >::bp_compute() override
Perform the computation for the backward propagation step.
References lbann::Layer::m_using_gpus, lbann::base_convolution_layer::compute_gradients_cudnn, lbann::base_convolution_layer::apply_transposed_convolution_cudnn, lbann::base_convolution_layer::compute_gradients_im2col, lbann::base_convolution_layer::apply_transposed_convolution_im2col.