lbann::lbann_callback
int lbann::lbann_callback::m_batch_interval
Batch methods should once every this many steps.
Referenced by get_batch_interval.
lbann_summary* lbann::lbann_callback::m_summarizer
Optional summarizer for the callbacks to use.
Referenced by set_summarizer, lbann::lbann_callback_imcomm::do_summary, lbann::lbann_callback_summary::~lbann_callback_summary, lbann::lbann_callback_summary::on_batch_end, lbann::lbann_callback_summary::on_epoch_end, lbann::lbann_callback_summary::on_test_end, lbann::lbann_callback_summary::save_histograms, lbann::lbann_callback_timer::batch_timing_end.
lbann::lbann_callback::lbann_callback(int batch_interval=1, lbann_summary *summarizer=nullptr)
Initialize a callback with an optional batch interval and summarizer.
References max, operator=.
lbann::lbann_callback::lbann_callback(const lbann_callback &)=default
lbann_callback& lbann::lbann_callback::operator=(const lbann_callback &)=default
Referenced by lbann_callback.
virtual lbann::lbann_callback::~lbann_callback()
References copy.
virtual lbann_callback* lbann::lbann_callback::copy() const =0
Referenced by ~lbann_callback.
void lbann::lbann_callback::set_summarizer(lbann_summary *summarizer)
References m_summarizer.
virtual void lbann::lbann_callback::setup(model *m)
Called once to set up the callback (after all layers are set up).
virtual void lbann::lbann_callback::on_train_begin(model *m)
Called at the beginning of training.
virtual void lbann::lbann_callback::on_train_end(model *m)
Called at the end of training.
virtual void lbann::lbann_callback::on_phase_end(model *m)
Called at the end of every phase (multiple epochs) in a layer-wise model training
virtual void lbann::lbann_callback::on_epoch_begin(model *m)
Called at the beginning of each epoch.
virtual void lbann::lbann_callback::on_epoch_end(model *m)
Called immediate after the end of each epoch.
virtual void lbann::lbann_callback::on_batch_begin(model *m)
Called at the beginning of a (mini-)batch.
virtual void lbann::lbann_callback::on_batch_end(model *m)
Called immediately after the end of a (mini-)batch.
virtual void lbann::lbann_callback::on_test_begin(model *m)
Called at the beginning of testing.
virtual void lbann::lbann_callback::on_test_end(model *m)
Called immediately after the end of testing.
virtual void lbann::lbann_callback::on_validation_begin(model *m)
Called at the beginning of validation.
virtual void lbann::lbann_callback::on_validation_end(model *m)
Called immediately after the end of validation.
virtual void lbann::lbann_callback::on_forward_prop_begin(model *m)
Called when a model begins forward propagation.
Referenced by lbann::lbann_callback_timeline::name.
virtual void lbann::lbann_callback::on_forward_prop_begin(model *m, Layer *l)
Called when a layer begins forward propagation.
virtual void lbann::lbann_callback::on_forward_prop_end(model *m)
Called when a model ends forward propagation.
Referenced by lbann::lbann_callback_timeline::name.
virtual void lbann::lbann_callback::on_forward_prop_end(model *m, Layer *l)
Called when a layer ends forward propagation.
virtual void lbann::lbann_callback::on_backward_prop_begin(model *m)
Called when a model begins backward propagation.
Referenced by lbann::lbann_callback_timeline::name.
virtual void lbann::lbann_callback::on_backward_prop_begin(model *m, Layer *l)
Called when a layer begins backward propagation.
virtual void lbann::lbann_callback::on_backward_prop_end(model *m)
Called when a model ends backward propagation.
Referenced by lbann::lbann_callback_timeline::name.
virtual void lbann::lbann_callback::on_backward_prop_end(model *m, Layer *l)
Called when a layer ends backward propagation.
virtual void lbann::lbann_callback::on_optimize_begin(model *m)
Called when a model begins optimization.
Referenced by lbann::lbann_callback_timeline::name.
virtual void lbann::lbann_callback::on_optimize_begin(model *m, weights *w)
Called when weights begins optimization.
virtual void lbann::lbann_callback::on_optimize_end(model *m)
Called when a model ends optimization.
Referenced by lbann::lbann_callback_timeline::name.
virtual void lbann::lbann_callback::on_optimize_end(model *m, weights *w)
Called when weights ends optimization.
virtual void lbann::lbann_callback::on_batch_evaluate_begin(model *m)
Called at the beginning of a (mini-)batch evaluation (validation / testing).
virtual void lbann::lbann_callback::on_batch_evaluate_end(model *m)
Called at the end of a (mini-)batch evaluation (validation / testing).
virtual void lbann::lbann_callback::on_evaluate_forward_prop_begin(model *m)
Called when a model begins forward propagation for evaluation (validation / testing).
virtual void lbann::lbann_callback::on_evaluate_forward_prop_begin(model *m, Layer *l)
Called when a layer begins forward propagation for evaluation (validation / testing).
virtual void lbann::lbann_callback::on_evaluate_forward_prop_end(model *m)
Called when a model ends forward propagation for evaluation (validation / testing).
virtual void lbann::lbann_callback::on_evaluate_forward_prop_end(model *m, Layer *l)
Called when a layer ends forward propagation for evaluation (validation / testing).
int lbann::lbann_callback::get_batch_interval() const
Return the batch interval.
References m_batch_interval, name.
virtual std::string lbann::lbann_callback::name() const =0
Return this callback's name.
Referenced by get_batch_interval.