lbann::geom_negloglike
lbann::geom_negloglike::geom_negloglike(EvalType scale_factor=EvalType(1))
Default constructor.
References operator=, ~geom_negloglike.
Referenced by copy.
lbann::geom_negloglike::geom_negloglike(const geom_negloglike &other)=default
Copy constructor.
geom_negloglike& lbann::geom_negloglike::operator=(const geom_negloglike &other)=default
Copy assignment operator.
Referenced by geom_negloglike.
lbann::geom_negloglike::~geom_negloglike() override=default
Destructor.
Referenced by geom_negloglike.
geom_negloglike* lbann::geom_negloglike::copy() const override
Copy function.
References geom_negloglike.
std::string lbann::geom_negloglike::name() const override
Get the name of the objective function term.
void lbann::geom_negloglike::start_evaluate_compute(const AbsDistMat &prediction, const AbsDistMat &ground_truth) override
Compute the Geometric negative log-likelihood objective function. Given a prediction $\hat{y}$ and ground truth $y$, the Geometric negative log-likelihood is \[ Geom_nll(\hat{y},y) = -y \log(1-\hat{y}) + \log(\hat{y}) \] This function updates the objective function value with the mean value of the mean squared error across the mini-batch.
References finish_evaluate_compute, prediction, differentiate_compute.
EvalType lbann::geom_negloglike::finish_evaluate_compute(const AbsDistMat &prediction, const AbsDistMat &ground_truth) override
Finish evaluation of the loss function. This should not include the scale factor.
References lbann::objective_function_term::get_comm, lbann::lbann_comm::allreduce.
Referenced by start_evaluate_compute.
void lbann::geom_negloglike::differentiate_compute(const AbsDistMat &prediction, const AbsDistMat &ground_truth, AbsDistMat &gradient) override
Compute the gradient of the Geometric negative log-likelihood objective function. Given a prediction $y$ and ground truth $\hat{y}$, the gradient of the Geometric negative log-likelihood is \[ \nabla_{\hat{y}} \text{Geom}_{\text{nll}} (\hat{y},y) = y/(1-\hat{y}) + 1/\hat{y} \]
Referenced by start_evaluate_compute.