lbann::hypergradient_adam
DataType lbann::hypergradient_adam::m_hyper_learning_rate
Hypergradient learning rate.
Referenced by operator=, get_description, step_compute.
DataType lbann::hypergradient_adam::m_beta1
Update factor for first moment estimate.
Referenced by operator=, get_description, step_compute.
DataType lbann::hypergradient_adam::m_beta2
Update factor for second moment estimate.
Referenced by operator=, get_description, step_compute.
DataType lbann::hypergradient_adam::m_eps
Small factor to avoid division by zero.
Referenced by operator=, get_description, step_compute.
DataType lbann::hypergradient_adam::m_current_beta1
beta1 ^ iteration.
Referenced by operator=, step_compute.
DataType lbann::hypergradient_adam::m_current_beta2
beta2 ^ iteration.
Referenced by operator=, step_compute.
AbsDistMat* lbann::hypergradient_adam::m_moment1
First moment estimates.
Referenced by hypergradient_adam, operator=, ~hypergradient_adam, setup, step_compute.
AbsDistMat* lbann::hypergradient_adam::m_moment2
Second moment estimates.
Referenced by hypergradient_adam, operator=, ~hypergradient_adam, setup, step_compute.
AbsDistMat* lbann::hypergradient_adam::m_old_gradient
Gradient estimate from the prior step (for hypergradient).
Referenced by hypergradient_adam, operator=, ~hypergradient_adam, setup, step_compute.
lbann::hypergradient_adam::hypergradient_adam(lbann_comm *comm, DataType init_learning_rate, DataType hyper_learning_rate=DataType(1e-7), DataType beta1=DataType(0.9), DataType beta2=DataType(0.99), DataType eps=DataType(1e-8))
Constructor init_learning_rate Initial Adam learning rate (0.001 reasonable). hyper_learning_rate Hypergradient learning rate. beta1 Decay rate for the first moment moving average. beta2 Decay rate for the second moment moving average. eps A small value.
Referenced by copy.
lbann::hypergradient_adam::hypergradient_adam(const hypergradient_adam &other)
Copy constructor.
References m_moment1, m_moment2, m_old_gradient.
hypergradient_adam & lbann::hypergradient_adam::operator=(const hypergradient_adam &other)
Copy assignment operator.
References lbann::optimizer::operator=, m_hyper_learning_rate, m_beta1, m_beta2, m_eps, m_current_beta1, m_current_beta2, m_moment1, m_moment2, m_old_gradient.
lbann::hypergradient_adam::~hypergradient_adam() override
Destructor.
References m_moment1, m_moment2, m_old_gradient.
hypergradient_adam* lbann::hypergradient_adam::copy() const override
Create a copy.
References hypergradient_adam.
std::string lbann::hypergradient_adam::get_type() const override
Returns the optimizer name.
References get_description, setup, step_compute.
std::string lbann::hypergradient_adam::get_description() const override
Get a human-readable description of the optimizer.
References lbann::optimizer::get_description, m_hyper_learning_rate, m_beta1, m_beta2, m_eps.
Referenced by get_type.
void lbann::hypergradient_adam::setup(weights &w) override
Setup optimizer.
References lbann::optimizer::setup, m_moment1, lbann::optimizer::m_gradient, m_moment2, m_old_gradient.
Referenced by get_type.
void lbann::hypergradient_adam::step_compute(AbsDistMat &values, const AbsDistMat &gradient) override
Perform the computation in an optimization step.
References m_current_beta1, m_beta1, m_current_beta2, m_beta2, m_moment1, m_moment2, m_old_gradient, lbann::optimizer::m_learning_rate, m_hyper_learning_rate, m_eps.
Referenced by get_type.