lbann::directed_acyclic_graph_model
lbann::directed_acyclic_graph_model::directed_acyclic_graph_model(lbann_comm *comm, int max_mini_batch_size, objective_function *obj_fn, optimizer *default_optimizer)
Constructor.
Referenced by copy.
lbann::directed_acyclic_graph_model::directed_acyclic_graph_model(const directed_acyclic_graph_model &other)=default
Copy constructor.
directed_acyclic_graph_model& lbann::directed_acyclic_graph_model::operator=(const directed_acyclic_graph_model &other)=default
Copy assignment operator.
lbann::directed_acyclic_graph_model::~directed_acyclic_graph_model() override=default
Destructor.
directed_acyclic_graph_model* lbann::directed_acyclic_graph_model::copy() const override
Create copy.
References directed_acyclic_graph_model.
std::string lbann::directed_acyclic_graph_model::name() const override
Get model name.
void lbann::directed_acyclic_graph_model::freeze_layers_under_frozen_surface() override
For general DAG models, users need to manually specify each layer to freeze in the model description prototext.
References setup_layer_execution_order.
void lbann::directed_acyclic_graph_model::setup_layer_execution_order() override
Set up layer execution order. Called in setup function. A topological sort applied is to the layer list so that we can traverse a directed acyclic graph without violating dependencies.
References lbann::model::construct_layer_graph, lbann::graph::topological_sort, lbann::model::permute_layers, lbann::model::setup_layer_execution_order.
Referenced by freeze_layers_under_frozen_surface, lbann::siamese_model::setup_layer_topology.