lbann::polya_negloglike
AbsDistMat* lbann::polya_negloglike::m_counts
Referenced by polya_negloglike, operator=, ~polya_negloglike, setup, finish_evaluate_compute, differentiate_compute.
AbsDistMat* lbann::polya_negloglike::m_alpha_sums
Referenced by polya_negloglike, operator=, ~polya_negloglike, setup, finish_evaluate_compute, differentiate_compute.
AbsDistMat* lbann::polya_negloglike::m_lgamma_alpha_sums
Referenced by polya_negloglike, operator=, ~polya_negloglike, setup, finish_evaluate_compute.
AbsDistMat* lbann::polya_negloglike::m_lgamma_alpha_level_count_sums
Referenced by polya_negloglike, operator=, ~polya_negloglike, setup, finish_evaluate_compute.
lbann::polya_negloglike::polya_negloglike(EvalType scale_factor=EvalType(1))
Default constructor.
Referenced by copy.
lbann::polya_negloglike::polya_negloglike(const polya_negloglike &other)
Copy constructor.
References m_counts, m_alpha_sums, m_lgamma_alpha_sums, m_lgamma_alpha_level_count_sums.
polya_negloglike & lbann::polya_negloglike::operator=(const polya_negloglike &other)
Copy assignment operator.
References lbann::loss_function::operator=, m_counts, m_alpha_sums, m_lgamma_alpha_sums, m_lgamma_alpha_level_count_sums.
lbann::polya_negloglike::~polya_negloglike() override
Destructor.
References m_counts, m_alpha_sums, m_lgamma_alpha_sums, m_lgamma_alpha_level_count_sums.
polya_negloglike* lbann::polya_negloglike::copy() const override
Copy function.
References polya_negloglike.
std::string lbann::polya_negloglike::name() const override
Get the name of the objective function term.
References setup.
void lbann::polya_negloglike::setup(model &m) override
Setup term.
References lbann::loss_function::setup, lbann::loss_function::m_gradient, m_counts, m_alpha_sums, m_lgamma_alpha_sums, m_lgamma_alpha_level_count_sums.
Referenced by name.
void lbann::polya_negloglike::start_evaluate_compute(const AbsDistMat &prediction, const AbsDistMat &ground_truth) override
Compute the Polya negative log-likelihood objective function. Given the parameters $(\alpha_1,\dots,\alpha_K)$ of the predicted Polya distribution, the ground truth label counts $(k_1,\dots,k_K)$, and total counts $n = \sum_{i=0}^K k_i$ the Polya negative log-likelihood is \[ Poly_nll(\vec{\alpha}, \vec{k}) = -\log \Gamma(\sum_{i=0}^K \hat{y}_i) + \log \Gamma(n + \sum_{i=0}^K \hat{y}_i) - \sum_{i=0}^K \left\{\log \Gamma(\hat{y}_i + \alpha_i) - \log \Gamma(\alpha_i) \right\} \] This function updates the objective function value with the mean Polya negative log-likelihood across the mini-batch. Note that each column of the predictions and ground truth matrices should have non-negative entries.
References finish_evaluate_compute, prediction, differentiate_compute.
EvalType lbann::polya_negloglike::finish_evaluate_compute(const AbsDistMat &prediction, const AbsDistMat &ground_truth) override
Finish evaluation of the loss function. This should not include the scale factor.
References m_counts, m_alpha_sums, m_lgamma_alpha_sums, m_lgamma_alpha_level_count_sums, lbann::objective_function_term::get_comm, lbann::lbann_comm::allreduce.
Referenced by start_evaluate_compute.
void lbann::polya_negloglike::differentiate_compute(const AbsDistMat &prediction, const AbsDistMat &ground_truth, AbsDistMat &gradient) override
Compute the gradient of the Polya negative log-likelihood objective function. Given the parameters $(\alpha_1,\dots,\alpha_K)$ of the predicted Polya distribution, the ground truth label counts $(k_1,\dots,k_K)$, and total counts $n = \sum_{i=0}^K k_i$, the gradient of the Polya negative log-likelihood function is \[ \nabla_{alpha_i} Poly_nll(\vec{\alpha}, \vec{k}) = -\Psi(\sum_{i=1}^K \alpha_i) + \Psi(n + \sum_{i=1}^K \alpha_i) - \Psi(k_i + \alpha_i) + \Psi(\alpha_i) \]
References m_counts, m_alpha_sums, digamma.
Referenced by start_evaluate_compute.