options
bool options::has_int(std::string option)
Returns true if the database contains the option
References m_test_int.
Referenced by get, get_cmdline_overrides.
bool options::has_bool(std::string option)
References m_test_int.
Referenced by get, lbann::pilot2_molecular_reader::load, lbann::data_store_imagenet::setup, lbann::generic_data_store::generic_data_store, get_cmdline_overrides, lbann::stack_profiler::activate, lbann::stack_trace::open_output_file, lbann::stack_trace::register_handler.
bool options::has_string(std::string option)
References m_test_string.
Referenced by get, set_data_readers_filenames, get_cmdline_overrides, save_session.
bool options::has_float(std::string option)
References has_double, set_option, get_int, get_bool, get_string.
Referenced by get_cmdline_overrides.
bool options::has_double(std::string option)
References m_test_double.
Referenced by has_float.
void options::set_option(std::string name, int value)
insert option in database; if option already exists it's value will changed
References m_opts.
Referenced by has_float, lbann::data_store_imagenet::setup, get_bool, get_int, get_double.
void options::set_option(std::string name, bool value)
References m_opts.
void options::set_option(std::string name, std::string value)
References m_opts.
void options::set_option(std::string name, float value)
References m_opts.
void options::set_option(std::string name, double value)
References m_opts.
int options::get_int(std::string option)
returns the value of the option; throws exception if option doesn't exist, or if it's associated value (which is stored internally as a string) cannot be cast to the specified return type
References m_test_int.
Referenced by has_float, get_float, get_cmdline_overrides.
bool options::get_bool(std::string option)
References m_test_int.
Referenced by has_float, get_float, lbann::pilot2_molecular_reader::load, lbann::data_store_imagenet::setup, lbann::generic_data_store::generic_data_store, get_cmdline_overrides, lbann::stack_profiler::activate, lbann::stack_trace::open_output_file, lbann::stack_trace::register_handler.
std::string options::get_string(std::string option)
References m_test_string.
Referenced by has_float, get_float, set_data_readers_filenames, get_cmdline_overrides, save_session.
float options::get_float(std::string option)
References get_double, get_int, get_bool, get_string.
Referenced by set_data_readers_percent, get_cmdline_overrides.
double options::get_double(std::string option)
References m_test_double.
Referenced by get_float.
int options::get_int(std::string option, int the_default)
returns the value of the option; if option isn't found, inserts the option in the internal db, with the specified default value, and returns the the_default
References m_test_int, set_option.
bool options::get_bool(std::string option, bool the_default)
References m_test_int, set_option.
std::string options::get_string(std::string option, std::string the_default)
References m_test_string.
float options::get_float(std::string option, float the_default)
References get_double.
double options::get_double(std::string option, double the_default)
References m_test_double, set_option.
int options::m_rank
Referenced by init, m_parse_file.
std::map<std::string, std::string> options::m_opts
the "database;" all options are stored as strings, and may be cast to int, etc.
Referenced by init, m_has_opt, m_test_int, m_test_double, m_test_string, set_option, m_parse_file, m_parse_cmd_line, print.
std::vector<std::string> options::m_cmd_line
Referenced by init.
int options::m_argc
Referenced by init.
char** options::m_argv
Referenced by init.
options * options::s_instance
Referenced by get.
static options* options::get()
returns a pointer to the Options singleton
References s_instance, init, print, has_int, has_bool, has_string.
Referenced by lbann::data_reader_merge_samples::load, lbann::pilot2_molecular_reader::load, lbann::data_store_imagenet::setup, lbann::generic_data_store::generic_data_store, set_data_readers_filenames, set_data_readers_percent, get_cmdline_overrides, save_session, lbann::stack_profiler::activate, lbann::stack_trace::open_output_file, lbann::stack_trace::register_handler.
void options::init(int argc, char **argv)
if cmd line contains "--loadme=<string>" then initialize options database from that file. Next, intialize from all other options on cmd line.
References m_rank, m_argc, m_argv, m_opts, m_cmd_line, m_parse_opt, m_parse_file, m_parse_cmd_line.
Referenced by get.
void options::print(std::ostream &out=std::cout)
prints all registered options to 'out'
References m_opts.
Referenced by get.
options::options()
private constructor to ensure this class is a singleton
options::options(options &)
options& options::operator=(options const &)
void options::m_parse_file(std::string fn)
References m_rank, m_parse_opt, m_opts.
Referenced by init.
bool options::m_has_opt(std::string option)
References m_opts.
Referenced by m_test_int, m_test_double, m_test_string.
bool options::m_test_int(std::string option, int &out)
References m_has_opt, m_opts.
Referenced by get_bool, get_int, has_int, has_bool.
bool options::m_test_double(std::string option, double &out)
References m_has_opt, m_opts, lower.
Referenced by get_double, has_double.
bool options::m_test_string(std::string option, std::string &out)
References m_has_opt, m_opts.
Referenced by get_string, has_string.
void options::m_parse_cmd_line(int arg, char **argv)
References m_parse_opt, m_opts.
Referenced by init.