lbann::image_utils
bool lbann::image_utils::loadIMG(std::vector< unsigned char > &image_buf, int &Width, int &Height, bool Flip, unsigned char *&Pixels)
Referenced by lbann::imagenet_reader_org::fetch_datum.
bool lbann::image_utils::loadIMG(const std::string &Imagefile, int &Width, int &Height, bool Flip, unsigned char *&Pixels)
bool lbann::image_utils::saveIMG(const std::string &Imagefile, int Width, int Height, bool Flip, unsigned char *Pixels)
bool lbann::image_utils::load_image(const std::string &filename, int &Width, int &Height, int &Type, cv_process &pp, std::vector< uint8_t > &buf)
Load an image from a file and put it into a serialized buffer.
References _LBANN_MILD_EXCEPTION.
Referenced by lbann::imagenet_reader::fetch_datum, lbann::imagenet_reader_patches::fetch_datum, lbann::data_reader_multi_images::fetch_datum, lbann::data_reader_triplet::fetch_datum.
bool lbann::image_utils::save_image(const std::string &filename, const int Width, const int Height, const int Type, cv_process &pp, const std::vector< uint8_t > &buf)
Save an image from a serialized buffer into a file.
References _LBANN_MILD_EXCEPTION.
bool lbann::image_utils::load_image(std::vector< unsigned char > &image_buf, int &Width, int &Height, int &Type, cv_process &pp, ::Mat &data)
References _LBANN_MILD_EXCEPTION.
bool lbann::image_utils::load_image(std::vector< unsigned char > &image_buf, int &Width, int &Height, int &Type, cv_process_patches &pp, std::vector<::Mat > &data)
filename The name of the image file to read in Width The width of a patch from the image read Height The height of a patch from the image read Type The type of the image patches (OpenCV code used for cv::Mat) pp The pre-processing parameters data The pre-processed image data to be stored in El::Matrix<DataType> format
References _LBANN_MILD_EXCEPTION.
bool lbann::image_utils::load_image(const std::string &filename, int &Width, int &Height, int &Type, cv_process &pp, ::Mat &data)
Load an image from a file and put it into an LBANN Mat data block.
filename The name of the image file to read in Width The width of the image read Height The height of the image read Type The type of the image read (OpenCV code used for cv::Mat) pp The pre-processing parameters data The pre-processed image data to be stored in El::Matrix<DataType> format
References _LBANN_MILD_EXCEPTION.
bool lbann::image_utils::load_image(const std::string &filename, int &Width, int &Height, int &Type, cv_process_patches &pp, std::vector<::Mat > &data)
Load an image from a file, extract patches from it and put them into LBANN Mat data blocks.
filename The name of the image file to read in Width The width of a patch from the image read Height The height of a patch from the image read Type The type of the image patches (OpenCV code used for cv::Mat) pp The pre-processing parameters data The pre-processed image data to be stored in El::Matrix<DataType> format
References _LBANN_MILD_EXCEPTION.
bool lbann::image_utils::save_image(const std::string &filename, const int Width, const int Height, const int Type, cv_process &pp, const ::Mat &data)
Save an image using data from an LBANN Mat data block.
filename The name of the image file to write Width The width of the image to be written Height The height of the image to be written Type The type of the image to be written (OpenCV code used for cv::Mat) pp The post-processing parameters data The image data in El::Matrix<DataType> format to post-process and write
References _LBANN_MILD_EXCEPTION.
bool lbann::image_utils::import_image(cv::InputArray inbuf, int &Width, int &Height, int &Type, cv_process &pp, ::Mat &data)
Import an image from a file buffer (inbuf) and put it into an LBANN Mat data block.
inbuf The buffer that contains the raw bytes read from an image file This can be for example, const std:vector<uchar>& or const cv::Mat&. http://docs.opencv.org/trunk/d4/d32/classcv_1_1__InputArray.html Width The width of the image consturcted out of inbuf Height The height of the image consructed Type The type of the image constructed (OpenCV code used for cv::Mat) pp The pre-processing parameters data The pre-processed image data. A set of sub-matrix Views can be used to store the data.
References _LBANN_MILD_EXCEPTION.
Referenced by lbann::imagenet_reader_single::fetch_datum, lbann::data_reader_mnist_siamese::fetch_labels.
bool lbann::image_utils::import_image(cv::InputArray inbuf, int &Width, int &Height, int &Type, cv_process_patches &pp, std::vector<::Mat > &data)
Import an image from a file buffer (inbuf), extract patches from it and put them into LBANN Mat data blocks.
inbuf The buffer that contains the raw bytes read from an image file This can be for example, const std:vector<uchar>& or const cv::Mat&. http://docs.opencv.org/trunk/d4/d32/classcv_1_1__InputArray.html Width The width of a patch from the image consturcted out of inbuf Height The height of a patch from the image consructed Type The type of the image patches (OpenCV code used for cv::Mat) pp The pre-processing parameters data The pre-processed image data. A set of sub-matrix Views can be used to store the data.
References _LBANN_MILD_EXCEPTION.
bool lbann::image_utils::export_image(const std::string &fileExt, std::vector< uchar > &outbuf, const int Width, const int Height, const int Type, cv_process &pp, const ::Mat &data)
Export an image using data from an LBANN Mat block into a file buffer (outbuf)
fileExt The format extension name of image file: e.g., ".jpeg", ".png" outbuf The preallocated buffer to contain the bytes to be written into an image file Width The width of the image to be consturcted based on the given data of Mat Height The height of the image Type The type of the image (OpenCV code used for cv::Mat) pp The post-processing parameters data The image data. A sub-matrix View can be passed instead of the entire matrix.
References _LBANN_MILD_EXCEPTION.