lbann::siamese_model
int lbann::siamese_model::m_num_heads
The number of heads in Siamese model.
Referenced by setup_layer_topology.
std::unordered_map<Layer *, Layer *> lbann::siamese_model::m_follower_to_master_layer
Map from follower to master layers. Layers in follower heads map to corresponding layers in master head. All other layers map to themselves.
Referenced by setup_layer_topology, setup_layers.
lbann::siamese_model::siamese_model(lbann_comm *comm, int mini_batch_size, objective_function *obj_fn, optimizer *default_optimizer, int num_heads)
Constructor.
Referenced by copy.
lbann::siamese_model::siamese_model(const siamese_model &other)=default
Copy constructor.
siamese_model& lbann::siamese_model::operator=(const siamese_model &other)=default
Copy assignment operator.
lbann::siamese_model::~siamese_model() override=default
Destructor.
siamese_model* lbann::siamese_model::copy() const override
Create copy.
References siamese_model.
std::string lbann::siamese_model::name() const override
Get model name.
References freeze_layers_under_frozen_surface, setup_layer_topology, setup_layers.
void lbann::siamese_model::freeze_layers_under_frozen_surface() override
For Siamese models, users specify only the last layer to freeze in the model description prototext. Then, the layers that precedes it will automatically be frozen as well.
References lbann::model::m_layers.
Referenced by name, setup_layer_topology.
void lbann::siamese_model::setup_layer_topology() override
Set up topology of Siamese network. Called in setup function. Determines the network's master head and duplicates it.
References m_follower_to_master_layer, lbann::model::setup_layer_topology, lbann::directed_acyclic_graph_model::setup_layer_execution_order, lbann::model::m_layers, m_num_heads, lbann::Layer::copy, lbann::Layer::set_name, lbann::Layer::get_name, freeze_layers_under_frozen_surface.
Referenced by name.
void lbann::siamese_model::setup_layers() override
Set up layers. Called in setup function. Layers in follower heads share weights with corresponding layers in master head.
References lbann::model::m_layers, m_follower_to_master_layer, lbann::model::get_weights, lbann::model::m_comm, lbann::lbann_comm::am_world_master, lbann::model::print_layer_description.
Referenced by name.