lbann::lbann_callback_dump_gradients
std::string lbann::lbann_callback_dump_gradients::m_basename
Basename for writing files.
Referenced by on_backward_prop_end.
lbann::lbann_callback_dump_gradients::lbann_callback_dump_gradients(std::string basename, int batch_interval=1)
basename The basename for writing files.
References operator=.
Referenced by copy.
lbann::lbann_callback_dump_gradients::lbann_callback_dump_gradients(const lbann_callback_dump_gradients &)=default
lbann_callback_dump_gradients& lbann::lbann_callback_dump_gradients::operator=(const lbann_callback_dump_gradients &)=default
Referenced by lbann_callback_dump_gradients.
lbann_callback_dump_gradients* lbann::lbann_callback_dump_gradients::copy() const override
References lbann_callback_dump_gradients, on_backward_prop_end.
void lbann::lbann_callback_dump_gradients::on_backward_prop_end(model *m) override
Called when a model ends backward propagation.
References lbann::model::get_weights, m_basename, lbann::model::get_comm, lbann::lbann_comm::get_model_rank, lbann::model::get_cur_epoch, lbann::model::get_cur_step, lbann::optimizer::get_gradient.
Referenced by copy.
std::string lbann::lbann_callback_dump_gradients::name() const override
Return this callback's name.