lbann::lbann_callback_timer
EvalType lbann::lbann_callback_timer::m_start_time
Start time for the current timing.
Referenced by timing_begin, timing_end.
EvalType lbann::lbann_callback_timer::m_batch_start_time
Start time for the current mini-batch.
Referenced by batch_timing_begin, batch_timing_end.
std::vector<EvalType> lbann::lbann_callback_timer::m_batch_times
History of mini-batch times for the current timing.
Referenced by batch_timing_end, timing_begin, timing_end.
lbann::lbann_callback_timer::lbann_callback_timer(lbann_summary *summarizer=nullptr)
Constructor.
References operator=.
Referenced by copy.
lbann::lbann_callback_timer::lbann_callback_timer(const lbann_callback_timer &)=default
Copy constructor.
lbann_callback_timer& lbann::lbann_callback_timer::operator=(const lbann_callback_timer &)=default
Copy assignment operator.
Referenced by lbann_callback_timer.
lbann_callback_timer* lbann::lbann_callback_timer::copy() const override
Copy function.
References lbann_callback_timer.
void lbann::lbann_callback_timer::on_epoch_begin(model *m) override
Start timing for a training epoch.
References timing_begin.
void lbann::lbann_callback_timer::on_epoch_end(model *m) override
Report timing for a training epoch.
References timing_end.
void lbann::lbann_callback_timer::on_validation_begin(model *m) override
Start timing for validation.
References timing_begin.
void lbann::lbann_callback_timer::on_validation_end(model *m) override
Report timing for validation.
References timing_end.
void lbann::lbann_callback_timer::on_test_begin(model *m) override
Start timing for testing.
References timing_begin.
void lbann::lbann_callback_timer::on_test_end(model *m) override
Report timing for testing.
References timing_end.
void lbann::lbann_callback_timer::on_batch_begin(model *m) override
Record training mini-batch start time.
References batch_timing_begin.
void lbann::lbann_callback_timer::on_batch_end(model *m) override
Record training mini-batch run time.
References batch_timing_end.
void lbann::lbann_callback_timer::on_batch_evaluate_begin(model *m) override
Record evaluation mini-batch start time.
References batch_timing_begin.
void lbann::lbann_callback_timer::on_batch_evaluate_end(model *m) override
Record evaluation mini-batch run time.
References batch_timing_end.
std::string lbann::lbann_callback_timer::name() const override
Callback name.
void lbann::lbann_callback_timer::timing_begin(model *m)
Start timing.
References m_batch_times, m_start_time, lbann::get_time.
Referenced by on_epoch_begin, on_validation_begin, on_test_begin.
void lbann::lbann_callback_timer::timing_end(model *m)
Print timing results to standard output.
References comm, lbann::model::get_comm, lbann::get_time, m_start_time, m_batch_times, lbann::model::get_execution_mode, training, lbann::model::get_cur_epoch, validation, testing, lbann::lbann_comm::get_num_models, lbann::lbann_comm::am_model_master, lbann::lbann_comm::am_world_master, lbann::lbann_comm::intermodel_gather, lbann::lbann_comm::get_intermodel_master.
Referenced by on_epoch_end, on_validation_end, on_test_end.
void lbann::lbann_callback_timer::batch_timing_begin(model *m)
Start mini-batch timing.
References m_batch_start_time, lbann::get_time.
Referenced by on_batch_begin, on_batch_evaluate_begin.
void lbann::lbann_callback_timer::batch_timing_end(model *m)
Record mini-batch timing.
References lbann::get_time, m_batch_start_time, m_batch_times, lbann::lbann_callback::m_summarizer, lbann::lbann_summary::reduce_scalar, lbann::model::get_cur_step.
Referenced by on_batch_end, on_batch_evaluate_end.