lbann::data_reader_jag
model_mode_t
using lbann::data_reader_jag::data_t = double
using lbann::data_reader_jag::scalar_t = double
using lbann::data_reader_jag::input_t = double
model_mode_t lbann::data_reader_jag::m_model_mode
The current mode of modeling.
Referenced by set_model_mode, get_linearized_data_size, get_linearized_response_size, get_data_dims, load, check_data, get_description, fetch_datum, fetch_response.
bool lbann::data_reader_jag::m_image_loaded
Whether image output data have been loaded.
Referenced by set_linearized_image_size, load, check_data, get_description, normalize_image, get_image_ptr, get_image_max, get_image_min.
bool lbann::data_reader_jag::m_scalar_loaded
Whether scalar output data have been loaded.
Referenced by set_linearized_scalar_size, load, check_data, get_scalar_ptr.
bool lbann::data_reader_jag::m_input_loaded
Whether simulation input data have been loaded.
Referenced by set_linearized_input_size, load, check_data, get_input_ptr.
size_t lbann::data_reader_jag::m_num_samples
The number of samples.
Referenced by get_num_samples, load, normalize_image.
size_t lbann::data_reader_jag::m_linearized_image_size
The linearized size of an image.
Referenced by get_linearized_image_size, set_linearized_image_size, get_linearized_data_size, get_linearized_response_size, get_data_dims, check_data, normalize_image, get_image, get_image_max, get_image_min, fetch_datum, fetch_response.
size_t lbann::data_reader_jag::m_linearized_scalar_size
The linearized size of scalar outputs.
Referenced by get_linearized_scalar_size, set_linearized_scalar_size, get_linearized_data_size, get_linearized_response_size, get_data_dims, check_data, get_scalar, fetch_datum, fetch_response.
size_t lbann::data_reader_jag::m_linearized_input_size
The linearized size of inputs.
Referenced by get_linearized_input_size, set_linearized_input_size, get_linearized_response_size, check_data, get_input, fetch_response.
int lbann::data_reader_jag::m_image_normalization
image normalization mode
Referenced by set_normalization_mode, get_description, normalize_image.
int lbann::data_reader_jag::m_image_width
image width
Referenced by set_image_dims, set_linearized_image_size, get_data_dims, get_description, save_image.
int lbann::data_reader_jag::m_image_height
image height
Referenced by set_image_dims, set_linearized_image_size, get_data_dims, get_description, get_image, save_image.
cnpy::NpyArray lbann::data_reader_jag::m_images
List of jag output images.
Referenced by set_linearized_image_size, load, check_data, get_description, get_image_ptr, get_image_max, get_image_min.
cnpy::NpyArray lbann::data_reader_jag::m_scalars
List of jag scalar outputs.
Referenced by set_linearized_scalar_size, load, check_data, get_description, get_scalar_ptr.
cnpy::NpyArray lbann::data_reader_jag::m_inputs
List of jag input.
Referenced by set_linearized_input_size, load, check_data, get_description, get_input_ptr.
data_t lbann::data_reader_jag::m_img_min
The smallest pixel value in image data (useful for normalization or visualization)
Referenced by load, get_description.
data_t lbann::data_reader_jag::m_img_max
The largest pixel value in image data (useful for normalization or visualization)
Referenced by load, get_description.
lbann::data_reader_jag::data_reader_jag(bool shuffle=true)
References max.
Referenced by copy.
lbann::data_reader_jag::data_reader_jag(const data_reader_jag &)=default
data_reader_jag& lbann::data_reader_jag::operator=(const data_reader_jag &)=default
lbann::data_reader_jag::~data_reader_jag() override
data_reader_jag* lbann::data_reader_jag::copy() const override
References data_reader_jag.
std::string lbann::data_reader_jag::get_type() const override
Return this data_reader's type
References set_model_mode, set_normalization_mode, set_image_dims, load, get_description, get_num_samples, get_linearized_image_size, get_linearized_scalar_size, get_linearized_input_size, get_linearized_data_size, get_linearized_response_size, get_data_dims, get_image_ptr, get_image, get_scalar_ptr, get_scalar, get_input_ptr, get_input, save_image, fetch_datum, fetch_response, check_data, normalize_image, set_linearized_image_size, set_linearized_scalar_size, set_linearized_input_size, get_image_max, get_image_min.
void lbann::data_reader_jag::set_model_mode(const model_mode_t mm)
Set the modeling mode: Inverse, AutoI, or AutoS.
References AutoS, m_model_mode.
Referenced by get_type.
void lbann::data_reader_jag::set_normalization_mode(int mode)
Set normalization mode: 0 = none, 1 = dataset-wise, 2 = image-wise.
References m_image_normalization.
Referenced by get_type.
void lbann::data_reader_jag::set_image_dims(const int width, const int height)
Set the image dimension.
References m_image_width, m_image_height.
Referenced by get_type.
void lbann::data_reader_jag::load() override
Load data and do data reader's chores.
References lbann::add_delimiter, lbann::generic_data_reader::get_file_dir, lbann::generic_data_reader::get_data_filename, lbann::get_tokens, lbann::generic_data_reader::m_first_n, get_num_samples, lbann::generic_data_reader::set_use_percent, lbann::generic_data_reader::set_absolute_sample_count, lbann::generic_data_reader::m_shuffled_indices, lbann::generic_data_reader::select_subset_of_data.
Referenced by get_type.
std::string lbann::data_reader_jag::get_description() const
Show the description.
References m_model_mode, lbann::cnpy_utils::show_shape, m_images, m_scalars, m_inputs, m_image_loaded, m_img_min, m_img_max, m_image_width, m_image_height, m_image_normalization.
Referenced by get_type, load.
size_t lbann::data_reader_jag::get_num_samples() const
Return the number of samples.
References m_num_samples.
Referenced by get_type, load.
size_t lbann::data_reader_jag::get_linearized_image_size() const
Return the linearized size of an image.
References m_linearized_image_size.
Referenced by get_type.
size_t lbann::data_reader_jag::get_linearized_scalar_size() const
Return the linearized size of scalar outputs.
References m_linearized_scalar_size.
Referenced by get_type.
size_t lbann::data_reader_jag::get_linearized_input_size() const
Return the linearized size of inputs.
References m_linearized_input_size.
Referenced by get_type.
int lbann::data_reader_jag::get_linearized_data_size() const override
Get the linearized size (i.e. number of elements) in a sample.
References m_model_mode, Inverse, m_linearized_image_size, AutoI, AutoS, m_linearized_scalar_size.
Referenced by get_type.
int lbann::data_reader_jag::get_linearized_response_size() const override
Get the linearized size (i.e. number of elements) in a response.
References m_model_mode, Inverse, m_linearized_input_size, AutoI, m_linearized_image_size, AutoS, m_linearized_scalar_size.
Referenced by get_type.
const std::vector< int > lbann::data_reader_jag::get_data_dims() const override
Get the dimensions of the data.
References m_model_mode, Inverse, m_image_height, m_image_width, AutoI, m_linearized_image_size, AutoS, m_linearized_scalar_size.
Referenced by get_type.
data_reader_jag::data_t * lbann::data_reader_jag::get_image_ptr(const size_t i) const
Return the pointer to the raw image data.
References m_image_loaded, m_images.
Referenced by get_type, normalize_image, get_image, get_image_max, get_image_min, fetch_datum, fetch_response.
cv::Mat lbann::data_reader_jag::get_image(const size_t i) const
Return the image data as a 1-D vector of lbann::DataType.
References get_image_ptr, m_linearized_image_size, m_image_height.
Referenced by get_type.
data_reader_jag::scalar_t * lbann::data_reader_jag::get_scalar_ptr(const size_t i) const
Return the pointer to the raw scalar data.
References m_scalar_loaded, m_scalars.
Referenced by get_type, get_scalar, fetch_datum, fetch_response.
std::vector< DataType > lbann::data_reader_jag::get_scalar(const size_t i) const
Return the scalar values of the i-th sample.
References get_scalar_ptr, m_linearized_scalar_size.
Referenced by get_type.
data_reader_jag::input_t * lbann::data_reader_jag::get_input_ptr(const size_t i) const
Return the pointer to the raw input data.
References m_input_loaded, m_inputs.
Referenced by get_type, get_input, fetch_response.
std::vector< DataType > lbann::data_reader_jag::get_input(const size_t i) const
Return the input values of the simulation correspoding to the i-th sample.
References get_input_ptr, m_linearized_input_size.
Referenced by get_type.
void lbann::data_reader_jag::save_image(Mat &pixels, const std::string filename, bool do_scale=true) override
Save pixels to an image. The implementing data reader is responsible for handling format detection, conversion, etc.
References lbann::lbann_image_preprocessor::internal_save_image, m_image_height, m_image_width.
Referenced by get_type.
bool lbann::data_reader_jag::fetch_datum(Mat &X, int data_id, int mb_idx, int tid) override
Fetch a single sample into a matrix. X The matrix to load data into. data_id The index of the datum to fetch. mb_idx The index within the mini-batch.
References m_model_mode, Inverse, get_image_ptr, m_linearized_image_size, AutoI, AutoS, get_scalar_ptr, m_linearized_scalar_size.
Referenced by get_type.
bool lbann::data_reader_jag::fetch_response(Mat &Y, int data_id, int mb_idx, int tid) override
Fetch a single response into a matrix. Y The matrix to load data into. data_id The index of the datum to fetch. mb_idx The index within the mini-batch.
References m_model_mode, Inverse, get_input_ptr, m_linearized_input_size, AutoI, get_image_ptr, m_linearized_image_size, AutoS, get_scalar_ptr, m_linearized_scalar_size.
Referenced by get_type.
void lbann::data_reader_jag::load(const std::string image_file, const std::string scalar_file, const std::string input_file, const size_t first_n=0u)
Load the data in the numpy format file. Use only first_n available samples if specified.
References m_model_mode, Inverse, AutoI, lbann::check_if_file_exists, AutoS, m_num_samples, m_images, lbann::cnpy_utils::shrink_to_fit, m_image_loaded, set_linearized_image_size, m_scalars, m_scalar_loaded, set_linearized_scalar_size, m_inputs, m_input_loaded, set_linearized_input_size, check_data, get_description, m_img_min, get_image_min, m_img_max, get_image_max, normalize_image.
bool lbann::data_reader_jag::check_data(size_t &num_samples) const
Check the dimensions of loaded data.
References m_image_loaded, m_linearized_image_size, m_images, m_scalar_loaded, m_linearized_scalar_size, m_scalars, m_input_loaded, m_linearized_input_size, m_inputs, m_model_mode, Inverse, AutoI, AutoS.
Referenced by get_type, load.
void lbann::data_reader_jag::normalize_image()
Normalize image data to [0 1] scale once after loading based on the mode 0 (none): no normalization 1 (dataset-wise): map the min/max of all the pixels in image data to 0/1 2 (image-wise): map the min/max of all the pixels in current image to 0/1
References m_image_loaded, m_image_normalization, get_image_ptr, m_num_samples, m_linearized_image_size.
Referenced by get_type, load.
void lbann::data_reader_jag::set_linearized_image_size()
Set the linearized size of an image.
References m_image_loaded, m_linearized_image_size, m_image_width, m_image_height, m_images.
Referenced by get_type, load.
void lbann::data_reader_jag::set_linearized_scalar_size()
Set the linearized size of scalar outputs.
References m_scalar_loaded, m_linearized_scalar_size, m_scalars.
Referenced by get_type, load.
void lbann::data_reader_jag::set_linearized_input_size()
Return the linearized size of inputs.
References m_input_loaded, m_linearized_input_size, m_inputs.
Referenced by get_type, load.
data_reader_jag::data_t lbann::data_reader_jag::get_image_max() const
Return the maximum element of all the images.
References m_image_loaded, get_image_ptr, m_images, m_linearized_image_size.
Referenced by get_type, load.
data_reader_jag::data_t lbann::data_reader_jag::get_image_min() const
Return the minimum element of all the images.
References m_image_loaded, get_image_ptr, m_images, m_linearized_image_size.
Referenced by get_type, load.