lbann::generic_input_layer
using lbann::generic_input_layer::data_reader_map_t = std::map<execution_mode, generic_data_reader *>
generic_io_buffer* lbann::generic_input_layer::io_buffer
Referenced by ~generic_input_layer, operator=, initialize_io_buffer, lbann::input_layer< T_io_buffer, T_layout >::input_layer, lbann::input_layer< T_io_buffer, T_layout >::get_type, lbann::proto::construct_layer.
dataset lbann::generic_input_layer::m_training_dataset
Referenced by generic_input_layer, get_dataset, select_first_valid_dataset, get_num_samples_trained, get_total_num_training_samples, save_to_checkpoint_shared, load_from_checkpoint_shared.
dataset lbann::generic_input_layer::m_testing_dataset
Referenced by generic_input_layer, get_dataset, select_first_valid_dataset, get_num_samples_tested, get_total_num_testing_samples, save_to_checkpoint_shared, load_from_checkpoint_shared.
dataset lbann::generic_input_layer::m_validation_dataset
Referenced by generic_input_layer, get_dataset, select_first_valid_dataset, save_to_checkpoint_shared, load_from_checkpoint_shared.
data_reader_map_t lbann::generic_input_layer::m_data_readers
Referenced by generic_input_layer, ~generic_input_layer, operator=, setup_data, get_data_reader, select_first_valid_dataset, get_linearized_data_size, get_linearized_label_size, get_linearized_response_size, at_new_epoch, save_to_checkpoint_shared, load_from_checkpoint_shared.
lbann::generic_input_layer::generic_input_layer(lbann_comm *comm, int num_parallel_readers, std::map< execution_mode, generic_data_reader *> data_readers, bool data_set_spans_models=true, bool for_regression=false)
References lbann::Layer::m_expected_num_parent_layers, m_data_readers, training, m_training_dataset, lbann::dataset::total_samples, validation, m_validation_dataset, testing, m_testing_dataset.
lbann::generic_input_layer::~generic_input_layer() override
References io_buffer, m_data_readers.
lbann::generic_input_layer::generic_input_layer(const generic_input_layer &other)
References m_data_readers.
generic_input_layer& lbann::generic_input_layer::operator=(const generic_input_layer &other)
References lbann::Layer::operator=, io_buffer, lbann::generic_io_buffer::copy, m_data_readers, initialize_io_buffer, comm.
void lbann::generic_input_layer::initialize_io_buffer(lbann_comm *comm, int num_parallel_readers, std::map< execution_mode, generic_data_reader *> data_readers)
Referenced by operator=.
std::string lbann::generic_input_layer::get_type() const override
Get the layer type's name. A layer type name should be brief, human-readable description of the layer's mathematical operation.
Referenced by lbann::lbann_callback_debug_io::print_fp_start.
std::string lbann::generic_input_layer::get_description() const override
Returns description of ctor params
References get_topo_description, lbann::generic_io_buffer::get_type, lbann::Layer::get_data_layout_string, lbann::Layer::get_data_layout.
void lbann::generic_input_layer::setup_dims() override
Setup tensor dimensions Called by the setup function. The base method sets the dimensions of the activation tensors equal to the dimensions of the first previous activation tensor.
References lbann::Layer::setup_dims, lbann::Layer::m_neuron_dims, get_data_dims, lbann::Layer::m_num_neuron_dims, lbann::Layer::m_num_neurons.
void lbann::generic_input_layer::setup_data() override
Setup layer data. Called by the setup function. The base method sets the previous activation, activation, previous error signal, and error signal matrices to zero matrices with the proper dimensions. Matrix buffers are pinned if needed for GPU transfers.
References lbann::Layer::setup_data, m_data_readers, training, lbann::Layer::m_comm, validation, testing, lbann::Layer::m_model, lbann::model::get_max_mini_batch_size, lbann::io_layer::m_data_set_spans_models, calculate_num_iterations_per_epoch_training_spans_models, calculate_num_iterations_per_epoch_training_unique_per_models, lbann::generic_io_buffer::setup_data, lbann::Layer::m_num_neurons.
void lbann::generic_input_layer::fp_setup_data(int mini_batch_size) override
Define the standard view of the matrix and set it for the model Setup the effective (global) mini-batch size so that gradients are properly averaged across models.
References get_current_mini_batch_size, lbann::Layer::m_model, lbann::model::get_callbacks, get_current_global_mini_batch_size, lbann::model::set_current_mini_batch_size, lbann::model::set_effective_mini_batch_size, lbann::Layer::fp_setup_data, lbann::generic_io_buffer::set_local_matrix_bypass, lbann::Layer::get_local_activations, lbann::generic_io_buffer::set_std_matrix_view.
void lbann::generic_input_layer::fp_compute() override
Perform the computation for the forward propagation step.
References lbann::Layer::m_model, lbann::model::get_execution_mode, lbann::generic_io_buffer::fetch_to_local_matrix, get_data_reader, get_current_mini_batch_size, update_num_samples_processed, lbann::model::get_current_mini_batch_size, lbann::Layer::m_comm, lbann::lbann_comm::model_broadcast, lbann::model::set_current_mini_batch_size, get_current_world_master_mini_batch_adjustment, lbann::lbann_comm::get_model_rank, lbann::distributed_io_buffer::distribute_from_local_matrix, lbann::Layer::get_activations.
void lbann::generic_input_layer::bp_compute() override
Perform the computation for the backward propagation step.
bool lbann::generic_input_layer::update_compute() override
Once a mini-batch is processed, resuffle the data for the next batch if necessary
References lbann::generic_io_buffer::is_data_set_processed, get_data_reader, lbann::Layer::m_model, lbann::model::get_execution_mode.
generic_data_reader* lbann::generic_input_layer::get_data_reader(const execution_mode mode) const
References m_data_readers, training, validation, testing.
Referenced by lbann::generic_target_layer::fp_compute, lbann::generic_target_layer::update_compute, lbann::lbann_callback_debug_io::print_fp_start.
generic_data_reader* lbann::generic_input_layer::get_data_reader() const
References lbann::Layer::m_model, lbann::model::get_execution_mode.
Referenced by fp_compute, update_compute, get_num_parallel_readers, get_num_iterations_per_epoch, get_current_step_in_epoch, get_mini_batch_size, get_last_mini_batch_size, get_current_mini_batch_size, get_global_mini_batch_size, get_global_last_mini_batch_size, get_current_global_mini_batch_size, get_world_master_mini_batch_adjustment, get_current_world_master_mini_batch_adjustment, calculate_num_iterations_per_epoch_training_spans_models, calculate_num_iterations_per_epoch_training_unique_per_models, select_data_reader, get_sample_indices_per_mb, get_data_dims.
virtual int lbann::generic_input_layer::get_num_parallel_readers(execution_mode mode) const
References get_data_reader, lbann::generic_data_reader::get_num_parallel_readers.
virtual int lbann::generic_input_layer::get_num_parallel_readers() const
References lbann::Layer::m_model, lbann::model::get_execution_mode.
virtual int lbann::generic_input_layer::get_num_iterations_per_epoch(execution_mode mode) const
References get_data_reader, lbann::generic_data_reader::get_num_iterations_per_epoch.
Referenced by lbann::lbann_callback_check_dataset::on_epoch_end, lbann::lbann_callback_debug_io::print_fp_start, lbann::lbann_callback_print::on_epoch_begin, lbann::model::get_num_iterations_per_epoch.
virtual int lbann::generic_input_layer::get_num_iterations_per_epoch() const
References lbann::Layer::m_model, lbann::model::get_execution_mode.
virtual int lbann::generic_input_layer::get_current_step_in_epoch(execution_mode mode) const
References get_data_reader, lbann::generic_data_reader::get_current_step_in_epoch.
virtual int lbann::generic_input_layer::get_current_step_in_epoch() const
References lbann::Layer::m_model, lbann::model::get_execution_mode.
virtual int lbann::generic_input_layer::get_mini_batch_size(execution_mode mode) const
References get_data_reader, lbann::generic_data_reader::get_mini_batch_size.
Referenced by lbann::lbann_callback_print::on_epoch_begin.
virtual int lbann::generic_input_layer::get_last_mini_batch_size(execution_mode mode) const
References get_data_reader, lbann::generic_data_reader::get_last_mini_batch_size.
Referenced by lbann::lbann_callback_print::on_epoch_begin.
virtual int lbann::generic_input_layer::get_last_mini_batch_size() const
References lbann::Layer::m_model, lbann::model::get_execution_mode.
virtual int lbann::generic_input_layer::get_current_mini_batch_size(execution_mode mode) const
References get_data_reader, lbann::generic_data_reader::get_current_mini_batch_size.
Referenced by lbann::lbann_callback_debug_io::print_fp_start.
virtual int lbann::generic_input_layer::get_current_mini_batch_size() const
References lbann::Layer::m_model, lbann::model::get_execution_mode.
Referenced by fp_setup_data, fp_compute.
virtual int lbann::generic_input_layer::get_global_mini_batch_size(execution_mode mode) const
References get_data_reader, lbann::generic_data_reader::get_global_mini_batch_size.
Referenced by lbann::lbann_callback_print::on_epoch_begin.
virtual int lbann::generic_input_layer::get_global_last_mini_batch_size(execution_mode mode) const
References get_data_reader, lbann::generic_data_reader::get_global_last_mini_batch_size.
Referenced by lbann::lbann_callback_print::on_epoch_begin.
virtual int lbann::generic_input_layer::get_current_global_mini_batch_size(execution_mode mode) const
References get_data_reader, lbann::generic_data_reader::get_current_global_mini_batch_size.
Referenced by lbann::lbann_callback_debug_io::print_fp_start.
virtual int lbann::generic_input_layer::get_current_global_mini_batch_size() const
References lbann::Layer::m_model, lbann::model::get_execution_mode.
Referenced by fp_setup_data.
virtual int lbann::generic_input_layer::get_world_master_mini_batch_adjustment(execution_mode mode) const
References get_data_reader, lbann::generic_data_reader::get_world_master_mini_batch_adjustment.
Referenced by lbann::lbann_callback_print::on_epoch_begin.
virtual int lbann::generic_input_layer::get_world_master_mini_batch_adjustment() const
References lbann::Layer::m_model, lbann::model::get_execution_mode.
virtual int lbann::generic_input_layer::get_current_world_master_mini_batch_adjustment(execution_mode mode, int model_rank) const
References get_data_reader, lbann::generic_data_reader::get_current_world_master_mini_batch_adjustment.
Referenced by fp_compute, get_current_world_master_mini_batch_adjustment.
virtual int lbann::generic_input_layer::get_current_world_master_mini_batch_adjustment(int model_rank) const
References get_current_world_master_mini_batch_adjustment, lbann::Layer::m_model, lbann::model::get_execution_mode.
void lbann::generic_input_layer::calculate_num_iterations_per_epoch_training_spans_models(int mini_batch_size)
Calculate how many iterations are required for training, testing, and validation given a specified mini-batch size and that the training data set is spanning all of the models.
References lbann::generic_io_buffer::calculate_num_iterations_per_epoch_spanning_models, get_data_reader, training, lbann::generic_io_buffer::calculate_num_iterations_per_epoch_single_model, validation, testing.
Referenced by setup_data, lbann::lbann_callback_variable_minibatch::on_train_begin, lbann::lbann_callback_variable_minibatch::on_epoch_end.
void lbann::generic_input_layer::calculate_num_iterations_per_epoch_training_unique_per_models(int mini_batch_size)
References lbann::generic_io_buffer::calculate_num_iterations_per_epoch_single_model, get_data_reader, training, validation, testing.
Referenced by setup_data.
dataset& lbann::generic_input_layer::get_dataset(execution_mode m) override
Return the dataset for the given execution mode.
References training, m_training_dataset, validation, m_validation_dataset, testing, m_testing_dataset.
Referenced by select_dataset, is_execution_mode_valid, lbann::generic_target_layer::get_dataset.
const dataset& lbann::generic_input_layer::get_dataset(execution_mode m) const override
References training, m_training_dataset, validation, m_validation_dataset, testing, m_testing_dataset.
dataset& lbann::generic_input_layer::select_dataset() override
Return the dataset associated with the current execution mode.
References get_dataset, lbann::Layer::m_model, lbann::model::get_execution_mode.
Referenced by update_num_samples_processed, lbann::generic_target_layer::select_dataset.
const dataset& lbann::generic_input_layer::select_dataset() const override
References get_dataset, lbann::Layer::m_model, lbann::model::get_execution_mode.
dataset* lbann::generic_input_layer::select_first_valid_dataset() override
Return the first dataset with a valid (non-null) datareader. Returns null if none are valid.
References m_data_readers, training, m_training_dataset, validation, m_validation_dataset, testing, m_testing_dataset.
Referenced by lbann::generic_target_layer::select_first_valid_dataset.
generic_data_reader* lbann::generic_input_layer::select_data_reader() const override
Return the data reader associated with the current execution mode.
References get_data_reader.
Referenced by lbann::generic_target_layer::select_data_reader.
long lbann::generic_input_layer::update_num_samples_processed(long num_samples) override
Update the number of samples processed for the current execution mode.
References select_dataset, lbann::dataset::num_samples_processed, lbann::dataset::get_num_samples_processed.
Referenced by fp_compute, lbann::generic_target_layer::update_num_samples_processed.
El::Matrix<El::Int>* lbann::generic_input_layer::get_sample_indices_per_mb() override
Return the sample indices fetched in the current mini-batch.
References get_data_reader, lbann::generic_data_reader::get_indices_fetched_per_mb.
Referenced by lbann::generic_target_layer::get_sample_indices_per_mb.
const std::vector<int> lbann::generic_input_layer::get_data_dims() const override
Get the dimensions of the underlying data.
References get_data_reader, lbann::generic_data_reader::get_data_dims.
Referenced by setup_dims, lbann::generic_target_layer::get_data_dims.
std::string lbann::generic_input_layer::get_topo_description() const override
Get a human-readable description of the activation tensors. Activation tensors are stored in distributed matrices where each column corresponds to a mini-batch sample. Within each column, the data is packed w.r.t. the last tensor dimension, then w.r.t. the penultimate dimension, and so on. 3D tensors are assumed to be 2D images in NCHW format.
References lbann::Layer::m_neuron_dims.
Referenced by get_description, lbann::generic_target_layer::get_topo_description.
long lbann::generic_input_layer::get_linearized_data_size() const override
Get the linearized size of the underlying data.
References m_data_readers, training, validation, testing.
Referenced by lbann::generic_target_layer::get_linearized_data_size.
long lbann::generic_input_layer::get_linearized_label_size() const override
Get the linearized size of the labels for the underlying data.
References lbann::io_layer::is_for_regression, m_data_readers, training, validation, testing.
Referenced by lbann::generic_target_layer::get_linearized_label_size.
long lbann::generic_input_layer::get_linearized_response_size() const override
References lbann::io_layer::is_for_regression, m_data_readers, training, validation, testing.
Referenced by lbann::generic_target_layer::get_linearized_response_size.
long lbann::generic_input_layer::get_num_samples_trained() const override
References m_training_dataset, lbann::dataset::get_num_samples_processed.
Referenced by lbann::generic_target_layer::get_num_samples_trained.
long lbann::generic_input_layer::get_num_samples_tested() const override
References m_testing_dataset, lbann::dataset::get_num_samples_processed.
Referenced by lbann::generic_target_layer::get_num_samples_tested.
long lbann::generic_input_layer::get_total_num_training_samples() const override
References m_training_dataset, lbann::dataset::get_total_samples.
Referenced by lbann::generic_target_layer::get_total_num_training_samples.
long lbann::generic_input_layer::get_total_num_testing_samples() const override
References m_testing_dataset, lbann::dataset::get_total_samples.
Referenced by lbann::generic_target_layer::get_total_num_testing_samples.
bool lbann::generic_input_layer::at_new_epoch() const override
References m_data_readers, training.
Referenced by lbann::generic_target_layer::at_new_epoch.
bool lbann::generic_input_layer::is_execution_mode_valid(execution_mode mode) const override
References get_dataset, lbann::dataset::get_total_samples.
Referenced by lbann::generic_target_layer::is_execution_mode_valid.
bool lbann::generic_input_layer::save_to_checkpoint_shared(persist &p, bool val_end) const override
References m_data_readers, training, testing, lbann::persist::get_rank, lbann::persist::write_uint64, lbann::train, m_training_dataset, lbann::dataset::get_num_samples_processed, lbann::dataset::get_total_samples, m_testing_dataset, lbann::validate, m_validation_dataset, validation.
bool lbann::generic_input_layer::load_from_checkpoint_shared(persist &p) override
References m_data_readers, training, testing, lbann::persist::get_rank, lbann::persist::read_uint64, lbann::train, lbann::generic_input_layer::dataset_header::train_proc, lbann::generic_input_layer::dataset_header::train_total, lbann::generic_input_layer::dataset_header::test_proc, lbann::generic_input_layer::dataset_header::test_total, lbann::validate, lbann::generic_input_layer::dataset_header::validate_proc, lbann::generic_input_layer::dataset_header::validate_total, validation, m_training_dataset, lbann::dataset::num_samples_processed, lbann::dataset::total_samples, m_testing_dataset, m_validation_dataset.
void lbann::generic_input_layer::initialize_io_buffer(lbann_comm *comm, int num_parallel_readers, std::map< execution_mode, generic_data_reader *> data_readers)
References io_buffer.
void lbann::generic_input_layer::initialize_io_buffer(lbann_comm *comm, int num_parallel_readers, std::map< execution_mode, generic_data_reader *> data_readers)
References io_buffer.