lbann::lbann_callback_print
lbann::lbann_callback_print::lbann_callback_print(int batch_interval=1)
References operator=.
Referenced by copy.
lbann::lbann_callback_print::lbann_callback_print(const lbann_callback_print &)=default
lbann_callback_print& lbann::lbann_callback_print::operator=(const lbann_callback_print &)=default
Referenced by lbann_callback_print.
lbann_callback_print* lbann::lbann_callback_print::copy() const override
References lbann_callback_print, setup, on_epoch_begin, on_epoch_end, on_validation_end, on_test_end.
void lbann::lbann_callback_print::setup(model *m) override
Called once to set up the callback (after all layers are set up).
References comm, lbann::model::get_comm, lbann::lbann_comm::am_world_master, LBANN_MAKE_STR.
Referenced by copy.
void lbann::lbann_callback_print::on_epoch_begin(model *m) override
Called at the beginning of each epoch.
References comm, lbann::model::get_comm, lbann::lbann_comm::am_world_master, lbann::model::get_layers, LBANN_ERROR, lbann::model::get_cur_epoch, lbann::generic_input_layer::get_num_iterations_per_epoch, training, validation, testing, lbann::generic_input_layer::get_global_mini_batch_size, lbann::generic_input_layer::get_global_last_mini_batch_size, lbann::generic_input_layer::get_mini_batch_size, lbann::generic_input_layer::get_last_mini_batch_size, lbann::generic_input_layer::get_world_master_mini_batch_adjustment.
Referenced by copy.
void lbann::lbann_callback_print::on_epoch_end(model *m) override
Called immediate after the end of each epoch.
References report_results.
Referenced by copy.
void lbann::lbann_callback_print::on_validation_end(model *m) override
Called immediately after the end of validation.
References report_results.
Referenced by copy.
void lbann::lbann_callback_print::on_test_end(model *m) override
Called immediately after the end of testing.
References report_results.
Referenced by copy.
std::string lbann::lbann_callback_print::name() const override
Return this callback's name.
References report_results.
void lbann::lbann_callback_print::report_results(model *m)
Print objective function and metrics to standard output.
References comm, lbann::model::get_comm, lbann::model::get_execution_mode, training, lbann::model::get_cur_epoch, validation, testing, lbann::lbann_comm::am_model_master, lbann::lbann_comm::get_num_models, lbann::model::get_objective_function, lbann::objective_function::get_mean_value, lbann::objective_function::get_statistics_num_samples, lbann::lbann_comm::am_world_master, lbann::lbann_comm::intermodel_gather, lbann::lbann_comm::get_world_master, lbann::model::get_metrics, lbann::lbann_comm::get_intermodel_master.
Referenced by name, on_epoch_end, on_validation_end, on_test_end.