lbann::pooling_layer
const pool_mode lbann::pooling_layer< T_layout >::m_pool_mode
Pooling mode.
Referenced by lbann::pooling_layer< T_layout >::operator=, lbann::unpooling_layer< T_layout >::setup_pointers.
std::vector<int> lbann::pooling_layer< T_layout >::m_pool_dims
Pooling window dimensions.
Referenced by lbann::pooling_layer< T_layout >::operator=, lbann::unpooling_layer< T_layout >::fp_compute_im2col, lbann::unpooling_layer< T_layout >::bp_compute_im2col.
int lbann::pooling_layer< T_layout >::m_pool_size
Size of pooling window.
Referenced by lbann::pooling_layer< T_layout >::operator=, lbann::pooling_layer< T_layout >::fp_compute_im2col, lbann::pooling_layer< T_layout >::bp_compute_im2col, lbann::unpooling_layer< T_layout >::fp_compute_im2col, lbann::unpooling_layer< T_layout >::bp_compute_im2col.
std::vector<int> lbann::pooling_layer< T_layout >::m_pads
Pooling padding.
Referenced by lbann::pooling_layer< T_layout >::operator=, lbann::unpooling_layer< T_layout >::fp_compute_im2col, lbann::unpooling_layer< T_layout >::bp_compute_im2col.
std::vector<int> lbann::pooling_layer< T_layout >::m_strides
Pooling strides.
Referenced by lbann::pooling_layer< T_layout >::operator=, lbann::unpooling_layer< T_layout >::fp_compute_im2col, lbann::unpooling_layer< T_layout >::bp_compute_im2col.
std::vector<int> lbann::pooling_layer< T_layout >::m_max_pool_indices
Input indices for max pooling. Each entry corresponds to a local entry in the activations matrix. The entry gives the index of the maximum entry within the pooling window.
Referenced by lbann::pooling_layer< T_layout >::operator=, lbann::unpooling_layer< T_layout >::fp_compute_im2col, lbann::unpooling_layer< T_layout >::bp_compute_im2col.
friend class unpooling_layer< T_layout >
lbann::pooling_layer< T_layout >::pooling_layer(lbann_comm *comm, int num_data_dims, int pool_dim, int pad, int stride, pool_mode mode, cudnn::cudnn_manager *cudnn=nullptr)
Referenced by lbann::pooling_layer< T_layout >::copy.
lbann::pooling_layer< T_layout >::pooling_layer(lbann_comm *comm, int num_data_dims, std::vector< int > pool_dims, std::vector< int > pads, std::vector< int > strides, pool_mode mode, cudnn::cudnn_manager *cudnn=nullptr)
References DATA_PARALLEL, lbann::Layer::m_using_gpus, lbann::Layer::m_cudnn.
lbann::pooling_layer< T_layout >::pooling_layer(const pooling_layer &other)
pooling_layer& lbann::pooling_layer< T_layout >::operator=(const pooling_layer &other)
References lbann::Layer::operator=, lbann::pooling_layer< T_layout >::m_pool_mode, lbann::pooling_layer< T_layout >::m_pool_dims, lbann::pooling_layer< T_layout >::m_pool_size, lbann::pooling_layer< T_layout >::m_pads, lbann::pooling_layer< T_layout >::m_strides, lbann::pooling_layer< T_layout >::m_max_pool_indices.
pooling_layer* lbann::pooling_layer< T_layout >::copy() const override
Copy function. This function dynamically allocates memory for a layer instance and instantiates a copy. The caller is responsible for deallocating the instance.
References lbann::pooling_layer< T_layout >::pooling_layer.
std::string lbann::pooling_layer< T_layout >::get_type() const override
Get the layer type's name. A layer type name should be brief, human-readable description of the layer's mathematical operation.
data_layout lbann::pooling_layer< T_layout >::get_data_layout() const override
Get data layout of the data tensors. We assume that the data layouts of the previous activations, activations, previous error signals, and error signals are the same. Each concrete layer that is templated on its data layout should override this function to return its template parameter.
Referenced by lbann::pooling_layer< T_layout >::get_description.
std::string lbann::pooling_layer< T_layout >::get_description() const override
Returns description of ctor params
References get_pool_mode_name, lbann::Layer::get_data_layout_string, lbann::pooling_layer< T_layout >::get_data_layout.
lbann::pooling_layer< T_layout >::~pooling_layer() override
Destructor.
void lbann::pooling_layer< T_layout >::setup_dims() override
Setup tensor dimensions Called by the setup function. The base method sets the dimensions of the activation tensors equal to the dimensions of the first previous activation tensor.
References lbann::Layer::setup_dims, lbann::Layer::m_num_neuron_dims, lbann::Layer::m_prev_neuron_dims, lbann::Layer::m_neuron_dims, lbann::Layer::m_num_neurons.
void lbann::pooling_layer< T_layout >::setup_gpu() override
Initialize GPU objects.
References lbann::Layer::setup_gpu, max, average, average_no_pad.
void lbann::pooling_layer< T_layout >::fp_compute() override
Perform the computation for the forward propagation step.
References lbann::Layer::m_using_gpus, lbann::pooling_layer< T_layout >::fp_compute_cudnn, lbann::pooling_layer< T_layout >::fp_compute_im2col.
void lbann::pooling_layer< T_layout >::bp_compute() override
Perform the computation for the backward propagation step.
References lbann::Layer::m_using_gpus, lbann::pooling_layer< T_layout >::bp_compute_cudnn, lbann::pooling_layer< T_layout >::bp_compute_im2col.
void lbann::pooling_layer< T_layout >::fp_compute_cudnn()
Pooling forward propagation with cuDNN.
References lbann::Layer::m_cudnn.
Referenced by lbann::pooling_layer< T_layout >::fp_compute.
void lbann::pooling_layer< T_layout >::bp_compute_cudnn()
Pooling backward propagation with cuDNN.
References lbann::Layer::m_cudnn.
Referenced by lbann::pooling_layer< T_layout >::bp_compute.
void lbann::pooling_layer< T_layout >::fp_compute_im2col()
Pooling forward propagation with im2col.
References max, average, lbann::Layer::get_local_prev_activations, lbann::Layer::get_local_activations, lbann::Layer::m_prev_neuron_dims, lbann::Layer::m_num_neurons, lbann::im2col, lbann::Layer::m_num_prev_neuron_dims, lbann::pooling_layer< T_layout >::m_pool_size.
Referenced by lbann::pooling_layer< T_layout >::fp_compute.
void lbann::pooling_layer< T_layout >::bp_compute_im2col()
Pooling forward propagation with im2col.
References max, average, lbann::Layer::get_local_prev_error_signals, lbann::Layer::get_local_error_signals, lbann::Layer::m_prev_neuron_dims, lbann::Layer::m_num_neurons, lbann::pooling_layer< T_layout >::m_pool_size, lbann::col2im, lbann::Layer::m_num_prev_neuron_dims.
Referenced by lbann::pooling_layer< T_layout >::bp_compute.