lbann::objective_function
std::vector<objective_function_term*> lbann::objective_function::m_terms
List of objective function terms.
Referenced by add_term, get_terms, objective_function, operator=, ~objective_function, setup, start_evaluation, finish_evaluation, differentiate, compute_weight_regularization, get_layer_pointers, set_layer_pointers, get_weights_pointers, set_weights_pointers, save_to_checkpoint_shared, load_from_checkpoint_shared.
std::map<execution_mode,metric_statistics> lbann::objective_function::m_statistics
Objective funciton statistics.
Referenced by reset_statistics, operator=, finish_evaluation, get_mean_value, get_statistics_num_samples.
EvalType lbann::objective_function::m_evaluation_time
Time spent evaluating the objective function.
Referenced by get_evaluation_time, reset_counters, operator=, start_evaluation, finish_evaluation.
EvalType lbann::objective_function::m_differentiation_time
Time spent computing the objective function gradient.
Referenced by get_differentiation_time, reset_counters, operator=, differentiate, compute_weight_regularization.
lbann::objective_function::objective_function()
Default constructor.
References operator=, ~objective_function.
Referenced by copy.
lbann::objective_function::objective_function(const objective_function &other)
Copy constructor.
References m_terms.
objective_function & lbann::objective_function::operator=(const objective_function &other)
Copy assignment operator.
References m_terms, m_statistics, m_evaluation_time, m_differentiation_time.
Referenced by objective_function.
lbann::objective_function::~objective_function()
Destructor.
References m_terms.
Referenced by objective_function.
objective_function* lbann::objective_function::copy() const
Copy function.
References objective_function.
Referenced by lbann::model::model, lbann::model::operator=.
void lbann::objective_function::add_term(objective_function_term *term)
Add a term to the objective function. The objective function takes ownership of the objective function term and deallocates it during destruction.
References m_terms.
Referenced by lbann::proto::construct_objective_function.
std::vector<objective_function_term*> lbann::objective_function::get_terms()
Get list of objective function terms.
References m_terms, setup, start_evaluation, finish_evaluation, differentiate, compute_weight_regularization.
Referenced by lbann::greedy_layerwise_autoencoder::set_phase, lbann::greedy_layerwise_autoencoder::restore_sequential_model, lbann::proto::anonymous_namespace{model_factory.cpp}::assign_layers_to_objective_function.
void lbann::objective_function::setup(model &m)
Setup objective function.
References m_terms.
Referenced by get_terms, lbann::model::setup.
void lbann::objective_function::start_evaluation(execution_mode mode, int mini_batch_size)
Start evaluating the objective function. This function takes the model's current mini-batch size. If multiple models are being trained, the current mini-batch size may be different from the effective mini-batch size. The result is not guaranteed to be available until finish_evaluation is called.
References lbann::get_time, m_terms, m_evaluation_time.
Referenced by get_terms, lbann::lbann_callback_gradient_check::compute_objective_function, lbann::model::evaluate_mini_batch, lbann::model::train_mini_batch.
EvalType lbann::objective_function::finish_evaluation(execution_mode mode, int mini_batch_size)
Complete evaluation of the objective function. The result is stored in history.
References lbann::get_time, m_terms, m_statistics, m_evaluation_time.
Referenced by get_terms, lbann::lbann_callback_gradient_check::compute_objective_function, lbann::model::evaluate_mini_batch, lbann::model::train_mini_batch.
void lbann::objective_function::differentiate()
Compute the objective function gradient. The gradient is with respect to the objective function inputs
References lbann::get_time, m_terms, m_differentiation_time.
Referenced by get_terms, lbann::lbann_callback_gradient_check::on_test_begin, lbann::model::train_mini_batch.
void lbann::objective_function::compute_weight_regularization()
Compute the gradient of the weight regularization term. The gradient is computed w.r.t. the weights.
References lbann::get_time, m_terms, m_differentiation_time.
Referenced by get_terms, lbann::lbann_callback_gradient_check::on_test_begin, lbann::model::train_mini_batch.
void lbann::objective_function::reset_statistics()
Clear all statistics.
References m_statistics.
Referenced by lbann::model::reset_epoch_statistics.
void lbann::objective_function::reset_statistics(execution_mode mode)
Clear statistics for an execution mode.
References m_statistics, get_mean_value, get_statistics_num_samples, get_layer_pointers, set_layer_pointers, get_weights_pointers, set_weights_pointers.
EvalType lbann::objective_function::get_mean_value(execution_mode mode) const
Get mean objective function value. This is a weighted average such that each mini-batch sample makes an equal contribution.
References m_statistics.
Referenced by lbann::reconstruction_layer< T_layout >::summarize_stats, reset_statistics, lbann::lbann_callback_check_reconstruction_error::on_epoch_end, lbann::lbann_callback_early_stopping::on_validation_end, lbann::lbann_callback_adaptive_learning_rate::global_schedule, lbann::lbann_callback_print::report_results, lbann::model::summarize_stats.
int lbann::objective_function::get_statistics_num_samples(execution_mode mode) const
Get number of samples for statistics.
References m_statistics.
Referenced by reset_statistics, lbann::lbann_callback_print::report_results.
std::vector< Layer * > lbann::objective_function::get_layer_pointers() const
Get list of pointers to layers.
References m_terms.
Referenced by reset_statistics, lbann::model::remap_pointers.
void lbann::objective_function::set_layer_pointers(std::vector< Layer *> layers)
Set list of pointers to layers.
References m_terms.
Referenced by reset_statistics, lbann::model::remap_pointers.
std::vector< weights * > lbann::objective_function::get_weights_pointers() const
Get list of pointers to weights.
References m_terms.
Referenced by reset_statistics, lbann::model::remap_pointers, lbann::model::setup_weights.
void lbann::objective_function::set_weights_pointers(std::vector< weights *> w)
Set list of pointers to weights.
References m_terms.
Referenced by reset_statistics, lbann::model::remap_pointers.
EvalType lbann::objective_function::get_evaluation_time() const
Get the time spent evaluating the objective function.
References m_evaluation_time.
Referenced by lbann::model::summarize_stats.
EvalType lbann::objective_function::get_differentiation_time() const
Get the time spent computing the objective function gradient.
References m_differentiation_time.
Referenced by lbann::model::summarize_stats.
void lbann::objective_function::reset_counters()
Reset time counters.
References m_evaluation_time, m_differentiation_time, save_to_checkpoint_shared, load_from_checkpoint_shared.
Referenced by lbann::model::summarize_stats.
bool lbann::objective_function::save_to_checkpoint_shared(lbann::persist &p)
References m_terms.
Referenced by reset_counters.
bool lbann::objective_function::load_from_checkpoint_shared(lbann::persist &p)
References m_terms.
Referenced by reset_counters.