lbann::model
objective_function* lbann::model::m_objective_function
The objective function used to train the model.
Referenced by get_objective_function, lbann::greedy_layerwise_autoencoder::set_phase, lbann::greedy_layerwise_autoencoder::restore_sequential_model, model, operator=, ~model, remap_pointers, setup, setup_weights, reset_epoch_statistics, evaluate_mini_batch, train_mini_batch, summarize_stats.
execution_mode lbann::model::m_execution_mode
The model's current execution mode.
Referenced by set_execution_mode, get_execution_mode, operator=, evaluate_mini_batch, summarize_stats, save_to_checkpoint_shared, load_from_checkpoint_shared.
bool lbann::model::m_terminate_training
Flag telling the model to terminate training.
Referenced by get_terminate_training, set_terminate_training, operator=, save_to_checkpoint_shared, load_from_checkpoint_shared.
int lbann::model::m_current_epoch
Most recent/current epoch for the model.
Referenced by get_cur_epoch, lbann::greedy_layerwise_autoencoder::train, operator=, train, save_to_checkpoint_shared, load_from_checkpoint_shared.
int lbann::model::m_current_step
Most recent/current training step for the model.
Referenced by get_cur_step, operator=, train_mini_batch, save_to_checkpoint_shared, load_from_checkpoint_shared.
int lbann::model::m_current_validation_step
Referenced by get_cur_validation_step, operator=, evaluate_mini_batch, save_to_checkpoint_shared, load_from_checkpoint_shared.
int lbann::model::m_current_testing_step
Referenced by get_cur_testing_step, operator=, evaluate_mini_batch, save_to_checkpoint_shared, load_from_checkpoint_shared.
int lbann::model::m_max_mini_batch_size
Maximum possible minibatch size supported by layers in this model. Note that this is local to the particular model, not across multiple models.
Referenced by get_max_mini_batch_size, operator=, save_to_checkpoint_shared, load_from_checkpoint_shared, write_proto.
int lbann::model::m_current_mini_batch_size
Size of the current mini-batch in the model.
Referenced by set_current_mini_batch_size, get_current_mini_batch_size, operator=, clear_error_signals, save_to_checkpoint_shared, load_from_checkpoint_shared.
int lbann::model::m_effective_mini_batch_size
The "effective" size of a minibatch. This is the size of the minibatch across all models and used for e.g. correctly averaging gradients from multiple models.
Referenced by get_effective_mini_batch_size, set_effective_mini_batch_size, operator=.
int lbann::model::m_current_phase
current phase (multiple of epoch counts) in training a model
Referenced by get_current_phase, operator=, save_to_checkpoint_shared, load_from_checkpoint_shared.
lbann_comm* lbann::model::m_comm
Communicator for the model.
Referenced by get_comm, lbann::greedy_layerwise_autoencoder::set_phase, operator=, setup_layers, add_dummy_layers, add_split_layers, write_proto, lbann::recurrent_model::setup_layers, lbann::sequential_model::write_proto, lbann::siamese_model::setup_layers.
std::vector<lbann_callback *> lbann::model::m_callbacks
Current callbacks to process.
Referenced by get_callbacks, model, operator=, ~model, add_callback, setup, do_train_begin_cbs, do_train_end_cbs, do_evaluate_begin_cbs, do_evaluate_end_cbs, do_epoch_begin_cbs, do_epoch_end_cbs, do_batch_begin_cbs, do_batch_end_cbs, do_model_forward_prop_begin_cbs, do_model_forward_prop_end_cbs, do_layer_forward_prop_begin_cbs, do_layer_forward_prop_end_cbs, do_model_backward_prop_begin_cbs, do_model_backward_prop_end_cbs, do_layer_backward_prop_begin_cbs, do_layer_backward_prop_end_cbs, do_model_optimize_begin_cbs, do_model_optimize_end_cbs, do_weight_optimize_begin_cbs, do_weight_optimize_end_cbs.
optimizer* lbann::model::m_default_optimizer
Default optimizer. If a layer needs to construct an optimizer during setup, it will make a copy of the default optimizer.
Referenced by ~model, create_optimizer.
std::vector<metric *> lbann::model::m_metrics
List of model metrics. A metric can be used to evaluate the performance of the model without affecting the training process.
Referenced by get_metrics, model, operator=, ~model, add_metric, remap_pointers, setup, reset_epoch_statistics, evaluate_mini_batch, train_mini_batch, summarize_stats.
std::vector<Layer *> lbann::model::m_layers
List of layers in model. The list is in execution order for forward propagation.
Referenced by get_layers, lbann::greedy_layerwise_autoencoder::setup_layer_topology, lbann::greedy_layerwise_autoencoder::set_phase, lbann::greedy_layerwise_autoencoder::restore_sequential_model, lbann::greedy_layerwise_autoencoder::forward_prop, lbann::greedy_layerwise_autoencoder::backward_prop, model, operator=, ~model, add_layer, set_layers, is_execution_mode_valid, construct_layer_graph, permute_layers, remap_pointers, freeze_layers_under_frozen_surface, setup_layer_topology, setup_layer_execution_order, setup_layers, setup_weights, add_connected_layers, add_dummy_layers, add_split_layers, get_num_iterations_per_epoch, collect_indices, reset_mode_and_model, clear_error_signals, forward_prop, backward_prop, update_layers, summarize_stats, summarize_matrices, lbann::recurrent_model::setup_layer_topology, lbann::recurrent_model::setup_layers, lbann::sequential_model::setup_layer_topology, lbann::sequential_model::save_to_checkpoint, lbann::sequential_model::load_from_checkpoint, lbann::sequential_model::save_to_checkpoint_shared, lbann::sequential_model::write_proto, lbann::sequential_model::load_from_checkpoint_shared, lbann::siamese_model::freeze_layers_under_frozen_surface, lbann::siamese_model::setup_layer_topology, lbann::siamese_model::setup_layers.
std::vector<weights *> lbann::model::m_weights
List of weights in model.
Referenced by get_weights, model, operator=, ~model, add_weights, replace_weights, setup_weights, clear_gradients, backward_prop, update_weights, lbann::sequential_model::save_to_checkpoint_shared, lbann::sequential_model::load_from_checkpoint_shared.
lbann::model::model(lbann_comm *comm, int mini_batch_size, objective_function *obj_fn, optimizer *default_optimizer=nullptr)
Constructor.
References training.
lbann::model::model(const model &other)
Copy constructor.
References m_objective_function, m_metrics, m_callbacks, m_layers, m_weights, lbann::objective_function::copy, remap_pointers.
model & lbann::model::operator=(const model &other)
Copy assignment operator.
References m_objective_function, m_metrics, m_callbacks, m_layers, m_weights, m_execution_mode, m_terminate_training, m_current_epoch, m_current_step, m_current_validation_step, m_current_testing_step, m_max_mini_batch_size, m_current_mini_batch_size, m_effective_mini_batch_size, m_current_phase, m_comm, lbann::objective_function::copy, remap_pointers.
lbann::model::~model()
Destructor.
References m_objective_function, m_default_optimizer, m_layers, m_weights, m_metrics, m_callbacks.
virtual model* lbann::model::copy() const =0
Copy model.
virtual std::string lbann::model::name() const =0
Return the model's name.
void lbann::model::setup()
Set up the model.
References setup_layer_topology, setup_layer_execution_order, setup_layers, setup_weights, m_objective_function, lbann::objective_function::setup, m_metrics, m_callbacks.
void lbann::model::add_layer(Layer *layer)
Add layer to model.
References m_layers.
Referenced by set_layers.
void lbann::model::add_weights(weights *w)
Add weights to model.
References m_weights.
Referenced by lbann::base_convolution_layer::setup_data, lbann::batch_normalization< T_layout >::setup_data.
void lbann::model::add_callback(lbann_callback *cb)
Register a new callback for the model.
References m_callbacks.
virtual std::vector<lbann_callback*>& lbann::model::get_callbacks()
Get the list of callbacks for the model.
References m_callbacks, add_metric, create_optimizer.
Referenced by lbann::generic_input_layer::fp_setup_data, lbann::lbann_callback_ltfb::setup.
void lbann::model::add_metric(metric *m)
Register a new metric for the model.
References m_metrics.
Referenced by get_callbacks.
optimizer * lbann::model::create_optimizer() const
Construct an instance of the default optimizer. If there is no default optimizer, a null pointer is returned.
References m_default_optimizer, lbann::optimizer::copy.
Referenced by lbann::base_convolution_layer::setup_data, lbann::batch_normalization< T_layout >::setup_data, get_callbacks.
objective_function* lbann::model::get_objective_function() const
Return the model's objective function.
References m_objective_function.
Referenced by lbann::reconstruction_layer< T_layout >::summarize_stats, lbann::lbann_callback_check_reconstruction_error::on_epoch_end, lbann::lbann_callback_early_stopping::on_validation_end, lbann::lbann_callback_gradient_check::on_test_begin, lbann::lbann_callback_gradient_check::compute_objective_function, lbann::lbann_callback_adaptive_learning_rate::global_schedule, lbann::lbann_callback_print::report_results.
virtual const std::vector<metric *>& lbann::model::get_metrics() const
Return the model's metrics.
References m_metrics, set_layers.
Referenced by lbann::anonymous_namespace{callback_ltfb.cpp}::evaluate, lbann::lbann_callback_print::report_results, lbann::lbann_callback_summary::on_epoch_end, lbann::lbann_callback_summary::on_test_end.
void lbann::model::set_layers(std::vector< Layer *> &layers)
Set the model's layers.
References m_layers, add_layer.
Referenced by get_metrics.
virtual const std::vector<Layer *>& lbann::model::get_layers() const
Return the model's layers.
References m_layers, replace_weights.
Referenced by lbann::lbann_callback_check_dataset::on_epoch_end, lbann::lbann_callback_checknan::dump_network, lbann::lbann_callback_debug_io::print_phase_start, lbann::lbann_callback_dump_activations::on_test_end, lbann::lbann_callback_gradient_check::on_test_begin, lbann::lbann_callback_gradient_check::compute_objective_function, lbann::lbann_callback_io::on_epoch_end, lbann::lbann_callback_io::on_test_end, lbann::lbann_callback_print::on_epoch_begin, lbann::lbann_callback_save_images::on_epoch_end, lbann::lbann_callback_save_images::on_phase_end, lbann::lbann_callback_save_images::on_test_end, lbann::lbann_callback_summary::on_test_end, lbann::lbann_callback_summary::save_histograms, lbann::lbann_callback_timeline::on_train_begin, lbann::lbann_callback_variable_minibatch::on_train_begin, lbann::lbann_callback_variable_minibatch::on_epoch_end, lbann::metric::setup, lbann::kl_divergence::setup, lbann::loss_function::setup.
void lbann::model::replace_weights(std::vector< weights *> &w)
Replace the model's weights.
References m_weights, remap_pointers.
Referenced by get_layers.
const std::vector<weights *>& lbann::model::get_weights() const
Return the model's weights.
References m_weights.
Referenced by lbann::lbann_callback_check_init::on_train_begin, lbann::lbann_callback_checknan::on_backward_prop_end, lbann::lbann_callback_checknan::on_batch_end, lbann::lbann_callback_checknan::dump_network, lbann::lbann_callback_checksmall::on_backward_prop_end, lbann::lbann_callback_checksmall::on_batch_end, lbann::lbann_callback_dump_gradients::on_backward_prop_end, lbann::lbann_callback_dump_weights::dump_weights, lbann::lbann_callback_gradient_check::on_test_begin, lbann::lbann_callback_imcomm::setup, lbann::lbann_callback_imcomm::on_train_begin, lbann::lbann_callback_imcomm::on_epoch_end, lbann::lbann_callback_imcomm::on_backward_prop_end, lbann::lbann_callback_learning_rate::setup, lbann::lbann_callback_ltfb::setup, lbann::lbann_callback_ltfb::on_batch_begin, lbann::lbann_callback_summary::save_histograms, lbann::lbann_callback_timeline::on_train_begin, lbann::lbann_callback_variable_minibatch::change_learning_rate, lbann::lbann_callback_variable_minibatch::get_current_learning_rate, lbann::siamese_model::setup_layers, lbann::group_lasso_weight_regularization::setup, lbann::l1_weight_regularization::setup, lbann::l2_weight_regularization::setup.
lbann_comm* lbann::model::get_comm() const
Get the model's comm.
References m_comm.
Referenced by lbann::lbann_callback_hang::on_train_begin, lbann::lbann_callback_check_dataset::on_epoch_end, lbann::lbann_callback_check_dataset::on_validation_end, lbann::lbann_callback_check_dataset::on_test_end, lbann::lbann_callback_check_init::on_train_begin, lbann::lbann_callback_check_reconstruction_error::on_epoch_end, lbann::lbann_callback_checknan::on_forward_prop_end, lbann::lbann_callback_checknan::on_backward_prop_end, lbann::lbann_callback_checknan::on_batch_end, lbann::lbann_callback_checknan::dump_network, lbann::lbann_callback_checkpoint::need_checkpoint, lbann::lbann_callback_checkpoint::checkpointShared, lbann::lbann_callback_checkpoint::restartShared, lbann::lbann_callback_checksmall::on_forward_prop_end, lbann::lbann_callback_checksmall::on_backward_prop_end, lbann::lbann_callback_checksmall::on_batch_end, lbann::lbann_callback_debug::on_forward_prop_begin, lbann::lbann_callback_debug::on_forward_prop_end, lbann::lbann_callback_debug::on_backward_prop_begin, lbann::lbann_callback_debug::on_backward_prop_end, lbann::lbann_callback_debug::on_batch_evaluate_begin, lbann::lbann_callback_debug::on_batch_evaluate_end, lbann::lbann_callback_debug::on_evaluate_forward_prop_begin, lbann::lbann_callback_debug::on_evaluate_forward_prop_end, lbann::lbann_callback_debug_io::on_forward_prop_begin, lbann::lbann_callback_debug_io::print_fp_start, lbann::lbann_callback_debug_io::print_phase_start, lbann::lbann_callback_debug_io::on_evaluate_forward_prop_begin, lbann::lbann_callback_dump_activations::on_forward_prop_end, lbann::lbann_callback_dump_activations::on_test_end, lbann::lbann_callback_dump_gradients::on_backward_prop_end, lbann::lbann_callback_dump_minibatch_sample_indices::dump_to_file, lbann::lbann_callback_dump_weights::dump_weights, lbann::lbann_callback_early_stopping::on_validation_end, lbann::lbann_callback_gradient_check::on_test_begin, lbann::lbann_callback_imcomm::on_train_begin, lbann::lbann_callback_imcomm::on_epoch_end, lbann::lbann_callback_imcomm::on_backward_prop_end, lbann::lbann_callback_imcomm::do_summary, lbann::lbann_callback_io::on_epoch_end, lbann::lbann_callback_io::on_test_end, lbann::lbann_callback_learning_rate::on_epoch_end, lbann::lbann_callback_ltfb::setup, lbann::lbann_callback_print::setup, lbann::lbann_callback_print::on_epoch_begin, lbann::lbann_callback_print::report_results, lbann::lbann_callback_save_images::save_image, lbann::lbann_callback_save_model::on_epoch_end, lbann::lbann_callback_summary::on_batch_end, lbann::lbann_callback_summary::on_test_end, lbann::lbann_callback_timeline::on_train_begin, lbann::lbann_callback_timeline::on_train_end, lbann::lbann_callback_timer::timing_end, lbann::lbann_callback_variable_minibatch::on_train_begin, lbann::lbann_callback_variable_minibatch::on_epoch_end, lbann::objective_function_term::setup.
int lbann::model::get_cur_epoch() const
Get the current epoch for the model.
References m_current_epoch.
Referenced by lbann::lbann_callback_check_init::on_train_begin, lbann::lbann_callback_checknan::dump_network, lbann::lbann_callback_checkpoint::need_checkpoint, lbann::lbann_callback_checkpoint::checkpointShared, lbann::lbann_callback_debug::on_forward_prop_begin, lbann::lbann_callback_debug::on_forward_prop_end, lbann::lbann_callback_debug::on_backward_prop_begin, lbann::lbann_callback_debug::on_backward_prop_end, lbann::lbann_callback_debug_io::print_fp_start, lbann::lbann_callback_dump_activations::on_forward_prop_end, lbann::lbann_callback_dump_gradients::on_backward_prop_end, lbann::lbann_callback_dump_minibatch_sample_indices::dump_to_file, lbann::lbann_callback_dump_weights::dump_weights, lbann::lbann_callback_io::on_epoch_end, lbann::lbann_callback_io::on_test_end, lbann::lbann_callback_learning_rate::on_epoch_end, lbann::lbann_callback_step_learning_rate::global_schedule, lbann::lbann_callback_adaptive_learning_rate::global_schedule, lbann::lbann_callback_drop_fixed_learning_rate::global_schedule, lbann::lbann_callback_linear_growth_learning_rate::global_schedule, lbann::lbann_callback_print::on_epoch_begin, lbann::lbann_callback_print::report_results, lbann::lbann_callback_save_images::on_epoch_end, lbann::lbann_callback_timer::timing_end, lbann::lbann_callback_variable_minibatch::on_train_begin, lbann::lbann_callback_variable_minibatch::on_epoch_end, lbann::lbann_callback_step_minibatch::schedule, lbann::lbann_callback_minibatch_schedule::schedule.
int lbann::model::get_cur_step() const
Get the current step for the model.
References m_current_step.
Referenced by lbann::lbann_callback_check_dataset::on_forward_prop_end, lbann::lbann_callback_checknan::on_forward_prop_end, lbann::lbann_callback_checknan::on_backward_prop_end, lbann::lbann_callback_checknan::on_batch_end, lbann::lbann_callback_checknan::dump_network, lbann::lbann_callback_checkpoint::need_checkpoint, lbann::lbann_callback_checkpoint::checkpointShared, lbann::lbann_callback_checksmall::on_forward_prop_end, lbann::lbann_callback_checksmall::on_backward_prop_end, lbann::lbann_callback_checksmall::on_batch_end, lbann::lbann_callback_debug::on_forward_prop_begin, lbann::lbann_callback_debug::on_forward_prop_end, lbann::lbann_callback_debug::on_backward_prop_begin, lbann::lbann_callback_debug::on_backward_prop_end, lbann::lbann_callback_debug_io::print_fp_start, lbann::lbann_callback_debug_io::print_phase_start, lbann::lbann_callback_dump_activations::on_forward_prop_end, lbann::lbann_callback_dump_gradients::on_backward_prop_end, lbann::lbann_callback_dump_minibatch_sample_indices::dump_to_file, lbann::lbann_callback_dump_minibatch_sample_indices::on_forward_prop_end, lbann::lbann_callback_imcomm::do_summary, lbann::lbann_callback_poly_learning_rate::optimizer_schedule, lbann::lbann_callback_ltfb::on_batch_begin, lbann::lbann_callback_summary::on_batch_end, lbann::lbann_callback_summary::on_epoch_end, lbann::lbann_callback_summary::on_test_end, lbann::lbann_callback_summary::save_histograms, lbann::lbann_callback_timer::batch_timing_end, do_batch_begin_cbs, do_batch_end_cbs, do_model_forward_prop_begin_cbs, do_model_forward_prop_end_cbs, do_layer_forward_prop_begin_cbs, do_layer_forward_prop_end_cbs, do_model_backward_prop_begin_cbs, do_model_backward_prop_end_cbs, do_layer_backward_prop_begin_cbs, do_layer_backward_prop_end_cbs, do_model_optimize_begin_cbs, do_model_optimize_end_cbs, do_weight_optimize_begin_cbs, do_weight_optimize_end_cbs, summarize_stats, summarize_matrices.
int lbann::model::get_cur_validation_step() const
Get the current validation step for the model.
References m_current_validation_step.
Referenced by lbann::lbann_callback_check_dataset::on_evaluate_forward_prop_end, lbann::lbann_callback_debug::on_batch_evaluate_begin, lbann::lbann_callback_debug::on_batch_evaluate_end, lbann::lbann_callback_debug::on_evaluate_forward_prop_begin, lbann::lbann_callback_debug::on_evaluate_forward_prop_end, lbann::lbann_callback_debug_io::print_fp_start, lbann::lbann_callback_debug_io::print_phase_start, lbann::lbann_callback_dump_minibatch_sample_indices::on_evaluate_forward_prop_end.
int lbann::model::get_cur_testing_step() const
Get the current testing step for the model.
References m_current_testing_step.
Referenced by lbann::lbann_callback_check_dataset::on_evaluate_forward_prop_end, lbann::lbann_callback_debug::on_batch_evaluate_begin, lbann::lbann_callback_debug::on_batch_evaluate_end, lbann::lbann_callback_debug::on_evaluate_forward_prop_begin, lbann::lbann_callback_debug::on_evaluate_forward_prop_end, lbann::lbann_callback_debug_io::print_fp_start, lbann::lbann_callback_debug_io::print_phase_start, lbann::lbann_callback_dump_minibatch_sample_indices::on_evaluate_forward_prop_end.
void lbann::model::set_execution_mode(execution_mode mode)
Set the model (and all layers') execution mode.
References m_execution_mode.
Referenced by lbann::anonymous_namespace{callback_ltfb.cpp}::evaluate, reset_mode_and_model.
execution_mode lbann::model::get_execution_mode() const
Get the model's execution mode.
References m_execution_mode.
Referenced by lbann::generic_input_layer::fp_compute, lbann::generic_input_layer::update_compute, lbann::generic_input_layer::get_data_reader, lbann::generic_input_layer::get_num_parallel_readers, lbann::generic_input_layer::get_num_iterations_per_epoch, lbann::generic_input_layer::get_current_step_in_epoch, lbann::generic_input_layer::get_last_mini_batch_size, lbann::generic_input_layer::get_current_mini_batch_size, lbann::generic_input_layer::get_current_global_mini_batch_size, lbann::generic_input_layer::get_world_master_mini_batch_adjustment, lbann::generic_input_layer::get_current_world_master_mini_batch_adjustment, lbann::generic_input_layer::select_dataset, lbann::generic_target_layer::fp_compute, lbann::generic_target_layer::update_compute, lbann::reconstruction_layer< T_layout >::summarize_stats, lbann::batch_normalization< T_layout >::fp_compute_gpu, lbann::batch_normalization< T_layout >::bp_compute_gpu, lbann::batch_normalization< T_layout >::fp_compute_cpu, lbann::batch_normalization< T_layout >::bp_compute_cpu, lbann::dropout< T_layout >::fp_setup_data, lbann::dropout< T_layout >::fp_compute_cpu, lbann::dropout< T_layout >::bp_compute_cpu, lbann::dropout< T_layout >::fp_compute_gpu, lbann::dropout< T_layout >::bp_compute_gpu, lbann::selu_dropout< T_layout >::fp_compute, lbann::selu_dropout< T_layout >::bp_compute, lbann::bernoulli_layer< T_layout >::fp_compute, lbann::gaussian_layer< T_layout >::fp_compute, lbann::uniform_layer< T_layout >::fp_compute, lbann::lbann_callback_check_dataset::on_evaluate_forward_prop_end, lbann::lbann_callback_check_reconstruction_error::on_epoch_end, lbann::lbann_callback_debug::on_batch_begin, lbann::lbann_callback_debug::on_forward_prop_begin, lbann::lbann_callback_debug::on_forward_prop_end, lbann::lbann_callback_debug::on_backward_prop_begin, lbann::lbann_callback_debug::on_backward_prop_end, lbann::lbann_callback_debug::on_batch_evaluate_begin, lbann::lbann_callback_debug::on_batch_evaluate_end, lbann::lbann_callback_debug::on_evaluate_forward_prop_begin, lbann::lbann_callback_debug::on_evaluate_forward_prop_end, lbann::lbann_callback_debug_io::on_forward_prop_begin, lbann::lbann_callback_debug_io::print_fp_start, lbann::lbann_callback_debug_io::on_evaluate_forward_prop_begin, lbann::lbann_callback_dump_minibatch_sample_indices::dump_to_file, lbann::lbann_callback_dump_minibatch_sample_indices::on_evaluate_forward_prop_end, lbann::lbann_callback_early_stopping::on_validation_end, lbann::lbann_callback_gradient_check::compute_objective_function, lbann::lbann_callback_imcomm::on_epoch_end, lbann::lbann_callback_imcomm::on_backward_prop_end, lbann::lbann_callback_adaptive_learning_rate::global_schedule, lbann::anonymous_namespace{callback_ltfb.cpp}::evaluate, lbann::lbann_callback_ltfb::on_batch_begin, lbann::lbann_callback_print::report_results, lbann::lbann_callback_summary::on_epoch_end, lbann::lbann_callback_summary::on_test_end, lbann::lbann_callback_timer::timing_end.
void lbann::model::set_current_mini_batch_size(int mini_batch_size)
Set the model's current mini-batch size.
References m_current_mini_batch_size.
Referenced by lbann::generic_input_layer::fp_setup_data, lbann::generic_input_layer::fp_compute.
int lbann::model::get_current_mini_batch_size() const
Get the model's current mini-batch size.
References m_current_mini_batch_size.
Referenced by lbann::generic_input_layer::fp_compute, lbann::generic_target_layer::fp_compute, lbann::evaluation_layer< T_layout >::fp_compute, lbann::lbann_callback_gradient_check::on_test_begin, lbann::lbann_callback_gradient_check::compute_objective_function, lbann::Layer::forward_prop, lbann::Layer::back_prop, evaluate_mini_batch, train_mini_batch.
int lbann::model::get_max_mini_batch_size() const
Get the model's maximum mini-batch size.
References m_max_mini_batch_size.
Referenced by lbann::generic_input_layer::setup_data, lbann::generic_target_layer::setup_data, lbann::lbann_callback_check_dataset::on_epoch_end, lbann::lbann_callback_variable_minibatch::on_train_begin, lbann::lbann_callback_variable_minibatch::on_epoch_end, lbann::Layer::setup_data, lbann::Layer::setup_gpu, lbann::Layer::get_bp_output, lbann::categorical_accuracy_metric::setup, lbann::pearson_correlation_metric::setup.
int lbann::model::get_effective_mini_batch_size() const
Get the model's effective mini-batch size.
References m_effective_mini_batch_size.
Referenced by lbann::base_convolution_layer::compute_gradients_cudnn, lbann::base_convolution_layer::compute_gradients_im2col, lbann::batch_normalization< T_layout >::bp_compute_gpu, lbann::batch_normalization< T_layout >::bp_compute_cpu.
void lbann::model::set_effective_mini_batch_size(int mini_batch_size)
Set the model's effective mini-batch size.
References m_effective_mini_batch_size, get_num_iterations_per_epoch.
Referenced by lbann::generic_input_layer::fp_setup_data.
int lbann::model::get_num_iterations_per_epoch(execution_mode mode) const
References m_layers, lbann::generic_input_layer::get_num_iterations_per_epoch.
Referenced by set_effective_mini_batch_size, lbann::lbann_callback_poly_learning_rate::setup.
int lbann::model::get_current_phase() const
Get the current phase (multiple epochs) in layer-wise model training.
References m_current_phase, summarize_stats, summarize_matrices.
Referenced by lbann::lbann_callback_save_images::on_phase_end.
void lbann::model::summarize_stats(lbann_summary &summarizer)
Summarize statistics (e.g. timers, counters); these should be computable quickly.
References m_layers, get_cur_step, lbann::lbann_summary::reduce_scalar, m_objective_function, lbann::objective_function::get_mean_value, m_execution_mode, lbann::objective_function::get_evaluation_time, lbann::objective_function::get_differentiation_time, lbann::objective_function::reset_counters, m_metrics.
Referenced by get_current_phase, lbann::lbann_callback_summary::on_batch_end.
void lbann::model::summarize_matrices(lbann_summary &summarizer)
Summarize matrices (e.g. means); these are called less frequently and can be more expensive.
References m_layers, get_cur_step.
Referenced by get_current_phase, lbann::lbann_callback_summary::on_batch_end.
bool lbann::model::get_terminate_training() const
Return true if the flag to stop training is set.
References m_terminate_training.
Referenced by lbann::greedy_layerwise_autoencoder::train, train.
void lbann::model::set_terminate_training(bool f)
Set the terminate training flag (on or off).
References m_terminate_training, train, evaluate, collect_indices, save_to_checkpoint_shared, load_from_checkpoint_shared, write_proto.
Referenced by lbann::lbann_callback_early_stopping::on_validation_end.
void lbann::model::train(int num_epochs)
Train model.
References do_train_begin_cbs, m_current_epoch, get_terminate_training, reset_mode_and_model, training, do_epoch_begin_cbs, train_mini_batch, do_epoch_end_cbs, reset_epoch_statistics, evaluate, validation, do_train_end_cbs.
Referenced by set_terminate_training.
void lbann::model::evaluate(execution_mode mode)
Evaluate model.
References is_execution_mode_valid, validation, testing, reset_epoch_statistics, reset_mode_and_model, do_evaluate_begin_cbs, evaluate_mini_batch, do_evaluate_end_cbs.
Referenced by set_terminate_training, lbann::anonymous_namespace{callback_ltfb.cpp}::evaluate, lbann::greedy_layerwise_autoencoder::train, train.
void lbann::model::collect_indices(execution_mode mode)
Run one epoch using only the input layer; this supports data_store functionality
References reset_mode_and_model, m_layers, reset_epoch_statistics.
Referenced by set_terminate_training, lbann::generic_data_store::setup.
bool lbann::model::save_to_checkpoint_shared(persist &p, bool val_end)
Checkpoint model to given file descriptor, return number of bytes written
References lbann::persist::get_rank, lbann::persist::write_uint32, lbann::train, m_execution_mode, m_terminate_training, lbann::persist::write_uint64, m_current_epoch, m_current_step, m_current_testing_step, m_max_mini_batch_size, m_current_mini_batch_size, m_current_phase, lbann::validate, m_current_validation_step, lbann::save_rng_to_checkpoint_shared.
Referenced by set_terminate_training, lbann::lbann_callback_checkpoint::checkpointShared, lbann::sequential_model::save_to_checkpoint_shared.
bool lbann::model::load_from_checkpoint_shared(persist &p)
Restore model by reading checkpoint from given file descriptor, return number of bytes read
References lbann::persist::get_rank, lbann::persist::read_uint32, lbann::train, lbann::lbann_model_header::execution_mode, lbann::lbann_model_header::terminate_training, lbann::persist::read_uint64, lbann::lbann_model_header::current_epoch, lbann::lbann_model_header::current_step, lbann::validate, lbann::lbann_model_header::current_validation_step, lbann::lbann_model_header::current_testing_step, lbann::lbann_model_header::max_mini_batch_size, lbann::lbann_model_header::current_mini_batch_size, lbann::lbann_model_header::current_phase, lbann::load_rng_from_checkpoint_shared, m_execution_mode, m_terminate_training, m_current_epoch, m_current_step, m_current_validation_step, m_current_testing_step, m_max_mini_batch_size, m_current_mini_batch_size, m_current_phase.
Referenced by set_terminate_training, lbann::lbann_callback_checkpoint::restartShared, lbann::sequential_model::load_from_checkpoint_shared.
void lbann::model::write_proto(lbann_data::Model *proto)
Write model to proto file
References m_comm, lbann::lbann_comm::am_world_master, m_max_mini_batch_size.
Referenced by set_terminate_training, lbann::lbann_callback_save_model::on_epoch_end, lbann::sequential_model::write_proto.
bool lbann::model::is_execution_mode_valid(execution_mode mode) const
Check if the model execution mode is valid.
References m_layers.
Referenced by evaluate.
std::string lbann::model::print_layer_description(const Layer *layer) const
Print out the description of a layer set up.
References lbann::Layer::get_name, lbann::Layer::get_type, lbann::Layer::get_num_prev_neurons, lbann::Layer::get_num_neurons, lbann::Layer::get_topo_description, lbann::Layer::is_frozen.
Referenced by setup_layers, lbann::recurrent_model::setup_layers, lbann::siamese_model::setup_layers.
void lbann::model::construct_layer_graph(std::set< int > &nodes, std::map< int, std::set< int >> &edges) const
Construct a layer graph.
References m_layers.
Referenced by lbann::directed_acyclic_graph_model::setup_layer_execution_order, lbann::sequential_model::setup_layer_topology.
void lbann::model::permute_layers(const std::vector< int > &permutation)
Reorder layers.
References m_layers.
Referenced by lbann::directed_acyclic_graph_model::setup_layer_execution_order.
void lbann::model::remap_pointers(const std::unordered_map< Layer *, Layer *> &layer_map, const std::unordered_map< weights *, weights *> &weights_map)
Remap pointers. Layer and weights pointers are remapped using the provided maps. If a pointer is not a key in the corresponding map, the pointer is not changed.
References m_objective_function, lbann::objective_function::get_layer_pointers, lbann::objective_function::set_layer_pointers, lbann::objective_function::get_weights_pointers, lbann::objective_function::set_weights_pointers, m_metrics, m_layers.
Referenced by model, operator=, replace_weights.
void lbann::model::freeze_layers_under_frozen_surface()
In case that a layer is frozen, also freeze layers that precede it if that makes senses for the particular model, such as sequential or siamese. For othe models, users can manually control the behaivor by indicating whether to freeze each layer in the model description prototext.
References m_layers.
Referenced by lbann::sequential_model::setup_layer_topology.
void lbann::model::setup_layer_topology()
Set up topology of layer graph. Called in setup function. All layers in connected component of layer graph are added to the model and all parent/child relationships between layers are reciprocated.
References add_connected_layers, m_layers, add_dummy_layers, add_split_layers.
Referenced by setup, lbann::recurrent_model::setup_layer_topology, lbann::sequential_model::setup_layer_topology, lbann::siamese_model::setup_layer_topology.
void lbann::model::setup_layer_execution_order()
Set up layer execution order. Called in setup function.
References m_layers.
Referenced by lbann::directed_acyclic_graph_model::setup_layer_execution_order, setup.
void lbann::model::setup_layers()
Set up layers. Called in setup function.
References m_layers, m_comm, lbann::lbann_comm::am_world_master, print_layer_description.
Referenced by setup.
void lbann::model::setup_weights()
Set up weights. Called in setup function. All weights being used by layers or the objective function are added to the model and all unused weights are deleted.
References m_weights, m_layers, m_objective_function, lbann::objective_function::get_weights_pointers.
Referenced by setup.
void lbann::model::reset_mode_and_model(execution_mode mode)
Reset model pointer and execution mode.
References set_execution_mode, m_layers.
Referenced by lbann::greedy_layerwise_autoencoder::train, evaluate, collect_indices, train, evaluate_mini_batch, train_mini_batch.
void lbann::model::reset_epoch_statistics(execution_mode mode)
Reset model statistics for an epoch.
References m_objective_function, lbann::objective_function::reset_statistics, m_metrics.
Referenced by lbann::greedy_layerwise_autoencoder::train, evaluate, collect_indices, train.
bool lbann::model::evaluate_mini_batch(execution_mode mode)
Evaluate model on a mini-batch
References reset_mode_and_model, do_batch_begin_cbs, forward_prop, m_objective_function, lbann::objective_function::start_evaluation, get_current_mini_batch_size, lbann::objective_function::finish_evaluation, m_metrics, update_layers, m_execution_mode, validation, m_current_validation_step, testing, m_current_testing_step, do_batch_end_cbs.
Referenced by evaluate.
bool lbann::model::train_mini_batch()
Train model on a mini-batch.
References reset_mode_and_model, training, do_batch_begin_cbs, clear_gradients, forward_prop, m_objective_function, lbann::objective_function::start_evaluation, get_current_mini_batch_size, m_metrics, clear_error_signals, lbann::objective_function::differentiate, backward_prop, lbann::objective_function::compute_weight_regularization, lbann::objective_function::finish_evaluation, update_weights, update_layers, m_current_step, do_batch_end_cbs.
Referenced by lbann::greedy_layerwise_autoencoder::train, train.
void lbann::model::forward_prop(execution_mode mode)
Forward propagation step.
References do_model_forward_prop_begin_cbs, m_layers, do_layer_forward_prop_begin_cbs, do_layer_forward_prop_end_cbs, do_model_forward_prop_end_cbs.
Referenced by lbann::greedy_layerwise_autoencoder::forward_prop, evaluate_mini_batch, train_mini_batch.
void lbann::model::backward_prop()
Backward propagation step.
References do_model_backward_prop_begin_cbs, m_layers, do_layer_backward_prop_begin_cbs, lbann::Layer::back_prop, do_layer_backward_prop_end_cbs, m_weights, do_model_backward_prop_end_cbs.
Referenced by lbann::greedy_layerwise_autoencoder::backward_prop, train_mini_batch.
void lbann::model::clear_gradients()
Clear each optimizer's gradient. This must be called before training forward prop since layers set an optimizer flag during forward prop.
References m_weights, lbann::optimizer::clear_gradient.
Referenced by train_mini_batch.
void lbann::model::clear_error_signals()
Clear each layer's error signal tensor. This must be called after the input layer's forward prop since it determines the current mini-batch size.
References m_layers, m_current_mini_batch_size.
Referenced by train_mini_batch.
void lbann::model::update_weights()
Update weights step.
References do_model_optimize_begin_cbs, m_weights, do_weight_optimize_begin_cbs, lbann::optimizer::step, do_weight_optimize_end_cbs, do_model_optimize_end_cbs.
Referenced by train_mini_batch.
bool lbann::model::update_layers()
Update layers step.
References m_layers.
Referenced by evaluate_mini_batch, train_mini_batch.
void lbann::model::do_train_begin_cbs()
Execute callbacks at start of training.
References m_callbacks.
Referenced by lbann::greedy_layerwise_autoencoder::train, train.
void lbann::model::do_train_end_cbs()
Execute callbacks at end of training.
References m_callbacks.
Referenced by lbann::greedy_layerwise_autoencoder::train, train.
void lbann::model::do_evaluate_begin_cbs(execution_mode mode)
Execute callbacks at start of evaluation.
References m_callbacks, validation, testing.
Referenced by evaluate.
void lbann::model::do_evaluate_end_cbs(execution_mode mode)
Execute callbacks at end of evaluation.
References m_callbacks, validation, testing.
Referenced by evaluate.
void lbann::model::do_epoch_begin_cbs()
Execute callbacks at start of epoch.
References m_callbacks.
Referenced by lbann::greedy_layerwise_autoencoder::train, train.
void lbann::model::do_epoch_end_cbs()
Execute callbacks at end of epoch.
References m_callbacks.
Referenced by lbann::greedy_layerwise_autoencoder::train, train.
void lbann::model::do_batch_begin_cbs(execution_mode mode)
Execute callbacks at start of mini-batch.
References m_callbacks, training, get_cur_step, validation, testing.
Referenced by evaluate_mini_batch, train_mini_batch.
void lbann::model::do_batch_end_cbs(execution_mode mode)
Execute callbacks at end of mini-batch.
References m_callbacks, training, get_cur_step, validation, testing.
Referenced by evaluate_mini_batch, train_mini_batch.
void lbann::model::do_model_forward_prop_begin_cbs(execution_mode mode)
Execute callbacks at start of model forward propagation.
References m_callbacks, training, get_cur_step, validation, testing.
Referenced by lbann::greedy_layerwise_autoencoder::forward_prop, forward_prop.
void lbann::model::do_model_forward_prop_end_cbs(execution_mode mode)
Execute callbacks at end of model forward propagation.
References m_callbacks, training, get_cur_step, validation, testing.
Referenced by lbann::greedy_layerwise_autoencoder::forward_prop, forward_prop.
void lbann::model::do_layer_forward_prop_begin_cbs(execution_mode mode, Layer *l)
Execute callbacks at start of layer forward propagation.
References m_callbacks, training, get_cur_step, validation, testing.
Referenced by lbann::greedy_layerwise_autoencoder::forward_prop, forward_prop.
void lbann::model::do_layer_forward_prop_end_cbs(execution_mode mode, Layer *l)
Execute callbacks at end of layer forward propagation.
References m_callbacks, training, get_cur_step, validation, testing.
Referenced by lbann::greedy_layerwise_autoencoder::forward_prop, forward_prop.
void lbann::model::do_model_backward_prop_begin_cbs()
Execute callbacks at start of model backward propagation.
References m_callbacks, get_cur_step.
Referenced by lbann::greedy_layerwise_autoencoder::backward_prop, backward_prop.
void lbann::model::do_model_backward_prop_end_cbs()
Execute callbacks at end of model backward propagation.
References m_callbacks, get_cur_step.
Referenced by lbann::greedy_layerwise_autoencoder::backward_prop, backward_prop.
void lbann::model::do_layer_backward_prop_begin_cbs(Layer *l)
Execute callbacks at start of layer backward propagation.
References m_callbacks, get_cur_step.
Referenced by lbann::greedy_layerwise_autoencoder::backward_prop, backward_prop.
void lbann::model::do_layer_backward_prop_end_cbs(Layer *l)
Execute callbacks at end of layer backward propagation.
References m_callbacks, get_cur_step.
Referenced by lbann::greedy_layerwise_autoencoder::backward_prop, backward_prop.
void lbann::model::do_model_optimize_begin_cbs()
Execute callbacks at start of model optimization.
References m_callbacks, get_cur_step.
Referenced by update_weights.
void lbann::model::do_model_optimize_end_cbs()
Execute callbacks at end of model optimization.
References m_callbacks, get_cur_step.
Referenced by update_weights.
void lbann::model::do_weight_optimize_begin_cbs(weights *w)
Execute callbacks at the start of weight optimization.
References m_callbacks, get_cur_step.
Referenced by update_weights.
void lbann::model::do_weight_optimize_end_cbs(weights *w)
Execute callbacks at the end of weight optimization.
References m_callbacks, get_cur_step.
Referenced by update_weights.
void lbann::model::add_connected_layers()
Search layer graph and add all connected layers.
References m_layers, lbann::Layer::get_parent_layers, lbann::Layer::get_child_layers.
Referenced by setup_layer_topology.
void lbann::model::add_dummy_layers()
Insert dummy layers after layers with too few children. If a layer expects more child layers than it has, add dummy layers until it has enough children.
References m_layers, lbann::Layer::get_cudnn_manager, DATA_PARALLEL, m_comm, MODEL_PARALLEL, lbann::Layer::set_name, lbann::Layer::add_parent_layer.
Referenced by setup_layer_topology.
void lbann::model::add_split_layers()
Insert split layers after layers with too many children. If a layer expects one child layer but has multiple, add a split layer. The split layer will be the original layer's child and the split layer's children will be the original children.
References m_layers, lbann::Layer::get_cudnn_manager, DATA_PARALLEL, m_comm, MODEL_PARALLEL, lbann::Layer::set_name, lbann::Layer::add_child_layer, lbann::Layer::get_parent_layers, lbann::Layer::add_parent_layer.
Referenced by setup_layer_topology.