lbann::lbann_callback_summary
int lbann::lbann_callback_summary::m_mat_interval
Interval for doing matrix summarization.
Referenced by on_batch_end.
lbann::lbann_callback_summary::lbann_callback_summary(lbann_summary *summarizer, int batch_interval=1, int mat_interval=25)
summarizer The summary object to write to; this callback takes ownership of it.
Referenced by copy.
lbann::lbann_callback_summary::~lbann_callback_summary() override
References lbann::lbann_callback::m_summarizer.
lbann::lbann_callback_summary::lbann_callback_summary(const lbann_callback_summary &)=default
lbann_callback_summary& lbann::lbann_callback_summary::operator=(const lbann_callback_summary &)=default
lbann_callback_summary* lbann::lbann_callback_summary::copy() const override
References lbann_callback_summary, on_train_begin, on_batch_end, on_epoch_end, on_test_end.
void lbann::lbann_callback_summary::on_train_begin(model *m) override
Called at the beginning of training.
References save_histograms.
Referenced by copy.
void lbann::lbann_callback_summary::on_batch_end(model *m) override
Called immediately after the end of a (mini-)batch.
References lbann::model::summarize_stats, lbann::lbann_callback::m_summarizer, m_mat_interval, lbann::model::get_cur_step, lbann::model::summarize_matrices, comm, lbann::model::get_comm, lbann::lbann_comm::get_bytes_sent, lbann::lbann_comm::get_bytes_received, lbann::lbann_comm::get_num_model_barriers, lbann::lbann_comm::get_num_intermodel_barriers, lbann::lbann_comm::get_num_global_barriers, lbann::lbann_comm::reset_stats_counters, lbann::lbann_summary::sum_reduce_scalar, lbann::lbann_summary::reduce_scalar.
Referenced by copy.
void lbann::lbann_callback_summary::on_epoch_end(model *m) override
Called immediate after the end of each epoch.
References lbann::model::get_metrics, lbann::model::get_execution_mode, lbann::lbann_callback::m_summarizer, lbann::lbann_summary::reduce_scalar, lbann::model::get_cur_step, save_histograms, lbann::lbann_summary::flush.
Referenced by copy.
void lbann::lbann_callback_summary::on_test_end(model *m) override
Called immediately after the end of testing.
References comm, lbann::model::get_comm, lbann::model::get_metrics, lbann::model::get_execution_mode, lbann::lbann_callback::m_summarizer, lbann::lbann_summary::reduce_scalar, lbann::model::get_cur_step, lbann::lbann_comm::reset_stats_counters, lbann::model::get_layers.
Referenced by copy.
std::string lbann::lbann_callback_summary::name() const override
Return this callback's name.
References save_histograms.
void lbann::lbann_callback_summary::save_histograms(model *m)
Write out histograms from the model's layers.
References lbann::model::get_layers, lbann::lbann_callback::m_summarizer, lbann::lbann_summary::reduce_histogram, lbann::model::get_cur_step, lbann::model::get_weights, lbann::optimizer::get_gradient.
Referenced by name, on_train_begin, on_epoch_end.