lbann::lbann_callback_imcomm
comm_type
comm_type lbann::lbann_callback_imcomm::m_default_ct
Default communication type.
Referenced by setup.
std::unordered_map<weights *, imcomm_params> lbann::lbann_callback_imcomm::m_weights_params
Per-weights parameters.
Referenced by lbann_callback_imcomm, set_weights_comm, set_weights_adaptive, set_weights_threshold, setup, on_epoch_end, on_backward_prop_end, do_summary.
lbann_quantizer lbann::lbann_callback_imcomm::m_quantizer
Quantizer for quantization of updates, if needed.
Referenced by on_backward_prop_end, do_summary.
lbann::lbann_callback_imcomm::lbann_callback_imcomm(comm_type ct=NORMAL, lbann_summary *summarizer=nullptr)
Initialize with ct being used for all weights.
Referenced by copy.
lbann::lbann_callback_imcomm::lbann_callback_imcomm(const lbann_callback_imcomm &)=default
lbann_callback_imcomm& lbann::lbann_callback_imcomm::operator=(const lbann_callback_imcomm &)=default
lbann_callback_imcomm* lbann::lbann_callback_imcomm::copy() const override
References lbann_callback_imcomm, set_weights_comm, set_weights_adaptive, set_weights_threshold, setup, on_train_begin, on_epoch_end, on_backward_prop_end.
lbann::lbann_callback_imcomm::lbann_callback_imcomm(comm_type ct, std::unordered_set< weights *> weights_list, lbann_summary *summarizer=nullptr)
Convenience initialization to do one update type for specific weights. Implies no inter-model updates for other weights.
References m_weights_params.
void lbann::lbann_callback_imcomm::set_weights_comm(weights *w, comm_type ct)
Choose comm type ct for weights.
References m_weights_params.
Referenced by copy.
void lbann::lbann_callback_imcomm::set_weights_adaptive(weights *w, int proportion)
Set weights to use adaptive quantization with proportion.
References m_weights_params, ADAPTIVE_QUANTIZATION.
Referenced by copy.
void lbann::lbann_callback_imcomm::set_weights_threshold(weights *w, DataType pos_thresh, DataType neg_thresh)
Set weights to use threshold quantization with given thresholds.
References m_weights_params, THRESH_QUANTIZATION.
Referenced by copy.
void lbann::lbann_callback_imcomm::setup(model *m) override
Do initialization for this model.
References lbann::model::get_weights, m_weights_params, m_default_ct, NONE, lbann::lbann_callback_imcomm::imcomm_params::ct, ct_needs_reshape, ct_does_quantization, lbann::optimizer::get_gradient, lbann::lbann_callback_imcomm::imcomm_params::reshape_height, lbann::lbann_callback_imcomm::imcomm_params::error, lbann::lbann_callback_imcomm::imcomm_params::reshape_width.
Referenced by copy.
void lbann::lbann_callback_imcomm::on_train_begin(model *m) override
Make sure all models have the same weights.
References comm, lbann::model::get_comm, lbann::lbann_comm::get_num_models, lbann::model::get_weights, lbann::lbann_comm::intermodel_broadcast_matrix.
Referenced by copy.
void lbann::lbann_callback_imcomm::on_epoch_end(model *m) override
Clear out remaining error if needed.
References comm, lbann::model::get_comm, lbann::lbann_comm::get_num_models, lbann::model::get_execution_mode, training, lbann::model::get_weights, m_weights_params, ct_does_quantization, lbann::lbann_callback_imcomm::imcomm_params::ct, lbann::lbann_comm::intermodel_sum_matrix, lbann::lbann_callback_imcomm::imcomm_params::error, lbann::optimizer::clear_gradient, lbann::optimizer::get_gradient, lbann::lbann_callback_imcomm::imcomm_params::reshape_height, reshape_mat, lbann::lbann_callback_imcomm::imcomm_params::reshape_width, lbann::optimizer::add_to_gradient, lbann::optimizer::step.
Referenced by copy.
void lbann::lbann_callback_imcomm::on_backward_prop_end(model *m) override
Do inter-model gradient updates.
References comm, lbann::model::get_comm, lbann::lbann_comm::get_num_models, lbann::model::get_execution_mode, training, lbann::model::get_weights, lbann::get_time, m_weights_params, lbann::lbann_callback_imcomm::imcomm_params::ct, NONE, lbann::optimizer::get_gradient, lbann::lbann_callback_imcomm::imcomm_params::reshape_height, reshape_mat, lbann::lbann_callback_imcomm::imcomm_params::reshape_width, NORMAL, lbann::lbann_comm::intermodel_sum_matrix, ONEBIT_QUANTIZATION, m_quantizer, lbann::lbann_quantizer::intermodel_sum_onebit_quantized, lbann::lbann_callback_imcomm::imcomm_params::error, THRESH_QUANTIZATION, lbann::lbann_quantizer::intermodel_sum_threshold_quantized, lbann::lbann_callback_imcomm::imcomm_params::pos_thresh, lbann::lbann_callback_imcomm::imcomm_params::neg_thresh, ADAPTIVE_QUANTIZATION, lbann::lbann_quantizer::intermodel_sum_adaptive_quantized, lbann::lbann_callback_imcomm::imcomm_params::proportion, lbann::optimizer::clear_gradient, lbann::optimizer::add_to_gradient, do_summary.
Referenced by copy.
std::string lbann::lbann_callback_imcomm::name() const override
Return this callback's name.
bool lbann::lbann_callback_imcomm::ct_does_quantization(comm_type ct) const
Return true if the comm type does quantization.
References ONEBIT_QUANTIZATION, THRESH_QUANTIZATION, ADAPTIVE_QUANTIZATION.
Referenced by ct_needs_reshape, setup, on_epoch_end, do_summary.
bool lbann::lbann_callback_imcomm::ct_needs_reshape(comm_type ct) const
Return true if the comm type prefers reshaping.
References ct_does_quantization.
Referenced by setup.
void lbann::lbann_callback_imcomm::reshape_mat(Mat &mat, Mat &reshaped, El::Int height, El::Int width)
Get a matrix that reinterprets mat as being height x width. Assumes that mat.Height()*mat.Width() == height*width.
References do_summary, lbann::get_comm_type_name.
Referenced by on_epoch_end, on_backward_prop_end.
void lbann::lbann_callback_imcomm::do_summary(model *m, weights *w, EvalType im_time)
Summarize relevant statistics.
References lbann::lbann_callback::m_summarizer, comm, lbann::model::get_comm, lbann::weights::get_name, lbann::lbann_summary::reduce_scalar, lbann::model::get_cur_step, ct_does_quantization, m_weights_params, lbann::lbann_comm::get_ar_bytes_sent, lbann::lbann_comm::get_ar_bytes_received, lbann::weights::get_optimizer, lbann::optimizer::get_gradient, lbann::lbann_comm::get_ar_rs_bytes_sent, lbann::lbann_comm::get_ar_ag_bytes_sent, lbann::lbann_comm::get_ar_rs_bytes_received, lbann::lbann_comm::get_ar_ag_bytes_received, lbann::lbann_comm::get_ar_send_transform_time, lbann::lbann_comm::get_ar_recv_transform_time, lbann::lbann_comm::get_ar_recv_apply_transform_time, ADAPTIVE_QUANTIZATION, m_quantizer, lbann::lbann_quantizer::get_quantized_count, lbann::lbann_quantizer::reset_counters, lbann::lbann_comm::reset_stats_counters.
Referenced by reshape_mat, on_backward_prop_end.