lbann::data_store_imagenet_patches
lbann::data_store_imagenet_patches::data_store_imagenet_patches(generic_data_reader *reader, model *m)
ctor
References operator=.
Referenced by copy.
lbann::data_store_imagenet_patches::data_store_imagenet_patches(const data_store_imagenet_patches &)=default
copy ctor
data_store_imagenet_patches& lbann::data_store_imagenet_patches::operator=(const data_store_imagenet_patches &)=default
operator=
Referenced by data_store_imagenet_patches.
data_store_imagenet_patches* lbann::data_store_imagenet_patches::copy() const override
References data_store_imagenet_patches.
lbann::data_store_imagenet_patches::~data_store_imagenet_patches() override
dtor
References setup.
void lbann::data_store_imagenet_patches::setup() override
called by generic_data_reader::setup_data_store
References lbann::generic_data_store::m_rank, lbann::generic_data_store::m_reader, lbann::generic_data_reader::get_role, lbann::generic_data_store::set_name, lbann::data_store_imagenet::setup.
Referenced by ~data_store_imagenet_patches.