lbann::lbann_summary
lbann::lbann_summary::lbann_summary(std::string logdir, lbann_comm *comm)
void lbann::lbann_summary::reduce_mean(const std::string tag, const AbsDistMat &mat, int step)
Referenced by lbann::Layer::summarize_matrices.
void lbann::lbann_summary::reduce_min(const std::string tag, const AbsDistMat &mat, int step)
Referenced by lbann::Layer::summarize_matrices.
void lbann::lbann_summary::reduce_max(const std::string tag, const AbsDistMat &mat, int step)
Referenced by lbann::Layer::summarize_matrices.
void lbann::lbann_summary::reduce_stdev(const std::string tag, const AbsDistMat &mat, int step)
Referenced by lbann::Layer::summarize_matrices.
void lbann::lbann_summary::reduce_scalar(const std::string tag, DataType s, int step)
Referenced by lbann::reconstruction_layer< T_layout >::summarize_stats, lbann::lbann_callback_imcomm::do_summary, lbann::lbann_callback_summary::on_batch_end, lbann::lbann_callback_summary::on_epoch_end, lbann::lbann_callback_summary::on_test_end, lbann::lbann_callback_timer::batch_timing_end, lbann::Layer::summarize_stats, lbann::model::summarize_stats.
void lbann::lbann_summary::sum_reduce_scalar(const std::string tag, DataType s, int step)
Referenced by lbann::lbann_callback_summary::on_batch_end.
void lbann::lbann_summary::reduce_histogram(const std::string tag, const AbsDistMat &mat, int step)
Referenced by lbann::lbann_callback_summary::save_histograms.
void lbann::lbann_summary::reduce_2norm(const std::string tag, const AbsDistMat &mat, int step)
Referenced by lbann::Layer::summarize_matrices.
void lbann::lbann_summary::flush()
Referenced by lbann::lbann_callback_summary::on_epoch_end.