lbann::slice_layer
int lbann::slice_layer< T_layout >::m_slice_axis
Tensor dimension to slice.
Referenced by lbann::slice_layer< T_layout >::operator=, lbann::slice_layer< T_layout >::fp_compute_cpu, lbann::slice_layer< T_layout >::bp_compute_cpu, lbann::slice_layer< T_layout >::fp_compute_gpu, lbann::slice_layer< T_layout >::bp_compute_gpu, lbann::slice_layer< T_layout >::get_neuron_dims.
std::vector<int> lbann::slice_layer< T_layout >::m_slice_points
Slice points for each child layer.
Referenced by lbann::slice_layer< T_layout >::operator=, lbann::slice_layer< T_layout >::get_slice_points.
AbsDistMat* lbann::slice_layer< T_layout >::m_input_region_v
View into region of input tensor.
Referenced by lbann::slice_layer< T_layout >::operator=, lbann::slice_layer< T_layout >::~slice_layer, lbann::slice_layer< T_layout >::setup_matrices.
AbsDistMat* lbann::slice_layer< T_layout >::m_output_region_v
View into region of output tensor.
Referenced by lbann::slice_layer< T_layout >::operator=, lbann::slice_layer< T_layout >::~slice_layer, lbann::slice_layer< T_layout >::setup_matrices.
lbann::slice_layer< T_layout >::slice_layer(lbann_comm *comm, int slice_axis, std::vector< int > slice_points, cudnn::cudnn_manager *cudnn=nullptr)
References lbann::Layer::m_expected_num_child_layers, lbann::Layer::m_using_gpus, lbann::Layer::m_cudnn.
Referenced by lbann::slice_layer< T_layout >::copy.
lbann::slice_layer< T_layout >::slice_layer(const slice_layer &other)
slice_layer& lbann::slice_layer< T_layout >::operator=(const slice_layer &other)
References lbann::Layer::operator=, lbann::slice_layer< T_layout >::m_slice_axis, lbann::slice_layer< T_layout >::m_slice_points, lbann::slice_layer< T_layout >::m_input_region_v, lbann::slice_layer< T_layout >::m_output_region_v.
virtual lbann::slice_layer< T_layout >::~slice_layer() override
References lbann::slice_layer< T_layout >::m_input_region_v, lbann::slice_layer< T_layout >::m_output_region_v.
slice_layer* lbann::slice_layer< T_layout >::copy() const override
Copy function. This function dynamically allocates memory for a layer instance and instantiates a copy. The caller is responsible for deallocating the instance.
References lbann::slice_layer< T_layout >::slice_layer.
std::string lbann::slice_layer< T_layout >::get_type() const override
Get the layer type's name. A layer type name should be brief, human-readable description of the layer's mathematical operation.
data_layout lbann::slice_layer< T_layout >::get_data_layout() const override
Get data layout of the data tensors. We assume that the data layouts of the previous activations, activations, previous error signals, and error signals are the same. Each concrete layer that is templated on its data layout should override this function to return its template parameter.
Referenced by lbann::slice_layer< T_layout >::get_description.
std::string lbann::slice_layer< T_layout >::get_description() const override
Returns description of ctor params
References lbann::Layer::m_child_layers, lbann::Layer::get_data_layout_string, lbann::slice_layer< T_layout >::get_data_layout.
void lbann::slice_layer< T_layout >::setup_pointers() override
Setup pointers to parent and child layers. Called by the setup function. The base method checks that the number of parents and children are valid. Pointers to the parent/child layers are assumed to be already initialized.
References lbann::Layer::setup_pointers, lbann::Layer::get_num_children.
void lbann::slice_layer< T_layout >::setup_matrices(const El::Grid &grid) override
Instantiate distributed matrices. If the layer has already been setup, this function should destroy all matrices and reinstantiate them. However, it is not guaranteed that derived classes will obey this behavior.
References lbann::Layer::setup_matrices, lbann::slice_layer< T_layout >::m_input_region_v, lbann::slice_layer< T_layout >::m_output_region_v, lbann::Layer::get_prev_activations.
void lbann::slice_layer< T_layout >::setup_dims() override
Setup tensor dimensions Called by the setup function. The base method sets the dimensions of the activation tensors equal to the dimensions of the first previous activation tensor.
References lbann::Layer::setup_dims, lbann::Layer::m_child_layers, lbann::Layer::m_neuron_dims, lbann::Layer::get_layer_names.
std::vector<int>& lbann::slice_layer< T_layout >::get_slice_points()
Get slice points.
References lbann::slice_layer< T_layout >::m_slice_points.
Referenced by lbann::recurrent_model::setup_layers.
const std::vector<int>& lbann::slice_layer< T_layout >::get_slice_points() const
Get slice points (const).
References lbann::slice_layer< T_layout >::m_slice_points.
void lbann::slice_layer< T_layout >::fp_compute() override
Perform the computation for the forward propagation step.
References lbann::Layer::m_using_gpus, lbann::slice_layer< T_layout >::fp_compute_gpu, lbann::slice_layer< T_layout >::fp_compute_cpu.
void lbann::slice_layer< T_layout >::bp_compute() override
Perform the computation for the backward propagation step.
References lbann::Layer::m_using_gpus, lbann::slice_layer< T_layout >::bp_compute_gpu, lbann::slice_layer< T_layout >::bp_compute_cpu.
void lbann::slice_layer< T_layout >::fp_compute_cpu()
References lbann::Layer::get_prev_activations, lbann::Layer::m_prev_neuron_dims, lbann::slice_layer< T_layout >::m_slice_axis, lbann::Layer::get_num_children, lbann::Layer::get_activations.
Referenced by lbann::slice_layer< T_layout >::fp_compute.
void lbann::slice_layer< T_layout >::bp_compute_cpu()
References lbann::Layer::get_error_signals, lbann::Layer::m_prev_neuron_dims, lbann::slice_layer< T_layout >::m_slice_axis, lbann::Layer::get_num_children, lbann::Layer::get_prev_error_signals.
Referenced by lbann::slice_layer< T_layout >::bp_compute.
void lbann::slice_layer< T_layout >::fp_compute_gpu()
References lbann::Layer::m_prev_neuron_dims, lbann::slice_layer< T_layout >::m_slice_axis, lbann::Layer::m_cudnn, lbann::Layer::get_num_children.
Referenced by lbann::slice_layer< T_layout >::fp_compute.
void lbann::slice_layer< T_layout >::bp_compute_gpu()
References lbann::Layer::m_prev_neuron_dims, lbann::slice_layer< T_layout >::m_slice_axis, lbann::Layer::m_cudnn, lbann::Layer::get_num_children.
Referenced by lbann::slice_layer< T_layout >::bp_compute.
std::vector<int> lbann::slice_layer< T_layout >::get_neuron_dims(int child_index=0) const override
Get the dimensions of an activations tensor.
References lbann::Layer::m_neuron_dims, lbann::slice_layer< T_layout >::m_slice_axis.
Referenced by lbann::slice_layer< T_layout >::get_num_neurons, lbann::slice_layer< T_layout >::fp_output_dims.
int lbann::slice_layer< T_layout >::get_num_neurons(int child_index=0) const override
Get the size of an activations tensor.
References lbann::slice_layer< T_layout >::get_neuron_dims.
std::vector<int> lbann::slice_layer< T_layout >::fp_output_dims(const Layer *next_layer) const override
Get dimensions of forward propagation output to a child layer. Returns the dimensions of the appropriate activations tensor.
References lbann::Layer::m_neuron_dims, lbann::Layer::m_child_layers, lbann::slice_layer< T_layout >::get_neuron_dims.