lbann::lbann_callback_checknan
lbann::lbann_callback_checknan::lbann_callback_checknan()
References operator=.
Referenced by copy.
lbann::lbann_callback_checknan::lbann_callback_checknan(const lbann_callback_checknan &)=default
lbann_callback_checknan& lbann::lbann_callback_checknan::operator=(const lbann_callback_checknan &)=default
Referenced by lbann_callback_checknan.
lbann_callback_checknan* lbann::lbann_callback_checknan::copy() const override
References lbann_callback_checknan, on_forward_prop_end, on_backward_prop_end, on_batch_end.
void lbann::lbann_callback_checknan::on_forward_prop_end(model *m, Layer *l) override
Check that activations are good.
References lbann::Layer::get_activations, is_good, dump_network, name, lbann::model::get_comm, lbann::lbann_comm::get_rank_in_world, lbann::Layer::get_name, lbann::model::get_cur_step.
Referenced by copy.
void lbann::lbann_callback_checknan::on_backward_prop_end(model *m) override
Check that gradients are good.
References lbann::model::get_weights, is_good, lbann::optimizer::get_gradient, dump_network, name, lbann::model::get_comm, lbann::lbann_comm::get_rank_in_world, lbann::model::get_cur_step.
Referenced by copy.
void lbann::lbann_callback_checknan::on_batch_end(model *m) override
Check that weights are good.
References lbann::model::get_weights, is_good, dump_network, name, lbann::model::get_comm, lbann::lbann_comm::get_rank_in_world, lbann::model::get_cur_step.
Referenced by copy.
std::string lbann::lbann_callback_checknan::name() const override
Return this callback's name.
References is_good, dump_network.
Referenced by on_forward_prop_end, on_backward_prop_end, on_batch_end.
bool lbann::lbann_callback_checknan::is_good(const AbsDistMat &m)
Return true if there are no problems with m.
Referenced by name, on_forward_prop_end, on_backward_prop_end, on_batch_end.
void lbann::lbann_callback_checknan::dump_network(model *m)
Dump the (local) network matrices for debugging.
References lbann::model::get_layers, lbann::model::get_comm, lbann::lbann_comm::get_model_rank, lbann::lbann_comm::get_rank_in_model, lbann::model::get_cur_epoch, lbann::model::get_cur_step, lbann::model::get_weights.
Referenced by name, on_forward_prop_end, on_backward_prop_end, on_batch_end.