lbann::data_store_csv
csv_reader* lbann::data_store_csv::m_csv_reader
Referenced by setup, get_data_buf_DataType, populate_datastore.
int lbann::data_store_csv::m_vector_size
size of the vectors that are returned by reader->fetch_line_label_response(data_id)
Referenced by setup, exchange_data, populate_datastore.
std::unordered_map<int, size_t> lbann::data_store_csv::m_offset_mapping
maps: shuffled index to offset in owner's data store
std::unordered_map<int, std::vector<DataType> > lbann::data_store_csv::m_my_minibatch_data
buffers for data that will be passed to the data reader's fetch_datum method
Referenced by get_data_buf_DataType, exchange_data.
std::map<int, std::vector<DataType> > lbann::data_store_csv::m_data
will contain the data that this processor owns; Maps a global index to its associated data
Referenced by get_my_indices, exchange_data, populate_datastore.
lbann::data_store_csv::data_store_csv(generic_data_reader *reader, model *m)
ctor
References lbann::generic_data_store::set_name.
Referenced by copy.
lbann::data_store_csv::data_store_csv(const data_store_csv &)=default
copy ctor
data_store_csv& lbann::data_store_csv::operator=(const data_store_csv &)=default
operator=
data_store_csv* lbann::data_store_csv::copy() const override
References data_store_csv, ~data_store_csv, get_data_buf_DataType, setup.
lbann::data_store_csv::~data_store_csv() override
dtor
Referenced by copy.
void lbann::data_store_csv::get_data_buf_DataType(int data_id, std::vector< DataType > *&buf) override
References m_my_minibatch_data, lbann::generic_data_store::m_extended_testing, lbann::generic_data_store::m_master, m_csv_reader, lbann::csv_reader::fetch_line_label_response, lbann::generic_data_store::m_rank.
Referenced by copy.
void lbann::data_store_csv::setup() override
called by generic_data_reader::setup_data_store
References lbann::get_time, lbann::generic_data_store::m_master, lbann::generic_data_store::m_reader, lbann::generic_data_reader::get_role, lbann::generic_data_store::setup, lbann::generic_data_store::m_in_memory, m_csv_reader, lbann::generic_data_store::m_np, lbann::generic_data_reader::get_num_parallel_readers, lbann::generic_data_store::get_minibatch_index_vector, lbann::generic_data_store::exchange_mb_indices, lbann::generic_data_store::get_my_datastore_indices, lbann::csv_reader::fetch_line_label_response, m_vector_size, lbann::generic_data_store::m_mpi_comm, populate_datastore, exchange_data.
Referenced by copy.
void lbann::data_store_csv::exchange_data() override
retrive data needed for passing to the data reader for the next epoch
References lbann::get_time, get_indices, lbann::generic_data_store::m_rank, m_my_minibatch_data, m_vector_size, lbann::generic_data_store::get_index_owner, lbann::generic_data_store::m_np, lbann::cnpy_utils::data, lbann::generic_data_store::m_mpi_comm, get_my_indices, m_data, lbann::generic_data_store::m_reader, lbann::generic_data_reader::get_role, lbann::generic_data_store::m_master.
Referenced by setup.
void lbann::data_store_csv::get_indices(std::unordered_set< int > &indices, int p)
returns, in "indices," the set of indices that processor "p" needs for the next epoch. Called by exchange_data
References lbann::generic_data_store::m_all_minibatch_indices, lbann::generic_data_store::m_shuffled_indices.
Referenced by exchange_data.
void lbann::data_store_csv::get_my_indices(std::unordered_set< int > &indices, int p)
returns, in "indices," the subset of indices that processor "p" needs for the next epoch and that this processor owns. Called by exchange_data
References lbann::generic_data_store::m_all_minibatch_indices, m_data.
Referenced by exchange_data.
void lbann::data_store_csv::populate_datastore()
fills in m_data (the data store)
References lbann::generic_data_store::m_my_datastore_indices, m_data, m_csv_reader, lbann::csv_reader::fetch_line_label_response, m_vector_size, lbann::generic_data_store::m_rank.
Referenced by setup.
void lbann::data_store_csv::printme(const char *fn)