lbann::lbann_callback_checksmall
const DataType lbann::lbann_callback_checksmall::m_threshold
Smallest allowable value.
Referenced by is_good.
lbann::lbann_callback_checksmall::lbann_callback_checksmall()
References operator=.
Referenced by copy.
lbann::lbann_callback_checksmall::lbann_callback_checksmall(const lbann_callback_checksmall &)=default
lbann_callback_checksmall& lbann::lbann_callback_checksmall::operator=(const lbann_callback_checksmall &)=default
Referenced by lbann_callback_checksmall.
lbann_callback_checksmall* lbann::lbann_callback_checksmall::copy() const override
References lbann_callback_checksmall, on_forward_prop_end, on_backward_prop_end, on_batch_end.
void lbann::lbann_callback_checksmall::on_forward_prop_end(model *m, Layer *l) override
Check that activations are good.
References lbann::Layer::get_activations, is_good, name, lbann::model::get_comm, lbann::lbann_comm::get_rank_in_world, lbann::Layer::get_name, lbann::model::get_cur_step.
Referenced by copy.
void lbann::lbann_callback_checksmall::on_backward_prop_end(model *m) override
Check that gradients are good.
References lbann::model::get_weights, is_good, lbann::optimizer::get_gradient, name, lbann::model::get_comm, lbann::lbann_comm::get_rank_in_world, lbann::model::get_cur_step.
Referenced by copy.
void lbann::lbann_callback_checksmall::on_batch_end(model *m) override
Check that weights are good.
References lbann::model::get_weights, is_good, name, lbann::model::get_comm, lbann::lbann_comm::get_rank_in_world, lbann::model::get_cur_step.
Referenced by copy.
std::string lbann::lbann_callback_checksmall::name() const override
Return this callback's name.
Referenced by on_forward_prop_end, on_backward_prop_end, on_batch_end.
bool lbann::lbann_callback_checksmall::is_good(const AbsDistMat &m)
Return true if there are no problems with m.
References m_threshold.
Referenced by on_forward_prop_end, on_backward_prop_end, on_batch_end.