lbann::data_reader_mnist_siamese
using lbann::data_reader_mnist_siamese::label_t = unsigned char
using lbann::data_reader_mnist_siamese::sample_t = std::pair<int, int>
std::vector<int> lbann::data_reader_mnist_siamese::m_shuffled_indices2
To randomly choose the siamese pair input online.
Referenced by operator=, fetch_data, fetch_labels, shuffle_indices.
std::vector<std::vector<unsigned char> > lbann::data_reader_mnist_siamese::m_image_data
Store the preloaded data.
Referenced by operator=, fetch_labels, fetch_label, load.
lbann::data_reader_mnist_siamese::data_reader_mnist_siamese(const std::shared_ptr< cv_process > &pp, bool shuffle=true)
References set_defaults.
Referenced by copy.
lbann::data_reader_mnist_siamese::data_reader_mnist_siamese(const data_reader_mnist_siamese &)
data_reader_mnist_siamese & lbann::data_reader_mnist_siamese::operator=(const data_reader_mnist_siamese &)
References lbann::data_reader_multi_images::operator=, m_shuffled_indices2, m_image_data.
lbann::data_reader_mnist_siamese::~data_reader_mnist_siamese() override
data_reader_mnist_siamese* lbann::data_reader_mnist_siamese::copy() const override
References data_reader_mnist_siamese.
std::string lbann::data_reader_mnist_siamese::get_type() const override
Return this data_reader's type
References set_input_params, load, fetch_data, fetch_labels, setup_data_store, set_defaults, lbann::data_reader_multi_images::fetch_datum, lbann::data_reader_multi_images::fetch_label, fetch_datum, fetch_label, shuffle_indices, lbann::generic_data_reader::m_shuffled_indices.
Referenced by fetch_data, fetch_labels, fetch_datum, fetch_label, load.
void lbann::data_reader_mnist_siamese::set_input_params(const int, const int, const int, const int) override
Set up MNIST dataset-specific input parameters, which are pre-defined and also set as the default. This does not change the setup, but only preserves the default.
References set_defaults.
Referenced by get_type.
void lbann::data_reader_mnist_siamese::load() override
Load the dataset. Each data reader implementation should implement this to initialize its internal data structures, determine the number of samples and their dimensionality (if needed), and set up and shuffle samples.
References lbann::generic_data_reader::is_master, get_type, m_image_data, lbann::generic_data_reader::get_file_dir, lbann::generic_data_reader::get_data_filename, lbann::generic_data_reader::get_label_filename, lbann::load_mnist_data, lbann::generic_data_reader::m_first_n, lbann::generic_data_reader::set_use_percent, lbann::generic_data_reader::set_absolute_sample_count, lbann::generic_data_reader::m_shuffled_indices, lbann::generic_data_reader::select_subset_of_data.
Referenced by get_type.
int lbann::data_reader_mnist_siamese::fetch_data(Mat &X) override
Fetch this mini-batch's samples into X by calling the new overloaded fetch_datum()
Fill the input minibatch matrix with the samples of image pairs by using the overloaded fetch_datum()
References lbann::generic_data_reader::position_valid, get_type, lbann::generic_data_reader::m_current_pos, lbann::generic_data_reader::m_shuffled_indices, lbann::generic_data_reader::preprocess_data_source, lbann::generic_data_reader::get_loaded_mini_batch_size, lbann::generic_data_reader::m_sample_stride, lbann::generic_data_reader::m_indices_fetched_per_mb, m_shuffled_indices2, fetch_datum, lbann::lbann_report_exception, lbann::generic_data_reader::postprocess_data_source.
Referenced by get_type.
int lbann::data_reader_mnist_siamese::fetch_labels(Mat &Y) override
Fetch this mini-batch's labels into Y by calling the new overloaded fetch_label()
Fill the ground truth table by using the overloaded fetch_label()
References lbann::generic_data_reader::position_valid, lbann::generic_data_reader::get_loaded_mini_batch_size, lbann::generic_data_reader::m_current_pos, lbann::generic_data_reader::m_shuffled_indices, lbann::generic_data_reader::m_sample_stride, m_shuffled_indices2, fetch_label, lbann::lbann_report_exception, fetch_datum, lbann::data_reader_multi_images::create_datum_views, m_image_data, lbann::image_utils::import_image, lbann::imagenet_reader::m_pps, get_type, lbann::image_data_reader::m_image_linearized_size.
Referenced by get_type.
void lbann::data_reader_mnist_siamese::setup_data_store(model *m) override
sets up a data_store.
References lbann::generic_data_reader::m_data_store.
Referenced by get_type.
void lbann::data_reader_mnist_siamese::set_defaults() override
Set the default configuration such as the width, height, and number of channels of the image sample.
References lbann::image_data_reader::m_image_width, lbann::image_data_reader::m_image_height, lbann::image_data_reader::m_image_num_channels, lbann::image_data_reader::set_linearized_image_size, lbann::image_data_reader::m_num_labels, lbann::data_reader_multi_images::m_num_img_srcs.
Referenced by get_type, data_reader_mnist_siamese, set_input_params.
bool lbann::data_reader_mnist_siamese::fetch_datum(::Mat &X, int data_id, int mb_idx, int tid) override
References get_type.
Referenced by get_type, fetch_data, fetch_labels.
bool lbann::data_reader_mnist_siamese::fetch_label(::Mat &Y, int data_id, int mb_idx, int tid) override
References get_type, lbann::load_mnist_data, m_image_data.
Referenced by get_type, fetch_labels.
virtual bool lbann::data_reader_mnist_siamese::fetch_datum(::Mat &X, std::pair< int, int > data_id, int mb_idx, int tid)
Fetch two data items identified by the pair of indices to the pre-loaded data list, and put them into the column mb_idx of matrix x.
virtual bool lbann::data_reader_mnist_siamese::fetch_label(::Mat &Y, std::pair< int, int > data_id, int mb_idx, int tid)
Take a pair of indices to the preloaded sample list, and compare the labels of the corresponding samples. Store 1 if equal or 0 at the column mb_idx of the given matrix Y.
void lbann::data_reader_mnist_siamese::shuffle_indices() override
Shuffle the second index list added in this class as well as the one in the base class whenever the latter gets shuffled.
References m_shuffled_indices2, lbann::generic_data_reader::m_shuffled_indices, lbann::generic_data_reader::m_shuffle, lbann::get_data_seq_generator.
Referenced by get_type.