lbann::generic_data_reader
int lbann::generic_data_reader::m_rank
generic_data_store* lbann::generic_data_reader::m_data_store
Referenced by get_data_store, update, setup_data_store, lbann::csv_reader::fetch_datum, lbann::csv_reader::setup_data_store, lbann::imagenet_reader::fetch_datum, lbann::imagenet_reader::setup_data_store, lbann::imagenet_reader_patches::fetch_datum, lbann::imagenet_reader_patches::setup_data_store, lbann::data_reader_merge_features::setup_data_store, lbann::data_reader_merge_samples::setup_data_store, lbann::data_reader_mnist_siamese::setup_data_store, lbann::data_reader_multi_images::fetch_datum, lbann::data_reader_multi_images::setup_data_store, lbann::pilot2_molecular_reader::fetch_datum, lbann::pilot2_molecular_reader::setup_data_store, lbann::data_reader_triplet::fetch_datum, lbann::data_reader_triplet::setup_data_store.
lbann_comm* lbann::generic_data_reader::m_comm
Referenced by set_comm, get_comm, lbann::data_reader_merge_features::load, lbann::data_reader_merge_samples::load_using_data_store, lbann::data_reader_merge_samples::load, lbann::pilot2_molecular_reader::load.
int lbann::generic_data_reader::m_mini_batch_size
Referenced by set_mini_batch_size, get_mini_batch_size, get_mini_batch_max, pack_scalars, unpack_scalars, unpack_header, setup, get_loaded_mini_batch_size, get_current_mini_batch_size, lbann::image_data_reader::get_image_list_of_current_mb, lbann::data_reader_multi_images::get_image_list_of_current_mb, lbann::data_reader_triplet::get_image_list_of_current_mb.
int lbann::generic_data_reader::m_current_pos
Referenced by position_valid, set_initial_position, get_position, pack_scalars, unpack_scalars, unpack_header, fetch_data, fetch_labels, fetch_responses, update, get_next_position, lbann::data_reader_mnist_siamese::fetch_data, lbann::data_reader_mnist_siamese::fetch_labels.
int lbann::generic_data_reader::m_stride_to_next_mini_batch
Batch Stride is typically batch_size, but may be a multiple of batch size if there are multiple readers.
Referenced by set_stride_to_next_mini_batch, get_stride_to_next_mini_batch, pack_scalars, unpack_scalars, unpack_header, setup, update, get_next_position.
int lbann::generic_data_reader::m_base_offset
If there are multiple instances of the reader, then it may not reset to zero
Referenced by set_base_offset, get_base_offset, set_initial_position, pack_scalars, unpack_scalars, unpack_header, setup.
int lbann::generic_data_reader::m_model_offset
If there are multiple models with multiple instances of the reader, each model's set of readers may not reset to zero Provide a set of size, strides, and thresholds to handle the last mini batch of a dataset
Referenced by set_model_offset, get_model_offset, set_initial_position, pack_scalars, unpack_scalars, unpack_header.
int lbann::generic_data_reader::m_sample_stride
Sample stride is used when a mini-batch is finely interleaved across a DATA_PARALELL distribution.
Referenced by set_sample_stride, get_sample_stride, pack_scalars, unpack_scalars, unpack_header, setup, fetch_data, fetch_labels, fetch_responses, lbann::data_reader_mnist_siamese::fetch_data, lbann::data_reader_mnist_siamese::fetch_labels.
int lbann::generic_data_reader::m_iteration_stride
Stride used by parallel data readers within the model.
Referenced by set_iteration_stride, get_iteration_stride, pack_scalars, unpack_scalars, unpack_header, is_data_reader_done, update, get_next_position.
std::vector<int> lbann::generic_data_reader::m_shuffled_indices
Referenced by set_shuffled_indices, get_shuffled_indices, position_valid, get_indices, get_num_data, pack_scalars, unpack_scalars, lbann::data_reader_mnist_siamese::get_type, shuffle_indices, fetch_data, fetch_labels, fetch_responses, update, select_subset_of_data, use_unused_index_set, load_from_checkpoint_shared, lbann::ascii_reader::load, lbann::cifar10_reader::load, lbann::csv_reader::load, lbann::image_data_reader::load, lbann::imagenet_reader_single::load, lbann::data_reader_jag::load, lbann::data_reader_merge_features::load, lbann::data_reader_merge_samples::setup_indices, lbann::mesh_reader::load, lbann::mnist_reader::load, lbann::data_reader_mnist_siamese::fetch_data, lbann::data_reader_mnist_siamese::fetch_labels, lbann::data_reader_mnist_siamese::load, lbann::data_reader_mnist_siamese::shuffle_indices, lbann::data_reader_multi_images::load, lbann::numpy_reader::load, lbann::pilot2_molecular_reader::load, lbann::data_reader_synthetic::load, lbann::data_reader_triplet::load.
std::vector<int> lbann::generic_data_reader::m_unused_indices
Record of the indicies that are not being used for training.
Referenced by get_num_unused_data, get_unused_data, pack_scalars, unpack_scalars, select_subset_of_data, use_unused_index_set, load_from_checkpoint_shared.
int lbann::generic_data_reader::m_last_mini_batch_size
Referenced by set_last_mini_batch_size, get_last_mini_batch_size, pack_scalars, unpack_scalars, unpack_header, get_loaded_mini_batch_size, get_current_mini_batch_size.
int lbann::generic_data_reader::m_stride_to_last_mini_batch
Referenced by set_stride_to_last_mini_batch, get_stride_to_last_mini_batch, pack_scalars, unpack_scalars, unpack_header, setup, update, get_next_position.
int lbann::generic_data_reader::m_reset_mini_batch_index
The index at which this data reader starts its epoch.
Referenced by at_new_epoch, set_reset_mini_batch_index, get_reset_mini_batch_index, set_initial_position, pack_scalars, unpack_scalars, unpack_header.
int lbann::generic_data_reader::m_loaded_mini_batch_idx
The index of the current mini-batch that has been loaded.
Referenced by at_new_epoch, get_loaded_mini_batch_index, set_initial_position, pack_scalars, unpack_scalars, unpack_header, is_data_reader_done, update, get_loaded_mini_batch_size.
int lbann::generic_data_reader::m_current_mini_batch_idx
The index of the current mini-batch that is being processed (train/test/validate)
Referenced by at_new_epoch, get_current_mini_batch_index, set_initial_position, get_current_step_in_epoch, pack_scalars, unpack_scalars, unpack_header, setup, update, get_current_mini_batch_size, get_current_global_mini_batch_size, get_current_world_master_mini_batch_adjustment, get_next_position.
int lbann::generic_data_reader::m_num_iterations_per_epoch
Referenced by set_num_iterations_per_epoch, get_num_iterations_per_epoch, pack_scalars, unpack_scalars, unpack_header, setup, is_data_reader_done, update, get_loaded_mini_batch_size, get_current_mini_batch_size, get_current_global_mini_batch_size, get_current_world_master_mini_batch_adjustment, get_next_position.
int lbann::generic_data_reader::m_global_mini_batch_size
How many iterations all readers will execute.
Referenced by set_global_mini_batch_size, get_global_mini_batch_size, pack_scalars, unpack_scalars, unpack_header, setup, get_current_global_mini_batch_size.
int lbann::generic_data_reader::m_global_last_mini_batch_size
Referenced by set_global_last_mini_batch_size, get_global_last_mini_batch_size, pack_scalars, unpack_scalars, unpack_header, setup, get_current_global_mini_batch_size.
int lbann::generic_data_reader::m_world_master_mini_batch_adjustment
Referenced by set_world_master_mini_batch_adjustment, get_world_master_mini_batch_adjustment, pack_scalars, unpack_scalars, unpack_header, setup, get_current_mini_batch_size, get_current_world_master_mini_batch_adjustment.
int lbann::generic_data_reader::m_num_parallel_readers
Referenced by set_num_parallel_readers, get_num_parallel_readers, pack_scalars, unpack_scalars, unpack_header, update.
int lbann::generic_data_reader::m_model_rank
How many parallel readers are being used.
Referenced by set_rank, get_rank, pack_scalars, unpack_scalars, unpack_header.
std::string lbann::generic_data_reader::m_file_dir
What is the rank of the data reader within a given model.
Referenced by set_file_dir, get_file_dir, lbann::ascii_reader::load.
std::string lbann::generic_data_reader::m_data_fn
Referenced by set_data_filename, get_data_filename.
std::string lbann::generic_data_reader::m_label_fn
Referenced by set_label_filename, get_label_filename.
bool lbann::generic_data_reader::m_shuffle
Referenced by set_shuffle, is_shuffled, shuffle_indices, update, select_subset_of_data, lbann::data_reader_mnist_siamese::shuffle_indices.
size_t lbann::generic_data_reader::m_absolute_sample_count
Referenced by set_absolute_sample_count, get_absolute_sample_count.
double lbann::generic_data_reader::m_validation_percent
Referenced by set_validation_percent, get_validation_percent.
double lbann::generic_data_reader::m_use_percent
Referenced by set_use_percent, get_use_percent.
int lbann::generic_data_reader::m_first_n
Referenced by set_first_n, lbann::data_reader_jag::load, lbann::load_mnist_data, lbann::mnist_reader::load, lbann::data_reader_mnist_siamese::load, lbann::data_reader_triplet::load.
std::string lbann::generic_data_reader::m_role
Referenced by set_role, get_role.
bool lbann::generic_data_reader::m_master
Referenced by set_master, is_master.
El::Matrix<El::Int> lbann::generic_data_reader::m_indices_fetched_per_mb
1-D Matrix of which indices were fetched in this mini-batch
Referenced by get_indices_fetched_per_mb, setup, fetch_data, update, lbann::image_data_reader::get_image_list_of_current_mb, lbann::data_reader_mnist_siamese::fetch_data, lbann::data_reader_multi_images::get_image_list_of_current_mb, lbann::data_reader_triplet::get_image_list_of_current_mb.
bool lbann::generic_data_reader::m_save_minibatch_indices
added to support data store functionality
Referenced by fetch_data, update, set_save_minibatch_entries.
std::vector<std::vector<int> > lbann::generic_data_reader::m_my_minibatch_indices
added to support data store functionality
Referenced by get_minibatch_indices, fetch_data, set_save_minibatch_entries.
int lbann::generic_data_reader::m_compound_rank
added to support data store functionality
Referenced by get_compound_rank, set_compound_rank.
size_t lbann::generic_data_reader::m_num_global_indices
added to support data store functionality
Referenced by get_num_global_indices, select_subset_of_data.
friend class data_reader_merge_features
friend class data_reader_merge_samples
lbann::generic_data_reader::generic_data_reader(bool shuffle=true)
ctor
References operator=.
lbann::generic_data_reader::generic_data_reader(const generic_data_reader &)=default
generic_data_reader& lbann::generic_data_reader::operator=(const generic_data_reader &)=default
Referenced by lbann::generic_compound_data_reader::operator=, generic_data_reader, lbann::csv_reader::operator=, lbann::image_data_reader::operator=, lbann::numpy_reader::operator=.
lbann::generic_data_reader::~generic_data_reader() override
References copy.
virtual generic_data_reader* lbann::generic_data_reader::copy() const =0
Referenced by ~generic_data_reader, lbann::data_reader_merge_features::data_reader_merge_features, lbann::data_reader_merge_features::operator=.
void lbann::generic_data_reader::set_comm(lbann_comm *comm)
set the comm object
References m_comm, comm, set_master, lbann::lbann_comm::am_world_master.
Referenced by init_data_readers.
lbann_comm* lbann::generic_data_reader::get_comm() const
returns a (possibly nullptr) to comm
References m_comm, set_file_dir, get_file_dir, set_data_filename, get_data_filename, set_label_filename, get_label_filename.
void lbann::generic_data_reader::set_file_dir(std::string s)
Set base directory for your data. Optional: if given, then get_data_filename will concatenate the value passed to this method with the value passed to set_data_filename, and similarly for get_label_filename
References lbann::endsWith, m_file_dir.
Referenced by get_comm, init_data_readers.
std::string lbann::generic_data_reader::get_file_dir() const
Returns the base directory for your data. If set_file_dir was not called, returns the empty string
References m_file_dir.
Referenced by get_comm, lbann::ascii_reader::fetch_datum, lbann::ascii_reader::fetch_label, lbann::ascii_reader::load, lbann::cifar10_reader::load, lbann::csv_reader::setup_ifstreams, lbann::imagenet_reader::fetch_datum, lbann::imagenet_reader_org::fetch_datum, lbann::imagenet_reader_patches::fetch_datum, lbann::imagenet_reader_single::load, lbann::imagenet_reader_single::open_data_stream, lbann::data_reader_jag::load, lbann::mesh_reader::load, lbann::mesh_reader::construct_filename, lbann::mnist_reader::load, lbann::data_reader_mnist_siamese::load, lbann::data_reader_multi_images::fetch_datum, lbann::pilot2_molecular_reader::load, lbann::data_reader_triplet::fetch_datum.
void lbann::generic_data_reader::set_data_filename(std::string s)
Set the filename for your data (images, etc). This may either be a complete filepath, or a subdirectory; see note for set_file_dir(). Also, use this method for cases where the file contains a list of files (e.g, imagenet)
References m_data_fn.
Referenced by get_comm, init_data_readers.
std::string lbann::generic_data_reader::get_data_filename() const
Returns the complete filepath to you data file. See not for set_file_dir()
References m_data_fn.
Referenced by get_comm, lbann::ascii_reader::fetch_datum, lbann::ascii_reader::fetch_label, lbann::ascii_reader::load, lbann::cifar10_reader::load, lbann::csv_reader::load, lbann::csv_reader::setup_ifstreams, lbann::image_data_reader::load, lbann::imagenet_reader_single::load, lbann::imagenet_reader_single::open_data_stream, lbann::data_reader_jag::load, lbann::mnist_reader::load, lbann::data_reader_mnist_siamese::load, lbann::data_reader_multi_images::load, lbann::numpy_reader::load, lbann::pilot2_molecular_reader::load, lbann::data_reader_triplet::load.
void lbann::generic_data_reader::set_label_filename(std::string s)
Set the filename for your data (images, etc). This may either be a complete filepath, or a subdirectory; see note for set_file_dir()
References m_label_fn.
Referenced by get_comm, init_data_readers.
std::string lbann::generic_data_reader::get_label_filename() const
Returns the complete filepath to you data file. See not for set_file_dir(). Note: some pipelines (autoencoders) will not make use of this method.
References m_label_fn.
Referenced by get_comm, lbann::mnist_reader::load, lbann::data_reader_mnist_siamese::load.
void lbann::generic_data_reader::set_shuffle(bool b)
If set to false, indices (data samples) are not shuffled default (in ctor) is true.
References m_shuffle.
bool lbann::generic_data_reader::is_shuffled() const
Returns true if data samples are shuffled.
References m_shuffle.
void lbann::generic_data_reader::set_shuffled_indices(const std::vector< int > &indices)
Set shuffled indices; primary use is for testing and reproducibility
References m_shuffled_indices.
const std::vector<int>& lbann::generic_data_reader::get_shuffled_indices() const
Returns the shuffled indices; primary use is for testing.
References m_shuffled_indices, set_first_n, set_absolute_sample_count, set_use_percent, set_validation_percent.
Referenced by lbann::generic_data_store::setup.
void lbann::generic_data_reader::set_first_n(int n)
Read the first 'n' samples. If nonzero, this over-rides set_absolute_sample_count, set_use_percent. The intent is to use this for testing. A problem with set_absolute_sample_count and set_use_percent is that the entire data set is read in, then a subset is selected
References m_first_n.
Referenced by get_shuffled_indices, init_data_readers.
void lbann::generic_data_reader::set_absolute_sample_count(size_t s)
Sets the absolute number of data samples that will be used for training or testing.
References m_absolute_sample_count.
Referenced by get_shuffled_indices, lbann::data_reader_jag::load, lbann::mnist_reader::load, lbann::data_reader_mnist_siamese::load, lbann::data_reader_triplet::load, init_data_readers.
void lbann::generic_data_reader::set_use_percent(double s)
Set the percentage of the data set to use for training and validation or testing. s The percentage used, in the range [0, 1].
References m_use_percent.
Referenced by get_shuffled_indices, lbann::data_reader_jag::load, lbann::mnist_reader::load, lbann::data_reader_mnist_siamese::load, lbann::data_reader_triplet::load, init_data_readers.
void lbann::generic_data_reader::set_validation_percent(double s)
Sets the percentage of the dataset to be used for validation. s The percentage used, in the range [0, 1].
References m_validation_percent.
Referenced by lbann::generic_compound_data_reader::set_validation_percent, get_shuffled_indices, init_data_readers.
virtual void lbann::generic_data_reader::set_role(std::string role)
Set an idenifier for the dataset. The role should be one of "train", "test", or "validate".
References m_role.
Referenced by lbann::generic_compound_data_reader::set_role, init_data_readers.
std::string lbann::generic_data_reader::get_role() const
Get the role for this dataset.
References m_role, load, setup, get_type, fetch_data, fetch_labels, fetch_responses.
Referenced by lbann::imagenet_reader_single::fetch_datum, lbann::pilot2_molecular_reader::load, lbann::data_store_csv::setup, lbann::data_store_csv::exchange_data, lbann::data_store_image::get_data_buf, lbann::data_store_imagenet::setup, lbann::data_store_imagenet::test_data, lbann::data_store_imagenet::test_file_sizes, lbann::data_store_imagenet_patches::setup, lbann::data_store_merge_features::~data_store_merge_features, lbann::data_store_merge_samples::setup, lbann::data_store_multi_images::setup, lbann::data_store_pilot2_molecular::setup, lbann::data_store_pilot2_molecular::exchange_data, lbann::data_store_triplet::setup, lbann::generic_data_store::setup.
virtual void lbann::generic_data_reader::load()=0
Load the dataset. Each data reader implementation should implement this to initialize its internal data structures, determine the number of samples and their dimensionality (if needed), and set up and shuffle samples.
Referenced by get_role, lbann::data_reader_merge_features::load, init_data_readers.
void lbann::generic_data_reader::setup()
Prepare to start processing an epoch of data. If shuffle is true, then shuffle the indices of the data set If the base offset is not specified set it to 0 If the stride is not specified set it to batch size
References m_base_offset, m_sample_stride, m_stride_to_next_mini_batch, m_stride_to_last_mini_batch, m_current_mini_batch_idx, m_num_iterations_per_epoch, m_global_mini_batch_size, m_global_last_mini_batch_size, m_world_master_mini_batch_adjustment, m_indices_fetched_per_mb, m_mini_batch_size, set_initial_position, shuffle_indices.
Referenced by get_role.
virtual std::string lbann::generic_data_reader::get_type() const =0
Return this data_reader's type
Referenced by get_role, lbann::generic_data_store::setup, init_image_data_reader.
int lbann::generic_data_reader::fetch_data(Mat &X)
Fetch this mini-batch's samples into X.
References position_valid, m_current_pos, m_shuffled_indices, m_save_minibatch_indices, preprocess_data_source, get_loaded_mini_batch_size, m_sample_stride, m_indices_fetched_per_mb, m_my_minibatch_indices, fetch_datum, lbann::lbann_report_exception, postprocess_data_source.
Referenced by get_role, lbann::fetch_data_functor::operator().
int lbann::generic_data_reader::fetch_labels(Mat &Y)
Fetch this mini-batch's labels into Y.
References position_valid, get_loaded_mini_batch_size, m_current_pos, m_shuffled_indices, m_sample_stride, fetch_label, lbann::lbann_report_exception.
Referenced by get_role, lbann::fetch_data_functor::operator().
int lbann::generic_data_reader::fetch_responses(Mat &Y)
Fetch this mini-batch's responses into Y.
References position_valid, get_loaded_mini_batch_size, m_current_pos, m_shuffled_indices, m_sample_stride, fetch_response, lbann::lbann_report_exception.
Referenced by get_role, lbann::fetch_data_functor::operator().
void lbann::generic_data_reader::save_image(Mat &pixels, const std::string filename, bool do_scale=true) override
Save pixels to an image. The implementing data reader is responsible for handling format detection, conversion, etc.
References NOT_IMPLEMENTED, is_data_reader_done, update.
Referenced by lbann::lbann_callback_save_images::save_image.
bool lbann::generic_data_reader::is_data_reader_done(bool is_active_reader)
References m_loaded_mini_batch_idx, m_iteration_stride, m_num_iterations_per_epoch.
Referenced by save_image, lbann::update_data_reader_functor::operator().
bool lbann::generic_data_reader::update(bool is_active_reader)
During the network's update phase, the data reader will advanced the current position pointer. If the pointer wraps around, then reshuffle the data indicies.
References m_current_mini_batch_idx, m_current_pos, get_next_position, m_save_minibatch_indices, m_indices_fetched_per_mb, m_loaded_mini_batch_idx, m_iteration_stride, m_num_iterations_per_epoch, m_shuffled_indices, get_rank, m_num_parallel_readers, m_stride_to_next_mini_batch, m_stride_to_last_mini_batch, m_shuffle, lbann::get_data_seq_generator, set_initial_position, m_data_store, lbann::generic_data_store::set_shuffled_indices.
Referenced by save_image, lbann::update_data_reader_functor::operator().
virtual int lbann::generic_data_reader::get_num_labels() const
Return the number of labels (classes) in this dataset.
Referenced by lbann::data_reader_merge_features::get_num_labels.
virtual int lbann::generic_data_reader::get_num_responses() const
Return the number of responses in this dataset.
virtual int lbann::generic_data_reader::get_linearized_data_size() const
Get the linearized size (i.e. number of elements) in a sample.
virtual int lbann::generic_data_reader::get_linearized_label_size() const
Get the linearized size (i.e. number of elements) in a label.
Referenced by lbann::data_reader_merge_features::get_linearized_label_size.
virtual int lbann::generic_data_reader::get_linearized_response_size() const
Get the linearized size (i.e. number of elements) in a response.
virtual const std::vector<int> lbann::generic_data_reader::get_data_dims() const
Get the dimensions of the data.
Referenced by lbann::generic_input_layer::get_data_dims.
bool lbann::generic_data_reader::position_valid() const
True if the data reader's current position is valid.
References m_current_pos, m_shuffled_indices.
Referenced by fetch_data, fetch_labels, fetch_responses, lbann::data_reader_mnist_siamese::fetch_data, lbann::data_reader_mnist_siamese::fetch_labels.
bool lbann::generic_data_reader::at_new_epoch() const
True if the data reader is at the start of an epoch.
References m_loaded_mini_batch_idx, m_reset_mini_batch_index, m_current_mini_batch_idx.
void lbann::generic_data_reader::set_mini_batch_size(const int s)
Set the mini batch size.
References m_mini_batch_size.
Referenced by lbann::distributed_io_buffer::calculate_num_iterations_per_epoch, lbann::partitioned_io_buffer::calculate_num_iterations_per_epoch_spanning_models, lbann::partitioned_io_buffer::calculate_num_iterations_per_epoch_single_model.
int lbann::generic_data_reader::get_mini_batch_size() const
Get the mini batch size.
References m_mini_batch_size, get_loaded_mini_batch_size, get_current_mini_batch_size, get_current_global_mini_batch_size, get_current_world_master_mini_batch_adjustment.
Referenced by lbann::generic_input_layer::get_mini_batch_size, lbann::lbann_callback_debug_io::print_phase_start.
int lbann::generic_data_reader::get_loaded_mini_batch_size() const
Get the loaded mini-batch size.
References m_loaded_mini_batch_idx, m_num_iterations_per_epoch, m_last_mini_batch_size, m_mini_batch_size.
Referenced by get_mini_batch_size, fetch_data, fetch_labels, fetch_responses, lbann::data_reader_mnist_siamese::fetch_data, lbann::data_reader_mnist_siamese::fetch_labels.
int lbann::generic_data_reader::get_current_mini_batch_size() const
Get the current mini-batch size.
References m_current_mini_batch_idx, m_num_iterations_per_epoch, m_last_mini_batch_size, m_world_master_mini_batch_adjustment, m_mini_batch_size.
Referenced by get_mini_batch_size, lbann::generic_input_layer::get_current_mini_batch_size.
int lbann::generic_data_reader::get_current_global_mini_batch_size() const
Get the current global mini-batch size.
References m_current_mini_batch_idx, m_num_iterations_per_epoch, m_global_last_mini_batch_size, m_global_mini_batch_size.
Referenced by get_mini_batch_size, lbann::generic_input_layer::get_current_global_mini_batch_size.
int lbann::generic_data_reader::get_current_world_master_mini_batch_adjustment(int model_rank) const
Get the current mini-batch size.
Returns the current adjustment to the mini-batch size based on if the world master (model 0) has any extra samples Note that any rank in model 0 does not need to add in this offset since the model will already be aware of the extra samples
References m_current_mini_batch_idx, m_num_iterations_per_epoch, m_world_master_mini_batch_adjustment.
Referenced by get_mini_batch_size, lbann::generic_input_layer::get_current_world_master_mini_batch_adjustment.
int lbann::generic_data_reader::get_mini_batch_max() const
Return the full mini_batch_size.
References m_mini_batch_size.
void lbann::generic_data_reader::set_global_mini_batch_size(const int s)
Set the mini batch size across all models (global)
References m_global_mini_batch_size.
Referenced by lbann::distributed_io_buffer::calculate_num_iterations_per_epoch, lbann::partitioned_io_buffer::calculate_num_iterations_per_epoch_spanning_models, lbann::partitioned_io_buffer::calculate_num_iterations_per_epoch_single_model.
int lbann::generic_data_reader::get_global_mini_batch_size() const
Return the mini_batch_size across all models (global)
References m_global_mini_batch_size.
Referenced by lbann::generic_input_layer::get_global_mini_batch_size, lbann::lbann_callback_debug_io::print_phase_start.
void lbann::generic_data_reader::set_stride_to_next_mini_batch(const int s)
Set the mini batch stride.
References m_stride_to_next_mini_batch.
Referenced by lbann::distributed_io_buffer::calculate_num_iterations_per_epoch, lbann::partitioned_io_buffer::calculate_num_iterations_per_epoch_spanning_models, lbann::partitioned_io_buffer::calculate_num_iterations_per_epoch_single_model.
int lbann::generic_data_reader::get_stride_to_next_mini_batch() const
Return the mini batch stride.
References m_stride_to_next_mini_batch.
Referenced by lbann::lbann_callback_debug_io::print_phase_start, lbann::distributed_io_buffer::calculate_num_iterations_per_epoch, lbann::partitioned_io_buffer::calculate_num_iterations_per_epoch_spanning_models, lbann::partitioned_io_buffer::calculate_num_iterations_per_epoch_single_model.
void lbann::generic_data_reader::set_sample_stride(const int s)
Set the sample stride.
References m_sample_stride.
Referenced by lbann::distributed_io_buffer::calculate_num_iterations_per_epoch, lbann::partitioned_io_buffer::calculate_num_iterations_per_epoch_spanning_models, lbann::partitioned_io_buffer::calculate_num_iterations_per_epoch_single_model.
int lbann::generic_data_reader::get_sample_stride() const
Return the sample stride.
References m_sample_stride.
Referenced by lbann::lbann_callback_debug_io::print_fp_start.
void lbann::generic_data_reader::set_iteration_stride(const int s)
Set the iteration stride.
References m_iteration_stride.
Referenced by lbann::distributed_io_buffer::calculate_num_iterations_per_epoch, lbann::partitioned_io_buffer::calculate_num_iterations_per_epoch_spanning_models, lbann::partitioned_io_buffer::calculate_num_iterations_per_epoch_single_model.
int lbann::generic_data_reader::get_iteration_stride() const
Return the iteration stride.
References m_iteration_stride.
void lbann::generic_data_reader::set_base_offset(const int s)
Return the base offset.
References m_base_offset.
Referenced by lbann::distributed_io_buffer::calculate_num_iterations_per_epoch, lbann::partitioned_io_buffer::calculate_num_iterations_per_epoch_spanning_models, lbann::partitioned_io_buffer::calculate_num_iterations_per_epoch_single_model.
int lbann::generic_data_reader::get_base_offset() const
Return the base offset.
References m_base_offset.
Referenced by lbann::lbann_callback_debug_io::print_phase_start, lbann::partitioned_io_buffer::calculate_num_iterations_per_epoch_spanning_models.
void lbann::generic_data_reader::set_model_offset(const int s)
Set the model offset.
References m_model_offset.
Referenced by lbann::distributed_io_buffer::calculate_num_iterations_per_epoch, lbann::partitioned_io_buffer::calculate_num_iterations_per_epoch_spanning_models, lbann::partitioned_io_buffer::calculate_num_iterations_per_epoch_single_model.
int lbann::generic_data_reader::get_model_offset() const
Return the model offset.
References m_model_offset.
Referenced by lbann::lbann_callback_debug_io::print_phase_start, lbann::partitioned_io_buffer::calculate_num_iterations_per_epoch_spanning_models.
void lbann::generic_data_reader::set_last_mini_batch_size(const int s)
Set the last mini batch size.
References m_last_mini_batch_size.
Referenced by lbann::distributed_io_buffer::calculate_num_iterations_per_epoch, lbann::partitioned_io_buffer::calculate_num_iterations_per_epoch_spanning_models, lbann::partitioned_io_buffer::calculate_num_iterations_per_epoch_single_model.
int lbann::generic_data_reader::get_last_mini_batch_size() const
Return the last mini batch size.
References m_last_mini_batch_size.
Referenced by lbann::generic_input_layer::get_last_mini_batch_size, lbann::lbann_callback_debug_io::print_phase_start, lbann::distributed_io_buffer::calculate_num_iterations_per_epoch, lbann::partitioned_io_buffer::calculate_num_iterations_per_epoch_spanning_models.
void lbann::generic_data_reader::set_global_last_mini_batch_size(const int s)
Set the last mini batch size across all models (global)
References m_global_last_mini_batch_size.
Referenced by lbann::distributed_io_buffer::calculate_num_iterations_per_epoch, lbann::partitioned_io_buffer::calculate_num_iterations_per_epoch_spanning_models, lbann::partitioned_io_buffer::calculate_num_iterations_per_epoch_single_model.
int lbann::generic_data_reader::get_global_last_mini_batch_size() const
Return the last mini batch size across all models (global)
References m_global_last_mini_batch_size.
Referenced by lbann::generic_input_layer::get_global_last_mini_batch_size, lbann::lbann_callback_debug_io::print_phase_start.
void lbann::generic_data_reader::set_world_master_mini_batch_adjustment(const int s)
Set the world master mini batch adjustment (global)
References m_world_master_mini_batch_adjustment.
Referenced by lbann::distributed_io_buffer::calculate_num_iterations_per_epoch.
int lbann::generic_data_reader::get_world_master_mini_batch_adjustment() const
Return the world master mini batch adjustment (global)
References m_world_master_mini_batch_adjustment.
Referenced by lbann::generic_input_layer::get_world_master_mini_batch_adjustment.
void lbann::generic_data_reader::set_stride_to_last_mini_batch(const int s)
Set the last mini batch stride.
References m_stride_to_last_mini_batch.
Referenced by lbann::distributed_io_buffer::calculate_num_iterations_per_epoch, lbann::partitioned_io_buffer::calculate_num_iterations_per_epoch_spanning_models, lbann::partitioned_io_buffer::calculate_num_iterations_per_epoch_single_model.
int lbann::generic_data_reader::get_stride_to_last_mini_batch() const
Return the last mini batch stride.
References m_stride_to_last_mini_batch.
Referenced by lbann::lbann_callback_debug_io::print_phase_start.
void lbann::generic_data_reader::set_num_parallel_readers(const int s)
Set the number of parallel readers per model.
References m_num_parallel_readers.
Referenced by lbann::distributed_io_buffer::calculate_num_iterations_per_epoch, lbann::partitioned_io_buffer::calculate_num_iterations_per_epoch_spanning_models, lbann::partitioned_io_buffer::calculate_num_iterations_per_epoch_single_model.
int lbann::generic_data_reader::get_num_parallel_readers() const
Return the number of parallel readers per model.
References m_num_parallel_readers.
Referenced by lbann::generic_input_layer::get_num_parallel_readers, lbann::lbann_callback_debug_io::print_phase_start, lbann::data_store_csv::setup, lbann::generic_data_store::setup, lbann::distributed_io_buffer::fetch_to_local_matrix, lbann::distributed_io_buffer::distribute_from_local_matrix, lbann::distributed_io_buffer::is_data_set_processed, lbann::partitioned_io_buffer::fetch_to_local_matrix.
void lbann::generic_data_reader::set_reset_mini_batch_index(const int s)
Set the starting mini-batch index for the epoch.
References m_reset_mini_batch_index.
Referenced by lbann::distributed_io_buffer::calculate_num_iterations_per_epoch.
int lbann::generic_data_reader::get_reset_mini_batch_index() const
Return the starting mini-batch index for the epoch.
References m_reset_mini_batch_index.
int lbann::generic_data_reader::get_loaded_mini_batch_index() const
Return the current mini-batch index for the epoch.
References m_loaded_mini_batch_idx.
Referenced by lbann::lbann_callback_debug_io::print_fp_start.
int lbann::generic_data_reader::get_current_mini_batch_index() const
Return the current mini-batch index for the epoch.
References m_current_mini_batch_idx.
Referenced by lbann::lbann_callback_debug_io::print_fp_start.
void lbann::generic_data_reader::set_initial_position()
Set the current position based on the base and model offsets.
References m_current_pos, m_base_offset, m_model_offset, m_loaded_mini_batch_idx, m_reset_mini_batch_index, m_current_mini_batch_idx.
Referenced by setup, update, lbann::distributed_io_buffer::calculate_num_iterations_per_epoch, lbann::partitioned_io_buffer::calculate_num_iterations_per_epoch_spanning_models, lbann::partitioned_io_buffer::calculate_num_iterations_per_epoch_single_model.
int lbann::generic_data_reader::get_position() const
Get the current position in the data reader.
References m_current_pos, get_next_position.
Referenced by lbann::lbann_callback_debug_io::print_fp_start.
int lbann::generic_data_reader::get_next_position() const
Get the next position in the data reader.
References m_current_mini_batch_idx, m_iteration_stride, m_num_iterations_per_epoch, m_current_pos, m_stride_to_last_mini_batch, m_stride_to_next_mini_batch.
Referenced by get_position, update.
int* lbann::generic_data_reader::get_indices()
Get a pointer to the start of the shuffled indices.
References m_shuffled_indices.
int lbann::generic_data_reader::get_num_data() const
Get the number of samples in this dataset.
References m_shuffled_indices.
Referenced by select_subset_of_data, lbann::distributed_io_buffer::calculate_num_iterations_per_epoch, lbann::partitioned_io_buffer::calculate_num_iterations_per_epoch_spanning_models, lbann::partitioned_io_buffer::calculate_num_iterations_per_epoch_single_model, init_data_readers.
int lbann::generic_data_reader::get_num_unused_data() const
Get the number of unused samples in this dataset.
References m_unused_indices.
int* lbann::generic_data_reader::get_unused_data()
Get a pointer to the start of the unused sample indices.
References m_unused_indices.
El::Matrix<El::Int>* lbann::generic_data_reader::get_indices_fetched_per_mb()
Get a pointer to the fetched indices matrix.
References m_indices_fetched_per_mb.
Referenced by lbann::generic_input_layer::get_sample_indices_per_mb.
void lbann::generic_data_reader::set_num_iterations_per_epoch(int num_iterations_per_epoch)
Set the number of iterations in each epoch.
References m_num_iterations_per_epoch.
Referenced by lbann::distributed_io_buffer::calculate_num_iterations_per_epoch, lbann::partitioned_io_buffer::calculate_num_iterations_per_epoch_spanning_models, lbann::partitioned_io_buffer::calculate_num_iterations_per_epoch_single_model.
int lbann::generic_data_reader::get_num_iterations_per_epoch() const
Get the number of iterations in each epoch.
References m_num_iterations_per_epoch.
Referenced by lbann::generic_input_layer::get_num_iterations_per_epoch, lbann::lbann_callback_debug_io::print_phase_start, set_save_minibatch_entries, lbann::distributed_io_buffer::is_data_set_processed, lbann::partitioned_io_buffer::is_data_set_processed.
int lbann::generic_data_reader::get_current_step_in_epoch() const
Return the index of the current iteration step in the epoch (also the mini-batch index)
References m_current_mini_batch_idx.
Referenced by lbann::generic_input_layer::get_current_step_in_epoch, lbann::distributed_io_buffer::is_data_set_processed, lbann::partitioned_io_buffer::is_data_set_processed.
virtual void lbann::generic_data_reader::set_master(bool m)
only the master may write to cerr or cout; primarily for use in debugging during development
References m_master.
Referenced by lbann::generic_compound_data_reader::set_master, set_comm, init_data_readers.
bool lbann::generic_data_reader::is_master() const
only the master may write to cerr or cout; primarily for use in debugging during development
References m_master.
Referenced by lbann::ascii_reader::load, lbann::imagenet_reader_single::load, lbann::imagenet_reader_single::open_data_stream, lbann::mnist_reader::load, lbann::data_reader_mnist_siamese::load.
virtual void lbann::generic_data_reader::set_rank(int rank)
Allow the reader to know where it is in the model hierarchy.
References m_model_rank.
Referenced by lbann::generic_compound_data_reader::set_rank.
int lbann::generic_data_reader::get_rank() const
Allow the reader to know where it is in the model hierarchy.
References m_model_rank, select_subset_of_data, use_unused_index_set, save_to_checkpoint_shared, load_from_checkpoint_shared.
Referenced by lbann::lbann_callback_debug_io::print_phase_start, update, lbann::imagenet_reader_single::fetch_datum.
void lbann::generic_data_reader::select_subset_of_data()
Select the appropriate subset of data based on settings.
References m_num_global_indices, m_shuffled_indices, shuffle_indices, get_absolute_sample_count, get_use_percent, get_num_data, get_validation_percent, m_unused_indices, m_shuffle.
Referenced by get_rank, lbann::ascii_reader::load, lbann::cifar10_reader::load, lbann::csv_reader::load, lbann::image_data_reader::load, lbann::imagenet_reader_single::load, lbann::data_reader_jag::load, lbann::data_reader_merge_features::load, lbann::data_reader_merge_samples::setup_indices, lbann::mesh_reader::load, lbann::mnist_reader::load, lbann::data_reader_mnist_siamese::load, lbann::data_reader_multi_images::load, lbann::numpy_reader::load, lbann::pilot2_molecular_reader::load, lbann::data_reader_synthetic::load, lbann::data_reader_triplet::load.
void lbann::generic_data_reader::use_unused_index_set()
Replaced the shuffled index set with the unused index set, empying the unused set.
References m_shuffled_indices, m_unused_indices.
Referenced by get_rank, init_data_readers.
bool lbann::generic_data_reader::save_to_checkpoint_shared(persist &p, const char *name)
Given directory to store checkpoint files, write state to file and add to number of bytes written.
References lbann::persist::get_rank, pack_scalars.
Referenced by get_rank.
bool lbann::generic_data_reader::load_from_checkpoint_shared(persist &p, const char *name)
Given directory to store checkpoint files, read state from file and add to number of bytes read.
References lbann::persist::get_rank, unpack_scalars, unpack_header, m_shuffled_indices, lbann::generic_data_reader::packing_header::data_size, m_unused_indices, lbann::generic_data_reader::packing_header::unused_data_size.
Referenced by get_rank.
bool lbann::generic_data_reader::pack_scalars(persist &p, const char *name)
References lbann::validate, lbann::train, lbann::persist::write_uint64, m_mini_batch_size, m_current_mini_batch_idx, m_shuffled_indices, m_current_pos, lbann::persist::write_int32_contig, m_stride_to_last_mini_batch, m_stride_to_next_mini_batch, m_base_offset, m_model_offset, m_sample_stride, m_iteration_stride, m_loaded_mini_batch_idx, m_reset_mini_batch_index, m_unused_indices, m_last_mini_batch_size, m_num_iterations_per_epoch, m_global_mini_batch_size, m_global_last_mini_batch_size, m_num_parallel_readers, m_model_rank, m_world_master_mini_batch_adjustment.
Referenced by save_to_checkpoint_shared.
bool lbann::generic_data_reader::unpack_scalars(persist &p, struct packing_header *header, const char *name)
References lbann::validate, lbann::train, lbann::persist::read_uint64, m_mini_batch_size, m_current_mini_batch_idx, m_current_pos, m_shuffled_indices, lbann::persist::read_int32_contig, m_stride_to_last_mini_batch, m_stride_to_next_mini_batch, m_base_offset, m_model_offset, m_sample_stride, m_iteration_stride, m_loaded_mini_batch_idx, m_reset_mini_batch_index, m_unused_indices, m_last_mini_batch_size, m_num_iterations_per_epoch, m_global_mini_batch_size, m_global_last_mini_batch_size, m_num_parallel_readers, m_model_rank, m_world_master_mini_batch_adjustment, lbann::generic_data_reader::packing_header::data_size, lbann::generic_data_reader::packing_header::unused_data_size, lbann::generic_data_reader::packing_header::mini_batch_size, lbann::generic_data_reader::packing_header::current_pos, lbann::generic_data_reader::packing_header::current_mini_batch_idx, lbann::generic_data_reader::packing_header::stride_to_last_mini_batch, lbann::generic_data_reader::packing_header::stride_to_next_mini_batch, lbann::generic_data_reader::packing_header::base_offset, lbann::generic_data_reader::packing_header::model_offset, lbann::generic_data_reader::packing_header::sample_stride, lbann::generic_data_reader::packing_header::iteration_stride, lbann::generic_data_reader::packing_header::loaded_mini_batch_idx, lbann::generic_data_reader::packing_header::reset_mini_batch_index, lbann::generic_data_reader::packing_header::last_mini_batch_size, lbann::generic_data_reader::packing_header::num_iterations_per_epoch, lbann::generic_data_reader::packing_header::global_mini_batch_size, lbann::generic_data_reader::packing_header::global_last_mini_batch_size, lbann::generic_data_reader::packing_header::num_parallel_readers, lbann::generic_data_reader::packing_header::model_rank, lbann::generic_data_reader::packing_header::world_master_mini_batch_adjustment.
Referenced by load_from_checkpoint_shared.
void lbann::generic_data_reader::unpack_header(struct packing_header &header)
References m_mini_batch_size, lbann::generic_data_reader::packing_header::mini_batch_size, m_current_pos, lbann::generic_data_reader::packing_header::current_pos, m_current_mini_batch_idx, lbann::generic_data_reader::packing_header::current_mini_batch_idx, m_stride_to_last_mini_batch, lbann::generic_data_reader::packing_header::stride_to_last_mini_batch, m_stride_to_next_mini_batch, lbann::generic_data_reader::packing_header::stride_to_next_mini_batch, m_base_offset, lbann::generic_data_reader::packing_header::base_offset, m_model_offset, lbann::generic_data_reader::packing_header::model_offset, m_sample_stride, lbann::generic_data_reader::packing_header::sample_stride, m_iteration_stride, lbann::generic_data_reader::packing_header::iteration_stride, m_loaded_mini_batch_idx, lbann::generic_data_reader::packing_header::loaded_mini_batch_idx, m_reset_mini_batch_index, lbann::generic_data_reader::packing_header::reset_mini_batch_index, m_last_mini_batch_size, lbann::generic_data_reader::packing_header::last_mini_batch_size, m_num_iterations_per_epoch, lbann::generic_data_reader::packing_header::num_iterations_per_epoch, m_global_mini_batch_size, lbann::generic_data_reader::packing_header::global_mini_batch_size, m_global_last_mini_batch_size, lbann::generic_data_reader::packing_header::global_last_mini_batch_size, m_num_parallel_readers, lbann::generic_data_reader::packing_header::num_parallel_readers, m_model_rank, lbann::generic_data_reader::packing_header::model_rank, m_world_master_mini_batch_adjustment, lbann::generic_data_reader::packing_header::world_master_mini_batch_adjustment.
Referenced by load_from_checkpoint_shared.
generic_data_store* lbann::generic_data_reader::get_data_store() const
returns the data store
References m_data_store, setup_data_store, set_save_minibatch_entries.
Referenced by lbann::data_store_merge_features::~data_store_merge_features, lbann::data_store_merge_samples::setup.
void lbann::generic_data_reader::setup_data_store(model *m)
sets up a data_store.
References m_data_store.
Referenced by get_data_store.
void lbann::generic_data_reader::set_save_minibatch_entries(bool b)
This call changes the functionality of fetch_data(); when set, indices are added to m_my_minibatch_indices, but fetch_datum() is not called. This method is added to support data store functionality.
References m_save_minibatch_indices, m_my_minibatch_indices, get_num_iterations_per_epoch.
Referenced by get_data_store, lbann::generic_data_store::setup.
const std::vector<std::vector<int> >& lbann::generic_data_reader::get_minibatch_indices() const
support of data store functionality
References m_my_minibatch_indices.
Referenced by lbann::generic_data_store::setup.
int lbann::generic_data_reader::get_compound_rank()
support of data store functionality
References m_compound_rank.
Referenced by lbann::pilot2_molecular_reader::load, lbann::data_store_pilot2_molecular::setup.
void lbann::generic_data_reader::set_compound_rank(int r)
support of data store functionality
References m_compound_rank, get_absolute_sample_count, get_use_percent, get_validation_percent.
size_t lbann::generic_data_reader::get_absolute_sample_count() const
Return the absolute number of data samples that will be used for training or testing.
References m_absolute_sample_count.
Referenced by set_compound_rank, select_subset_of_data.
double lbann::generic_data_reader::get_use_percent() const
Returns the percent of the dataset to be used for training or testing. If training, this is the total for training and validation. Throws if set_use_percent was not called.
References m_use_percent.
Referenced by set_compound_rank, select_subset_of_data.
double lbann::generic_data_reader::get_validation_percent() const
Return the percent of the dataset to be used for validation.
References m_validation_percent.
Referenced by set_compound_rank, select_subset_of_data.
size_t lbann::generic_data_reader::get_num_global_indices()
Returns the number of global indices. For train and validation, this is the sum of their numbers
References m_num_global_indices.
virtual bool lbann::generic_data_reader::fetch_datum(Mat &X, int data_id, int mb_idx, int tid)
Fetch a single sample into a matrix. X The matrix to load data into. data_id The index of the datum to fetch. mb_idx The index within the mini-batch.
References NOT_IMPLEMENTED.
Referenced by fetch_data.
virtual bool lbann::generic_data_reader::fetch_label(Mat &Y, int data_id, int mb_idx, int tid)
Fetch a single label into a matrix. Y The matrix to load data into. data_id The index of the datum to fetch. mb_idx The index within the mini-batch.
References NOT_IMPLEMENTED.
Referenced by fetch_labels, lbann::data_reader_merge_features::fetch_label.
virtual bool lbann::generic_data_reader::fetch_response(Mat &Y, int data_id, int mb_idx, int tid)
Fetch a single response into a matrix. Y The matrix to load data into. data_id The index of the datum to fetch. mb_idx The index within the mini-batch.
References NOT_IMPLEMENTED.
Referenced by fetch_responses, lbann::data_reader_merge_features::fetch_response.
virtual void lbann::generic_data_reader::preprocess_data_source(int tid)
Called before fetch_datum/label/response to allow initialization.
Referenced by fetch_data, lbann::data_reader_mnist_siamese::fetch_data.
virtual void lbann::generic_data_reader::postprocess_data_source(int tid)
Called after fetch_datum/label/response to allow initialization.
References shuffle_indices.
Referenced by fetch_data, lbann::data_reader_mnist_siamese::fetch_data.
void lbann::generic_data_reader::shuffle_indices()
Shuffle indices.
References m_shuffle, m_shuffled_indices, lbann::get_data_seq_generator.
Referenced by postprocess_data_source, setup, select_subset_of_data.