lbann::data_store_merge_samples
std::vector<int> lbann::data_store_merge_samples::m_my_minibatch_indices
this contains a concatenation of the indices in m_minibatch_indices (see: generic_data_reader.hpp)
std::vector<data_store_pilot2_molecular*> lbann::data_store_merge_samples::m_subsidiary_stores
Referenced by setup.
MPI_Win lbann::data_store_merge_samples::m_win
allocate mem for m_data
when running in in-memory mode, this buffer will contain the concatenated datawill contain data to be passed to the data_reader maps indices wrt shuffled indices to indices in m_my_data
Referenced by ~data_store_merge_samples.
lbann::data_store_merge_samples::data_store_merge_samples(lbann_comm *comm, generic_data_reader *reader, model *m)
ctor
References lbann::generic_data_store::set_name.
Referenced by copy.
lbann::data_store_merge_samples::data_store_merge_samples(const data_store_merge_samples &)=default
copy ctor
data_store_merge_samples& lbann::data_store_merge_samples::operator=(const data_store_merge_samples &)=default
operator=
data_store_merge_samples* lbann::data_store_merge_samples::copy() const override
References data_store_merge_samples, ~data_store_merge_samples.
lbann::data_store_merge_samples::~data_store_merge_samples() override
dtor
References m_win.
Referenced by copy.
void lbann::data_store_merge_samples::get_data_buf(int data_id, std::vector< unsigned char > *&buf, int multi_idx=0) override
called by various image data readers
References setup, exchange_data.
void lbann::data_store_merge_samples::setup() override
called by generic_data_reader::setup_data_store
References lbann::generic_data_store::m_rank, lbann::generic_data_store::setup, lbann::generic_data_store::m_reader, lbann::generic_data_reader::get_role, lbann::generic_data_store::m_in_memory, lbann::generic_data_store::get_minibatch_index_vector, lbann::generic_compound_data_reader::get_data_readers, lbann::generic_data_reader::get_data_store, lbann::data_store_pilot2_molecular::clear_minibatch_indices, m_subsidiary_stores, lbann::data_reader_merge_samples::get_num_samples_psum, lbann::generic_data_store::m_my_minibatch_indices_v.
Referenced by get_data_buf.
void lbann::data_store_merge_samples::exchange_data() override
Referenced by get_data_buf.