lbann::stack_profiler
stack_profiler * lbann::stack_profiler::s_instance
Referenced by get, c_hash_create.
bool lbann::stack_profiler::m_full_stack_trace
Referenced by activate.
int lbann::stack_profiler::m_thread_id
Referenced by activate, print.
static stack_profiler* lbann::stack_profiler::get()
References s_instance, activate, print, stack_profiler, ~stack_profiler.
void lbann::stack_profiler::activate(int thread_id)
Turns on stack profiling if you have passed the cmd line option: st_on or st_on=1
References m_thread_id, c_hash_thread_id, options::get, options::has_bool, options::get_bool, c_hash_create, c_hash_profiling_is_turned_on, m_full_stack_trace, c_hash_fp_full_stack_trace, c_hash_fp_full_stack_trace_metadata.
Referenced by get.
void lbann::stack_profiler::print()
References m_thread_id, c_hash_the_hash_table, c_hash_table::count, lbann::cnpy_utils::data, c_hash_table::data, c_hash_table::size, c_hash_table::cur_mark, lbann::count_sorter, c_hash_lookups, c_hash_collisions.
Referenced by get.
lbann::stack_profiler::stack_profiler()
Referenced by get.
lbann::stack_profiler::~stack_profiler()
References c_hash_fp_full_stack_trace, c_hash_fp_full_stack_trace_metadata.
Referenced by get.
lbann::stack_profiler::stack_profiler(const stack_profiler &)
stack_profiler& lbann::stack_profiler::operator=(const stack_profiler &)