lbann::dataset
long lbann::dataset::m_num_samples_processed
Referenced by get_num_samples_processed, num_samples_processed.
long lbann::dataset::m_total_samples
Referenced by get_total_samples, total_samples.
lbann::dataset::dataset()
References operator=.
lbann::dataset::dataset(const dataset &other)=default
dataset& lbann::dataset::operator=(const dataset &other)=default
Referenced by dataset.
long lbann::dataset::get_num_samples_processed() const
References m_num_samples_processed.
Referenced by lbann::generic_input_layer::update_num_samples_processed, lbann::generic_input_layer::get_num_samples_trained, lbann::generic_input_layer::get_num_samples_tested, lbann::generic_input_layer::save_to_checkpoint_shared.
long& lbann::dataset::num_samples_processed()
References m_num_samples_processed.
Referenced by lbann::generic_input_layer::update_num_samples_processed, lbann::generic_input_layer::load_from_checkpoint_shared.
long lbann::dataset::get_total_samples() const
References m_total_samples.
Referenced by lbann::generic_input_layer::get_total_num_training_samples, lbann::generic_input_layer::get_total_num_testing_samples, lbann::generic_input_layer::is_execution_mode_valid, lbann::generic_input_layer::save_to_checkpoint_shared.
long& lbann::dataset::total_samples()
References m_total_samples.
Referenced by lbann::generic_input_layer::generic_input_layer, lbann::generic_input_layer::load_from_checkpoint_shared.