lbann::generic_io_buffer
lbann_comm* lbann::generic_io_buffer::m_comm
Referenced by lbann::distributed_io_buffer::fetch_to_local_matrix, lbann::distributed_io_buffer::distribute_from_local_matrix, lbann::distributed_io_buffer::is_data_set_processed, lbann::distributed_io_buffer::compute_max_num_parallel_readers, lbann::distributed_io_buffer::calculate_num_iterations_per_epoch, lbann::distributed_io_buffer::calculate_num_iterations_per_epoch_spanning_models, operator=, lbann::partitioned_io_buffer::fetch_to_local_matrix, lbann::partitioned_io_buffer::compute_max_num_parallel_readers, lbann::partitioned_io_buffer::calculate_num_iterations_per_epoch_spanning_models, lbann::partitioned_io_buffer::calculate_num_iterations_per_epoch_single_model.
const fetch_data_functor* lbann::generic_io_buffer::fetch_data_fn
Referenced by lbann::input_layer< T_io_buffer, T_layout >::input_layer, lbann::target_layer< T_io_buffer, T_layout >::target_layer, generic_io_buffer, operator=.
const update_data_reader_functor* lbann::generic_io_buffer::update_data_reader_fn
Referenced by lbann::input_layer< T_io_buffer, T_layout >::input_layer, lbann::target_layer< T_io_buffer, T_layout >::target_layer, generic_io_buffer, operator=.
lbann::generic_io_buffer::generic_io_buffer(lbann_comm *comm, int num_parallel_readers, std::map< execution_mode, generic_data_reader *> data_readers)
lbann::generic_io_buffer::generic_io_buffer(const generic_io_buffer &)
References fetch_data_fn, update_data_reader_fn.
generic_io_buffer & lbann::generic_io_buffer::operator=(const generic_io_buffer &)
References m_comm, fetch_data_fn, update_data_reader_fn.
Referenced by lbann::distributed_io_buffer::operator=.
virtual lbann::generic_io_buffer::~generic_io_buffer()
virtual generic_io_buffer* lbann::generic_io_buffer::copy() const =0
Referenced by lbann::generic_input_layer::operator=.
virtual std::string lbann::generic_io_buffer::get_type() const =0
Return this buffer's type, e.g: "partitioned_io_buffer," "distributed_io_buffer," etc.
Referenced by lbann::generic_input_layer::get_description, lbann::input_layer< T_io_buffer, T_layout >::get_type, lbann::generic_target_layer::get_description, lbann::target_layer< T_io_buffer, T_layout >::get_type.
virtual void lbann::generic_io_buffer::set_local_matrix_bypass(Mat *M_local)=0
Referenced by lbann::generic_input_layer::fp_setup_data, lbann::generic_target_layer::fp_setup_data.
virtual void lbann::generic_io_buffer::set_std_matrix_view(El::Int cur_mini_batch_size)=0
Referenced by lbann::generic_input_layer::fp_setup_data, lbann::generic_target_layer::fp_setup_data.
virtual void lbann::generic_io_buffer::setup_data(El::Int num_neurons, El::Int max_minibatch_size)=0
Referenced by lbann::generic_input_layer::setup_data, lbann::generic_target_layer::setup_data.
virtual int lbann::generic_io_buffer::fetch_to_local_matrix(generic_data_reader *data_reader, execution_mode mode)=0
Referenced by lbann::generic_input_layer::fp_compute, lbann::generic_target_layer::fp_compute.
virtual void lbann::generic_io_buffer::distribute_from_local_matrix(AbsDistMat &Ms, generic_data_reader *data_reader, execution_mode mode)
virtual bool lbann::generic_io_buffer::is_data_set_processed(generic_data_reader *data_reader, execution_mode mode)=0
Referenced by lbann::generic_input_layer::update_compute, lbann::generic_target_layer::update_compute.
virtual void lbann::generic_io_buffer::calculate_num_iterations_per_epoch_spanning_models(int max_mini_batch_size, generic_data_reader *data_reader)=0
Referenced by lbann::generic_input_layer::calculate_num_iterations_per_epoch_training_spans_models.
virtual void lbann::generic_io_buffer::calculate_num_iterations_per_epoch_single_model(int max_mini_batch_size, generic_data_reader *data_reader)=0
Referenced by lbann::generic_input_layer::calculate_num_iterations_per_epoch_training_spans_models, lbann::generic_input_layer::calculate_num_iterations_per_epoch_training_unique_per_models.
virtual int lbann::generic_io_buffer::compute_max_num_parallel_readers(long data_set_size, int mini_batch_size, int requested_num_parallel_readers) const =0