lbann::fan_in_fan_out_initializer
int lbann::fan_in_fan_out_initializer::m_fan_in
Fan-in dimension.
Referenced by set_fan_in, lbann::glorot_normal_initializer::initialize_entries, lbann::glorot_uniform_initializer::initialize_entries, lbann::he_normal_initializer::initialize_entries, lbann::he_uniform_initializer::initialize_entries.
int lbann::fan_in_fan_out_initializer::m_fan_out
Fan-out dimension.
Referenced by set_fan_out, lbann::glorot_normal_initializer::initialize_entries, lbann::glorot_uniform_initializer::initialize_entries, lbann::he_normal_initializer::initialize_entries, lbann::he_uniform_initializer::initialize_entries.
lbann::fan_in_fan_out_initializer::fan_in_fan_out_initializer(lbann_comm *comm)
Constructor.
References ~fan_in_fan_out_initializer.
lbann::fan_in_fan_out_initializer::~fan_in_fan_out_initializer() override=default
Destructor.
Referenced by fan_in_fan_out_initializer.
void lbann::fan_in_fan_out_initializer::set_fan_in(int fan_in)
Set fan-in dimension.
References m_fan_in.
Referenced by lbann::base_convolution_layer::setup_data, lbann::fully_connected_layer< T_layout >::setup_data.
void lbann::fan_in_fan_out_initializer::set_fan_out(int fan_out)
Set fan-out dimension.
References m_fan_out.