lbann::generic_compound_data_reader
std::vector<generic_data_reader*> lbann::generic_compound_data_reader::m_data_readers
List of readers providing data.
Referenced by generic_compound_data_reader, operator=, ~generic_compound_data_reader, set_validation_percent, set_role, set_master, set_rank, get_data_readers, lbann::data_reader_merge_samples::get_num_labels, lbann::data_reader_merge_samples::get_linearized_data_size, lbann::data_reader_merge_samples::get_linearized_label_size, lbann::data_reader_merge_samples::get_data_dims, lbann::data_reader_merge_features::load, lbann::data_reader_merge_features::fetch_datum, lbann::data_reader_merge_samples::load_using_data_store, lbann::data_reader_merge_samples::compute_num_samples_psum, lbann::data_reader_merge_samples::sanity_check_for_consistency, lbann::data_reader_merge_samples::load, lbann::data_reader_merge_samples::fetch_datum, lbann::data_reader_merge_samples::fetch_label, lbann::data_reader_merge_samples::fetch_response.
lbann::generic_compound_data_reader::generic_compound_data_reader(std::vector< generic_data_reader *> data_readers, bool shuffle=true)
References m_data_readers.
lbann::generic_compound_data_reader::generic_compound_data_reader(const generic_compound_data_reader &other)
References m_data_readers.
generic_compound_data_reader& lbann::generic_compound_data_reader::operator=(const generic_compound_data_reader &other)
References lbann::generic_data_reader::operator=, m_data_readers.
Referenced by lbann::data_reader_merge_features::operator=, lbann::data_reader_merge_samples::operator=.
lbann::generic_compound_data_reader::~generic_compound_data_reader() override
References m_data_readers, copy.
generic_compound_data_reader* lbann::generic_compound_data_reader::copy() const override=0
Referenced by ~generic_compound_data_reader.
void lbann::generic_compound_data_reader::set_validation_percent(double s) override
Apply operations to subsidiary data readers.
References lbann::generic_data_reader::set_validation_percent, m_data_readers.
void lbann::generic_compound_data_reader::set_role(std::string role) override
Set an idenifier for the dataset. The role should be one of "train", "test", or "validate".
References lbann::generic_data_reader::set_role, m_data_readers.
void lbann::generic_compound_data_reader::set_master(bool m) override
only the master may write to cerr or cout; primarily for use in debugging during development
References lbann::generic_data_reader::set_master, m_data_readers.
void lbann::generic_compound_data_reader::set_rank(int rank) override
Allow the reader to know where it is in the model hierarchy.
References lbann::generic_data_reader::set_rank, m_data_readers.
std::vector<generic_data_reader*>& lbann::generic_compound_data_reader::get_data_readers()
needed to support data_store_merge_samples
References m_data_readers.
Referenced by lbann::data_store_merge_features::~data_store_merge_features, lbann::data_store_merge_samples::setup.