lbann::distributed_io_buffer
typedef std::map<execution_mode, data_buffer *> lbann::distributed_io_buffer::data_buffer_map_t
int lbann::distributed_io_buffer::m_requested_max_num_parallel_readers
Requested maximum number of parallel readers (I/O streams)
Referenced by distributed_io_buffer, operator=, calculate_num_iterations_per_epoch.
data_buffer_map_t lbann::distributed_io_buffer::m_data_buffers
Referenced by distributed_io_buffer.
lbann::distributed_io_buffer::distributed_io_buffer(lbann_comm *comm, int num_parallel_readers, std::map< execution_mode, generic_data_reader *> data_readers)
References m_data_buffers, training, validation, testing.
lbann::distributed_io_buffer::distributed_io_buffer(const distributed_io_buffer &other)
References m_requested_max_num_parallel_readers.
distributed_io_buffer& lbann::distributed_io_buffer::operator=(const distributed_io_buffer &other)
References lbann::generic_io_buffer::operator=, m_requested_max_num_parallel_readers.
virtual lbann::distributed_io_buffer::~distributed_io_buffer()
distributed_io_buffer* lbann::distributed_io_buffer::copy() const override
std::string lbann::distributed_io_buffer::get_type() const override
Return this buffer's type, e.g: "partitioned_io_buffer," "distributed_io_buffer," etc.
void lbann::distributed_io_buffer::set_local_matrix_bypass(Mat *M_local) override
void lbann::distributed_io_buffer::set_std_matrix_view(El::Int cur_mini_batch_size) override
void lbann::distributed_io_buffer::setup_data(El::Int num_neurons, El::Int max_minibatch_size) override
References lbann::data_buffer::Ms.
int lbann::distributed_io_buffer::fetch_to_local_matrix(generic_data_reader *data_reader, execution_mode mode) override
References lbann::generic_data_reader::get_num_parallel_readers, get_data_buffer, lbann::data_buffer::m_root, lbann::generic_io_buffer::m_comm, lbann::lbann_comm::get_rank_in_model, lbann::data_buffer::m_local_reader_done, lbann::data_buffer::M_local, lbann::data_buffer::m_num_samples_in_batch, lbann::data_buffer::m_num_data_per_epoch, lbann::data_buffer::m_local_data_valid.
void lbann::distributed_io_buffer::distribute_from_local_matrix(AbsDistMat &Ms, generic_data_reader *data_reader, execution_mode mode) override
References lbann::generic_data_reader::get_num_parallel_readers, get_data_buffer, lbann::data_buffer::Ms, lbann::data_buffer::m_root, lbann::generic_io_buffer::m_comm, lbann::lbann_comm::model_barrier, lbann::lbann_comm::get_rank_in_model, lbann::data_buffer::m_local_data_valid, lbann::data_buffer::M_local, lbann::data_buffer::m_num_samples_in_batch.
Referenced by lbann::generic_input_layer::fp_compute, lbann::generic_target_layer::fp_compute.
bool lbann::distributed_io_buffer::is_data_set_processed(generic_data_reader *data_reader, execution_mode mode) override
References lbann::generic_data_reader::get_num_parallel_readers, lbann::generic_data_reader::get_num_iterations_per_epoch, lbann::generic_data_reader::get_current_step_in_epoch, get_data_buffer, lbann::generic_io_buffer::m_comm, lbann::lbann_comm::get_rank_in_model, lbann::data_buffer::m_root, lbann::data_buffer::m_local_data_valid, lbann::data_buffer::m_local_reader_done, lbann::data_buffer::m_num_data_per_epoch.
void lbann::distributed_io_buffer::calculate_num_iterations_per_epoch(int num_models, int model_rank, int max_mini_batch_size, generic_data_reader *data_reader)
References lbann::generic_data_reader::get_num_data, compute_max_num_parallel_readers, m_requested_max_num_parallel_readers, lbann::generic_data_reader::set_num_parallel_readers, lbann::generic_io_buffer::m_comm, lbann::lbann_comm::get_rank_in_model, lbann::generic_data_reader::set_mini_batch_size, lbann::generic_data_reader::set_stride_to_next_mini_batch, lbann::generic_data_reader::set_sample_stride, lbann::generic_data_reader::set_iteration_stride, lbann::generic_data_reader::set_reset_mini_batch_index, lbann::generic_data_reader::set_base_offset, lbann::generic_data_reader::set_model_offset, lbann::generic_data_reader::set_initial_position, lbann::generic_data_reader::set_global_mini_batch_size, lbann::generic_data_reader::set_last_mini_batch_size, lbann::generic_data_reader::set_global_last_mini_batch_size, lbann::generic_data_reader::set_world_master_mini_batch_adjustment, lbann::generic_data_reader::set_num_iterations_per_epoch, lbann::generic_data_reader::get_last_mini_batch_size, lbann::generic_data_reader::set_stride_to_last_mini_batch, lbann::generic_data_reader::get_stride_to_next_mini_batch.
Referenced by calculate_num_iterations_per_epoch_spanning_models, calculate_num_iterations_per_epoch_single_model.
void lbann::distributed_io_buffer::calculate_num_iterations_per_epoch_spanning_models(int max_mini_batch_size, generic_data_reader *data_reader) override
References calculate_num_iterations_per_epoch, lbann::generic_io_buffer::m_comm, lbann::lbann_comm::get_num_models, lbann::lbann_comm::get_model_rank.
void lbann::distributed_io_buffer::calculate_num_iterations_per_epoch_single_model(int max_mini_batch_size, generic_data_reader *data_reader) override
References calculate_num_iterations_per_epoch.
int lbann::distributed_io_buffer::compute_max_num_parallel_readers(long data_set_size, int mini_batch_size, int requested_num_parallel_readers) const override
Make sure that there are enough ranks and data for all of the parallel readers requested.
References lbann::generic_io_buffer::m_comm, lbann::lbann_comm::get_model_grid, lbann::lbann_comm::am_model_master, lbann::lbann_comm::get_num_models, lbann::lbann_comm::am_world_master.
Referenced by calculate_num_iterations_per_epoch.
data_buffer* lbann::distributed_io_buffer::get_data_buffer(const execution_mode mode) const
References training, validation, testing, lbann::data_buffer::data_buffer.
Referenced by fetch_to_local_matrix, distribute_from_local_matrix, is_data_set_processed.
virtual int lbann::distributed_io_buffer::current_root_rank(execution_mode mode) const
Return the rank of the current root node for the Elemental Distribution.
References lbann::data_buffer::m_root.
bool lbann::distributed_io_buffer::is_current_root(execution_mode mode) const
Is this rank the current root node for the Elemental Distribution.
References lbann::data_buffer::m_root.
virtual bool lbann::distributed_io_buffer::is_local_reader_done(execution_mode mode) const
Is the local reader done.
References lbann::data_buffer::m_local_reader_done.