lbann::optimizer
lbann_comm* lbann::optimizer::m_comm
LBANN communicator.
Referenced by operator=, get_gradient, start_gradient_staging_allreduce.
cudnn::cudnn_manager* lbann::optimizer::m_cudnn
cuDNN manager.
Referenced by lbann::adam::adam, lbann::adam::operator=, lbann::adam::~adam, lbann::adam::setup, operator=, get_gradient, start_gradient_staging_allreduce, clear_gradient, add_to_gradient, add_to_gradient_staging, setup, step, lbann::sgd::sgd, lbann::sgd::operator=, lbann::sgd::~sgd, lbann::sgd::setup.
weights* lbann::optimizer::m_weights
Weights being optimized.
Referenced by is_initialized, set_weights, lbann::adam::adam, lbann::adam::operator=, operator=, get_description, get_weights, add_to_gradient, add_to_gradient_staging, setup, step, lbann::sgd::sgd, lbann::sgd::operator=.
DataType lbann::optimizer::m_learning_rate
Learning rate.
Referenced by get_learning_rate, set_learning_rate, lbann::adagrad::step_compute, lbann::adam::step_compute, lbann::hypergradient_adam::step_compute, operator=, get_description, save_to_checkpoint_shared, load_from_checkpoint_shared, lbann::rmsprop::step_compute, lbann::sgd::step_compute.
AbsDistMat* lbann::optimizer::m_gradient
Gradient matrix.
Referenced by lbann::adagrad::setup, lbann::adam::setup, lbann::hypergradient_adam::setup, optimizer, operator=, ~optimizer, get_gradient, start_gradient_staging_allreduce, clear_gradient, add_to_gradient, setup, step, lbann::rmsprop::setup, lbann::sgd::setup.
std::unordered_set<const void*> lbann::optimizer::m_gradient_sources
Sources of gradient contributions. This set contains pointers to objects (i.e. layers and objective function terms) which depend on the weights being optimized and which contribute to the gradient. Objects should add themselves to the set as they request the weights and they should remove themselves as they add their gradient contribution. Once this set is empty, it is safe to perform an allreduce on the gradient staging matrix.
Referenced by get_num_gradient_sources, get_gradient, add_gradient_source, remove_gradient_source.
AbsDistMat* lbann::optimizer::m_gradient_staging
Gradient staging matrix. When the gradient is needed, an allreduce is applied over the redundant communicator of the staging matrix and the result is added to the gradient matrix.
Referenced by optimizer, operator=, ~optimizer, get_gradient, start_gradient_staging_allreduce, add_to_gradient_staging, setup.
bool lbann::optimizer::m_gradient_allreduce_needed
Whether the gradient staging matrix requires an allreduce.
Referenced by operator=, get_gradient, start_gradient_staging_allreduce, clear_gradient, add_to_gradient_staging.
bool lbann::optimizer::m_gradient_allreduce_started
Whether an allreduce on the gradient staging matrix has started.
Referenced by operator=, get_gradient, start_gradient_staging_allreduce, clear_gradient, add_to_gradient_staging.
bool lbann::optimizer::m_gradient_allreduce_finished
Whether an allreduce on the gradient staging matrix has been finished.
Referenced by operator=, get_gradient, start_gradient_staging_allreduce, clear_gradient.
double lbann::optimizer::m_step_time
Running count of the time spent in step().
Referenced by get_step_time, reset_counters, operator=, step.
Al::request lbann::optimizer::m_gradient_allreduce_req
The request for non-blocking allreduces.
Referenced by get_gradient, start_gradient_staging_allreduce.
lbann::optimizer::optimizer(lbann_comm *comm, DataType learning_rate=DataType(0))
lbann::optimizer::optimizer(const optimizer &other)
References m_gradient, m_gradient_staging.
optimizer & lbann::optimizer::operator=(const optimizer &other)
References m_comm, m_cudnn, m_weights, m_learning_rate, m_step_time, m_gradient_allreduce_needed, m_gradient_allreduce_started, m_gradient_allreduce_finished, m_gradient, m_gradient_staging.
Referenced by lbann::adagrad::operator=, lbann::adam::operator=, lbann::hypergradient_adam::operator=, lbann::rmsprop::operator=, lbann::sgd::operator=.
lbann::optimizer::~optimizer()
References m_gradient, m_gradient_staging.
virtual optimizer* lbann::optimizer::copy() const =0
Referenced by lbann::model::create_optimizer, lbann::weights::weights, lbann::weights::operator=.
virtual std::string lbann::optimizer::get_type() const =0
Get the optimizer name.
Referenced by get_description.
std::string lbann::optimizer::get_description() const
Get a human-readable description of the optimizer.
References get_type, m_weights, lbann::weights::get_name, m_learning_rate.
Referenced by lbann::adagrad::get_description, lbann::adam::get_description, lbann::hypergradient_adam::get_description, lbann::rmsprop::get_description, lbann::sgd::get_description.
bool lbann::optimizer::is_initialized() const
Whether the optimizer has been set up.
References m_weights, get_weights.
Referenced by get_weights, get_gradient, add_to_gradient, add_to_gradient_staging, setup, step.
weights & lbann::optimizer::get_weights()
Get weights being optimized.
References is_initialized, LBANN_ERROR, m_weights.
Referenced by is_initialized, lbann::lbann_callback_optimizerwise_adaptive_learning_rate::optimizer_schedule.
void lbann::optimizer::set_weights(weights &w)
Set weights being optimized.
References m_weights.
Referenced by setup, lbann::weights::weights.
DataType lbann::optimizer::get_learning_rate() const
Get learning rate.
References m_learning_rate.
Referenced by lbann::lbann_callback_learning_rate::optimizer_schedule, lbann::lbann_callback_learning_rate::setup, lbann::lbann_callback_learning_rate::on_epoch_end, lbann::lbann_callback_learning_rate::on_backward_prop_end, lbann::lbann_callback_optimizerwise_adaptive_learning_rate::optimizer_schedule, lbann::lbann_callback_variable_minibatch::get_current_learning_rate.
void lbann::optimizer::set_learning_rate(DataType learning_rate)
Set learning rate.
References m_learning_rate, get_gradient, clear_gradient, add_to_gradient, add_to_gradient_staging, start_gradient_staging_allreduce.
Referenced by lbann::lbann_callback_learning_rate::on_epoch_end, lbann::lbann_callback_learning_rate::on_backward_prop_end, lbann::lbann_callback_variable_minibatch::change_learning_rate.
const AbsDistMat & lbann::optimizer::get_gradient()
Get gradient matrix.
References is_initialized, LBANN_ERROR, m_gradient_allreduce_needed, m_gradient_allreduce_started, start_gradient_staging_allreduce, m_gradient_allreduce_finished, m_comm, lbann::lbann_comm::wait, m_gradient_allreduce_req, m_cudnn, add_to_gradient, m_gradient_staging, m_gradient, m_gradient_sources.
Referenced by set_learning_rate, lbann::lbann_callback_checknan::on_backward_prop_end, lbann::lbann_callback_checksmall::on_backward_prop_end, lbann::lbann_callback_dump_gradients::on_backward_prop_end, lbann::lbann_callback_imcomm::setup, lbann::lbann_callback_imcomm::on_epoch_end, lbann::lbann_callback_imcomm::on_backward_prop_end, lbann::lbann_callback_imcomm::do_summary, lbann::lbann_callback_optimizerwise_adaptive_learning_rate::optimizer_schedule, lbann::lbann_callback_summary::save_histograms, step.
void lbann::optimizer::clear_gradient()
Clear gradient matrix.
References m_cudnn, m_gradient, m_gradient_allreduce_needed, m_gradient_allreduce_started, m_gradient_allreduce_finished.
Referenced by set_learning_rate, lbann::lbann_callback_imcomm::on_epoch_end, lbann::lbann_callback_imcomm::on_backward_prop_end, lbann::model::clear_gradients, setup, step.
void lbann::optimizer::add_to_gradient(const AbsDistMat &gradient, DataType scale=DataType(1))
Add to the gradient matrix. If the optimizer has a cuDNN manager, the data is copied to GPUs and added to the GPU gradient matrix.
References is_initialized, LBANN_ERROR, m_cudnn, m_gradient, m_weights, lbann::weights::get_size.
Referenced by set_learning_rate, lbann::lbann_callback_imcomm::on_epoch_end, lbann::lbann_callback_imcomm::on_backward_prop_end, lbann::fully_connected_layer< T_layout >::bp_compute_cpu, get_gradient.
void lbann::optimizer::add_to_gradient_staging(const AbsDistMat &gradient, DataType scale=DataType(1))
Add to the gradient staging matrix. When the gradient is needed, an allreduce is applied over the redundant communicator of the staging matrix and the result is added to the gradient. If the optimizer has a cuDNN manager, the data is copied to GPUs and added to the GPU staging matrix.
References is_initialized, LBANN_ERROR, m_gradient_allreduce_started, m_gradient_allreduce_needed, m_cudnn, m_gradient_staging, m_weights, lbann::weights::get_size.
Referenced by lbann::base_convolution_layer::compute_gradients_cudnn, lbann::base_convolution_layer::compute_gradients_im2col, lbann::fully_connected_layer< T_layout >::bp_compute_cuda, lbann::batch_normalization< T_layout >::bp_compute_gpu, lbann::batch_normalization< T_layout >::bp_compute_cpu, set_learning_rate, lbann::fully_connected_layer< T_layout >::bp_compute_cpu.
void lbann::optimizer::start_gradient_staging_allreduce()
Start allreduce on the gradient staging matrix. If an allreduce is not needed or if it has already started, this function does nothing. This may call a non-blocking allreduce.
References m_gradient_allreduce_needed, m_gradient_allreduce_started, m_cudnn, m_comm, lbann::lbann_comm::nb_allreduce, m_gradient_staging, m_gradient_allreduce_req, m_gradient_allreduce_finished, LBANN_ERROR, m_gradient.
Referenced by set_learning_rate, get_gradient, remove_gradient_source.
int lbann::optimizer::get_num_gradient_sources() const
Get number of gradient sources. This is the number of objects that contribute to the gradient but have not added their contributions yet.
References m_gradient_sources, add_gradient_source, remove_gradient_source, setup, step, step_compute.
void lbann::optimizer::add_gradient_source(const void *source)
Add a gradient source. Objects that depend on the weights being optimized and which contribute to the gradient should add themselves as a gradient source.
References m_gradient_sources.
Referenced by get_num_gradient_sources, lbann::Layer::forward_prop.
void lbann::optimizer::remove_gradient_source(const void *source)
Remove a gradient source. Objects that contribute to the gradient should remove themselves as gradient sources when they add to the gradient. If there are no more gradient sources remaining, an allreduce is started on the gradient staging matrix.
References m_gradient_sources, start_gradient_staging_allreduce.
Referenced by get_num_gradient_sources.
void lbann::optimizer::setup(weights &w)
Setup optimizer.
References is_initialized, LBANN_ERROR, set_weights, m_weights, lbann::weights::get_matrix_height, lbann::weights::get_matrix_width, lbann::weights::get_values, m_gradient, m_gradient_staging, m_cudnn, lbann::weights::m_cudnn, clear_gradient.
Referenced by get_num_gradient_sources, lbann::adagrad::setup, lbann::adam::setup, lbann::hypergradient_adam::setup, lbann::rmsprop::setup, lbann::sgd::setup, lbann::weights::setup.
void lbann::optimizer::step()
Apply an optimization step.
References is_initialized, LBANN_ERROR, lbann::get_time, m_cudnn, m_weights, lbann::weights::get_size, lbann::weights::get_values, lbann::weights::m_values, get_gradient, step_compute, clear_gradient, m_step_time, m_gradient.
Referenced by get_num_gradient_sources, lbann::lbann_callback_imcomm::on_epoch_end, lbann::model::update_weights.
virtual void lbann::optimizer::step_compute(AbsDistMat &values, const AbsDistMat &gradient)=0
Perform the computation in an optimization step. It can be assumed that values and gradient are the same size and have the same matrix distribution.
Referenced by get_num_gradient_sources, step.
double lbann::optimizer::get_step_time() const
Get the time spent in step().
References m_step_time.
Referenced by lbann::Layer::summarize_stats.
virtual void lbann::optimizer::reset_counters()
Reset stats counters.
References m_step_time.
Referenced by lbann::Layer::summarize_stats.
bool lbann::optimizer::save_to_checkpoint_shared(persist &p, std::string m_name)
References lbann::persist::write_datatype, lbann::train, m_learning_rate.
Referenced by lbann::adagrad::save_to_checkpoint_shared, lbann::adam::save_to_checkpoint_shared, lbann::rmsprop::save_to_checkpoint_shared, lbann::sgd::save_to_checkpoint_shared, lbann::weights::save_to_checkpoint_shared.
bool lbann::optimizer::load_from_checkpoint_shared(persist &p, std::string m_name)
References lbann::persist::read_datatype, lbann::train, m_learning_rate.
Referenced by lbann::adagrad::load_from_checkpoint_shared, lbann::adam::load_from_checkpoint_shared, lbann::rmsprop::load_from_checkpoint_shared, lbann::sgd::load_from_checkpoint_shared, lbann::weights::load_from_checkpoint_shared.