lbann::DataGenerator
Int lbann::DataGenerator::m_num_samples
Referenced by DataGenerator, load.
Int lbann::DataGenerator::m_data_width
Referenced by getDataWidth, get_linearized_data_size, DataGenerator, operator=.
Int lbann::DataGenerator::m_data_height
Referenced by getDataHeight, get_linearized_data_size, DataGenerator, operator=.
StarMat lbann::DataGenerator::m_data
Referenced by load, fetch_data.
lbann::DataGenerator::DataGenerator(Int num_samples, Int width, Int height, Int batchSize)
References m_num_samples, m_data_width, m_data_height.
lbann::DataGenerator::DataGenerator(const DataGenerator &source)
lbann::DataGenerator::~DataGenerator()
int lbann::DataGenerator::fetch_data(Mat &X)
References get_linearized_data_size, m_data.
int lbann::DataGenerator::fetch_label(Mat &Y)
int lbann::DataGenerator::getDataWidth()
References m_data_width.
int lbann::DataGenerator::getDataHeight()
References m_data_height.
int lbann::DataGenerator::get_linearized_data_size()
References m_data_width, m_data_height.
Referenced by load, fetch_data.
int lbann::DataGenerator::get_linearized_label_size()
References load, operator=.
void lbann::DataGenerator::load()
References m_num_samples, lbann::uniform_fill_procdet, m_data, get_linearized_data_size.
Referenced by get_linearized_label_size.
lbann::DataGenerator & lbann::DataGenerator::operator=(const DataGenerator &source)
References m_data_width, m_data_height.
Referenced by get_linearized_label_size.