lbann::poisson_negloglike
lbann::poisson_negloglike::poisson_negloglike(EvalType scale_factor=EvalType(1))
Default constructor.
References operator=, ~poisson_negloglike.
Referenced by copy.
lbann::poisson_negloglike::poisson_negloglike(const poisson_negloglike &other)=default
Copy constructor.
poisson_negloglike& lbann::poisson_negloglike::operator=(const poisson_negloglike &other)=default
Copy assignment operator.
Referenced by poisson_negloglike.
lbann::poisson_negloglike::~poisson_negloglike() override=default
Destructor.
Referenced by poisson_negloglike.
poisson_negloglike* lbann::poisson_negloglike::copy() const override
Copy function.
References poisson_negloglike.
std::string lbann::poisson_negloglike::name() const override
Get the name of the objective function term.
void lbann::poisson_negloglike::start_evaluate_compute(const AbsDistMat &prediction, const AbsDistMat &ground_truth) override
Compute the Poisson negative log-likelihood objective function. Given a prediction $\hat{y}$ and ground truth $y$, the Poisson negative log-likelihood is \[ Pois_nll(\hat{y}, y) = \hat{y} - y\log(\hat{y}) + \log(\Gamma(y + 1)) \] This function updates the objective function value with the mean value of the Poisson negative log-likelihood across the mini-batch.
References finish_evaluate_compute, prediction, differentiate_compute.
EvalType lbann::poisson_negloglike::finish_evaluate_compute(const AbsDistMat &prediction, const AbsDistMat &ground_truth) override
Finish evaluation of the loss function. This should not include the scale factor.
References lbann::objective_function_term::get_comm, lbann::lbann_comm::allreduce.
Referenced by start_evaluate_compute.
void lbann::poisson_negloglike::differentiate_compute(const AbsDistMat &prediction, const AbsDistMat &ground_truth, AbsDistMat &gradient) override
Compute the gradient of the Poisson negative log-likelihood objective function. Given a prediction $\hat{y}$ and ground truth $y$, the gradient of the Poisson negative log-likelihood is \[ \nabla_y Pois_nll(\hat{y},y) = 1 - y/\hat{y} \]
Referenced by start_evaluate_compute.