lbann::layer_term
lbann::layer_term::layer_term(EvalType scale_factor=EvalType(1))
Referenced by copy, lbann::proto::anonymous_namespace{model_factory.cpp}::assign_layers_to_objective_function.
layer_term* lbann::layer_term::copy() const override
Copy function.
References layer_term.
std::string lbann::layer_term::name() const override
Get the name of the objective function term.
References set_evaluation_layer, setup, start_evaluation, finish_evaluation, differentiate.
void lbann::layer_term::set_evaluation_layer(Layer *l)
References lbann::objective_function_term::m_layers.
Referenced by name.
void lbann::layer_term::setup(model &m) override
Setup objective function term.
References lbann::objective_function_term::setup, lbann::objective_function_term::m_layers, LBANN_ERROR, lbann::objective_function_term::m_scale_factor.
Referenced by name.
void lbann::layer_term::start_evaluation() override
Start evaluation of the objective function term. This should include the scaling factor. The result is not available until finish_evaluation has been called.
Referenced by name.
EvalType lbann::layer_term::finish_evaluation() override
Complete evaluation of the objective function term.
References lbann::objective_function_term::m_scale_factor, lbann::objective_function_term::m_layers, lbann::evaluation_layer< T_layout >::set_scale.
Referenced by name.
void lbann::layer_term::differentiate() override
Compute the gradient of the objective function term. The gradient is computed w.r.t. the objective function term inputs. This should include the scaling factor.
References lbann::objective_function_term::m_layers, lbann::evaluation_layer< T_layout >::set_scale, lbann::objective_function_term::m_scale_factor.
Referenced by name.
void lbann::layer_term::compute_weight_regularization() override
Compute the gradient of the weight regularization term. The gradient is computed w.r.t. the weights.