lbann::pearson_correlation_metric
AbsDistMat* lbann::pearson_correlation_metric::m_prediction_means
Column-wise means of prediction matrix.
Referenced by pearson_correlation_metric, operator=, ~pearson_correlation_metric, setup, evaluate_compute.
AbsDistMat* lbann::pearson_correlation_metric::m_prediction_stdevs
Column-wise standard deviations of prediction matrix.
Referenced by pearson_correlation_metric, operator=, ~pearson_correlation_metric, setup, evaluate_compute.
AbsDistMat* lbann::pearson_correlation_metric::m_ground_truth_means
Column-wise means of ground truth matrix.
Referenced by pearson_correlation_metric, operator=, ~pearson_correlation_metric, setup, evaluate_compute.
AbsDistMat* lbann::pearson_correlation_metric::m_ground_truth_stdevs
Column-wise standard deviations of ground truth matrix.
Referenced by pearson_correlation_metric, operator=, ~pearson_correlation_metric, setup, evaluate_compute.
AbsDistMat* lbann::pearson_correlation_metric::m_covariances
Column-wise covariance between prediction and ground truth matrices.
Referenced by pearson_correlation_metric, operator=, ~pearson_correlation_metric, setup, evaluate_compute.
lbann::pearson_correlation_metric::pearson_correlation_metric(lbann_comm *comm)
Constructor.
Referenced by copy.
lbann::pearson_correlation_metric::pearson_correlation_metric(const pearson_correlation_metric &other)
Copy constructor.
References m_prediction_means, m_prediction_stdevs, m_ground_truth_means, m_ground_truth_stdevs, m_covariances.
pearson_correlation_metric & lbann::pearson_correlation_metric::operator=(const pearson_correlation_metric &other)
Copy assignment operator.
References lbann::metric::operator=, m_prediction_means, m_prediction_stdevs, m_ground_truth_means, m_ground_truth_stdevs, m_covariances.
lbann::pearson_correlation_metric::~pearson_correlation_metric()
Destructor.
References m_prediction_means, m_prediction_stdevs, m_ground_truth_means, m_ground_truth_stdevs, m_covariances.
pearson_correlation_metric* lbann::pearson_correlation_metric::copy() const override
Copy function.
References pearson_correlation_metric.
std::string lbann::pearson_correlation_metric::name() const override
Return a string name for this metric.
References setup, evaluate_compute, prediction.
void lbann::pearson_correlation_metric::setup(model &m) override
Setup metric.
References lbann::metric::setup, lbann::metric::get_target_layer, m_prediction_means, m_prediction_stdevs, m_ground_truth_means, m_ground_truth_stdevs, m_covariances, lbann::model::get_max_mini_batch_size.
Referenced by name.
EvalType lbann::pearson_correlation_metric::evaluate_compute(const AbsDistMat &prediction, const AbsDistMat &ground_truth) override
Computation to evaluate the metric function. This returns the sum of metric values across the mini-batch, not the mean value.
References lbann::columnwise_mean_and_stdev, m_prediction_means, m_prediction_stdevs, m_ground_truth_means, m_ground_truth_stdevs, lbann::columnwise_covariance, m_covariances, lbann::metric::get_comm, lbann::lbann_comm::allreduce.
Referenced by name.