lbann::mean_squared_error_loss
EvalType lbann::mean_squared_error_loss::m_sum
Sum of the the squared errors.
Referenced by start_evaluate_compute, finish_evaluate_compute.
Al::request lbann::mean_squared_error_loss::m_allreduce_req
Non-blocking allreduce request.
Referenced by start_evaluate_compute, finish_evaluate_compute.
lbann::mean_squared_error_loss::mean_squared_error_loss(EvalType scale_factor=EvalType(1))
Default constructor.
References operator=, ~mean_squared_error_loss.
Referenced by copy.
lbann::mean_squared_error_loss::mean_squared_error_loss(const mean_squared_error_loss &other)=default
Copy constructor.
mean_squared_error_loss& lbann::mean_squared_error_loss::operator=(const mean_squared_error_loss &other)=default
Copy assignment operator.
Referenced by mean_squared_error_loss.
lbann::mean_squared_error_loss::~mean_squared_error_loss() override=default
Destructor.
Referenced by mean_squared_error_loss.
mean_squared_error_loss* lbann::mean_squared_error_loss::copy() const override
Copy function.
References mean_squared_error_loss.
std::string lbann::mean_squared_error_loss::name() const override
Get the name of the objective function term.
References start_evaluate_compute, prediction, finish_evaluate_compute, differentiate_compute.
void lbann::mean_squared_error_loss::start_evaluate_compute(const AbsDistMat &prediction, const AbsDistMat &ground_truth) override
Compute the mean squared error objective function. Given a prediction $\hat{y}$ and ground truth $y$, the mean squared error is \[ MSE(\hat{y}, y) = \frac{1}{n} \lVert y - \hat{y} \rVert_2^2 \] This function updates the objective function value with the mean value of the mean absolute deviation across the mini-batch.
References m_sum, lbann::objective_function_term::get_comm, lbann::lbann_comm::nb_allreduce, m_allreduce_req.
Referenced by name.
EvalType lbann::mean_squared_error_loss::finish_evaluate_compute(const AbsDistMat &prediction, const AbsDistMat &ground_truth) override
Finish evaluation of the loss function. This should not include the scale factor.
References lbann::objective_function_term::get_comm, lbann::lbann_comm::wait, m_allreduce_req, m_sum.
Referenced by name.
void lbann::mean_squared_error_loss::differentiate_compute(const AbsDistMat &prediction, const AbsDistMat &ground_truth, AbsDistMat &gradient) override
Compute the gradient of the mean squared error objective function. Given a prediction $\hat{y}$ and ground truth $y$, the gradient of the mean squared error is \[ \nabla_y MSE (y,\hat{y}) = \frac{2}{n} (y - \hat{y}) \]
Referenced by name.