cyg_profile.hpp
HASH_1
HASH_2
FILE* c_hash_fp_full_stack_trace
This module contains pure C variables and functions that are used in conjunction with __cyg_profile_func_enter() and __cyg_profile_func_exit() to profile the stack at runtime. Some functions are inlined below; others are defined in src/utils/stack_profiler.cpp
Referenced by lbann::stack_profiler::~stack_profiler, lbann::stack_profiler::activate.
FILE* c_hash_fp_full_stack_trace_metadata
Referenced by lbann::stack_profiler::~stack_profiler, lbann::stack_profiler::activate.
int c_hash_thread_id
Referenced by c_hash_set_thread_id, lbann::stack_profiler::activate.
int c_hash_profiling_is_turned_on
Referenced by lbann::stack_profiler::activate.
char** c_hash_default_discard_strings
int c_hash_num_default_discard_items
short c_hash_func_id
Referenced by c_hash_insert.
short c_hash_depth
Referenced by __cyg_profile_func_exit, __cyg_profile_func_enter.
Dl_info c_hash_info
void** c_hash_discard_void_ptrs
char** c_hash_discard_strings
int* c_hash_discard_counts
int c_hash_discard_void_ptrs_num_active
long c_hash_lookups
Referenced by c_hash_lookup, lbann::stack_profiler::print.
long c_hash_collisions
Referenced by c_hash_lookup, lbann::stack_profiler::print.
c_hash_table* c_hash_the_hash_table
following are pure C functions for creating a hash table, and definitions for variables used in the 'extern "C"' inline functions in lbann/base.hppfollowing that are the stack_profiler class definitions; the stack_profiler is a c++ class in the lbann namespace
Referenced by c_hash_insert, c_hash_lookup, lbann::stack_profiler::print.
void c_hash_create(long size)
the hash table! This is a singleton creates the singleton hash table; the table will contain at least "size" slots (FYI, the table size is a power of two)
References c_hash_table::size, c_hash_table::count, c_hash_table::cur_mark, c_hash_table::data, c_hash_node::key, c_hash_node::mark, c_hash_node::func, lbann::stack_profiler::s_instance.
Referenced by lbann::stack_profiler::activate.
void c_hash_set_thread_id(int id)
References c_hash_thread_id.
void __cyg_profile_func_enter(void *func, void *caller)
References c_hash_depth, c_hash_insert_or_update.
void __cyg_profile_func_exit(void *func, void *caller)
References c_hash_depth.
static void c_hash_insert(void *func)
inserts "func" in a hash table slot. WARNING: this is for internal use; end users should instead call "c_hash_insert_or_update"insert "func" in a hash table slot. WARNING: this is for internal use; end users should instead call "c_hash_insert_or_update"
References c_hash_the_hash_table, c_hash_table::count, c_hash_table::size, c_hash_node::key, djb2_hash, HASH_1, HASH_2, c_hash_table::data, c_hash_node::mark, c_hash_table::cur_mark, c_hash_node::count, c_hash_node::name, c_hash_node::func, c_hash_node::id, c_hash_func_id.
Referenced by c_hash_insert_or_update.
c_hash_node * c_hash_lookup(void *func)
returns a pointer to the slot that has the (hashed) key, "name," or NULL if it doesn't exist
References c_hash_lookups, c_hash_the_hash_table, c_hash_node::key, djb2_hash, c_hash_table::size, HASH_1, c_hash_collisions, HASH_2, c_hash_table::data, c_hash_node::mark, c_hash_table::cur_mark, c_hash_node::func.
Referenced by c_hash_insert_or_update.
static void c_hash_insert_or_update(void *func)
create a slot in the table with the data: func, count=1; if a slot with the name already exists, increment the countcreate a slot in the table with the data: name, count=1, time=0.0; if a slot with the name already exists, increment the count, and time += time
References c_hash_lookup, c_hash_node::count, c_hash_node::id, c_hash_insert.
Referenced by __cyg_profile_func_enter.
static unsigned long long djb2_hash(void *, int table_size)
well known hash function (google it) Hashes a string to an integer
References c_hash_node::func.
Referenced by c_hash_insert, c_hash_lookup.