init_image_data_readers.cpp
void init_image_preprocessor(const lbann_data::Reader &pb_readme, const bool master, std::shared_ptr< cv_process > &pp, int &width, int &height, int &channels)
References anonymous_namespace{image_preprocessor.cpp}::pi.
Referenced by init_image_data_reader.
void init_image_data_reader(const lbann_data::Reader &pb_readme, const bool master, generic_data_reader *&reader)
References init_image_preprocessor, lbann::generic_data_reader::get_type, lbann::data_reader_multi_images::set_input_params.
Referenced by init_data_readers.
void init_generic_preprocessor(const lbann_data::Reader &pb_readme, const bool master, generic_data_reader *reader)
References lbann::lbann_image_preprocessor::horizontal_flip, lbann::lbann_image_preprocessor::vertical_flip, lbann::lbann_image_preprocessor::rotation, lbann::lbann_image_preprocessor::horizontal_shift, lbann::lbann_image_preprocessor::vertical_shift, lbann::lbann_image_preprocessor::shear_range, lbann::lbann_image_preprocessor::disable_augmentation, lbann::lbann_image_preprocessor::subtract_mean, lbann::lbann_image_preprocessor::unit_variance, lbann::lbann_image_preprocessor::scale, lbann::lbann_image_preprocessor::z_score, lbann::lbann_image_preprocessor::add_noise.
Referenced by init_org_image_data_reader, init_data_readers.
void init_org_image_data_reader(const lbann_data::Reader &pb_readme, const bool master, generic_data_reader *&reader)
References init_generic_preprocessor.
Referenced by init_data_readers.