lbann::proto::anonymous_namespace{model_factory.cpp}
model* lbann::proto::anonymous_namespace{model_factory.cpp}::instantiate_model(lbann_comm *comm, objective_function *obj, const lbann_data::Optimizer &proto_opt, const lbann_data::Model &proto_model)
Instantiate a model based on prototext.
References lbann::proto::construct_optimizer, LBANN_ERROR.
Referenced by lbann::proto::construct_model.
void lbann::proto::anonymous_namespace{model_factory.cpp}::assign_layers_to_objective_function(std::vector< Layer *> &layer_list, objective_function *obj, const lbann_data::ObjectiveFunction &proto_obj)
References LBANN_ERROR, lbann::objective_function::get_terms, lbann::layer_term::layer_term.
Referenced by lbann::proto::construct_model.
void lbann::proto::anonymous_namespace{model_factory.cpp}::assign_weights_to_layers(std::vector< Layer *> &layer_list, std::vector< weights *> &weights_list, const lbann_data::Model &proto_model)
Setup pointers from layers to weights.
References LBANN_ERROR.
Referenced by lbann::proto::construct_model.