lbann::stack_trace
std::ofstream lbann::stack_trace::to_file
int lbann::stack_trace::my_lbann_tracing_id
struct sigaction lbann::stack_trace::sa
Referenced by register_handler.
void lbann::stack_trace::set_lbann_stack_trace_world_rank(int rank)
This module contains functions for printing a stack trace when either a signal is caught or an lbann exception is thrown. Default behavior: processes write to cerr. The cmd line option "--stack_trace_to_file" will additionally cause each processor to attempt to write its stack trace to "stack_trace_<rank_in_world>.txt"To use in your driver, you need to call register_handler() after the call to options::get()->init(), and also include the option catch_signals on the command lineFor internal use; made public for testing. called by initialize()
Referenced by lbann::initialize.
static bool lbann::stack_trace::open_output_file()
References options::get, options::has_bool, options::get_bool.
Referenced by print_lbann_exception_stack_trace, lbann_signal_handler.
static void lbann::stack_trace::close_output_file()
Referenced by print_lbann_exception_stack_trace, lbann_signal_handler.
void lbann::stack_trace::print_stack_trace()
For internal use; made public for testing. Attempts to print a stack trace. Calls non-reentrant functions, so behaviour may be undefined if used within a signal handler. Can be used when exceptions are thrown without undefined behavior.
References MAX_STACK_FRAMES.
Referenced by print_lbann_exception_stack_trace, lbann_signal_handler.
void lbann::stack_trace::print_lbann_exception_stack_trace(std::string m)
For internal use; made public for testing. Attempts to print a stack trace when an lbann_exception is thrown. Called by lbann_exception() ctor.
References open_output_file, print_stack_trace, close_output_file.
Referenced by lbann::lbann_exception::lbann_exception.
std::string lbann::stack_trace::sig_name(int signal)
For internal use; made public for testing. called by print_lbann_signal_stack_trace().
Referenced by lbann_signal_handler.
void lbann::stack_trace::register_handler()
Register our signal handler; This is called in initialize(), but only if the cmd line option "--catch_signals" is present. It is not active by default, because the handler calls non-reentrant, functions, which can result in undefined behavior. See: https://www.ibm.com/developerworks/library/l-reent/ for discussion. That said, it is possible (likely?) that our handler will work correctly. And if there's a SIGSEV and it doesn't, nothing much is lost (IMO).
References options::get, options::has_bool, options::get_bool, sa, lbann_signal_handler.
void lbann::stack_trace::lbann_signal_handler(int signal)
For internal use; made public for testing.
References open_output_file, sig_name, print_stack_trace, close_output_file.
Referenced by register_handler.