lbann::graph
void lbann::graph::print(const std::set< int > &nodes, const std::map< int, std::set< int >> &edges, std::ostream &os)
Print the nodes and edges of a graph to an output stream.
References get_neighbors.
std::set< int > lbann::graph::get_neighbors(int node, const std::map< int, std::set< int >> &edges)
Get nodes adjacent to a given node.
Referenced by print, is_closure, is_topologically_sorted, is_cyclic, transpose, induce_subgraph, breadth_first_search, depth_first_search, condensation.
bool lbann::graph::is_closure(const std::set< int > &nodes, const std::map< int, std::set< int >> &edges)
Check whether a graph is a closure. A closure is a set of nodes with no edges to nodes outside the set.
References get_neighbors.
Referenced by is_topologically_sorted, is_cyclic, transpose, topological_sort.
bool lbann::graph::is_topologically_sorted(const std::set< int > &nodes, const std::map< int, std::set< int >> &edges)
Check whether a graph is topologically sorted. A topologically sorted graph has no edges going from a node to an earlier node. The graph must be a directed acyclic graph.
References is_closure, get_neighbors.
Referenced by lbann::sequential_model::setup_layer_topology, is_cyclic, topological_sort.
bool lbann::graph::is_cyclic(const std::set< int > &nodes, const std::map< int, std::set< int >> &edges)
Check whether a directed graph is cyclic.
References is_closure, is_topologically_sorted, get_neighbors.
Referenced by topological_sort.
std::map< int, std::set< int > > lbann::graph::transpose(const std::set< int > &nodes, const std::map< int, std::set< int >> &edges)
Construct the transpose of a graph. Reverses the direction of edges in the graph and returns the new set of edges.
References is_closure, get_neighbors.
Referenced by condensation.
std::map< int, std::set< int > > lbann::graph::induce_subgraph(const std::set< int > &nodes, const std::map< int, std::set< int >> &edges)
Construct an induced subgraph. Removes edges to nodes outside the set of nodes and returns the new set of edges.
References get_neighbors.
std::vector< int > lbann::graph::breadth_first_search(int root, const std::map< int, std::set< int >> &edges)
Perform a breadth-first search starting from a given root node. The search order is deterministic.
References get_neighbors.
std::vector< int > lbann::graph::depth_first_search(int root, const std::map< int, std::set< int >> &edges)
Perform a depth-first search starting from a given root node. A depth-first search post-order is returned. The search order is deterministic.
References get_neighbors.
Referenced by topological_sort, condensation.
std::vector< int > lbann::graph::topological_sort(const std::set< int > &nodes, const std::map< int, std::set< int >> &edges)
Topologically sort a graph. A topologically sorted graph has no edges going from a node to an earlier node. The sort is deterministic and does not affect graphs that are already topologically sorted.
References is_closure, is_cyclic, is_topologically_sorted, depth_first_search.
Referenced by lbann::directed_acyclic_graph_model::setup_layer_execution_order, condensation.
void lbann::graph::condensation(const std::set< int > &nodes, const std::map< int, std::set< int >> &edges, std::map< int, std::set< int >> &components, std::set< int > &condensation_nodes, std::map< int, std::set< int >> &condensation_edges)
Construct the condensation of a graph. The condensation of a graph is constructed by determining the strongly connected components, i.e. sets of nodes that are reachable from all nodes in the set, and coalescing them into single nodes. The condensation is a DAG and will be topologically sorted.
References transpose, depth_first_search, get_neighbors, topological_sort.