anonymous_namespace{profiler.cpp}
static void anonymous_namespace{profiler.cpp}::prof_region_begin(const char *s, int c)
Referenced by lbann::lbann_callback_profiler::on_epoch_begin, lbann::lbann_callback_profiler::on_batch_begin, lbann::lbann_callback_profiler::on_forward_prop_begin, lbann::lbann_callback_profiler::on_backward_prop_begin.
static void anonymous_namespace{profiler.cpp}::prof_region_end(const char *s)
Referenced by lbann::lbann_callback_profiler::on_epoch_end, lbann::lbann_callback_profiler::on_batch_end, lbann::lbann_callback_profiler::on_forward_prop_end, lbann::lbann_callback_profiler::on_backward_prop_end.