lbann::anonymous_namespace{recurrent.cpp}
void lbann::anonymous_namespace{recurrent.cpp}::unroll_input_layer(int unroll_depth, std::vector< Layer *> &layers, std::unordered_map< const Layer *, Layer *> &prev_step_layer, std::unordered_map< const Layer *, Layer *> &next_step_layer)
Setup input layer to match unrolled network. The first layer is assumed to be an input layer. A slice layer and a split layer are inserted after the input layer.
References comm, DATA_PARALLEL, MODEL_PARALLEL, lbann::Layer::set_name, lbann::Layer::add_child_layer, lbann::Layer::add_parent_layer.
Referenced by lbann::recurrent_model::setup_layer_topology.
void lbann::anonymous_namespace{recurrent.cpp}::unroll_target_layer(int unroll_depth, std::vector< Layer *> &layers, std::unordered_map< const Layer *, Layer *> &prev_step_layer, std::unordered_map< const Layer *, Layer *> &next_step_layer)
Setup target layer to match unrolled network. The last layer is assumed to be a target layer. A concatenation layer is inserted before the target layer.
References comm, DATA_PARALLEL, MODEL_PARALLEL.
Referenced by lbann::recurrent_model::setup_layer_topology.
void lbann::anonymous_namespace{recurrent.cpp}::add_unrolled_layers(int unroll_depth, std::vector< Layer *> &layers, std::unordered_map< const Layer *, Layer *> &prev_step_layer, std::unordered_map< const Layer *, Layer *> &next_step_layer)
Duplicate layer network to achieve desired recurrence depth. The layers within each recurrence step have the same topology as the original network.
Referenced by lbann::recurrent_model::setup_layer_topology.
void lbann::anonymous_namespace{recurrent.cpp}::add_placeholder_layers(std::vector< Layer *> &layers, std::unordered_map< const Layer *, Layer *> &prev_step_layer, std::unordered_map< const Layer *, Layer *> &next_step_layer)
Add placeholder layers for first and last recurrence step. If a layer in the first recurrence step expects input from an earlier recurrence step, we insert a zero-valued constant layer. If a layer in the last recurrence step expects to output to a later recurrence step, we insert a dummy layer.
References comm, DATA_PARALLEL, MODEL_PARALLEL, lbann::Layer::set_name, lbann::Layer::add_parent_layer.
Referenced by lbann::recurrent_model::setup_layer_topology.
void lbann::anonymous_namespace{recurrent.cpp}::setup_unrolled_layer_pointers(std::vector< Layer *> &layers, const std::unordered_map< const Layer *, Layer *> &prev_step_layer, const std::unordered_map< const Layer *, Layer *> &next_step_layer)
Setup pointers between recurrence steps. If a layer's parent appears after the layer itself, change the parent to the corresponding layer in the previous recurrence step. Similarly, if a layer's child appears before the layer itself, change the child to the corresponding layer in the next recurrence step.
Referenced by lbann::recurrent_model::setup_layer_topology.