El
void El::ColumnSum(const Matrix< F > &X, Matrix< F > &sums)
Referenced by lbann::reduction_layer< T_layout >::fp_compute, ColumnSum.
void El::ColumnSum(const AbstractDistMatrix< F > &A, AbstractDistMatrix< F > &sums)
References ColumnSum.
void El::RowSum(const Matrix< F > &X, Matrix< F > &sums)
Referenced by RowSum, lbann::fully_connected_layer< T_layout >::bp_compute_cpu.
void El::RowSum(const AbstractDistMatrix< F > &A, AbstractDistMatrix< F > &sums)
References RowSum, LBANN_PROTO_FLOAT, LBANN_PROTO_DOUBLE.