lbann::cnpy_utils
size_t lbann::cnpy_utils::compute_cnpy_array_offset(const cnpy::NpyArray &na, std::vector< size_t > indices)
Return the offset to the element (in terms of the number of elements from the beginning of the array) of a loaded numpy array na specified by indices If the number of indices is less than the dimension of na array, the indices vector is appended with zeros to match the dimension.
Referenced by data, data_ptr.
void lbann::cnpy_utils::shrink_to_fit(cnpy::NpyArray &na, size_t sz)
Shrink the first dimension of cnpy::NpyArray to the given size. This is used to choose only first sz samples in data.
Referenced by data_ptr< void >, lbann::data_reader_jag::load, lbann::offline_patches_npz::load.
std::string lbann::cnpy_utils::show_shape(const cnpy::NpyArray &na)
Show the dimensions of loaded data.
Referenced by data_ptr< void >, lbann::data_reader_jag::get_description, lbann::offline_patches_npz::get_description.
T& lbann::cnpy_utils::data(const cnpy::NpyArray &na, const std::vector< size_t > indices)
Allow the access to the data element identified by the indices and the word_size of the array na, but present it as a type T element at the address.
References compute_cnpy_array_offset.
Referenced by lbann::lbann_comm::allreduce, lbann::lbann_comm::nb_allreduce, lbann::numpy_reader::load, lbann::numpy_reader::fetch_datum, lbann::numpy_reader::fetch_label, lbann::numpy_reader::fetch_response, lbann::pilot2_molecular_reader::fetch_molecule, lbann::data_store_csv::exchange_data, lbann::data_store_image::exchange_data, lbann::data_store_pilot2_molecular::fill_in_data, lbann::data_store_pilot2_molecular::exchange_data, lbann::stack_profiler::print, lbann::entrywise_mean_and_stdev, lbann::columnwise_mean_and_stdev, lbann::rowwise_mean_and_stdev.
T* lbann::cnpy_utils::data_ptr(const cnpy::NpyArray &na, const std::vector< size_t > indices)
Return the address of the data element identified by the indices and the word_size of the array na, but present it as the address of a type T element
References compute_cnpy_array_offset.
void* lbann::cnpy_utils::data_ptr< void >(const cnpy::NpyArray &na, const std::vector< size_t > indices)
References shrink_to_fit, show_shape.