lbann::proto
lbann_callback * lbann::proto::construct_callback(lbann_comm *comm, const lbann_data::Callback &proto_cb, std::map< execution_mode, generic_data_reader *> &data_readers, std::vector< Layer *> layer_list, std::vector< weights *> weights_list, lbann_summary *summarizer)
Construct a callback specified with prototext.
References training, LBANN_ERROR, validation, testing, lbann::lbann_comm::am_world_master.
Referenced by construct_model.
lbann_summary * lbann::proto::construct_summarizer(lbann_comm *comm, const lbann_data::Model &m)
Construct a summarizer specified with prototext. The summarizer is only constructed if the summarizer callback is enabled.
References lbann::lbann_comm::am_world_master, comm.
Referenced by construct_model.
Layer * lbann::proto::construct_layer(lbann_comm *comm, std::map< execution_mode, generic_data_reader *> &data_readers, int num_parallel_readers, cudnn::cudnn_manager *cudnn, const lbann_data::Layer &proto_layer)
Construct a layer specified with prototext.
References MODEL_PARALLEL, comm, lbann::generic_input_layer::io_buffer, training, lbann::generic_target_layer::get_linearized_data_size, DATA_PARALLEL, invalid, max, average, average_no_pad, lbann::INVALID, lbann::SUM, lbann::AVERAGE, LBANN_ERROR.
template Layer* lbann::proto::construct_layer< data_layout::DATA_PARALLEL >(lbann_comm *comm, std::map< execution_mode, generic_data_reader *> &data_readers, int num_parallel_readers, cudnn::cudnn_manager *cudnn, const lbann_data::Layer &proto_layer)
template Layer* lbann::proto::construct_layer< data_layout::MODEL_PARALLEL >(lbann_comm *comm, std::map< execution_mode, generic_data_reader *> &data_readers, int num_parallel_readers, cudnn::cudnn_manager *cudnn, const lbann_data::Layer &proto_layer)
std::vector< Layer * > lbann::proto::construct_layer_graph(lbann_comm *comm, std::map< execution_mode, generic_data_reader *> &data_readers, cudnn::cudnn_manager *cudnn, const lbann_data::Model &proto_model)
Construct a layer graph specified with a prototext.
References LBANN_ERROR, invalid, DATA_PARALLEL, MODEL_PARALLEL, comm, lbann::Layer::set_name, lbann::Layer::get_name, lbann::lbann_comm::am_world_master, lbann::Layer::freeze, lbann::proto::anonymous_namespace{layer_graph_factory.cpp}::setup_parents_and_children, lbann::proto::anonymous_namespace{layer_graph_factory.cpp}::setup_target_pointers, lbann::proto::anonymous_namespace{layer_graph_factory.cpp}::setup_reconstruction_pointers, lbann::proto::anonymous_namespace{layer_graph_factory.cpp}::setup_unpooling_pointers.
Referenced by construct_model.
metric * lbann::proto::construct_metric(lbann_comm *comm, const lbann_data::Metric &proto_metric)
Construct a metric specified with prototext.
References comm.
Referenced by construct_model.
model * lbann::proto::construct_model(lbann_comm *comm, cudnn::cudnn_manager *cudnn, std::map< execution_mode, generic_data_reader *> &data_readers, const lbann_data::Optimizer &proto_opt, const lbann_data::Model &proto_model)
Construct a model specified with a prototext.
References construct_layer_graph, construct_objective_function, lbann::proto::anonymous_namespace{model_factory.cpp}::assign_layers_to_objective_function, lbann::proto::anonymous_namespace{model_factory.cpp}::instantiate_model, construct_weights, lbann::proto::anonymous_namespace{model_factory.cpp}::assign_weights_to_layers, construct_metric, construct_summarizer, construct_callback.
objective_function * lbann::proto::construct_objective_function(const lbann_data::ObjectiveFunction &proto_obj)
Construct an objective function specified with prototext.
References lbann::objective_function::add_term.
Referenced by construct_model.
optimizer * lbann::proto::construct_optimizer(lbann_comm *comm, const lbann_data::Optimizer &proto_opt)
Construct an optimizer specified with prototext.
Referenced by lbann::proto::anonymous_namespace{model_factory.cpp}::instantiate_model, construct_weights.
weights * lbann::proto::construct_weights(lbann_comm *comm, cudnn::cudnn_manager *cudnn, const lbann_data::Optimizer &proto_opt, const lbann_data::Weights &proto_weights)
Construct weights specified with prototext.
References LBANN_ERROR, lbann::weights::set_name, lbann::weights::set_initializer, lbann::proto::anonymous_namespace{weights_factory.cpp}::construct_initializer, lbann::weights::set_optimizer, construct_optimizer.
Referenced by construct_model.
std::vector<T> lbann::proto::parse_list(std::string str)
Parse a space-separated list.