lbann
persist_type
device
reduction_mode
using lbann::rng_gen = typedef std::mt19937
using lbann::fast_rng_gen = typedef std::minstd_rand
std::vector<std::string> lbann::comm_type_names
lbann_comm * lbann::initialize(int &argc, char **&argv, int seed)
Initialize LBANN. The comm instance this returns places every process in one model. This can be changed with lbann_comm::split_models afterward. argc The program's argc. argv The program's argv. seed Optional seed for random number generators.
References comm, init_random, init_data_seq_random, lbann::stack_trace::set_lbann_stack_trace_world_rank.
void lbann::finalize(lbann_comm *comm)
Perform finalization.
References comm.
static bool lbann::write_latest(const char *dir, const char *name, int epoch, int train)
References openwrite, write_string, closewrite.
Referenced by lbann::lbann_callback_checkpoint::checkpointShared.
static bool lbann::read_latest(const char *dir, const char *name, int *epochLast, int *trainLast)
Reads the "latest" file and returns the epoch number and sample offset for most recent checkpoint.
References openread, read_string, closeread.
Referenced by lbann::lbann_callback_checkpoint::restartShared.
std::string lbann::get_comm_type_name(lbann_callback_imcomm::comm_type m)
returns a string representation of the weight_initialization
Referenced by lbann::lbann_callback_imcomm::reshape_mat.
void lbann::load_mnist_data(const std::string imagepath, const std::string labelpath, const int m_first_n, std::vector< std::vector< unsigned char > > &m_image_data)
References __swapEndianInt, lbann::generic_data_reader::m_first_n, lbann::mnist_reader::m_image_data.
Referenced by lbann::mnist_reader::load, lbann::data_reader_mnist_siamese::fetch_label, lbann::data_reader_mnist_siamese::load.
void lbann::Layer::instantiate_matrices< data_layout::MODEL_PARALLEL >(const El::Grid &grid)
References lbann::Layer::get_num_parents, lbann::Layer::m_prev_activations, lbann::Layer::m_error_signals, lbann::Layer::get_num_children, lbann::Layer::m_activations, lbann::Layer::m_prev_error_signals.
void lbann::Layer::instantiate_matrices< data_layout::DATA_PARALLEL >(const El::Grid &grid)
References lbann::Layer::get_num_parents, lbann::Layer::m_prev_activations, lbann::Layer::m_error_signals, lbann::Layer::get_num_children, lbann::Layer::m_activations, lbann::Layer::m_prev_error_signals.
std::vector< int > lbann::get_tokens(std::string str, const std::vector< char > delims)
Tokenize a string into integers by an ordered sequence of delimiter characters.
Referenced by lbann::path_delimiter::operator(), lbann::data_reader_jag::load.
std::vector< std::string > lbann::get_tokens(const std::string str, const std::string delims=" :;\\\")
Tokenize a string into substrings by set of delimiter characters.
bool lbann::parse_path(const std::string &path, std::string &dir, std::string &basename)
Divide a given path into dir and basename.
Referenced by lbann::path_delimiter::operator(), get_ext_name, get_basename_without_ext, modify_file_name.
std::string lbann::get_ext_name(const std::string file_name)
Return file extention name.
References parse_path.
Referenced by lbann::path_delimiter::operator(), modify_file_name.
std::string lbann::get_basename_without_ext(const std::string file_name)
Return basename without extention.
References parse_path.
Referenced by lbann::path_delimiter::operator(), modify_file_name.
std::string lbann::add_delimiter(const std::string dir)
This automatically attaches the directory deliminator at the end of the given directory as necessary. If "" is given, it will do nothing
References lbann::path_delimiter::check, lbann::path_delimiter::preferred.
Referenced by lbann::path_delimiter::operator(), lbann::data_reader_jag::load.
std::string lbann::modify_file_name(const std::string file_name, const std::string tag, const std::string new_ext)
Add tag to a file name and/or change the extension. i.e., given a file_name as "name.ext", a new name "name.tag.new_ext" is returned If a new extension is not specified, it assumes the same. To change the extension without adding a tag, set tag to a null string.
References parse_path, get_ext_name, get_basename_without_ext.
Referenced by lbann::path_delimiter::operator().
bool lbann::check_if_file_exists(const std::string &filename)
Return true if a file with the given name exists.
References check_if_dir_exists.
Referenced by lbann::path_delimiter::operator(), lbann::data_reader_jag::load, lbann::offline_patches_npz::load, check_if_dir_exists, create_dir.
bool lbann::check_if_dir_exists(const std::string &dirname)
References check_if_file_exists.
Referenced by check_if_file_exists, create_dir.
bool lbann::create_dir(const std::string dirname)
Create a directory, and return true if successful. If a directory with the same name already exists, simply return true.
References lbann::path_delimiter::check, check_if_file_exists, check_if_dir_exists.
Referenced by lbann::path_delimiter::operator().
void lbann::im2col(const Mat &im, Mat &col, int num_channels, int im_num_dims, const int *im_dims, const int *im_pads, const int *window_dims, const int *window_strides)
Rearrange image blocks into matrix columns.
The 'col' matrix is generated from the 'im' tensor im by shifting a window across im. Each column of col is produced by positioning the window, extracting entries from im, and flattening. im im tensor, represented as a column vector. col col matrix. Height should be equal to window size and width equal to number of window shifts. Data should be contiguous. num_channels Number of channels in im tensor. im_num_dims Number of dimensions in im tensor. im_dims im tensor dimensions. im_pads Zero pads for im tensor. window_dims Dimensions of window. window_strides Window shift strides.
References im2col_1x1, im2col_2d.
Referenced by lbann::base_convolution_layer::apply_convolution_im2col, lbann::base_convolution_layer::compute_gradients_im2col, lbann::pooling_layer< T_layout >::fp_compute_im2col, lbann::unpooling_layer< T_layout >::bp_compute_im2col.
void lbann::col2im(const Mat &col, Mat &im, int num_channels, int im_num_dims, const int *im_dims, const int *im_pads, const int *window_dims, const int *window_strides)
Rearrange matrix columns into image blocks.
This is approximately the inverse of im2col. The output tensor im is produced from the input matrix col by shifting a window across im. Each column of col is matched with the corresponding window position and corresponding entries are added to im. col col matrix. Height should be equal to window size and width equal to number of window shifts. Data should be contiguous. im im tensor, represented as a column vector. num_channels Number of channels in im tensor. im_num_dims Number of dimensions in im tensor. im_dims im tensor dimensions. im_pads Zero pads for im tensor. window_dims Dimensions of window. window_strides Window shift strides.
References col2im_1x1, col2im_2d.
Referenced by lbann::base_convolution_layer::apply_transposed_convolution_im2col, lbann::pooling_layer< T_layout >::bp_compute_im2col, lbann::unpooling_layer< T_layout >::fp_compute_im2col.
void lbann::col2im(const Mat &col, Mat &im, int num_channels, int im_num_dims, const int *im_dims, const int *im_pads, const int *window_dims, const int *window_strides, std::function< DataType(const DataType &, const DataType &)> reduction_op)
Rearrange matrix columns into image blocks.
This is approximately the inverse of im2col. The output tensor im is produced from the input matrix col by shifting a window across im. Each column of col is matched with the corresponding window position and corresponding entries are reduced to im. col col matrix. Height should be equal to window size and width equal to number of window shifts. Data should be contiguous. im im tensor, represented as a column vector. num_channels Number of channels in im tensor. im_num_dims Number of dimensions in im tensor. im_dims im tensor dimensions. im_pads Zero pads for im tensor. window_dims Dimensions of window. window_strides Window shift strides. reduction_op Reduction operation.
References col2im_1x1.
void lbann::im2col_1x1(const DataType *input_buffer, DataType *output_buffer, int num_channels, int num_input_dims, const int *input_dims)
Rearrange 1x1 image blocks into matrix columns.
This is an optimized implementation of im2col when the window has a size of one, there is no padding, and the window stride is one. im2col will automatically call this routine if it detects a 1x1 im2col.
Referenced by im2col.
void lbann::im2col_2d(const DataType *__restrict__ input_buffer, DataType *__restrict__ output_buffer, int input_dim_x, int input_dim_y, int input_pad_x, int input_pad_y, int num_channels, int window_dim_x, int window_dim_y, int offset_stride_x, int offset_stride_y)
Rearrange 2D image blocks into matrix columns.
This is an optimized implementation of im2col for 2D data. im2col will automatically call this routine if it detects 2D data.
Referenced by im2col.
void lbann::col2im_1x1(const DataType *input_buffer, DataType *output_buffer, const int num_channels, const int num_output_dims, const int *output_dims)
Rearrange matrix columns into 1x1 image blocks.
This is an optimized implementation of col2im when the window has a size of one, there is no padding, and the window stride is one. col2im will automatically call this routine if it detects a 1x1 col2im.
Referenced by col2im.
void lbann::col2im_2d(const DataType *__restrict__ input_buffer, DataType *__restrict__ output_buffer, int output_dim_x, int output_dim_y, int output_pad_x, int output_pad_y, int num_channels, int window_dim_x, int window_dim_y, int offset_stride_x, int offset_stride_y)
Rearrange matrix columns into 2D image blocks.
This is an optimized implementation of col2im for 2D data. col2im will automatically call this routine if it detects 2D data.
Referenced by col2im.
void lbann::display_omp_setup()
References get_sleep_sec, get_env_var, print_affinity_subset, print_affinity, th_print_affinity.
rng_gen & lbann::get_generator()
Return a reference to the global LBANN random number generator. If compiling with OpenMP, this is stored in a threadprivate variable.
References anonymous_namespace{random.cpp}::generator.
Referenced by lbann::dropout< T_layout >::bp_compute_gpu, lbann::rng< DistType, DType >::gen, lbann::lbann_image_preprocessor::augment, init_random, gaussian_fill_procdet, bernoulli_fill_procdet, uniform_fill_procdet.
fast_rng_gen & lbann::get_fast_generator()
Return a reference to a possibly-faster global LBANN random number generator. Compared to get_generator, this should be slightly faster. If compiling with OpenMP, this is stored in a threadprivate variable.
References anonymous_namespace{random.cpp}::fast_generator.
Referenced by lbann::dropout< T_layout >::fp_compute_cpu, lbann::anonymous_namespace{callback_ltfb.cpp}::assign_partners, lbann::mesh_reader::fetch_datum, lbann::lbann_quantizer::onebit_quantize, lbann::lbann_quantizer::proportion_threshold, lbann::lbann_quantizer::col_reconstruction, init_random.
rng_gen & lbann::get_data_seq_generator()
Return a reference to the global LBANN random number generator used for shuffling the data samples within each mini-bathc If compiling with OpenMP, this is stored in a threadprivate variable.
References anonymous_namespace{random.cpp}::data_seq_generator.
Referenced by lbann::generic_data_reader::shuffle_indices, lbann::generic_data_reader::update, lbann::data_reader_mnist_siamese::shuffle_indices, init_data_seq_random.
bool lbann::save_rng_to_checkpoint_shared(persist &p)
References lbann::persist::m_checkpoint_dir, anonymous_namespace{random.cpp}::data_seq_generator, anonymous_namespace{random.cpp}::generator, anonymous_namespace{random.cpp}::fast_generator.
Referenced by fast_rand_int_pow2, lbann::model::save_to_checkpoint_shared.
bool lbann::load_rng_from_checkpoint_shared(persist &p)
References lbann::persist::m_checkpoint_dir, anonymous_namespace{random.cpp}::data_seq_generator, anonymous_namespace{random.cpp}::generator, anonymous_namespace{random.cpp}::fast_generator.
Referenced by fast_rand_int_pow2, lbann::model::load_from_checkpoint_shared.
void lbann::init_random(int seed, lbann_comm *comm)
Initialize the random number generator (with optional seed). comm If present, mixes the process's rank within the model into the seed; if not, uses the MPI world rank. TodoSupport saving/restoring the generator's state. This is directly supported via the >> and << operators on the generator (reading/writing from/to a stream).
References get_generator, get_fast_generator, lbann::lbann_comm::get_rank_in_model.
Referenced by fast_rand_int_pow2, initialize.
void lbann::init_data_seq_random(int seed)
Initialize a random number generator (with optional seed) that is specifically used for sequencing the training / testing data samples. Using a separate RNG for the data sequences helps provide a stable training result that does not vary with how much I/O parallelism is applied. TodoSupport saving/restoring the generator's state. This is directly supported via the >> and << operators on the generator (reading/writing from/to a stream).
References get_data_seq_generator.
Referenced by fast_rand_int_pow2, initialize.
void lbann::gaussian_fill(AbsDistMat &mat, El::Int m, El::Int n, DataType mean, DataType stddev)
Make mat into an m x n matrix where each entry is independently drawn from a Gaussian distribution with given mean and standard deviation. Unless selected so at compile-time, this ensures the entries of the matrix do not change as the grid it is distributed over changes; that is, it will have the same entries when mat spans any number of processes.
References gaussian_fill_procdet.
Referenced by lbann::gaussian_layer< T_layout >::fp_compute, fast_rand_int_pow2, lbann::glorot_normal_initializer::initialize_entries, lbann::glorot_uniform_initializer::initialize_entries, lbann::he_normal_initializer::initialize_entries, lbann::he_uniform_initializer::initialize_entries, lbann::normal_initializer::initialize_entries.
void lbann::bernoulli_fill(AbsDistMat &mat, El::Int m, El::Int n, double p)
Make mat into an m x n matrix where each entry is an indepenent Bernoulli random variable with parameter p. This makes the same guarantees as gaussian_fill.
References bernoulli_fill_procdet.
Referenced by lbann::bernoulli_layer< T_layout >::fp_compute, fast_rand_int_pow2.
void lbann::uniform_fill(AbsDistMat &mat, El::Int m, El::Int n, DataType center, DataType radius)
Make mat into an m x n matrix where each entry is independently uniformly sampled from a ball with the given center and radius. This makes the same guarantees as gaussian_fill.
References uniform_fill_procdet.
Referenced by lbann::uniform_layer< T_layout >::fp_compute, fast_rand_int_pow2, lbann::uniform_initializer::initialize_entries.
void lbann::gaussian_fill_procdet(AbsDistMat &mat, El::Int m, El::Int n, DataType mean, DataType stddev)
Make mat into an m x n matrix where each entry is independently drawn from a Gaussian distribution with given mean and standard deviation. This always ensures that the entries of the matrix do not change as the grid it is distributed over changes.
References get_generator.
Referenced by fast_rand_int_pow2, gaussian_fill.
void lbann::bernoulli_fill_procdet(AbsDistMat &mat, El::Int m, El::Int n, double p)
Make mat into an m x n matrix where each entry is an independent Bernoulli random variable with parameter p. This makes the same guarantees as gaussian_fill_procdet.
References get_generator.
Referenced by lbann::dropout< T_layout >::fp_compute_cpu, fast_rand_int_pow2, bernoulli_fill.
void lbann::uniform_fill_procdet(AbsDistMat &mat, El::Int m, El::Int n, DataType center, DataType radius)
Make mat into an m x n matrix where each entry is independently uniformly sampled from a ball with the given center and radius. This makes the same guarantees as gaussian_fill_procdet.
References get_generator.
Referenced by fast_rand_int_pow2, lbann::DataGenerator::load, uniform_fill.
bool lbann::count_sorter(const std::pair< std::string, long > &a, const std::pair< std::string, long > &b)
Referenced by lbann::stack_profiler::print.
void lbann::entrywise_mean_and_stdev(const Mat &data, DataType &mean, DataType &stdev)
Compute mean and standard deviation over matrix entries.
data Input matrix. means Mean value (output). stdevs Standard deviation (output).
References lbann::cnpy_utils::data.
Referenced by lbann::lbann_image_preprocessor::mean_subtraction, lbann::lbann_image_preprocessor::unit_variance, lbann::lbann_image_preprocessor::z_score, lbann::r2_metric::evaluate_compute.
void lbann::entrywise_mean_and_stdev(const AbsDistMat &data, DataType &mean, DataType &stdev)
Compute mean and standard deviation over matrix entries.
data Input matrix. means Mean value (output). stdevs Standard deviation (output).
void lbann::columnwise_mean_and_stdev(const Mat &data, Mat &means, Mat &stdevs)
Compute column-wise means and standard deviations.
data Input matrix. means Mean vector. Output as a row vector with same number of columns as 'data'. stdevs Standard deviation vector. Output as a row vector with same number of columns as 'data'.
References lbann::cnpy_utils::data.
Referenced by lbann::pearson_correlation_metric::evaluate_compute.
void lbann::columnwise_sums_and_sqsums(const AbsDistMat &data, AbsDistMat &sums, AbsDistMat &sqsums)
Compute column-wise sum and sqsum.
TodoNumerically stable implementation data Input matrix in U,V format. sum Sum vector in STAR,V format. Output as a row vector with same number of columns as 'data'. sqsum Sum of squared vector in STAR,V format. Output as a row vector with same number of columns as 'data'.
Referenced by columnwise_mean_and_stdev.
void lbann::columnwise_mean_and_stdev(const AbsDistMat &data, AbsDistMat &means, AbsDistMat &stdevs)
Compute column-wise means and standard deviations.
TodoNumerically stable implementation data Input matrix in U,V format. means Mean vector in STAR,V format. Output as a row vector with same number of columns as 'data'. stdevs Standard deviation vector in STAR,V format. Output as a row vector with same number of columns as 'data'.
References columnwise_sums_and_sqsums.
void lbann::rowwise_mean_and_stdev(const Mat &data, Mat &means, Mat &stdevs)
Compute row-wise means and standard deviations.
data Input matrix. means Mean vector. Output as a column vector with same number of rows as 'data'. stdevs Standard deviation vector. Output as a column vector with same number of rows as 'data'.
References lbann::cnpy_utils::data.
void lbann::rowwise_sums_and_sqsums(const AbsDistMat &data, AbsDistMat &sums, AbsDistMat &sqsums)
Compute row-wise sum and sum of squares.
TodoNumerically stable implementation data Input matrix in U,V format. sum Sum vector in U,STAR format. Output as a column vector with same number of rows as 'data'. sqsum Sum of squared in U,STAR format. Output as a column vector with same number of rows as 'data'.
Referenced by rowwise_mean_and_stdev.
void lbann::rowwise_mean_and_stdev(const AbsDistMat &data, AbsDistMat &means, AbsDistMat &stdevs)
Compute row-wise means and standard deviations.
TodoNumerically stable implementation data Input matrix in U,V format. means Mean vector in U,STAR format. Output as a column vector with same number of rows as 'data'. stdevs Standard deviation vector in U,STAR format. Output as a column vector with same number of rows as 'data'.
References rowwise_sums_and_sqsums.
void lbann::columnwise_covariance(const AbsDistMat &data1, const AbsDistMat &data2, const AbsDistMat &means1, const AbsDistMat &means2, AbsDistMat &cov)
Compute column-wise covariances.
data1 Input matrix in U,V format. data2 Input matrix in U,V format. means1 Column-wise mean vector for data1 in STAR,V format. means2 Column-wise mean vector for data2 in STAR,V format. cov Covariance vector in STAR,V format. Output as a row vector with same number of columns as 'data1'.
Referenced by lbann::pearson_correlation_metric::evaluate_compute.
static bool lbann::endsWith(const std::string mainStr, const std::string &toMatch)
Referenced by lbann::generic_data_reader::set_file_dir, init_data_readers.
void lbann::set_minibatch_item(Mat &M, const int mb_idx, const T *const ptr, const size_t count)
int lbann::makedir(const char *dirname)
References comm, mode_dir.
Referenced by lbann::lbann_callback_checkpoint::checkpointShared, lbann::persist::open_checkpoint.
int lbann::exists(const char *filename)
References comm.
Referenced by lbann::persist::read_distmat, read_distmat, save_session.
int lbann::openread(const char *filename)
Referenced by read_latest, lbann::persist::open_restart.
int lbann::closeread(int fd, const char *filename)
Referenced by read_latest, lbann::persist::close_restart.
int lbann::openwrite(const char *filename)
Referenced by write_latest, lbann::persist::open_checkpoint.
int lbann::closewrite(int fd, const char *filename)
Referenced by write_latest, lbann::persist::close_checkpoint.
bool lbann::writeDist(int fd, const char *filename, const DistMat &M, uint64_t *bytes)
Given an open file descriptor, file name, and a matrix, write the matrix to the file descriptor, return the number of bytes written.
References layer_header::rank, layer_header::width, layer_header::height, layer_header::localwidth, layer_header::localheight, layer_header::ldim.
Referenced by lbann::persist::get_bytes.
bool lbann::readDist(int fd, const char *filename, DistMat &M, uint64_t *bytes)
Given an open file descriptor, file name, and a matrix, read the matrix from the file descriptor, return the number of bytes read.
References layer_header::height, layer_header::width.
Referenced by lbann::persist::get_bytes.
bool lbann::write_distmat(int fd, const char *name, DistMat *M, uint64_t *bytes)
Referenced by lbann::persist::get_bytes.
bool lbann::read_distmat(int fd, const char *name, DistMat *M, uint64_t *bytes)
References exists.
Referenced by lbann::persist::get_bytes.
bool lbann::write_bytes(int fd, const char *name, const void *buf, size_t size)
Referenced by lbann::persist::get_bytes, lbann::persist::write_uint32, lbann::persist::write_uint64, lbann::persist::write_int32_contig, lbann::persist::write_float, lbann::persist::write_double, lbann::persist::write_datatype, lbann::persist::write_string, write_uint32, write_uint64, write_int32_contig, write_float, write_double.
bool lbann::read_bytes(int fd, const char *name, void *buf, size_t size)
Referenced by lbann::persist::get_bytes, lbann::persist::read_uint32, lbann::persist::read_uint64, lbann::persist::read_int32_contig, lbann::persist::read_float, lbann::persist::read_double, lbann::persist::read_datatype, lbann::persist::read_string, read_uint32, read_uint64, read_int32_contig, read_float, read_double.
bool lbann::write_uint32(int fd, const char *name, uint32_t val)
References write_bytes.
Referenced by lbann::persist::get_bytes.
bool lbann::read_uint32(int fd, const char *name, uint32_t *val)
References read_bytes.
Referenced by lbann::persist::get_bytes.
bool lbann::write_uint64(int fd, const char *name, uint64_t val)
References write_bytes.
Referenced by lbann::persist::get_bytes.
bool lbann::read_uint64(int fd, const char *name, uint64_t *val)
References read_bytes.
Referenced by lbann::persist::get_bytes.
bool lbann::write_int32_contig(int fd, const char *name, const int32_t *buf, uint64_t count)
References write_bytes.
Referenced by lbann::persist::get_bytes.
bool lbann::read_int32_contig(int fd, const char *name, int32_t *buf, uint64_t count)
References read_bytes.
Referenced by lbann::persist::get_bytes.
bool lbann::write_float(int fd, const char *name, float val)
References write_bytes.
Referenced by lbann::persist::get_bytes.
bool lbann::read_float(int fd, const char *name, float *val)
References read_bytes.
Referenced by lbann::persist::get_bytes.
bool lbann::write_double(int fd, const char *name, double val)
References write_bytes.
Referenced by lbann::persist::get_bytes.
bool lbann::read_double(int fd, const char *name, double *val)
References read_bytes.
Referenced by lbann::persist::get_bytes.
bool lbann::write_string(int fd, const char *name, const char *buf, size_t size)
Referenced by lbann::persist::get_bytes, write_latest.
bool lbann::read_string(int fd, const char *name, char *buf, size_t size)
Referenced by lbann::persist::get_bytes, read_latest.
void lbann::lbann_report_exception(lbann_exception &e, lbann_comm *comm=nullptr, std::ostream &os=std::cerr)
References lbann::lbann_exception::what, comm.
Referenced by lbann::generic_data_reader::fetch_data, lbann::generic_data_reader::fetch_labels, lbann::generic_data_reader::fetch_responses, lbann::data_reader_mnist_siamese::fetch_data, lbann::data_reader_mnist_siamese::fetch_labels.
bool lbann::load_file(const std::string filename, T &buf)
Load a file into a buffer.
void lbann::__swapEndianInt(unsigned int &ui)
Referenced by load_mnist_data.
std::vector<std::string> lbann::glob(const std::string &pattern)
Wrapper around glob, which searches for paths matching pattern according to the shell. Note this does not do tilde expansion.
Referenced by lbann::mesh_reader::load, init_data_readers.
int lbann::get_num_pus()
int lbann::get_affinity(uint8_t *cpus, uint8_t *count)
void lbann::th_print_affinity(int rank, int np, char *host)
Referenced by display_omp_setup.
void lbann::print_affinity(int rank, int np, char *host)
Referenced by display_omp_setup.
int lbann::get_env_var(const char *id)
Referenced by display_omp_setup.
int lbann::get_sleep_sec()
Referenced by display_omp_setup.
void lbann::print_affinity_subset(int rank, int np, char *host)
Referenced by display_omp_setup.
T lbann::fast_rand_int(Generator &g, T max)
Return random integers uniformly distributed in [0, max). g C++ uniform random bit generator. max Upper bound on the distribution. It turns out that the GCC std::uniform_int_distribution is really slow. That implementation is used by most compilers. This implementation is roughly five times faster than that one.
Referenced by lbann::lbann_quantizer::onebit_quantize, lbann::lbann_quantizer::proportion_threshold, lbann::lbann_quantizer::col_reconstruction.
T lbann::fast_rand_int_pow2(Generator &g, T max)
Faster variant of fast_rand_int in the case that max is a power of 2. Do not call this if max is not a power of 2.
References init_random, comm, init_data_seq_random, gaussian_fill, bernoulli_fill, uniform_fill, gaussian_fill_procdet, bernoulli_fill_procdet, uniform_fill_procdet, save_rng_to_checkpoint_shared, load_rng_from_checkpoint_shared.
Referenced by lbann::lbann_quantizer::col_reconstruction.
void lbann::rng_bernoulli(const float p, DistMat *m)
Multiply entries of distributed matrix with a multiplier generated according to bernoulli_distribution
References lbann::rng< DistType, DType >::gen.
double lbann::get_time()
Return time in fractional seconds since an epoch.
Referenced by lbann::lbann_callback_timeline::get_rel_time, lbann::lbann_callback_imcomm::on_backward_prop_end, lbann::lbann_callback_timeline::on_train_begin, lbann::lbann_callback_timer::batch_timing_begin, lbann::lbann_callback_timer::batch_timing_end, lbann::lbann_callback_timer::timing_begin, lbann::lbann_callback_timer::timing_end, lbann::lbann_comm::recursive_doubling_allreduce_pow2, lbann::lbann_comm::pe_ring_allreduce, lbann::lbann_comm::ring_allreduce, lbann::lbann_comm::rabenseifner_allreduce, lbann::data_store_csv::setup, lbann::data_store_csv::exchange_data, lbann::data_store_image::setup, lbann::data_store_imagenet::setup, lbann::data_store_multi_images::setup, lbann::data_store_pilot2_molecular::setup, lbann::data_store_pilot2_molecular::exchange_data, lbann::data_store_triplet::setup, lbann::Layer::forward_prop, lbann::Layer::back_prop, lbann::Layer::update, lbann::metric::evaluate, lbann::objective_function::start_evaluation, lbann::objective_function::finish_evaluation, lbann::objective_function::differentiate, lbann::objective_function::compute_weight_regularization, lbann::optimizer::step, lbann::lbann_quantizer::proportion_threshold.