lbann::anonymous_namespace{callback_ltfb.cpp}
int lbann::anonymous_namespace{callback_ltfb.cpp}::assign_partners(lbann_comm *comm)
Assign partners for current tournament. This function pairs models up and returns the partner model corresponding to the current process. If there is an odd number of models, one of them is partnered with itself.
References lbann::lbann_comm::am_world_master, lbann::lbann_comm::get_num_models, lbann::lbann_comm::get_procs_per_model, lbann::get_fast_generator, lbann::lbann_comm::scatter, lbann::lbann_comm::get_world_comm.
Referenced by lbann::lbann_callback_ltfb::on_batch_begin.
void lbann::anonymous_namespace{callback_ltfb.cpp}::exchange_weights(lbann_comm *comm, std::vector< weights *> &model_weights, std::vector< weights *> &local_weights, int partner)
Exchange weights with remote model. Weights from the local model are copied into local_weights and weights from the remote model are copied into model_weights.
References lbann::lbann_comm::sendrecv.
Referenced by lbann::lbann_callback_ltfb::on_batch_begin.
EvalType lbann::anonymous_namespace{callback_ltfb.cpp}::evaluate(model *m)
Evaluate a model on tournament data and return its accuracy.
References lbann::model::get_execution_mode, lbann::model::evaluate, validation, lbann::model::set_execution_mode, lbann::model::get_metrics.
Referenced by lbann::metric::get_unit, lbann::lbann_callback_ltfb::on_batch_begin.