lbann::proto::anonymous_namespace{layer_graph_factory.cpp}
void lbann::proto::anonymous_namespace{layer_graph_factory.cpp}::setup_parents_and_children(lbann_comm *comm, std::vector< Layer *> &layers, std::unordered_map< std::string, Layer *> &names_to_layers, const lbann_data::Model &proto_model)
Setup parent/child relationships between layers.
References LBANN_ERROR.
Referenced by lbann::proto::construct_layer_graph.
void lbann::proto::anonymous_namespace{layer_graph_factory.cpp}::setup_target_pointers(lbann_comm *comm, std::vector< Layer *> &layers, std::unordered_map< std::string, Layer *> &names_to_layers, const lbann_data::Model &proto_model)
Setup paired input layers for target layers.
References lbann::Layer::get_name, LBANN_ERROR, lbann::io_layer::is_for_regression, lbann::generic_target_layer::set_paired_input_layer.
Referenced by lbann::proto::construct_layer_graph.
void lbann::proto::anonymous_namespace{layer_graph_factory.cpp}::setup_reconstruction_pointers(lbann_comm *comm, std::vector< Layer *> &layers, std::unordered_map< std::string, Layer *> &names_to_layers, const lbann_data::Model &proto_model)
Setup original layers for reconstruction layers.
References lbann::Layer::get_name, LBANN_ERROR, lbann::reconstruction_layer< T_layout >::set_original_layer.
Referenced by lbann::proto::construct_layer_graph.
void lbann::proto::anonymous_namespace{layer_graph_factory.cpp}::setup_unpooling_pointers(lbann_comm *comm, std::vector< Layer *> &layers, std::unordered_map< std::string, Layer *> &names_to_layers, const lbann_data::Model &proto_model)
Setup paired pooling layers for unpooling layers.
References lbann::Layer::get_name, LBANN_ERROR, lbann::unpooling_layer< T_layout >::set_pooling_layer.
Referenced by lbann::proto::construct_layer_graph.