options.cpp
void m_parse_opt(std::string tmp, std::string &key, std::string &val)
Referenced by options::init, options::m_parse_file, options::m_parse_cmd_line.
void lower(std::string &s)
Referenced by options::m_test_double.
void lower(char *s)