proto_common.cpp
bool has_motifs(lbann_comm *comm, const lbann_data::LbannPB &p)
Returns true if the Model contains at least one MotifLayer.
References lbann::lbann_comm::am_world_master.
void expand_motifs(lbann_comm *comm, lbann_data::LbannPB &pb)
References lbann::lbann_comm::am_world_master.
void init_data_readers(lbann::lbann_comm *comm, const lbann_data::LbannPB &p, std::map< execution_mode, generic_data_reader *> &data_readers)
instantiates one or more generic_data_readers and inserts them in &data_readers
References lbann::lbann_comm::am_world_master, init_org_image_data_reader, init_image_data_reader, lbann::endsWith, lbann::glob, lbann::generic_data_reader::set_data_filename, lbann::generic_data_reader::set_label_filename, lbann::generic_data_reader::set_file_dir, lbann::generic_data_reader::set_absolute_sample_count, lbann::generic_data_reader::set_use_percent, lbann::generic_data_reader::set_first_n, init_generic_preprocessor, lbann::generic_data_reader::set_role, lbann::generic_data_reader::set_validation_percent, lbann::generic_data_reader::set_master, lbann::generic_data_reader::set_comm, lbann::generic_data_reader::load, training, testing, lbann::generic_data_reader::use_unused_index_set, lbann::generic_data_reader::get_num_data, validation.
void read_prototext_file(std::string fn, lbann_data::LbannPB &pb, bool master)
Referenced by lbann::protobuf_utils::read_in_prototext_files.
bool write_prototext_file(const char *fn, lbann_data::LbannPB &pb)
void set_num_parallel_readers(lbann::lbann_comm *comm, lbann_data::LbannPB &p)
adjusts the number of parallel data readers
References lbann::lbann_comm::am_world_master, lbann::lbann_comm::get_procs_per_model.
void set_data_readers_filenames(std::string which, lbann_data::LbannPB &p)
References options::get, options::has_string, options::get_string.
Referenced by get_cmdline_overrides.
void set_data_readers_percent(lbann_data::LbannPB &p)
References options::get, options::get_float.
Referenced by get_cmdline_overrides.
void get_cmdline_overrides(lbann::lbann_comm *comm, lbann_data::LbannPB &p)
adjusts the values in p by querying the options db
References lbann::lbann_comm::am_world_master, options::get, options::has_int, options::get_int, options::has_string, set_data_readers_filenames, set_data_readers_percent, options::get_string, options::has_bool, options::get_bool, options::has_float, options::get_float.
void print_parameters(lbann::lbann_comm *comm, lbann_data::LbannPB &p)
print various params (learn_rate, etc) to cout
References lbann::lbann_comm::am_world_master.
void print_help(lbann::lbann_comm *comm)
prints usage information
References lbann::lbann_comm::am_world_master.
void copy_file(std::string fn, std::ofstream &out)
void save_session(lbann::lbann_comm *comm, int argc, char **argv, lbann_data::LbannPB &p)
prints prototext file, cmd line, etc to file
References lbann::lbann_comm::am_world_master, options::get, options::has_string, options::get_string, lbann::exists, LBANN_MAKE_STR, lbann::lbann_comm::get_procs_in_world.