lbann::metric_statistics
EvalType lbann::metric_statistics::m_sum
Sum of metric values.
Referenced by add_value, get_mean, reset, pack_scalars, unpack_scalars, unpack_header.
int lbann::metric_statistics::m_num_samples
Number of samples.
Referenced by get_num_samples, add_value, get_mean, reset, pack_scalars, unpack_scalars, unpack_header.
lbann::metric_statistics::metric_statistics()
Default constructor.
References reset, operator=, ~metric_statistics, add_value, get_mean.
lbann::metric_statistics::metric_statistics(metric_statistics &other)=default
Move constructor.
lbann::metric_statistics::metric_statistics(const metric_statistics &other)=default
Copy constructor.
metric_statistics& lbann::metric_statistics::operator=(metric_statistics &other)=default
Move assignment operator.
Referenced by metric_statistics.
metric_statistics& lbann::metric_statistics::operator=(const metric_statistics &other)=default
Copy assignment operator.
lbann::metric_statistics::~metric_statistics()=default
Destructor.
Referenced by metric_statistics.
void lbann::metric_statistics::add_value(EvalType value, int num_samples=1)
Add metric value to statistics.
References m_sum, m_num_samples.
Referenced by metric_statistics.
EvalType lbann::metric_statistics::get_mean() const
Get mean metric value. If mini-batch sizes are not identical, the mean is over the sample values rather than over the mini-batch mean values.
References m_num_samples, m_sum.
Referenced by metric_statistics.
int lbann::metric_statistics::get_num_samples() const
Get number of samples.
References m_num_samples, reset.
void lbann::metric_statistics::reset()
Reset statistics.
References m_sum, m_num_samples.
Referenced by metric_statistics, get_num_samples.
bool lbann::metric_statistics::pack_scalars(persist &p)
References lbann::persist::write_double, lbann::validate, m_sum, lbann::persist::write_uint64, m_num_samples.
bool lbann::metric_statistics::unpack_scalars(persist &p, struct packing_header *header)
References lbann::persist::read_double, lbann::validate, lbann::persist::read_uint64, m_sum, m_num_samples, lbann::metric_statistics::packing_header::sum, lbann::metric_statistics::packing_header::num_samples.
void lbann::metric_statistics::unpack_header(struct packing_header &header)
References m_sum, lbann::metric_statistics::packing_header::sum, m_num_samples, lbann::metric_statistics::packing_header::num_samples.