lbann::path_delimiter
const std::string lbann::path_delimiter::characters
static std::string lbann::path_delimiter::preferred()
Referenced by lbann::add_delimiter.
static bool lbann::path_delimiter::check(const char ch)
Referenced by lbann::add_delimiter, lbann::create_dir.
bool lbann::path_delimiter::operator()(const char ch) const
References lbann::get_tokens, lbann::parse_path, lbann::get_ext_name, lbann::get_basename_without_ext, lbann::add_delimiter, lbann::modify_file_name, lbann::check_if_file_exists, lbann::create_dir.